screwdriver-cd/ui

- Dockerfile
- bin/incrementVersion.sh
- wercker.yml
* tar up static assets and publish as a release
* Dockerfile to pull down release and build in nginx container
> Docker magic

- app/components/sd-build-log/component.js
- app/components/sd-build-log/styles.scss
- app/components/sd-build-step-collection/template.hbs
- app/components/sd-build-step-container/component.js
- app/components/sd-build-step-container/template.hbs
- app/components/sd-build-step/component.js
- app/components/sd-build-step/styles.scss
- app/components/sd-build-step/template.hbs
- config/coverage.js
- package.json
- tests/integration/components/sd-build-log/component-test.js
- tests/integration/components/sd-build-step-container/component-test.js
- tests/integration/components/sd-build-step/component-test.js
* Mock calls to api to fetch logs (actually test log component)
* Better user interaction tests of step view
* Fix coverage to not include handlebars code in templates
* Decouple log component and step view component, a container component handles communication between them
> Open logs when page loads if step failed

- app/components/build-banner/template.hbs
> add a link to pipeline page from build banner

- app/components/app-header/styles.scss
The button has some arbitrary padding and we want it to be aligned with text on the right of the page.
> move login button over

- app/components/pipeline-workflow/component.js
- app/components/pipeline-workflow/styles.scss
- app/components/pipeline-workflow/template.hbs
- app/helpers/get-last-build.js
- app/job/model.js
- app/pipeline/builds/index/template.hbs
- tests/integration/components/pipeline-workflow/component-test.js
- tests/unit/helpers/get-last-build-test.js
- tests/unit/job/model-test.js
- Add workflow to pipeline page
- The color of a workflow job indicates the latest build status for that job
- SUCCESS > green
- FAILURE > red
- No build yet > gray
- Click on the job will redirect to the latest build page
> Add a workflow bar to pipeline page

- app/authenticators/screwdriver-api.js
Auth refresh was a little naieve about the auth token.
* Refresh now checks expiry in the auth token
* Set better auth window settings when opened
> Make auth a little more intelligent

- screwdriver.yaml
Uses these cool scripts: https://gist.github.com/stjohnjohnson/3d2388b2a7ba658cdcdaffa8cd874e50
> Moving publish/release to Screwdriver

- Dockerfile
- nginx.conf
Fixing the download so it's not rate limited.  Also adding redirect to SD api.
> Adding redirect to API badge service and fix download of release

- .eslintrc.js
- app/build/model.js
- app/components/build-banner/template.hbs
- app/components/build-details/template.hbs
- app/components/build-step-view/component.js
- app/components/build-step-view/template.hbs
- app/components/pipeline-build-view/template.hbs
- bower.json
- ember-cli-build.js
- tests/integration/components/build-banner/component-test.js
- tests/integration/components/build-details/component-test.js
- tests/integration/components/build-step-view/component-test.js
- tests/integration/components/pipeline-build-view/component-test.js
- tests/unit/build/model-test.js
- Switch to [ humannizeDuration](http://evanhahn.github.io/HumanizeDuration.js) for `duration` `createTime` and `startTime`  display
- No more `a few seconds` yeah!
> Humanize duration display

- app/components/search-list/component.js
- app/components/search-list/styles.scss
- app/components/search-list/template.hbs
- app/router.js
- app/search/route.js
- app/search/template.hbs
- tests/integration/components/search-list/component-test.js
- tests/unit/search/route-test.js
Simple search result page. Displaying a list of all pipelines for now.
> Add a seach result page

- screwdriver.yaml
This will auto-deploy to prod once the docker image is available
> Continuously Delivering the UI to Prod

- app/components/app-header/component.js
- app/components/app-header/styles.scss
- app/components/app-header/template.hbs
- app/components/pipeline-header/styles.scss
- public/assets/svg/write.svg
- tests/integration/components/app-header/component-test.js
Simplified markup and styles, too.
> Add create pipeline link to header

- app/pipeline/builds/index/controller.js
- Allow startMainBuild when there is no build yet
> Fix to allow startMainBuild when there is no build yet

- .ember-cli
- app/components/app-header/component.js
- app/components/app-header/styles.scss
- app/components/app-header/template.hbs
- app/pipeline/builds/build/controller.js
- app/pipeline/builds/build/route.js
- config/coverage.js
- config/environment.js
- tests/acceptance/build-test.js
- tests/acceptance/pipeline-builds-test.js
- tests/acceptance/search-test.js
- tests/acceptance/secrets-test.js
- tests/integration/components/app-header/component-test.js
- tests/unit/pipeline/builds/build/controller-test.js
- tests/unit/pipeline/builds/index/controller-test.js
- tests/unit/pipeline/secrets/controller-test.js
In Ember, acceptance tests are one step above integration tests exercising the entirety of the app from route to component. The goal of this PR is to get code coverage > 95%.
Adding tests for:
Lines 98.09% | Branches 91.41% | Functions 100% | Statements 98.11%
> Acceptance Tests

- app/components/app-header/styles.scss
- app/components/build-banner/styles.scss
- app/components/build-banner/template.hbs
- app/components/build-log/styles.scss
- app/components/build-step-collection/styles.scss
- app/components/build-step-collection/template.hbs
- app/components/build-step-view/styles.scss
- app/components/build-step-view/template.hbs
- app/components/home-hero/styles.scss
- app/components/home-hero/template.hbs
- app/components/loading-view/component.js
- app/components/pipeline-build-view/styles.scss
- app/components/pipeline-nav/styles.scss
- app/components/pipeline-nav/template.hbs
- app/components/pipeline-pr-list/styles.scss
- app/components/pipeline-secret-settings/styles.scss
- app/components/pipeline-secret-settings/template.hbs
- app/components/pipeline-workflow/styles.scss
- app/styles/fuji-colors.scss
- tests/integration/components/build-step-collection/component-test.js
- tests/integration/components/pipeline-nav/component-test.js
Another pass of CSS updates with our designer.
> making css styles more consistant across components

- app/components/build-log/template.hbs
{{html sanitized}}, {{{not html sanitized}}}
> Fix logs losing colored output

- app/application/adapter.js
- tests/unit/application/adapter-test.js
- Reload the secrets after delete it
> reload secrets after delete

- app/components/loading-view/component.js
- app/components/pipeline-nav/template.hbs
- app/components/pipeline-options/component.js
- app/components/pipeline-options/styles.scss
- app/components/pipeline-options/template.hbs
- app/job/model.js
- app/job/serializer.js
- app/pipeline/options/controller.js
- app/pipeline/options/route.js
- app/pipeline/options/template.hbs
- app/router.js
- tests/acceptance/pipeline-options-test.js
- tests/integration/components/pipeline-nav/component-test.js
- tests/integration/components/pipeline-options/component-test.js
- tests/integration/components/pipeline-secret-settings/component-test.js
- tests/unit/job/serializer-test.js
- tests/unit/pipeline/options/controller-test.js
- tests/unit/pipeline/options/route-test.js
* Add new route `options` to pipeline page
* Add section to set jobs as disabled
* Add section to remove pipeline
* Add tests for stuff for coverage
> Add route to pipeline-options

- app/components/login-button/styles.scss
- app/components/login-button/template.hbs
- tests/integration/components/login-button/component-test.js
Not sure if it is any more clear than before, but this is no longer specifically referencing github
> Update copy on login page

- app/components/build-banner/component.js
- app/components/pipeline-builds-list/styles.scss
- app/components/pipeline-options/component.js
- app/components/pipeline-options/styles.scss
- app/components/pipeline-options/template.hbs
- app/components/pipeline-pr-list/styles.scss
- app/pipeline/builds/index/route.js
- app/styles/screwdriver-colors.scss
- config/environment.js
- package.json
- tests/integration/components/pipeline-options/component-test.js
> Update options page

- app/components/pipeline-event-view/component.js
- app/components/pipeline-event-view/styles.scss
- app/components/pipeline-event-view/template.hbs
- app/components/user-link/component.js
- app/components/user-link/styles.scss
trying out a different design. also made the view more reactive.
Wide screen:
Phone:
> move around commiter picture

- app/components/app-header/template.hbs
- app/components/home-hero/component.js
- app/components/home-hero/styles.scss
- app/components/home-hero/template.hbs
- tests/integration/components/home-hero/component-test.js
> Make a new getting started section instead of one-pager

- app/components/build-log/component.js
- app/components/build-log/styles.scss
- tests/acceptance/build-test.js
- tests/integration/components/build-log/component-test.js
- tests/integration/components/build-step/component-test.js
- tests/unit/build-logs/service-test.js
Adds timestamps to logs
issue: https://github.com/screwdriver-cd/screwdriver/issues/392
> feat: display timestamps in logs

- app/components/search-list/styles.scss
- app/components/search-list/template.hbs
- bower.json
- package.json
- tests/acceptance/search-test.js
- tests/integration/components/search-list/component-test.js
- Show number of search results
- Highlight query term
Related to https://github.com/screwdriver-cd/screwdriver/issues/394
> feat: add number of search results and highlight query term

- package.json
- tests/helpers/start-app.js
> chore: update ember-cli

- app/components/pipeline-options/component.js
- app/components/pipeline-options/styles.scss
- app/components/pipeline-options/template.hbs
- app/sync/service.js
- tests/integration/components/pipeline-options/component-test.js
- tests/unit/sync/service-test.js
- Add sync buttons to options tab
- Show error message on top if there is error
- Show a loading modal after clicking the button
Related to https://github.com/screwdriver-cd/screwdriver/issues/417
> feat: add sync buttons to options tab

- README.md
Also just trying to get a new build to run.
> docs: Correcting the Description

- README.md
remove the placeholder sentence to re-run the ui build
> docs: remove the placeholder sentence

- app/app.js
- app/application/route.js
I added a feature described in screwdriver-cd/screwdriver#425. 
I haven't added tests yet, but could you review the changes if you have a chance? @petey
> feat(425): Redirect to previous page after login

- .eslintignore
- app/application/adapter.js
- app/components/validator-input/component.js
- app/components/validator-input/styles.scss
- app/components/validator-input/template.hbs
- app/components/validator-job/component.js
- app/components/validator-job/styles.scss
- app/components/validator-job/template.hbs
- app/components/validator-results/component.js
- app/components/validator-results/styles.scss
- app/components/validator-results/template.hbs
- app/router.js
- app/validator/controller.js
- app/validator/route.js
- app/validator/service.js
- app/validator/template.hbs
- config/environment.js
- ember-cli-build.js
- package.json
- tests/integration/components/validator-input/component-test.js
- tests/integration/components/validator-job/component-test.js
- tests/integration/components/validator-results/component-test.js
- tests/unit/validator/controller-test.js
- tests/unit/validator/route-test.js
- tests/unit/validator/service-test.js
Provides a way to copy in a configuration and see if anything is wrong.
> feat: Add validator UI

- app/components/pipeline-events-list/component.js
- app/pipeline/builds/index/controller.js
- app/pipeline/builds/index/template.hbs
Addresses: https://github.com/screwdriver-cd/screwdriver/issues/589
> fix(589): fix calls to reload() on Array

- app/application/template.hbs
- app/components/artifact-tree/style.scss
- app/components/build-banner/styles.scss
- app/components/build-step-collection/styles.scss
- app/components/pipeline-event-view/styles.scss
- app/components/pipeline-events-list/styles.scss
- app/components/pipeline-header/component.js
- app/components/pipeline-nav/component.js
- app/components/pipeline-options/styles.scss
- app/components/pipeline-secret-settings/styles.scss
- app/components/pipeline-start/styles.scss
- app/components/pipeline-workflow/styles.scss
- app/components/user-link/styles.scss
Currently pipeline detail page has a horizontal scrollbar - https://cd.screwdriver.cd/pipelines/7
This is because of a typo in the css class used at`application/template.hbs` Fixing the scroll bar also requires adjusting padding across pages, hence rest of the changes.
This PR will fix the issue.
> (fix): Fix horizontal scroll bar in pipeline detail page

- app/components/collections-flyout/template.hbs
- tests/acceptance/dashboards-test.js
- tests/integration/components/collections-flyout/component-test.js
Forgot to add some acceptance tests for dashboards previously so adding it in this PR along with some more integration tests for collections-flyout component.
Related PRs: #195, #197, #198, #199
> test(collections): Add more tests for collections / dashboards

- app/components/collection-view/template.hbs
- app/components/collections-flyout/component.js
- app/components/collections-flyout/styles.scss
- app/components/collections-flyout/template.hbs
- tests/acceptance/dashboards-test.js
- tests/integration/components/collections-flyout/component-test.js
Add functionality to delete collections from flyout
Example:
> feat(collections): Delete collections from flyout

- app/components/template-section/styles.scss
Minor tweaks to template list to address weird wrapping behavior.
> fix: css updates for template list

- app/application/controller.js
- app/application/route.js
- app/application/template.hbs
- app/components/app-header/template.hbs
- tests/unit/application/route-test.js
> fix: Stay in current page after login/logout

- screwdriver.yaml
Related to https://github.com/screwdriver-cd/guide/blob/master/screwdriver.yaml#L31-L34, https://github.com/screwdriver-cd/screwdriver/issues/729
> fix: docker trigger after getting latest

- .eslintrc.js
- app/application/controller.js
- app/application/template.hbs
- app/components/build-health/component.js
- app/create/controller.js
- app/dashboard/show/controller.js
- app/dashboard/show/template.hbs
- app/login/controller.js
- app/login/route.js
- app/login/template.hbs
- app/pipeline/builds/build/controller.js
- app/pipeline/builds/build/template.hbs
- app/pipeline/controller.js
- app/pipeline/options/controller.js
- app/pipeline/options/template.hbs
- app/pipeline/secrets/controller.js
- app/pipeline/secrets/template.hbs
- app/pipeline/template.hbs
- app/search/controller.js
- app/search/template.hbs
- app/templates/detail/controller.js
- app/templates/detail/template.hbs
- app/user-settings/controller.js
- app/user-settings/template.hbs
- app/validator/controller.js
Context:
========
Continue to use recommended best-practices from ember team
Objective:
----------
Alias models, or hashed model properties per the recommended eslint rule:
https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/alias-model-in-controller.md
> fix: eslint fixes for ember/alias-model-in-controller

- app/scm/service.js
Due to new eslint 4.10.0:
https://github.com/eslint/eslint/commit/ebb530d
> fix: trailing spaces in comments

- app/components/pipeline-event-view/template.hbs
- app/components/workflow-graph-vis/component.js
- highlight startFrom node for events
> feat: highlight startFrom node for events

- app/utils/git.js
make the checkoutUrl regex consistent as https://github.com/screwdriver-cd/data-schema/blob/master/config/regex.js
> fix: fix the regex for checkoutUrl

- app/components/pipeline-workflow/component.js
- app/pipeline/index/template.hbs
Support restart from any past event. The API part is done and in prod.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/806
> fix: support restart from any past event

- config/coverage.js
- package-lock.json
- package.json
- screwdriver.yaml
Context
========
Collect code coverage metrics
Objective
---------
This repo has long had the configuration for a coverage tool, but for one reason or another we weren't using it. This PR adds back a fixed version of ember-cli-code-coverage so we can once again collect metrics on the coverage of the UI.
> feat: get code coverage reports for the UI

- .gitignore
- README.md
- app/builds/route.js
- app/router.js
- config/environment.js
- tests/unit/builds/route-test.js
Adds route `/builds/buildId` to UI which will redirect to actual url for the build. This is useful when debugging build errors when all you have is the build Id.
> feat: restore builds route

- app/pr-events/service.js
- tests/unit/pr-events/service-test.js
There was a bug where older pr events would prevent dropdowns of PRs from displaying properly
> fix bug where older pr events couldn't display dropdown properly

- app/components/build-banner/component.js
- app/components/build-banner/template.hbs
- app/pipeline/build/controller.js
- app/pr-events/service.js
- tests/integration/components/build-banner/component-test.js
- tests/unit/pr-events/service-test.js
> fix for dropdown not appearing for pr events

- app/404/route.js
- app/404/template.hbs
- app/command/service.js
- app/commands/detail/route.js
- app/components/404-display/styles.scss
- app/components/404-display/template.hbs
- app/dashboard/show/route.js
- app/pipeline/route.js
- app/router.js
- app/template/service.js
- app/templates/detail/route.js
- tests/unit/404/route-test.js
This 404 page appears every time you hit a dead link.
Gonna ask the design team to draw us some dope image and replace the above
related: 
https://github.com/screwdriver-cd/screwdriver/issues/769
> New 404 page

- app/command/service.js
- app/commands/controller.js
- app/commands/namespace/route.js
- app/commands/route.js
- app/commands/template.hbs
- app/components/command-section/styles.scss
- app/components/command-section/template.hbs
- app/router.js
- tests/integration/components/command-section/component-test.js
- tests/unit/commands/controller-test.js
Add breadcrumbs to the commands section 
issue: I'm not sure if there is one.........
> breadcrumbs for command

- app/components/collection-view/component.js
- app/components/collection-view/styles.scss
- app/components/collection-view/template.hbs
- tests/integration/components/collection-view/component-test.js
Can now edit descriptions of collections
> make collection description editable

- app/components/collection-view/component.js
- app/components/collection-view/styles.scss
- app/components/collection-view/template.hbs
- app/components/collections-flyout/component.js
- app/components/collections-flyout/styles.scss
- app/components/collections-flyout/template.hbs
- app/components/pipeline-secret-settings/styles.scss
- app/components/pipeline-secret-settings/template.hbs
- app/components/token-list/style.scss
- app/components/token-list/template.hbs
- app/dashboard/show/controller.js
- app/dashboard/show/template.hbs
- app/search/controller.js
- app/search/template.hbs
- app/styles/screwdriver-modal-styles.scss
- tests/integration/components/collection-view/component-test.js
- tests/integration/components/collections-flyout/component-test.js
Modal Css button color changes and the x which closes the modal is more vertically centered.
Users are now able to add a description to a collection even after they already created the collection by clicking on an area which says "add a description".
Related to https://github.com/screwdriver-cd/screwdriver/issues/1154
> modal css and edit collection description changes

- app/components/collection-dropdown/component.js
- app/components/collection-dropdown/template.hbs
- app/components/collection-modal/component.js
- app/components/pipeline-header/component.js
- app/components/pipeline-header/template.hbs
- app/components/search-list/component.js
- app/components/search-list/template.hbs
- app/pipeline/template.hbs
- app/search/template.hbs
- tests/integration/components/collection-dropdown/component-test.js
- tests/integration/components/collection-modal/component-test.js
When you create a collection from a dropdown, it will automatically add the associated pipeline to the collection
> fast add from collection modal

- screwdriver.yaml
Ah, looks like 10 secs was not enough :(
> fix: increase wait time

- app/build-logs/service.js
- app/components/build-log/component.js
- app/components/build-step-collection/template.hbs
- app/helpers/get-step-data.js
- config/environment.js
- ember-cli-build.js
- package-lock.json
- package.json
- tests/integration/components/build-log/component-test.js
- tests/unit/build-logs/service-test.js
To improve load time for steps with huge amount of logs
Lazily load in more older logs when user scrolls up
Related to https://github.com/screwdriver-cd/screwdriver/issues/1114
> feat(1114): Lazy scrolling load log from bottom for completed step

- app/components/workflow-graph-d3/component.js
This PR fix follow problems for workflow graph.
1. Job names are hiding on a link edge
2. Job names are not fully displayed ([issue1225](https://github.com/screwdriver-cd/screwdriver/issues/1225))
In order to solve the second problem, This PR fix to omit the job name exceeding 20 characters and added a tool tip instead.
Before:
After:
> fix: improve workflow graph

- app/components/build-log/component.js
fix remnant fetch from the component lifecycle
> fix: redundant fetch

- screwdriver.yaml
sleep more since the service takes longer to start
> fix: sleep more since the service takes longer to start

- nginx.conf
need to list ROOT_URL as env  in nginx.conf
> fix: need to list ROOT_URL as env

- nginx.conf
> fix: missing semicolon

- app/pipeline/build/controller.js
- app/pipeline/build/template.hbs
attempt to use explicitly one way binding to a deeper property inside a model, hope this works
> Attempt to fix stale `statusMessage`

- app/build/model.js
- app/build/serializer.js
- app/pipeline/build/controller.js
- app/pipeline/build/template.hbs
- tests/unit/build/model-test.js
- tests/unit/build/serializer-test.js
this should fix the issue where `statusMessage` not updating
doc: https://emberjs.com/api/ember-data/2.18/classes/DS.RESTSerializer/methods
> fix: make status message real

- app/pipeline/events/controller.js
this will fix the stale events after pipeline is changed
> fix: wipe events clean on pipeline change

- app/commands/index/template.hbs
- app/components/tc-collection-list/component.js
- app/components/tc-collection-list/styles.scss
- app/components/tc-collection-list/template.hbs
- app/templates/index/template.hbs
- tests/integration/components/tc-collection-list/component-test.js
- better filtering
- better query debouncing
- better not found message with scope
> fix: better filtering

- app/components/build-log/component.js
- package-lock.json
- tests/integration/components/build-log/component-test.js
modify some wording for init step
> fix: modify wording for init step

- app/components/build-log/component.js
- tests/integration/components/build-log/component-test.js
change init logs for failed init step
> fix: fix init logs when init failed

- app/components/pipeline-events-list/component.js
- app/components/pipeline-events-list/template.hbs
- app/components/pipeline-graph-nav/template.hbs
- app/components/pipeline-pr-view/template.hbs
- app/job/model.js
- app/pipeline/events/controller.js
- app/pipeline/events/template.hbs
- app/styles/app.scss
- app/styles/column-view.scss
- app/utils/build.js
- tests/integration/components/pipeline-events-list/component-test.js
- tests/unit/utils/build-test.js
* fix: colored icon for `CREATED` event status
* fix: widen event column
* fix: reduce column height on event page
* fix: ∞ scroll on event list
* fix: linkable user profile & pr url
* fix: sort PR by creation time
related: https://github.com/screwdriver-cd/screwdriver/issues/1419
blocked by: https://github.com/screwdriver-cd/data-schema/pull/309
> fix(pipeline detail): misc pipeline event page tweak

- app/components/pipeline-event-row/template.hbs
- tests/integration/components/pipeline-event-row/component-test.js
> fix: word choice for event build start

- app/event/model.js
- app/job/model.js
- app/pipeline/events/controller.js
- app/pipeline/events/route.js
- app/pipeline/events/template.hbs
- app/pipeline/pulls/route.js
- app/router.js
- app/styles/app.scss
- package-lock.json
- package.json
- tests/acceptance/pipeline-builds-test.js
- tests/integration/components/pipeline-options/component-test.js
- tests/unit/pipeline/pulls/route-test.js
* fix: computed props on builds
* fix: add route for /pipeline/{}/pulls
related: https://github.com/screwdriver-cd/screwdriver/issues/1337
> fix: update event/PR status based on its build(s) status

- app/components/pipeline-event-row/template.hbs
- app/components/pipeline-graph-nav/template.hbs
- app/event/model.js
- app/event/serializer.js
- tests/integration/components/pipeline-event-row/component-test.js
- tests/integration/components/pipeline-events-list/component-test.js
* fix: truncate commit message
* fix: workflow graph node ordering
> fix: event commit msg & workflow node ordering

- app/build/model.js
- app/components/build-banner/template.hbs
- app/components/build-log/component.js
- app/event/model.js
- app/utils/template.js
- tests/integration/components/build-banner/component-test.js
- tests/unit/build/model-test.js
Build page is failing to load with error:
```
Uncaught TypeError: n.getTime is not a function
```
This PR should check for element before calling getTime() on it.
> fix: Check if value exists before calling getTime

- app/components/build-log/styles.scss
fix: https://github.com/screwdriver-cd/screwdriver/issues/1003
> fix: increase build log height

- app/pipeline/events/controller.js
fix: https://github.com/screwdriver-cd/screwdriver/issues/1475
> fix: get most recent running event

- app/components/artifact-tree/component.js
download artifact upon click
related to: https://github.com/screwdriver-cd/screwdriver/issues/1476
related PRs:
- https://github.com/screwdriver-cd/screwdriver/pull/1498
- https://github.com/screwdriver-cd/store/pull/75
> fix: pass download flag to artifact endpoint

- app/styles/app.scss
by default, it will use red color.
> fix: add color for FROZEN and COLLAPSE icon

- app/components/build-banner/component.js
- tests/integration/components/build-banner/component-test.js
add validation for coverage meta to make it consistent
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1452
> fix(1452): add validation for coverage meta

- app/build/model.js
- app/components/pipeline-event-row/styles.scss
- app/components/pipeline-pr-list/styles.scss
- app/components/pipeline-pr-list/template.hbs
- app/components/pipeline-pr-view/component.js
- app/components/pipeline-pr-view/styles.scss
- app/components/pipeline-pr-view/template.hbs
- app/job/model.js
- app/pipeline/events/controller.js
- app/pipeline/events/template.hbs
- app/styles/column-view.scss
- app/styles/screwdriver-colors.scss
- app/utils/build.js
- tests/integration/components/pipeline-pr-list/component-test.js
- tests/integration/components/pipeline-pr-view/component-test.js
- tests/unit/utils/build-test.js
fix(1067): first step of redesign
fix(source path): do not show job without build
related to: https://github.com/screwdriver-cd/screwdriver/issues/1067
> fix(pr): group jobs under same pr

- app/components/artifact-tree/component.js
fix https://github.com/screwdriver-cd/screwdriver/issues/1551
> fix: open link on file not folder

- nginx.conf
add redirect for the new job badge endpoint
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1451
> fix: add redirect for job badge

- app/build/model.js
- app/components/build-banner/component.js
- app/event/model.js
- app/pipeline/build/route.js
- package-lock.json
- tests/integration/components/build-banner/component-test.js
- tests/unit/build/model-test.js
- tests/unit/pipeline/build/route-test.js
show 7 chars of sha to be consistent with git
> fix: show 7 chars of sha

- app/event/model.js
- app/mixins/model-reloader.js
- app/pipeline/build/route.js
Fix for https://github.com/screwdriver-cd/screwdriver/issues/1545
> fix(1545): disable event reload when in build detail page

- app/application/adapter.js
- app/components/build-step-collection/component.js
- app/components/chart-c3/component.js
- app/metric/model.js
- app/pipeline/build/step/route.js
- app/pipeline/build/template.hbs
- app/pipeline/metrics/controller.js
- app/pipeline/metrics/route.js
- app/pipeline/metrics/template.hbs
- app/router.js
- app/styles/chart.scss
- app/utils/time-range.js
- ember-cli-build.js
- package-lock.json
- package.json
- tests/acceptance/metrics-test.js
- tests/integration/components/build-step-collection/component-test.js
- tests/integration/components/chart-c3/component-test.js
- tests/mock/metrics.js
- tests/unit/application/adapter-test.js
- tests/unit/pipeline/build/step/route-test.js
- tests/unit/pipeline/metrics/controller-test.js
- tests/unit/utils/time-range-test.js
- added the steps chart
- added a filter for successful data points only
- added more preset range options
- added cursor line for better visualize interaction
- added more vibrant colors to color palette
- reduced number of monkey-patched prototype methods from c3
- custom tooltip and legend
- added click to lock down tooltip and fixated on selected data
- added "copy" button to tooltip to copy tooltip's text content to clipboard
- added "only" button to legend to hide all but the selected data
- unified the custom date selector into one calendar view and select dates only
- separated steps chart interaction from the rest of the charts (events and builds)
- refactored based on similarity between the charts
- added deep-linking to build as well as its steps (see tooltip on builds and …
> fix(build metrics): build metrics UI update

- app/components/build-step-collection/component.js
- app/pipeline/build/template.hbs
- app/pipeline/metrics/controller.js
- app/pipeline/metrics/route.js
- app/pipeline/metrics/template.hbs
- clicking on step item will change route
- fix bug on steps metrics w.r.t. success filter
- alias 6mo for 180d
update to: https://github.com/screwdriver-cd/screwdriver/issues/1412
> fix(build metrics): minor issues

- app/components/build-step-collection/component.js
- app/pipeline/build/controller.js
- app/pipeline/build/route.js
- app/pr-events/service.js
- app/utils/build.js
- tests/unit/pipeline/build/controller-test.js
- tests/unit/pipeline/build/route-test.js
1. Always navigate to step url unless build is in success state.
2. Fix for some SHAs not clickable in PR build detail page when selecting a past build.
> fix: PR list drop down to show only valid builds

- app/components/build-log/component.js
fix https://github.com/screwdriver-cd/screwdriver/issues/1640
> fix(1640): correct side effect of inProgress observer

- nginx.conf
Production and Development are running on different servers, namely `nginx` and `express`
Need to update nginx's CSP config to add `frame-src`
> feat: update nginx config for frame-src

- app/components/build-step-collection/component.js
- app/components/build-step-collection/template.hbs
- app/pipeline/build/artifacts/route.js
- app/pipeline/build/controller.js
- app/pipeline/build/route.js
- app/pipeline/build/step/route.js
- app/pipeline/build/template.hbs
- app/router.js
- package.json
- tests/unit/pipeline/build/artifacts/route-test.js
Users want to be able to share build's artifacts link
Create a route so users can share its artifacts link with other people
> feat: made artifacts into a separate route

- app/components/pipeline-event-row/component.js
- app/components/pipeline-event-row/styles.scss
- app/components/pipeline-event-row/template.hbs
- app/components/pipeline-graph-nav/template.hbs
- app/components/pipeline-parameterized-build/component.js
- app/components/pipeline-parameterized-build/styles.scss
- app/components/pipeline-parameterized-build/template.hbs
- app/components/pipeline-start/component.js
- app/components/pipeline-start/styles.scss
- app/components/pipeline-start/template.hbs
- app/components/pipeline-workflow/component.js
- app/components/pipeline-workflow/template.hbs
- app/components/validator-job/template.hbs
- app/components/validator-pipeline/template.hbs
- app/components/validator-results/component.js
- app/components/validator-results/template.hbs
- app/components/workflow-graph-d3/component.js
- app/event/serializer.js
- app/pipeline/events/controller.js
- app/pipeline/events/template.hbs
- app/pipeline/model.js
- app/utils/constants.js
- tests/integration/components/pipeline-parameterized-build/component-test.js
Some users want to create builds based on some input without changing their screwdriver template yaml files. 
```
shared:
image: node:8
jobs:
main:
steps:
- test: echo ok
parameters:
auth_strategy: simple
user:
value: sd-bot
description: User running build
```
See screenshot: 
This PR added the ability to users to use customized parameters to build as their pipeline needs.
https://github.com/screwdriver-cd/screwdriver/issues/1339
> fix(1339): add parameters to validator

- app/components/build-log/component.js
- app/components/pipeline-event-row/template.hbs
- app/components/pipeline-workflow/template.hbs
- app/helpers/get-length.js
- tests/integration/components/build-log/component-test.js
- tests/integration/helpers/get-length-test.js
Add in `sd-init-step` to show `parameters` for current build
This PR adds exactly that, see screenshot
> fix: add parameters info to sd-setup-init

- app/application/controller.js
- app/application/template.hbs
- app/components/app-header/component.js
- app/components/app-header/template.hbs
- package-lock.json
User has to do a reload of SD UI page to start seeing collections tab after login.
With My pipelines, user always have at least one collection.
> fix: always show collection

- app/components/collection-dropdown/component.js
- app/components/pipeline-start/component.js
- app/pipeline/controller.js
Fix a small bug that adding pipeline to collection.
This PR fixed the function arguments from model to `model.id`.
> fix: change collection to collection.id

- app/pipeline/controller.js
- tests/unit/pipeline/controller-test.js
> fix: typo of array.includes

- app/pipeline/metrics/controller.js
- app/pipeline/metrics/route.js
- app/pipeline/metrics/template.hbs
- tests/unit/pipeline/metrics/controller-test.js
selected job isn't the only job that is displaying
- fix display issue on the chart and legend
- fix bug on missing check of valid job id on pipeline
https://github.com/screwdriver-cd/screwdriver/issues/1822
> fix(build metrics): #1822 inquired job display issue

- app/components/pipeline-nav/template.hbs
- app/utils/build.js
- tests/integration/components/pipeline-graph-nav/component-test.js
1) remove beta on metrics class
2) change icon from times-circle to stop-circle for consistency sake
Before
After
Before:
After:
For Metrics: https://cd.screwdriver.cd/pipelines/1/metrics
Before:
After:
Add tests
> fix: minor ui design changes

- app/components/pipeline-workflow/component.js
- app/components/workflow-graph-d3/component.js
- tests/integration/components/pipeline-workflow/component-test.js
Building on top of https://github.com/screwdriver-cd/ui/pull/518
> fix: downstream workflow chart

- app/components/pipeline-graph-nav/template.hbs
- app/components/pipeline-list-coverage-cell/component.js
- app/components/pipeline-list-coverage-cell/template.hbs
- app/components/pipeline-list-history-cell/component.js
- app/components/pipeline-list-history-cell/styles.scss
- app/components/pipeline-list-history-cell/template.hbs
- app/components/pipeline-list-view/component.js
- app/components/pipeline-list-view/template.hbs
- app/helpers/is-number.js
- app/pipeline/events/controller.js
- app/pipeline/events/template.hbs
- app/shuttle/service.js
- config/environment.js
- tests/integration/components/pipeline-graph-nav/component-test.js
- tests/integration/components/pipeline-list-coverage-cell/component-test.js
- tests/integration/components/pipeline-list-history-cell/component-test.js
- tests/integration/components/pipeline-list-view/component-test.js
- tests/integration/helpers/is-number-test.js
- tests/unit/shuttle/service-test.js
Fixed items
See pending items in 
https://github.com/screwdriver-cd/screwdriver/issues/1967#issuecomment-630981995
Screenshot: 
- [Ember Test Helpers](https://github.com/emberjs/ember-test-helpers/blob/master/API.md)
> feat(1967): aggregate view bug fixes

- app/application/adapter.js
- app/build/adapter.js
- app/components/pipeline-list-actions-cell/template.hbs
- app/pipeline/events/controller.js
- tests/integration/components/pipeline-list-actions-cell/component-test.js
- tests/unit/pipeline/events/controller-test.js
1. disable  `skip further` until UI can ask for user choice
1. create fresh build for play button
1. fix restart build interaction 
> fix(1967): play button should create a fresh build.

- app/components/create-pipeline/component.js
- app/components/pipeline-create-form/component.js
- app/components/pipeline-create-form/template.hbs
- tests/integration/components/create-pipeline/component-test.js
Per community request, we are adding another useful feature to group templates by namespace 
Reference: https://github.com/screwdriver-cd/screwdriver/issues/2140
> fix(2140): add group by namespace when create pipeline

- app/components/validator-job/styles.scss
- app/components/validator-pipeline/styles.scss
Follow up of https://github.com/screwdriver-cd/ui/pull/576
Fix typo mentioned in https://github.com/screwdriver-cd/ui/pull/576#discussion_r466523277
> fix: typo in style

- app/components/pipeline-workflow/component.js
Fix typo that should not assign to `x.value` after retrieving values
> fix: verbose variable name and assignment typo for parameters

- app/components/pipeline-event-row/component.js
- app/components/pipeline-event-row/template.hbs
Fixes screwdriver-cd/screwdriver#1415
This PR adds displaying of subscribed events in the UI.
screwdriver-cd/screwdriver#1415
> feat(1415): Add displaying of subscribed events

- app/components/build-log/component.js
- tests/integration/components/build-log/component-test.js
We are moving download logic from ui to api
remove download logic from ui
https://github.com/screwdriver-cd/screwdriver/issues/2068
> fix(2068): remove download logic from ui

- app/components/build-log/component.js
Fix some syntax on https://github.com/screwdriver-cd/ui/pull/587
> fix: pr587 ember syntax

- app/components/build-log/styles.scss
> fix: make fullscreen log to take 100% width and height

- app/components/build-log/template.hbs
It's confusing to some users what these buttons do before they actually click on it.
Add title to show tooltip to help users to recognize what these buttons do 
> fix: add title to show tooltip for zoom and line wrap

- nginx.conf
To check for release env we need env variable exposed via the nginx config
This PR adds the env variable via the nginx.conf
> feat: add nginx config for env var

- nginx.conf
To fix static assets 404 error we need to add a cookie via the nginx on ui
This PR adds lua script to check if cookie exists and adds if not
> feat: add check for existing cookie

- app/components/pipeline-nav/component.js
- app/event/serializer.js
- app/pipeline/events/controller.js
- package-lock.json
- package.json
- tests/unit/pipeline/serializer-test.js
Nodes often disappear when showing triggers.
> fix: invalid workflow graph with triggers

- app/components/pipeline-options/component.js
- app/components/pipeline-options/styles.scss
- app/components/pipeline-options/template.hbs
- app/pipeline/model.js
- app/pipeline/options/controller.js
- app/pipeline/serializer.js
- app/shuttle/service.js
- app/utils/build.js
- config/environment.js
- tests/acceptance/pipeline-options-test.js
- tests/integration/components/pipeline-options/component-test.js
Allow users to define their own downtime jobs
> feat(2199): add pipeline settings

- app/components/pipeline-list-metrics-cell/component.js
- app/components/pipeline-list-metrics-cell/template.hbs
- app/components/pipeline-list-view/component.js
- tests/integration/components/pipeline-list-view/component-test.js
Add a link to job metrics from the list view.
> feat: Add link to job metrics

- app/pipeline/events/controller.js
In some cases, an error is thrown when rendering a workflow graph with triggers.
This PR fixes this error.
> fix: error while rendering graph with triggers

- screwdriver.yaml
We are passing coverage to a deprecated sonar property 
Change to correct sonar property
> Fix sonar setting

- app/components/collection-table-row/component.js
- app/components/pipeline-card/component.js
- package-lock.json
- package.json
This is a follow up pr for https://github.com/screwdriver-cd/ui/pull/633
Apply lazy loading for pipeline card/row component in collection page
https://github.com/screwdriver-cd/screwdriver/issues/2267
> feat(2267): apply lazy loading

- app/utils/graph-tools.js
a potential dfs bug which could cause block on call stack
expect no regression for DAG
> fix: dfs bug?

- app/search/controller.js
- app/search/route.js
- tests/acceptance/search-test.js
Spaces in search text doesn't return any results.
> feat: ignore spaces when searching.

- app/pipeline/events/controller.js
- app/pipeline/events/index/route.js
- app/pipeline/events/route.js
- app/pipeline/jobs/index/controller.js
- app/pipeline/jobs/index/route.js
- app/utils/error-messages.js
Follow up of https://github.com/screwdriver-cd/ui/pull/661
Show empty job list rather than not show jobs.
> fix: runtime error which does not have default values

- app/components/pipeline-options/component.js
- app/components/pipeline-options/template.hbs
- app/components/pipeline-workflow/component.js
- app/components/pipeline-workflow/template.hbs
- app/components/workflow-graph-d3/component.js
- app/pipeline/events/controller.js
- app/pipeline/events/route.js
- app/pipeline/events/template.hbs
- app/preference/pipeline/model.js
- app/shuttle/service.js
- app/utils/error-messages.js
- tests/acceptance/create-page-test.js
- tests/acceptance/dashboards-test.js
- tests/acceptance/pipeline-builds-test.js
- tests/acceptance/pipeline-options-test.js
- tests/acceptance/pipeline-pr-chain-test.js
- tests/integration/components/pipeline-options/component-test.js
- tests/integration/components/pipeline-workflow/component-test.js
Follow up of https://github.com/screwdriver-cd/ui/pull/665
> fix: add hide PR button under pipeline options with remote support

- screwdriver.yaml
update k8s host
update k8s host
> fix: update k8s host [skip ci]

- app/pipeline/events/controller.js
To fix scrolling issue introduced in PR: https://github.com/screwdriver-cd/ui/pull/678/files
> fix: scroll on events

- app/components/workflow-graph-d3/component.js
- app/pipeline/events/route.js
- app/pipeline/route.js
It works fine for pipeline like this:
But, runs into issues if the pipeline is customizied. 
Original: 
Before(which has error): 
The implementation of this is not recursive, and only removes one level.
1) Fix above error to be:
After(fixed):
2) This PR also fix redirect to 404 for non-existing pipelines
> fix: implement branch removal to recursion

- app/components/pipeline-options/component.js
- app/components/pipeline-options/template.hbs
Minor UX improvements
1) filter pr jobs in downdown
2) change label
> fix(ux improvements): filter pr jobs in dropdown and change label

- nginx.conf
* add variable declarations in nginx
- Nginx removes all variables excepted declared explicitly http://nginx.org/en/docs/ngx_core_module.html#env
> fix: update nginx environment variables

- nginx.conf
Update CSP to enable feedback widgets (allow fetching from 3rd party JavaScripts, such as analytics or translations)
Split the PR https://github.com/screwdriver-cd/ui/pull/696. In this PR, just update the CSP policy in `nginx.conf`.
> fix: update nginx.conf

- app/utils/graph-tools.js
> fix: skip cycle when walking graph

- nginx.conf
> fix: add defaultSrc to nginx.conf

- app/components/pipeline-workflow/component.js
fix the error reported below
https://github.com/screwdriver-cd/ui/pull/706/files#r620569516
Fix the error and enables linking to upstream/downstream jobs.
No error occurs.
> fix: the error on remote node selected

- app/components/pipeline-options/component.js
- app/components/pipeline-options/template.hbs
- app/shuttle/service.js
- tests/integration/components/pipeline-options/component-test.js
add an option in pipeline option to set pipeline to public
add an option in pipeline option to set pipeline to public
https://github.com/screwdriver-cd/screwdriver/issues/466
> fix(466): allow user to set pipeline to public

- app/components/pipeline-event-row/component.js
- app/components/pipeline-event-row/template.hbs
- app/components/pipeline-list-view/component.js
- app/components/pipeline-list-view/template.hbs
- app/components/pipeline-parameterized-build/component.js
- app/components/pipeline-parameterized-build/styles.scss
- app/components/pipeline-parameterized-build/template.hbs
- app/components/pipeline-start/component.js
- app/components/pipeline-start/template.hbs
- app/components/pipeline-workflow/component.js
- app/components/pipeline-workflow/template.hbs
- app/components/validator-job/template.hbs
- tests/integration/components/pipeline-parameterized-build/component-test.js
- tests/mock/jobs.js
Ability to define parameters at job level
Create builds with job level parameters
[screwdriver-cd/screwdriver#2346](https://github.com/screwdriver-cd/screwdriver/issues/2346)
> feat(2346): Support for job level parameters

- app/components/pipeline-options/component.js
- app/pipeline/events/show/route.js
Click on the options tab does not reflect the changes.
Fix the property path to reflect the changes
> fix: groupedEvents not being updated in option tab

- app/components/pipeline-options/component.js
- app/components/pipeline-options/template.hbs
- app/pipeline/events/controller.js
- app/pipeline/events/route.js
- app/pipeline/model.js
- app/shuttle/service.js
Add an option to set default behavior to show trigger
https://github.com/screwdriver-cd/screwdriver/issues/2610
> feat(2610): Add ability to save the preference of show triggers

- tests/acceptance/dashboards-test.js
- tests/integration/components/collection-table-row/component-test.js
- tests/integration/components/collection-view/component-test.js
- tests/integration/components/pipeline-card/component-test.js
- tests/integration/components/pipeline-list-coverage-cell/component-test.js
Some tests occasionally fails, so we should manually retry tests.
This PR fix component tests.
- Wait for pipeline-card, coverage-value rendering
- Set view mode of pipeline-card before tests
- Some tests should run in list-view mode, but these run in card-view mode.
- Ignore [this test](https://github.com/screwdriver-cd/ui/pull/782/files#diff-1d40fc3763f6a0d8c53bccb59972eb04fc0386972af290e245f57918576cb977R769-R789) since this feature is not implemented.
- Currently, this test succeeds when in "card-view" mode.
I tried PR build 5 times and these succeeded.
- https://cd.screwdriver.cd/pipelines/7/builds/788447/steps/test
- https://cd.screwdriver.cd/pipelines/7/builds/788448/steps/test
- https://cd.screwdriver.cd/pipelines/7/builds/788453/steps/test
- …
> fix: occasional failing tests

- app/components/pipeline-create-form/template.hbs
- app/components/pipeline-rootdir/template.hbs
- tests/acceptance/create-page-test.js
- tests/integration/components/pipeline-create-form/component-test.js
We cannot toggle a checkbox by clicking its label text.
This PR make it possible to toggle a checkbox by clicking its label text.
> fix: toggle checkbox when label text clicked

- tests/acceptance/pipeline-builds-test.js
Successor of https://github.com/screwdriver-cd/ui/pull/792
Add a test to catch non-existing-build redirects.
Ember route transition tests
https://github.com/emberjs/ember-test-helpers/compare/master...rwjblue:settled-router-transitions
> fix: add acceptance test for build not found

- app/collection/model.js
- app/collection/serializer.js
- app/components/collection-table-row/component.js
- app/components/collection-view/component.js
- app/components/collection-view/styles.scss
- app/components/collection-view/template.hbs
- tests/unit/pipeline/events/controller-test.js
* Dry code
* Update CSS
* Updated the serializer for the collection model by modifying the response to insert links for metrics
Screenshot
https://user-images.githubusercontent.com/15989893/174139104-2b9886fe-50e3-4f96-a163-7149a4e30ca7.mp4
When reviewing PR https://github.com/screwdriver-cd/ui/pull/787, I found computed property `failedBuildCount` does not work properly, because it depends on a property that API does not return, so UI needs to modify and insert the `metrics` [links](https://swagger.io/docs/specification/links/) for its rest adapter/serializer 
Also cleaned up on CSS to look nicer.
https://github.com/screwdriver-cd/ui/pull/787
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I …
> fix: dry code and update css style

- app/components/pipeline-workflow/template.hbs
This is a correction to the following PR
https://github.com/screwdriver-cd/ui/pull/795
There was a correction omission in the PR here.
The UI is showing the following error
```
Uncaught TypeError: Cannot read properties of undefined (reading 'find')
```
This error occurs because the pipeline information has not been obtained.
Make sure to pass pipeline information to the Component to be used.
Related to https://github.com/screwdriver-cd/ui/pull/795
> fix(2539): Failure to correct pipeline-workflow

- app/components/pipeline-options/component.js
- app/components/pipeline-options/styles.scss
- app/components/pipeline-options/template.hbs
it's not clear how to interact with pipeline alias section. Also, when trying to set pipeline alias, I don't get any sort of feedback that a request was sent or the action was successful.
User should see an alert displaying 'pipeline alias-name updated successfully'.
https://github.com/screwdriver-cd/screwdriver/issues/2750
> fix for pipeline alias interaction

- app/components/collection-table-row/styles.scss
- app/components/collection-table-row/template.hbs
- app/components/collection-view/styles.scss
- app/components/collection-view/template.hbs
- app/components/pipeline-options/component.js
- app/components/pipeline-options/styles.scss
- app/components/pipeline-options/template.hbs
- tests/acceptance/pipeline-options-test.js
- tests/integration/components/collection-view/component-test.js
- tests/integration/components/pipeline-options/component-test.js
UI changes for collection Dashboard.
Some minor UI changes for Collection Dashboard and pipeline options. 
Expected:
https://github.com/screwdriver-cd/screwdriver/issues/2758
> fix: UI changes for Collection Dashboard and pipeline options

- app/components/pipeline-options/component.js
- tests/unit/preference/pipeline/serializer-test.js
- tests/unit/preference/user/serializer-test.js
Add test coverages
Add tests to prevent accidental code changes
https://github.com/screwdriver-cd/ui/pull/820
> fix: add tests for user-settings

- Dockerfile
grep was broke because old url does not contain download link
resort to github api instead
> fix: update github link

- app/components/collection-view/template.hbs
To apply sorting on branch column in collection dashboard.
> feat : Add sorting on branch

- app/components/collection-view/template.hbs
- app/pipeline/model.js
Apply sorting on status column in collection Dashboard.
Priority based sorting on status column.
> feat: Sorting on status column

- app/components/build-banner/component.js
- app/components/pipeline-child-list-actions-cell/component.js
- app/components/pipeline-child-list-actions-cell/styles.scss
- app/components/pipeline-child-list-actions-cell/template.hbs
- app/components/pipeline-child-list-state-cell/component.js
- app/components/pipeline-child-list-state-cell/styles.scss
- app/components/pipeline-child-list-state-cell/template.hbs
- app/components/pipeline-list/component.js
- app/components/pipeline-list/styles.scss
- app/components/pipeline-list/template.hbs
- app/components/pipeline-start/component.js
- app/components/pipeline-start/template.hbs
- app/components/pipeline-workflow/component.js
- app/pipeline/build/template.hbs
- app/pipeline/child-pipelines/controller.js
- app/pipeline/child-pipelines/route.js
- app/pipeline/child-pipelines/template.hbs
- app/pipeline/events/controller.js
- app/pipeline/events/template.hbs
- app/pipeline/jobs/index/controller.js
- app/pipeline/jobs/index/template.hbs
- app/pipeline/model.js
- app/styles/screwdriver-colors.scss
- app/utils/pipeline.js
- tests/acceptance/pipeline-childPipelines-test.js
- tests/integration/components/pipeline-list/component-test.js
- tests/integration/components/pipeline-start/component-test.js
- tests/unit/utils/pipeline-test.js
Changes were made in https://github.com/screwdriver-cd/models/pull/534 and https://github.com/screwdriver-cd/screwdriver/pull/2724 to stop auto deletion of child pipelines when the SCM URLs removed/modified in the external config.
Child pipeline state will be set to `INACTIVE` when the associated SCM URL has been removed in the external configuration.
Pipeline admin can review and take necessary action on such inactive child pipeline
- reactivate the pipeline by restoring the SCM URL in the external config
- explicitly delete the pipeline from the UI/API
This PR includes changes in the UI to notify the user if inactive child pipeline exists and provide an option to delete it.
Here is the page level breakdown of UI changes...
1. Display info message at the top when there is one or more …
> Manage child pipelines

- app/utils/time-range.js
- tests/integration/components/pipeline-event-row/component-test.js
- tests/integration/components/pipeline-graph-nav/component-test.js
To fix timezone.
To set timezone as user local timezone.
> fix: timezone as per user local tz

- app/components/collection-view/component.js
- app/components/collection-view/styles.scss
- app/components/collection-view/template.hbs
- app/utils/metric.js
- app/utils/sort-functions.js
- package-lock.json
- tests/integration/components/collection-view/component-test.js
- tests/unit/utils/sort-functions-test.js
sorting on status column.
To sort status column based on priority sort.
> fix: Sorting on collection dashboard

- app/components/workflow-graph-d3/component.js
Before
After
This PR fixes the broken lines.
https://github.com/screwdriver-cd/screwdriver/issues/2803
> fix(2803): workflow graph line became dashed with too many vertical jobs

- app/components/collection-table-row/component.js
- app/components/collection-view/component.js
- app/components/pipeline-card/component.js
- app/utils/sort-functions.js
- tests/integration/components/collection-view/component-test.js
- tests/unit/utils/sort-functions-test.js
The collection view currently renders the received data from the backend as is, users have to click on each header to sort
1) let the initial collection view sort by name as default
2) use locale sort instead of string sort with case in-sensitivity
https://github.com/screwdriver-cd/screwdriver/issues/2806
> fix: collection sort

- app/components/pipeline-event-row/styles.scss
- app/components/pipeline-event-row/template.hbs
- tests/integration/components/pipeline-event-row/component-test.js
To make label clickable in events card.
To make label displayed in the Event Card also clickable.
https://github.com/screwdriver-cd/screwdriver/issues/2833
> Make label link clickable event cards

- app/components/build-banner/styles.scss
- app/components/build-banner/template.hbs
PR title not displaying correct.
> fix: PR title

- app/components/build-banner/component.js
- app/components/build-banner/template.hbs
To fix template label and link.
> fix: template label and link

- app/components/pipeline-list-history-cell/template.hbs
- tests/integration/components/pipeline-list-history-cell/component-test.js
add tests to PR https://github.com/screwdriver-cd/ui/pull/898
> feat:display build date/time

- app/components/pipeline-list-history-cell/template.hbs
- tests/integration/components/pipeline-list-history-cell/component-test.js
update moment format from DD/MM/YYYY HH:mm to MM/DD/YYYY HH:mmA
Before:
After:
> fix: update moment format from DD/MM/YYYY HH:mm to MM/DD/YYYY HH:mmA

- app/create/controller.js
- app/create/template.hbs
- app/styles/app.scss
- app/styles/create.scss
cd.screwdriver.cd/create & the create button should behave similarly, clicking the create button should have a permanent url.
before:
after:
https://github.com/screwdriver-cd/screwdriver/issues/2576
> fix: create & create pipeline button same route

- app/components/pipeline-event-row/template.hbs
- app/components/pipeline-events/component.js
- app/components/pipeline-nav/component.js
- app/components/validator-input/component.js
- tests/integration/components/pipeline-event-row/component-test.js
Bug fixes due to update Ember.js.
Fix below bugs.
- If event has label, label is rendered twice in the cell.
- The pipeline description shown wrong place.
- In the validator page, validate configuration cannot be collapsed.
- screwdriver-cd/screwdriver#2846
screwdriver-cd/screwdriver#2838
screwdriver-cd/screwdriver#2846
> fix(2838): Fix ember update bugs

- app/components/app-header/styles.scss
- app/components/artifact-tree-children/component.js
- app/components/artifact-tree-children/template.hbs
- app/components/artifact-tree-expander/component.js
- app/components/artifact-tree-expander/template.hbs
- app/components/artifact-tree/template.hbs
- app/components/bread-crumbs/style.scss
- app/components/bread-crumbs/template.hbs
- app/components/command-header/styles.scss
- app/components/command-header/template.hbs
- app/components/pipeline-list-view/component.js
- app/components/pipeline-search-panel/template.hbs
- app/components/tc-collection-list/styles.scss
- app/components/template-header/styles.scss
- app/components/template-header/template.hbs
Display corruption due to update Ember.js are fixed.
Fix the following display corruption and so on.
- The url does not update when we click on the artifacts' directory
- The url with directory link, artifact does not expand if the directory
- It is originally working when we added `/` at the end. With this modification, it is no longer necessary to add it. However, if we do not put `/` at the end, we get a Not Found error.
- The sort icons in job list view are not displayed
- The links to pipelines are not working in the modal to find pipeline and add to collection
- The search icon is corrupted
- Color of links on template/command page are changed
https://github.com/screwdriver-cd/screwdriver/issues/2838
https://github.com/screwdriver-cd/screwdriver/issues/2844
I confirm that this …
> fix(2838): Fix ember update display corruption

- app/components/pipeline-parameterized-build/template.hbs
The following PRs are missing fixes.
https://github.com/screwdriver-cd/ui/pull/916
The call parameter of action is different
Modify onkeydown -> onKeydown
https://github.com/screwdriver-cd/ui/pull/916
> fix(2838): Correction of small parameters

- app/components/pipeline-events/component.js
- app/components/pipeline-options/component.js
- app/pipeline/events/route.js
- app/pipeline/model.js
Follow up of https://github.com/screwdriver-cd/ui/pull/914
Sample Pipeline: https://cd.screwdriver.cd/pipelines/11326/events/735254
> fix: option to filter events that started by Screwdriver scheduler

- app/components/pipeline-graph-nav/styles.scss
- app/components/pipeline-list-view/styles.scss
- app/styles/chart.scss
Display corruption due to update Ember.js are fixed.
Fixed css not being applied to buttons.
https://github.com/screwdriver-cd/screwdriver/issues/2838#issuecomment-1544555560
> fix(2838): Last successful button style

- app/components/build-banner/styles.scss
- app/components/events-thumbnail/styles.scss
- app/components/pipeline-list-history-cell/styles.scss
- app/components/pipeline-list-job-cell/styles.scss
- app/components/workflow-graph-d3/component.js
- app/components/workflow-graph-d3/styles.scss
- app/event/model.js
- app/pipeline/build/template.hbs
- app/pipeline/jobs/index/controller.js
- app/styles/app.scss
- app/utils/build.js
- app/utils/graph-tools.js
https://github.com/screwdriver-cd/screwdriver/issues/2878
> feat(2878): add support for displaying user defined warnings

- app/components/validator-job/template.hbs
Before
After:
https://github.com/screwdriver-cd/screwdriver/issues/2920
> fix: add display for freezeWindow to validator and template view

- app/components/validator-job/template.hbs
- tests/integration/components/validator-job/component-test.js
Add tests for PR: https://github.com/screwdriver-cd/ui/pull/947
> fix: add tests for display for freezeWindow

- app/components/pipeline-header/component.js
- app/components/pipeline-header/template.hbs
Add description `SonarQube project: ${ID}` as tooltip for sonar badge
Screenshot: 
> fix: add and update tooltip description for SonarQube project

- app/user-settings/preferences/controller.js
Follow up for #992 
Need to await receive requestPermission response for change user settings after allow notification in first time.
Add await to requestPermission
screwdriver-cd/screwdriver#2369
> fix(2369): await requestPermission

- app/validator/service.js
Update regex in service.js to validate pipeline template
Update regex in service.js to validate pipeline template
> Update regex in service.js to validate pipeline template

- tests/unit/utils/graph-tools-test.js
Found a console.log in a test that isn't required
Remove a console.log that was checked into a test accidentally.
> Remove console log in test

- app/components/app-body/styles.scss
- app/components/app-body/template.hbs
- app/components/pipeline-events/style.scss
- app/components/pipeline-events/template.hbs
- app/components/pipeline-graph-nav/styles.scss
- app/components/pipeline-graph-nav/template.hbs
- app/components/pipeline-header/styles.scss
- app/components/pipeline-header/template.hbs
- app/components/pipeline-nav/styles.scss
- app/components/pipeline-workflow/styles.scss
- app/styles/app.scss
- tests/acceptance/pipeline-builds-test.js
- tests/acceptance/pipeline-pr-chain-test.js
- tests/integration/components/pipeline-graph-nav/component-test.js
- tests/integration/components/pipeline-header/component-test.js
The pipeline events page vertically overflows a bit causing the page to have a less than ideal user experience when vertically scrolling.
Restyle the pipeline events page to all fit within the vertical height of the window.  Also makes a few minor improvements for narrow widths so that elements will horizontally scroll rather than overflowing.
See image for summary of changes
https://github.com/screwdriver-cd/screwdriver/issues/2903
> fix: update pipeline events page style

- app/components/tc-collection-list/component.js
- tests/integration/components/tc-collection-list/component-test.js
commands table is not rendered correctly 
To add more integration tests to cover the code changes
> fix: commands table is not rendered correctly and add more tests

- app/templates/pipeline/detail/controller.js
- tests/acceptance/pipeline-template-test.js
add annotations and parameters to display for pipeline template
Before
After
https://github.com/screwdriver-cd/screwdriver/issues/3091
> fix(3091): display annotations and parameters for pipeline template

- app/router.js
These routes were not used, and need to be deleted
https://github.com/screwdriver-cd/ui/pull/1040
> fix: rm v2.dashboard routes

- app/components/loading-view/component.js
Add a new quote since it has been a while. 
> feat: add an item to the funny quote for loading

- app/components/newui-event-card/component.js
- app/components/newui-event-card/styles.scss
- app/components/newui-event-card/template.hbs
- app/v2/pipeline/events/route.js
- app/v2/pipeline/events/show/route.js
- app/v2/pipeline/events/template.hbs
- tests/integration/components/newui-event-card/component-test.js
Add event status, and builds' status to event card
Screenshot:
> feat: add event status and builds' status to event card

- app/components/pipeline/modal/toggle-job/component.js
- app/components/pipeline/modal/toggle-job/styles.scss
- app/components/pipeline/modal/toggle-job/template.hbs
- app/components/pipeline/styles.scss
- package-lock.json
- package.json
- tests/integration/components/pipeline/modal/toggle-job/component-test.js
Create a new glimmer component for the job toggle modal used in the pipeline events routes.  The existing modal component isn't compatible with the new UI work, so a new component needs to be created.
> feat: Glimmer component for job toggle modal

- app/components/workflow-graph-d3/component.js
Nodes of a stage are sometimes rendered outside the stage.
All the nodes of a stage should be enclosed within the the stage container irrespective of the position of other stages.
**Before:**
**After:**
https://github.com/screwdriver-cd/screwdriver/issues/3134
> fix(3134): Stage nodes sometimes are rendered outside the stage in the workflow graph

- app/components/collection/modal/add-to-collection/styles.scss
- app/components/collection/modal/add-to-collection/template.hbs
- tests/integration/components/collection/modal/add-to-collection/component-test.js
Updates the `Add to Collection` modal to use the latest shared modal styles of the new UI.  Adds a few other small changes to the modal so that the sections for user interaction have more context.
Updating the new UI to have a more consistent look and feel for modals.
> fix: Update add to collection modal

- tests/unit/utils/pipeline/parameters-test.js
The default value of parameter may contain an array, so add a test that handles arrays.
> fix: add test for parameter-utils

- app/components/validator-results/template.hbs
Should see workflowGraph when validating pipeline template.
This PR adds workflowGraph and stages to validator info for pipeline template. Also fixes annotations.
Related to https://github.com/screwdriver-cd/screwdriver/issues/3115
> fix(3115): Show workflowGraph for pipeline template validation

- app/templates/pipeline/detail/template.hbs
This PR adds some fields to pipeline template detail page.
Related to https://github.com/screwdriver-cd/ui/pull/1102
> fix: Add fields to pipeline template detail page

- app/components/pipeline/workflow/styles.scss
- app/components/pipeline/workflow/tooltip/component.js
- app/components/pipeline/workflow/tooltip/styles.scss
- app/components/pipeline/workflow/tooltip/template.hbs
- tests/integration/components/pipeline/workflow/tooltip/component-test.js
New tooltip menu for the v2 UI's workflow graph.  This requires the use of the tooltip utility from #1095.
Adds a new glimmer component for the workflow graph tooltip.
> feat: New tooltip component

- app/components/pipeline-options/template.hbs
- tests/integration/components/pipeline-options/component-test.js
Follow up for #1086 
The admin section has no executable buttons, so I just included a description of admin.
Modify admin section's description on the option page.
> fix: Fix admin description

- app/components/pipeline/event/card/util.js
- tests/unit/components/pipeline/event/card/util-test.js
The event card has a lot of information contained in it and a number of those values are calculated and extracted from the API responses.
Provide utility functions for the calculated values that need to be used in the event card component.
> feat: Utilities for rendering event cards

- app/v2/pipeline/events/show/styles.scss
- app/v2/pipeline/events/styles.scss
The styles related to the workflow graph should be moved to a child stylesheet.  This better aligns with the template structure and will allow for inclusion of error pages within the template in the future.
Refactor the styles related to the workflow graph.
> fix: Refactor workflow graph styles

- app/components/pipeline/event/card/component.js
- app/components/pipeline/event/card/styles.scss
- app/components/pipeline/event/card/template.hbs
- app/components/pipeline/event/styles.scss
- app/components/pipeline/styles.scss
- app/utils/pipeline/build.js
- app/utils/pipeline/event.js
- app/v2/pipeline/events/show/route.js
- app/v2/pipeline/events/show/template.hbs
- tests/integration/components/pipeline/event/card/component-test.js
- tests/unit/utils/pipeline/build-test.js
- tests/unit/utils/pipeline/event-test.js
Adding in a new component for event cards in the v2 UI.  The old ones were built using ember data, and are incompatible with how the v2 UI operates.
Provide a new component for the event cards for the v2 UI.  The new cards follow the general pattern of using modals for actions that require user confirmations.
Basic event card:
Event card with background color used for hover states (also note that the commit hash is highlighted indicating it is the latest commit):
Event card with background highlight indicating the event is the currently selected:
Event card showing the placement of the lab
el metadata:
Event card showing the placement of the configured parameters of an event:
Event card showing the abort button for an event that is still running:
I confirm that this contribution is made …
> feat: New event card for v2 UI

- package-lock.json
- package.json
Reverts screwdriver-cd/ui#1149
> fix: Revert "build(deps-dev): bump webpack from 5.76.2 to 5.94.0"

- package-lock.json
- package.json
Reverts screwdriver-cd/ui#1147
> fix: Revert "build(deps-dev): bump bootstrap from 4.6.2 to 5.0.0"

- package-lock.json
- package.json
`ember-models-table` v5 was released almost a year ago and does not contain any breaking changes that affect our code.
Update the `ember-models-table` dependency to the latest version
> fix: Update ember-models-table

- app/v2/pipeline/controller.js
- app/v2/pipeline/jobs/route.js
- app/v2/pipeline/jobs/styles.scss
- app/v2/pipeline/jobs/template.hbs
- app/v2/pipeline/styles.scss
- app/v2/pipeline/template.hbs
#1171 provides the new v2 UI for the jobs route.  This UI needs some additional UI elements to fully complete the UI for the new route's landing page.
Integrate the new v2 jobs UI into the v2 route.
Depends on #1156 and #1171
> feat: Integrate v2 jobs route

- app/components/pipeline/event/card/template.hbs
The event card template has some funky spacing of the elements.
Fix the mis-aligned template spacing.
> fix: Fix spacing in card template

- app/components/pipeline/event/card/styles.scss
- app/components/pipeline/event/card/template.hbs
- tests/integration/components/pipeline/event/card/component-test.js
Multiple event cards can be displayed in the UI at any given point so there are a couple of elements in the card that should not use ids for styling.  Additionally, the button to display the parameters configured for the event do not need to be available for all instances of the event cards.
1. Update the event card styling to better address variable content sizes
2. Moves event timing information to a new location in the card for improved legibility
3. Changes the buttons in the event card to not use text to help save space and allow for more functionality within the card component
Updated layout showing the new Objectives 2 and 3:
I confirm that this contribution is made under the terms of the license found in the root directory …
> fix: Event card update

- app/v2/pipeline/styles.scss
Refactors some CSS constants into a variable for better understand of the value's use
Use variables to better capture what the values represent.
> fix: Refactor constants for clarity of values

- app/components/pipeline/workflow/event-rail/component.js
Remove a left over class member that was not used.
Remove unused injected class member.
> fix: Remove unused injection

- app/components/pipeline/workflow/component.js
- app/components/pipeline/workflow/template.hbs
- app/workflow-data-reload/service.js
- tests/integration/components/pipeline/workflow/component-test.js
The workflow component needs some additional updates to handle the pull request page
- Update tests that were missed as part of https://github.com/screwdriver-cd/ui/pull/1240
- Adds support for pull requests
- Adds messaging for a pull request that does not exist
- Adds messaging for no pull requests for a pipeline
- Sets the data reloading to ignore latest commit event monitoring for pull requests
> feat: Add support for PRs in workflow component

- app/components/pipeline/workflow/component.js
- app/components/pipeline/workflow/event-rail/component.js
- app/components/pipeline/workflow/template.hbs
- app/v2/pipeline/pulls/show/route.js
- app/v2/pipeline/pulls/show/template.hbs
- app/workflow-data-reload/service.js
- tests/integration/components/pipeline/workflow/component-test.js
The event rail needs to support displaying event cards for PR events.
Updates the event rail to display PR events.
> feat: Event rail support for PRs

- app/components/pipeline/event/card/component.js
- app/components/pipeline/event/card/template.hbs
- app/selected-pr-sha/service.js
- app/v2/pipeline/pulls/show/route.js
- tests/integration/components/pipeline/event/card/component-test.js
- tests/unit/selected-pr-sha/service-test.js
The PR events have some additional updates that are needed to support navigation and pulling up the correct event history modal.
- Fixes event card highlighting to account for the SHA value for pull request events
- Updates the event history modal button to work with PR events
- Updates the event card navigation to handle PR events
> feat: PR event card

- app/v2/pipeline/template.hbs
- app/v2/template.hbs
The V2 page titles need to be filled in with proper information to replace the stub data
Updates the page titles to contain useful information
> fix: Update page titles

- app/v2/pipeline/pulls/show/route.js
The router makes an API request for the latest open PR when one may not exist.  In the absence of any open pull requests, the API request should not be made.  There is also an additional invalid dereference for extracting the SHA from an invalid event.
1. Fixes routing when an invalid PR is set.
2. Fixes invalid dereference for PR SHA value.
> fix: Fix routing for invalid PR

- app/components/pipeline/jobs/table/template.hbs
#1289 missed indenting a section of the template.
Fix indenting
> fix: Fix indenting

- app/components/pipeline/header/component.js
- app/components/pipeline/header/styles.scss
- app/components/pipeline/header/template.hbs
- app/v2/pipeline/styles.scss
- tests/integration/components/pipeline/header/component-test.js
When the pipeline description annotation is set, the UI should display it.
Update the UI to support display of the pipeline description.
> fix: Show pipeline description

- app/v2/pipeline/styles.scss
Fixes the height of the pipeline header to fix the content and the remaining grid area for the main content to fill the available space.
Adjust the grid rows to better fit the page contents
> fix: Update spacing for pipeline header

- app/components/validator-job/component.js
- tests/integration/components/validator-job/component-test.js
The template links are wrong on the validator page.
FIx the template links.
> fix: template link on validator page

- app/components/pipeline-header/component.js
- tests/integration/components/pipeline-header/component-test.js
Follow up https://github.com/screwdriver-cd/ui/pull/1274 .
The pipeline list fetched from API includes all scm pipelines.
e.g.)
```js
[
// github.com pipelines
{
id: 1,
scmRepo: { name: 'batman/batmobile', branch: '1' },
scmUri: 'github.com:123:master'
},
{
id: 2,
scmRepo: { name: 'batman/batmobile', branch: '2' },
scmUri: 'github.com:123:master'
},
// second.com pipelines
{
id: 3,
scmRepo: { name: 'batman/batmobile', branch: '1' },
scmUri: 'second.com:123:master'
},
{
id: 4,
scmRepo: { name: 'batman/batmobile-other', branch: '1' },
scmUri: 'second.com:123:master'
}
]
```
For this reason, break condition is satisfied even there are next sibling pipelines.
https://github.com/screwdriver-cd/ui/blob/e3b4dd75111a2b66249e0dd733186ac754032fb5/app/components/pipeline-header/component.js#L89-L90 …
> fix: other branch pipeline link does not include all of sibling pipeline when use other scm

- app/components/pipeline/header/component.js
- app/components/pipeline/header/template.hbs
- app/v2/pipeline/route.js
- app/v2/pipeline/template.hbs
- tests/integration/components/pipeline/header/component-test.js
When switching to a new pipeline via the v2 pipeline workflow graph, the route model change in the pipeline is not updating the pipeline header component.
Adds in the necessary tracking to the pipeline header component to update properly when a pipeline changes.
> fix: Fix pipeline header updating

- app/components/tokens/modal/delete/component.js
- app/components/tokens/modal/delete/template.hbs
- app/components/tokens/modal/edit/component.js
- app/components/tokens/modal/edit/template.hbs
- app/components/tokens/modal/refresh/component.js
- app/components/tokens/modal/refresh/template.hbs
- app/components/tokens/table/cell/actions/component.js
- app/components/tokens/table/cell/actions/template.hbs
- app/components/tokens/table/cell/last-used/template.hbs
- app/components/tokens/table/component.js
- app/components/tokens/table/styles.scss
- app/components/tokens/table/template.hbs
- tests/integration/components/tokens/modal/delete/component-test.js
- tests/integration/components/tokens/modal/refresh/component-test.js
- tests/integration/components/tokens/table/cell/actions/component-test.js
- tests/integration/components/tokens/table/cell/last-used/component-test.js
The API tokens needs a table component to allow users to modify existing tokens.  Creating new API tokens will be handled in an outer wrapping component that integrates this table component within it.
1. Creates a new table component for displaying and modifying tokens
2. Refactors the downstream modals to be more consistent
> feat: Glimmer token table

- app/components/build-banner/component.js
- app/components/build-banner/template.hbs
- app/components/pipeline/jobs/styles.scss
- app/components/pipeline/jobs/table/cost-table/component.js
- app/components/pipeline/jobs/table/cost-table/styles.scss
- app/components/pipeline/jobs/table/cost-table/template.hbs
- app/components/pipeline/workflow/component.js
- app/components/pipeline/workflow/styles.scss
- app/components/pipeline/workflow/template.hbs
Adding in some experimental UI treatments for displaying AWS build costs
1. Updates the build detail page to display AWS cost related information
2. Adds a new cost table in the V2 UI for AWS cost related information
> feat: Add ability to display AWS cost details

- app/components/pipeline/tab/styles.scss
The v2 pipeline page tab style can be simplified
Simplifies the styling of the pipeline tab component
> fix: Simplify styling

- app/components/pipeline-events/component.js
- app/pipeline/pulls/route.js
- app/utils/graph-tools.js
- tests/acceptance/pipeline-pr-chain-test.js
Implement pipeline stages for PR builds.
**This PR requires the following PR.**
- https://github.com/screwdriver-cd/data-schema/pull/602
- https://github.com/screwdriver-cd/workflow-parser/pull/59
- https://github.com/screwdriver-cd/models/pull/649
- https://github.com/screwdriver-cd/screwdriver/pull/3352
This PR is implemented in accordance with the following issue comments.
https://github.com/screwdriver-cd/screwdriver/issues/3043#issuecomment-2815181651
Sample
Issue - https://github.com/screwdriver-cd/screwdriver/issues/3043
> feat(3043): implement stages for pr [5]

- app/components/pipeline/settings/metrics/table/cell/toggle/component.js
- app/components/pipeline/settings/metrics/table/cell/toggle/styles.scss
- app/components/pipeline/settings/metrics/table/cell/toggle/template.hbs
- app/components/pipeline/settings/metrics/table/component.js
- app/components/pipeline/settings/metrics/table/styles.scss
- app/components/pipeline/settings/metrics/table/template.hbs
- tests/integration/components/pipeline/settings/metrics/table/cell/toggle/component-test.js
Creates a new table component that allows for an improved management experience for pipeline jobs included in the pipeline metrics.
> feat: Table for managing downtime jobs

- app/components/pipeline/settings/metrics/component.js
- app/components/pipeline/settings/metrics/styles.scss
- app/components/pipeline/settings/metrics/table/component.js
- app/components/pipeline/settings/metrics/template.hbs
- tests/integration/components/pipeline/settings/metrics/component-test.js
Adds a component for managing metrics settings.  Bulk actions for selecting or deselecting multiple jobs is available.
> feat: Component for managing metrics settings

- app/components/pipeline/settings/cache/component.js
- app/components/pipeline/settings/cache/styles.scss
- app/components/pipeline/settings/cache/template.hbs
- tests/integration/components/pipeline/settings/cache/component-test.js
Creates a component to manage clearing of pipeline and job caches
> feat: Component to manage pipeline and job cache

- app/components/pipeline/modal/toggle-job/component.js
- app/components/pipeline/modal/toggle-job/styles.scss
- app/components/pipeline/modal/toggle-job/template.hbs
- app/components/pipeline/workflow/tooltip/component.js
- app/components/pipeline/workflow/tooltip/template.hbs
- app/utils/pipeline/graph/tooltip.js
- tests/integration/components/pipeline/modal/toggle-job/component-test.js
- tests/unit/utils/pipeline/graph/tooltip-test.js
Refactor the existing job toggle modal to support toggling jobs in a batch
https://github.com/screwdriver-cd/screwdriver/issues/1576
> feat: Support toggle jobs in a batch

- app/components/pipeline/settings/jobs/table/cell/date/component.js
- app/components/pipeline/settings/jobs/table/cell/date/styles.scss
- app/components/pipeline/settings/jobs/table/cell/date/template.hbs
- app/components/pipeline/settings/jobs/table/cell/toggle/component.js
- app/components/pipeline/settings/jobs/table/cell/toggle/styles.scss
- app/components/pipeline/settings/jobs/table/cell/toggle/template.hbs
- app/components/pipeline/settings/jobs/table/component.js
- app/components/pipeline/settings/jobs/table/styles.scss
- app/components/pipeline/settings/jobs/table/template.hbs
- tests/integration/components/pipeline/settings/jobs/table/cell/date/component-test.js
- tests/integration/components/pipeline/settings/jobs/table/cell/toggle/component-test.js
Creates a table component for managing job settings
> feat: Table for managing job settings

- app/utils/graph-tools.js
- tests/unit/utils/graph-tools-test.js
The workflow graph is not shown on PR that has a new stage.
- Fix to get a correct stage object by its name
> fix(3043): show workflow graph properly on PR with new stages

- app/components/pipeline/settings/main/component.js
- app/components/pipeline/settings/main/template.hbs
- app/v2/pipeline/settings/index/route.js
- app/v2/pipeline/settings/index/template.hbs
The main pipeline settings UI should update accordingly when the underlying pipeline changes
Refactors the pipeline settings UI to respond properly to pipeline changes
> feat: Pipeline settings updates when pipeline changes

- app/components/pipeline/settings/cache/component.js
- app/components/pipeline/settings/cache/table/component.js
- app/components/pipeline/settings/cache/template.hbs
- app/v2/pipeline/settings/cache/route.js
- app/v2/pipeline/settings/cache/template.hbs
When the underlying pipeline changes, the v2 UI for pipeline job settings should update accordingly
Adds support for the pipeline cache settings to update when the pipeline changes
> feat: Cache settings updates when pipeline changes

- app/components/pipeline/settings/metrics/component.js
- app/components/pipeline/settings/metrics/table/component.js
- app/components/pipeline/settings/metrics/template.hbs
- app/v2/pipeline/settings/metrics/route.js
- app/v2/pipeline/settings/metrics/template.hbs
When the underlying pipeline changes, the v2 UI for pipeline job settings should update accordingly
Adds support for the pipeline metrics settings to update when the pipeline changes
> feat: Metrics table updates when pipeline changes

- app/components/pipeline/settings/preferences/component.js
- app/components/pipeline/settings/preferences/template.hbs
- app/v2/pipeline/settings/preferences/route.js
- app/v2/pipeline/settings/preferences/template.hbs
When the underlying pipeline changes, the v2 UI for pipeline job settings should update accordingly
Adds support for the pipeline preferences to update when the pipeline changes
> feat: Preferences update when pipeline changes
