wercker.yml
hopefully root is more accurate than output_dir. If this doesn't work, we'll rework the `ember build` command.
=> tar up the right directory

Dockerfile, package.json, wercker.yml
* The wercker step to install phantomjs is unreliable. Made it a devdep.
* use alpine linux version of nginx (it is tiny)
* fix missing wget and tarfile generation
=> Add phantomjs to devdeps

Dockerfile, nginx.conf
Ember does its own routing, so nginx needs to be configured to let it do so. This is a copy of the original config https://github.com/nginxinc/docker-nginx/blob/master/mainline/alpine/nginx.conf with our server config added.
=> Add nginx configuration for ember

screwdriver.yaml
Also the UI test container needs to run in node:6. Ember is transpiled with babel down to a browser-level after testing.
=> Bower needs a flag to install as root

app/components/sd-build-log/component.js
We were not stopping log requests because the header value(s) of 'true' and 'false' are both truthy strings.
=> Check for the string 'false' instead of boolean

app/components/pipeline-build-view/component.js, app/components/pipeline-build-view/styles.scss, app/components/pipeline-build-view/template.hbs, app/job/adapter.js, app/job/model.js, app/pipeline/adapter.js, app/pipeline/index/route.js, app/pipeline/index/template.hbs, app/pipeline/model.js, tests/integration/components/pipeline-build-view/component-test.js, tests/unit/job/adapter-test.js, tests/unit/job/model-test.js, tests/unit/pipeline/adapter-test.js, tests/unit/pipeline/index/route-test.js, tests/unit/pipeline/model-test.js
Rather silly way of fetching builds and associating the jobs they belong to. We should redo this completely when proper apis exist.
=> stupid implementation of builds page for pipelines

app/build/route.js, app/components/build-log/component.js, app/components/build-log/template.hbs, app/components/build-step/component.js, app/components/build-step/template.hbs, tests/integration/components/build-log/component-test.js, tests/integration/components/build-step/component-test.js
* Resolves #14 and #15. 
* Build model reloads after 5s when queued. 
* Build model reloads when step (logs) finish loading. 
* Log panels open when step is running or failed
* log panels scroll to bottom of logs
=> build page should refresh better

app/components/pipeline-secret-settings/component.js, app/components/pipeline-secret-settings/styles.scss, app/components/pipeline-secret-settings/template.hbs, app/components/secret-view/template.hbs, app/pipeline/secrets/controller.js, app/pipeline/secrets/template.hbs, app/secret/adapter.js, app/secret/model.js
Missing allowInPR field prevented secrets from being created properly.
Added some validation on key name, since that is the most likely thing to fail.
Added component to display error messages that occur when creating keys
=> Add allowInPR field

app/error/route.js
UnauthenticatedRouteMixin will prevent an authenticated user from seeing a page. Since the error page had this mixin added, no authenticated user could see the error page when visiting an unknown path.
=> make error page work for unknown paths

app/pipeline/secrets/route.js
The secrets page for a pipeline should require authentication. beforeModel messes up the AuthenticatedRouteMixin so refactoring the model function helps.
=> Refactor secrets model to be an authenticated route

app/components/build-step-view/styles.scss, app/components/pipeline-build-view/component.js, app/components/pipeline-build-view/styles.scss, app/components/pipeline-build-view/template.hbs, app/components/pipeline-builds-list/component.js, app/components/pipeline-builds-list/styles.scss, app/components/pipeline-builds-list/template.hbs, app/components/pipeline-pr-list/component.js, app/components/pipeline-pr-list/styles.scss, app/components/pipeline-pr-list/template.hbs, app/components/pipeline-pr-view/component.js, app/components/pipeline-pr-view/styles.scss, app/components/pipeline-pr-view/template.hbs, app/components/pipeline-secret-settings/styles.scss, app/pipeline/builds/index/route.js, app/pipeline/builds/index/template.hbs, tests/integration/components/pipeline-build-view/component-test.js, tests/integration/components/pipeline-builds-list/component-test.js, tests/integration/components/pipeline-pr-list/component-test.js, tests/integration/components/pipeline-pr-view/component-test.js
Redesign of build list, separates PRs from workflow builds.
Computes workflow, and adds a UI to builds to display workflow status
Extra hackery to get around /pipeline/:id/jobs not being complete.
=> Refresh of pipeline page builds list

app/components/pipeline-header/template.hbs, app/components/pipeline-pr-list/template.hbs, tests/integration/components/pipeline-header/component-test.js
Makes the pipeline appId a link to pipeline page. 
Instead, the branch links to github page.
Added some text to PR column when no PRs are present.
=> Cleanup pipeline header links

app/pipeline/builds/index/route.js
Gets rid of hackery for the pipeline/:id/jobs api call that filters disabled jobs, and reversed job order
=> Fix build page now that jobs api gives better data

app/components/pipeline-builds-list/component.js, app/components/pipeline-workflow/styles.scss
- Get the last build of a job associated with a given `sha` (now it is getting the oldest build)
- Add style to QUEUED and RUNNING status on workflow bar for consistency
=> Get latest build status

app/application/route.js, app/create/route.js, app/index.html, app/login/route.js, app/pipeline/builds/build/route.js, app/pipeline/route.js, app/pipeline/secrets/route.js, app/search/route.js, package.json, tests/unit/application/route-test.js, tests/unit/create/route-test.js, tests/unit/login/route-test.js, tests/unit/pipeline/builds/build/route-test.js, tests/unit/pipeline/route-test.js, tests/unit/pipeline/secrets/route-test.js, tests/unit/search/route-test.js
Uses https://github.com/kimroen/ember-cli-document-title to add titles to pages through routes. My preference would have been http://tim-evans.github.io/ember-page-title/, but this seems to be broken in more recent builds of ember.
=> Add page titles to routes

app/components/loading-view/component.js, app/components/loading-view/styles.scss, app/components/loading-view/template.hbs, app/templates/loading.hbs, tests/integration/components/loading-view/component-test.js
This will automatically fill an {{outlet}} with a loading indication when a model is slow to resolve.
=> add a loading panel

app/components/pipeline-pr-view/styles.scss, app/components/pipeline-pr-view/template.hbs
The graphic looked off-center and spun in a weird way.
=> make PRs build icons less funny when build is running

app/components/build-log/component.js, app/components/build-log/template.hbs, tests/integration/components/build-log/component-test.js
Logging component would not continue if x-more-data=false when no log lines were delivered. This made builds look like they were stuck until the page was refreshed.
Added scheduling of async work in Ember (https://guides.emberjs.com/v2.8.0/applications/run-loop/). This makes ember a little happier when running prod code, and makes tests happier when running async code.
=> Logs should stop loading when x-more-data is false

app/build/model.js, tests/unit/build/model-test.js
https://cd.screwdriver.cd/pipelines/34b6834028c4c904dce3d9391c8b2dd4994ec6a9/build/ca33f5909a54d1e31583896abde4c780ca87942d and https://api.screwdriver.cd/v4/builds/ca33f5909a54d1e31583896abde4c780ca87942d
=> Fix error calculating buildDuration when there is no startTime

screwdriver.yaml
This ensures we test beta environment first and don't accidentally break production
=> Deploy to beta first, then production

app/components/build-log/component.js, app/components/build-step-collection/component.js, app/components/build-step-collection/styles.scss, app/components/build-step-collection/template.hbs, app/components/build-step/template.hbs, app/components/loading-view/component.js, app/components/pipeline-build-view/styles.scss, app/pipeline/builds/build/route.js
It looked like after the last set of changes to log component, the log lines were added to the page after the scroll action occurred, resulting in scrolling appearing to be misaligned. This has been resolved by scheduling the scroll action to occur after the "render" event.
The autoscroll behavior made it difficult for a user to view parts of the log not at the end of the page. The autoscroll behavior is now turned off when the user has scrolled up at least 1% of the document height, and restores autoscroll when they scroll back to the bottom of the page.
* Wait until after rendering to scroll
* Wait until after render to reload builds
* Continue reloading build if still `RUNNING` and no steps are remaining to execute
* Discontinue scrolling when user has scrolled up > 1% from bottom of …
=> fix scrolling issues on build page

app/pipeline/builds/build/route.js
This has an unintended side effect of resetting logs every 5 seconds while they are loading.
=> Don't keep refreshing running builds

app/components/secret-view/component.js, app/components/secret-view/template.hbs, app/secret/serializer.js, tests/integration/components/pipeline-secret-settings/component-test.js, tests/integration/components/secret-view/component-test.js, tests/unit/secret/serializer-test.js
- Update a secret by sending only dirty fields to API
- Allow update a secret's `value` and `allowInPR` attributes
- Blocked by [PR - update secret route to API](https://github.com/screwdriver-cd/screwdriver/pull/238)
part of issue [#232](https://github.com/screwdriver-cd/screwdriver/issues/232)
=> Update a secret

app/build/model.js, app/components/pipeline-header/template.hbs, app/components/search-list/template.hbs, app/pipeline/model.js, app/pipeline/serializer.js, tests/acceptance/build-test.js, tests/acceptance/pipeline-builds-test.js, tests/integration/components/pipeline-header/component-test.js, tests/unit/pipeline/model-test.js, tests/unit/pipeline/serializer-test.js
- Send 'checkoutUrl' for creating pipeline
- Use `scmRepo` to get url, org/repoName, branch directly
- This PR is just making sure the UI  is compatible with the new API
- Another PR will clean up the naming of `scmUrl` to `checkoutUrl`
- Blocked by https://github.com/screwdriver-cd/screwdriver/pull/280
=> Adapt to v14 data-schema

app/build/serializer.js, app/components/build-banner/styles.scss, app/components/build-banner/template.hbs, app/styles/screwdriver-colors.scss, tests/integration/components/build-banner/component-test.js, tests/unit/build/serializer-test.js
Display the container the build was run in. Fix build-banner styles to use screwdriver-colors.
=> Display build container

app/utils/git.js, tests/integration/components/create-pipeline-data/component-test.js, tests/unit/utils/git-test.js
- Allow checkout url to be https
- Use regex defined in our schema
https://github.com/screwdriver-cd/data-schema/blob/master/config/regex.js#L18
- Delete the link returned in parse() because bitbucket and github have different links for branch
and we are not using the link any where
- Link to repo can be found in `scmRepo.url`
- https://api.screwdriver.cd/v4/pipelines/613a05120b3c7166749d049b549d5edece076cdf
Resolves https://github.com/screwdriver-cd/screwdriver/issues/333
=> Allow checkout url to be https

ember-cli-build.js
allows us to access /assets/unknown_user.png without knowing a fingerprint.
=> Remove fingerprint of unknown_user image

app/components/build-log/component.js, app/components/build-step-collection/component.js, app/components/build-step/template.hbs, app/pipeline/builds/build/template.hbs
* Move autoscroll handling into build-logs component, since that is what is actually doing the scrolling.
* Remove `autoscroll` passing to build-logs component
* Request `n + 1` when fetching the logs, so that you don't get duplicate lines.
=> fix logs not scrolling and dupe logs

app/components/build-bubble/component.js, app/components/pipeline-event-view/component.js, app/components/pipeline-events-list/component.js, app/components/pipeline-events-list/styles.scss, app/components/pipeline-events-list/template.hbs, app/event/model.js, app/mixins/model-reloader.js, app/pipeline/builds/build/controller.js, config/coverage.js, config/environment.js, tests/unit/event/model-test.js, tests/unit/mixins/model-reloader-test.js
* Adds ModelReloader mixin that will schedule reload on a model periodically.
* Build-bubble, event-list, event-view all use ModelReloader to schedule various model reloads
* event-list only shows 5 (configurable) events by default. Adds a link to show all.
https://github.com/screwdriver-cd/screwdriver/issues/391
=> feat: reload content on the pipeline page periodically

app/application/controller.js, app/application/template.hbs, app/components/app-header/component.js, app/components/app-header/template.hbs, app/search/route.js, tests/integration/components/app-header/component-test.js, tests/unit/application/controller-test.js
- Make the search-icon clickable
- Now both `Enter` and clicking `search-icon` will take you to the search page 
- Resolve https://github.com/screwdriver-cd/screwdriver/issues/390
=> fix: Search button actually searches

app/build-logs/service.js, app/components/build-log/component.js, app/components/build-log/template.hbs, app/helpers/ansi-colorize.js, config/environment.js, tests/acceptance/build-test.js, tests/integration/components/build-log/component-test.js, tests/integration/components/build-step/component-test.js, tests/unit/helpers/ansi-colorize-test.js
* Moves ansi colorizing to a htmlbars helper
* Use handlebars to sanitize raw logs before applying ansi colors
* Move html markup for log lines into template
* Reload logs on next tick if MAX_LOG_LINES is returned instead of waiting for BUILD_RELOAD_TIMER
Addresses https://github.com/screwdriver-cd/screwdriver/issues/395
=> fix: html entities in logs caused view issues

app/components/build-banner/component.js, app/components/build-banner/styles.scss, app/components/build-banner/template.hbs, app/pipeline/builds/build/route.js, app/pipeline/builds/build/template.hbs, tests/acceptance/build-test.js, tests/integration/components/build-banner/component-test.js
Add `Previous Job` and `Next Job` links to build banner.
Pass in builds of the current event and get the previous and next build IDs. If there is no previous job, it won't display. Same as next job.  
Related to https://github.com/screwdriver-cd/screwdriver/issues/396
=> feat(396): Add prev and next links to build banner

app/components/build-banner/styles.scss
The alignment got messed up because I changed it to use pure grid in [this PR](https://github.com/screwdriver-cd/ui/pull/115) and missed the CSS for the restart button. 
Right now:
After
=> fix: align restart button correctly

README.md, package.json
- Update badge links
- Temporarily pin resolver to version to `2.1.0` since the new version broke our tests. Will leave the fix to a different PR as I'm not sure why and it's out of the scope of this PR. 
```
not ok 1 PhantomJS 2.1 - Global error: Error: Compile Error: ansiColorize is not a helper at http://localhost:7357/assets/vendor.js, line 67394
15:46:15
---
15:46:15
Log: |
15:46:15
{ type: 'warn',
15:46:15
text: '\'WARNING: Attempted to lookup "helper:ansiColorize" which was not found. In previous versions of ember-resolver, a bug would have caused the module at "screwdriver-ui/helpers/ansi-colorize" to be returned for this camel case helper name. This has been fixed. Use the dasherized name to resolve the module that would have been returned in previous versions.\'\n' }
15:46:15
{ …
```
=> fix: Update badge links

app/components/search-list/component.js, tests/integration/components/search-list/component-test.js
I added the search filter feature described in screwdriver-cd/screwdriver#397. It supports multiple queries and uses `appId` as a default field.
For instance,
* `abc` => `appId:abc`
* `branch:master abc def` => `branch:master` AND `appId:abc` AND `appId:def`
=> feat: add support for search filter

app/components/build-log/template.hbs
I removed spaces around log elements which has the `white-space: pre-wrap` attribute. The spaces include CR or LF, so I think it causes the issue (screwdriver-cd/screwdriver#449).
This PR is another option of #140.
Chrome
FireFox (after)
FireFox (before)
Opera
=> fix: Remove spaces around log elements

ember-cli-build.js
Fix bower import paths:
The old paths won't work with [broccoli-concat](https://github.com/broccolijs/broccoli-concat)'s latest version `3.2.2` which is a dependency for `ember-cli`.
=> fix: fix bower import paths

app/pipeline/builds/build/route.js, package.json, tests/acceptance/build-test.js, tests/unit/pipeline/builds/build/route-test.js
I fixed a bug described in https://github.com/screwdriver-cd/screwdriver/issues/478.
There are 2 ways to avoid this bug.
1. show 404 page
2. redirect to somewhere
2.1 `/pipelines/:pipeline_id`
2.2 `/pipelines/:correct_pipeline_id/build/:build_id`
I think this will happen much when the end of the URL is trimmed such as copy/paste failure, so I chose the method 2.1.
=> fix(478): redirect to a pipeline page if a build doesn't belong to the pipeline

app/app.js, app/application/route.js, app/create/route.js, app/login/route.js, app/pipeline/builds/build/route.js, app/pipeline/builds/index/route.js, app/pipeline/builds/route.js, app/pipeline/options/route.js, app/pipeline/route.js, app/pipeline/secrets/route.js, app/search/route.js, config/environment.js
ember-simple-auth deprecated the application-wide settings of session auth routing.
This should resolve issue https://github.com/screwdriver-cd/screwdriver/issues/425, and reverts #148.
=> fix: resolve deprecation warnings by configuring routes specifically

app/router.js, tests/acceptance/build-test.js
The API endpoint is `/v4/builds/{id}` but the UI endpoint is `/pipelines/{pipeline.id}/build/{id}`. "builds" and "build" difference may make confuse us.
Fix endpoint to "builds" from "build".
If another repository of code that should fix exist, please teach me.
Related: https://github.com/screwdriver-cd/screwdriver/issues/527
=> fix(527): fix builds endpoint

app/application/route.js, package.json
Ember data seems to have made a breaking change in the way it handles errors. It now requires AdapterErrors to be supplied in JSONAPI format. This will be addressed when the ember2.13.x PR is ready, but for now we are pinning back.
I'm not sure what has regressed, but the login flow is now broken. Adjusted the routeAfterAuthenticated config in application adapter to fix.
=> fix: pin back ember-data

app/components/pipeline-secret-settings/component.js, app/components/pipeline-secret-settings/template.hbs, tests/integration/components/pipeline-secret-settings/component-test.js
Previously, the secrets are sorted by id in reverse order.
Change it to sort by name in alphabetical order.
Resolve https://github.com/screwdriver-cd/screwdriver/issues/514
=> fix(514): sort secrets by name in alphabetical order

app/components/pipeline-create-form/template.hbs, app/components/pipeline-secret-settings/component.js, app/components/pipeline-secret-settings/template.hbs, tests/integration/components/pipeline-secret-settings/component-test.js
Resolves to https://github.com/screwdriver-cd/screwdriver/issues/489
Resolves https://github.com/screwdriver-cd/screwdriver/issues/541
* add some text to the "create" page
* Add a title and some text to the "secrets" page
* make the placeholder text in the secret page valid as a secret key
* fix the error message when entering an invalid secret key
* add tooltips specifying what a valid key looks like, and what the "allow in PR" box is for
=> fix: Small UI improvements on the secrets page and create page

Dockerfile
nginx-lua has a dependency on nginx-mod-http-lua to be installed, and doesn't automatically bring in that dependency.
This PR updates the Dockerfile to bring in the new dependency.
=> fix: nginx-lua can not install in docker image

Dockerfile, nginx.conf
- Borrowed from here https://github.com/openresty/lua-nginx-module#installation
- I don't have any idea if this will work in the intended way, but I do
know that nginx starts with this config in place.
=> Added lines to load the new lua module in nginx.conf

app/app.js, app/components/pipeline-event-view/template.hbs, app/event/model.js, app/pipeline/builds/build/template.hbs, app/pipeline/builds/index/controller.js, app/pipeline/builds/index/template.hbs, tests/acceptance/build-test.js, tests/acceptance/create-page-test.js, tests/acceptance/pipeline-builds-test.js, tests/acceptance/pipeline-options-test.js, tests/acceptance/search-test.js, tests/acceptance/secrets-test.js, tests/integration/components/pipeline-event-view/component-test.js, tests/integration/components/pipeline-events-list/component-test.js
Context:
========
People are reporting that the build bubbles in events are displaying out of order intermitantly. Also, events sometimes appear out of order.
Investigations determined that the api returns lists of models sorted by `createTime` and this value is sometimes not very accurate. Some builds had a `createTime` value that was set after the `endTime` value. The sort by `createTime` was imposed some time ago when model ids were a hash, and thus not sortable by id.
Objective:
----------
This PR adds sorting to events and builds by model id to force them to display in the correct order regardless of the order the API returns them in.
Misc:
-----
* https://github.com/screwdriver-cd/screwdriver/issues/555
* Ember.MODEL_FACTORY_INJECTIONS removed as it is deprecated and unnecessary
* …
=> fix(555): build bubbles and events out of order

app/components/app-header/component.js, app/components/app-header/template.hbs, app/instance-initializers/supplementary-config.js, nginx.conf
Reverts screwdriver-cd/ui#165
For an unknown reason, `FEAT_DISPLAY_ALPHA` is being set to `nil` in the nginx config regardless of the value of the environment variable.
=> Revert "feat: add alpha banner with feature flag"

app/components/app-header/styles.scss, app/components/pipeline-nav/styles.scss, app/components/pipeline-start/styles.scss, app/components/pipeline-workflow/styles.scss, app/pipeline/builds/index/template.hbs, app/styles/app.scss
Addressing a few of the issues in https://github.com/screwdriver-cd/screwdriver/issues/584
Also in this PR:
Before:
After:
New Start button position:
=> fix(584): Make search bar smaller and make pipeline page tabs easier to read

app/components/app-header/styles.scss, app/components/app-header/template.hbs, package.json
Context:
========
When the header menu is collapsed, tooltips display on the menu center screen which can be confusing.
Objective:
----------
Hide tooltips when the menu is collapsed
Misc:
------
Fixes last verifiable issue in https://github.com/screwdriver-cd/screwdriver/issues/584
=> feat(584): hide app-header tooltips when menu is collapsed

app/components/validator-job/template.hbs, app/components/validator-pipeline/component.js, app/components/validator-pipeline/styles.scss, app/components/validator-pipeline/template.hbs, app/components/validator-results/component.js, app/components/validator-results/template.hbs, tests/integration/components/validator-job/component-test.js, tests/integration/components/validator-pipeline/component-test.js, tests/integration/components/validator-results/component-test.js
Validator now displays job-level annotations similar to image, steps,
etc.
In addition, this PR adds "Pipeline-Level Settings", which includes
Workflow and pipeline-level Annotations.
Related to https://github.com/screwdriver-cd/screwdriver/issues/580
=> feat(580): Add annotations to validator

package.json
Unit tests are failing due to the new ember-data version `v2.14.x` published during the weekend.
https://github.com/emberjs/data/releases
Failed build: https://cd.screwdriver.cd/pipelines/7/builds/5805
Unblock  the pipeline by pinning major and minor for now. Will create a sticky and figure out how to actually resolve it.
=> fix: pin major and minor version for ember-data to fix tests for now

app/components/validator-job/template.hbs, tests/integration/components/validator-job/component-test.js
Validator now displays the job description in the UI.
Related to [screwdriver-cd/screwdriver#423](https://github.com/screwdriver-cd/screwdriver/issues/423)
=> fix(423): Add job descriptions to validator in UI

app/components/build-step-view/component.js, app/components/build-step-view/styles.scss, app/components/build-step-view/template.hbs, tests/integration/components/build-step-view/component-test.js
Make screwdriver provided steps a grey-ish color to easily distinguish between user-defined steps. Related to [screwdriver-cd/screwdriver#608](https://github.com/screwdriver-cd/screwdriver/issues/608)
Screenshot of what it looks like:
=> fix(608): Visual difference for screwdriver-provided steps

README.md, app/components/pipeline-create-form/component.js, app/components/pipeline-options/component.js, app/components/pipeline-options/styles.scss, app/components/pipeline-options/template.hbs, app/pipeline/options/controller.js, app/pipeline/options/template.hbs, app/utils/git.js, tests/acceptance/pipeline-options-test.js, tests/integration/components/pipeline-options/component-test.js, tests/unit/utils/git-test.js
Users would like to be able to update their pipeline repo and branch from the Screwdriver UI.
This PR will add a pipeline section to Options tab and allow users to update checkout URL. There will also be validation to pipeline checkout URL update. There is also a one-liner added to README instructions for running a single test with ember.
**Invalid checkoutURL:**
**Valid checkoutURL:**
**Note:** The entire Pipeline options page definitely needs a redesign. Leaving those changes for another PR/time.
- Original issue: https://github.com/screwdriver-cd/screwdriver/issues/562
- API PR: https://github.com/screwdriver-cd/screwdriver/pull/627
=> feat(562): Allow users to update checkout URL for pipeline

app/components/pipeline-secret-settings/component.js, app/components/pipeline-secret-settings/styles.scss, app/components/pipeline-secret-settings/template.hbs, tests/integration/components/build-step-collection/component-test.js, tests/integration/components/pipeline-secret-settings/component-test.js, tests/integration/components/secret-view/component-test.js
Some of the feedback from https://github.com/screwdriver-cd/ui/pull/176 was also applicable to other places in the code.
* Changed pipeline-secret-settings to use `Ember.computed` instead of a function called on `key-up` events
* Changed indentation on some test headers to be consistent with the rest of the tests
=> refactor(secrets): set isButtonDisabled with Ember.computed

app/components/app-header/styles.scss
Context:
========
When focus is applied to the search bar it causes the page to shift by a pixel. The search button doesn't line up with the bottom of the search input border.
Objective:
----------
The header should always be the same height. The search button should be the same size as the search input.
Before:
After:
=> fix: minor header tweak

app/pipeline/options/controller.js, tests/integration/components/pipeline-options/component-test.js
The PR to update Ember to version 2.14 had some other side effects. The change here
https://github.com/screwdriver-cd/ui/pull/178/files#diff-2d27d36985688e321b57fcefe558fb7eR10
broke https://github.com/screwdriver-cd/ui/blob/master/app/pipeline/options/controller.js#L21.
This PR will fix the issue.
- Update Ember to version 2.14 PR: https://github.com/screwdriver-cd/ui/pull/178
- Resolves https://github.com/screwdriver-cd/screwdriver/issues/562
=> fix(562): Fix broken update checkout URL feature

app/components/pipeline-secret-settings/template.hbs, app/components/token-list/component.js, app/components/token-list/style.scss, app/components/token-list/template.hbs, app/components/token-view/component.js, app/components/token-view/style.scss, app/components/token-view/template.hbs, app/router.js, app/styles/app.scss, app/styles/screwdriver-modal-styles.scss, app/token/model.js, app/token/serializer.js, app/user-settings/controller.js, app/user-settings/route.js, app/user-settings/service.js, app/user-settings/template.hbs, tests/acceptance/tokens-test.js, tests/integration/components/token-list/component-test.js, tests/integration/components/token-view/component-test.js, tests/unit/token/model-test.js, tests/unit/token/serializer-test.js
* login/out item in the menu bar is now a dropdown when logged in which points to a "user-settings" page
* added user-settings page which displays a user's tokens and allows for creation, updating, refreshing, and revoking
* made the title of the "secrets" page smaller to match the tokens page (following feedback that it was too large)
Related to https://github.com/screwdriver-cd/screwdriver/issues/532
Resolves https://github.com/screwdriver-cd/screwdriver/issues/615
=> feat(tokens): Add tokens UI

app/components/app-header/template.hbs, public/assets/svg/login.svg, public/assets/svg/profile-outline.svg, tests/integration/components/app-header/component-test.js
The user-settings page now exists, but is not part of the menu bar! (Because it made for a smaller PR)
This PR changes the "log in" button to use an updated icon, and when the user is logged in it will be a dropdown featuring an option for "log out" and an option for "user settings."
Logged out:
Logged in:
Related to https://github.com/screwdriver-cd/screwdriver/issues/532
=> feat(tokens): Add user-settings page to menu bar

app/pipeline/options/controller.js, tests/unit/pipeline/options/controller-test.js
The delete pipeline flow was broken with the change to the model. (https://github.com/screwdriver-cd/ui/blob/master/app/pipeline/options/route.js#L10)
This PR fixes the issue.
Related to: https://github.com/screwdriver-cd/ui/pull/178, https://github.com/screwdriver-cd/ui/pull/181
=> fix: Fix delete pipeline flow

app/components/secret-view/component.js, app/components/secret-view/template.hbs, app/components/token-view/component.js, app/user-settings/controller.js, app/user-settings/service.js
There was a bug where "refreshed" was not being displayed on the alert when a token had its value refreshed, and one where creating a token with an empty description failed.
There is also a bug where if you refresh a token and then try to modify the same token without refreshing the page the button won't change from "delete" to "update." This seems to be because the `Ember.computed` block changing the button text stops caring about changes to the values after the line that sets it to `Delete` following an update.
This is fixed by modifying the setter for `buttonAction`.
Related to https://github.com/screwdriver-cd/screwdriver/issues/532
=> fix(tokens): Can create tokens with empty description

app/pipeline/controller.js, app/pipeline/template.hbs, tests/acceptance/pipeline-builds-test.js
Some users have pointed out that it's hard to tell when they're logged in, and additionally it was mentioned in the security training the other day that it's generally better not to show users options for things they aren't authorized to do.
This PR makes it such that if you're logged out you don't get to see the menu that would give you the "options" and "secrets" tabs when viewing a pipeline.
Logged in:
Logged out:
=> feat(builds): only show pipeline options when logged in

app/components/info-message/styles.scss, app/components/info-message/template.hbs, app/components/token-list/style.scss, app/components/token-list/template.hbs
1.1rem didn't come out to be the same pixel value as expected, and I neglected to verify that things looked the same after the change. Updated to just have the icons use regular font size.
Before:
After:
Related to https://github.com/screwdriver-cd/ui/pull/189
=> fix(alerts): fix sizing of icon in alerts

app/components/info-message/component.js
I tested that the new token alert came back after you dismissed it, but not that the info-message behaved the same way.
Related to https://github.com/screwdriver-cd/ui/pull/189
=> fix(alerts): new alerts show after old ones are hidden

app/components/build-banner/component.js, app/components/pipeline-events-list/styles.scss, app/pipeline/builds/build/controller.js, tests/integration/components/build-banner/component-test.js, tests/unit/pipeline/builds/build/controller-test.js
Currently when an ongoing job finishes, it does not display link to the next job which should be part of the same workflow. This PR fixes it by refetching builds tied to the same event.
=> fix: Show Next job link once current job finishes

app/components/info-message/styles.scss, app/components/pipeline-secret-settings/styles.scss, app/components/token-list/component.js, app/components/token-list/style.scss, app/components/token-list/template.hbs, app/components/token-view/component.js, app/pipeline/builds/index/template.hbs
I went through every page with alerts and made sure everything worked. Found two more issues, but this should be the last of it. Apologies for all the PRs on this, should have tested more thoroughly from the start. Won't happen again.
* fixed CSS styling issue on the pipeline overview page
* Ember.computed was breaking the ability of the error message to come back after being closed on the user-settings page, moved to setting the errorMessage as a string to be consistent with other places in the application
=> fix(alerts): fix alerts on user-settings page

app/authenticators/screwdriver-api.js, app/components/collections-flyout/component.js, app/components/collections-flyout/styles.scss, app/components/collections-flyout/template.hbs, app/styles/screwdriver-colors.scss, tests/integration/components/collections-flyout/component-test.js
For the user dashboard, the user needs to be able to create / view collections.
This PR adds a component that will act as a flyout component that can be added to the routes that require it. Right now, the component is not collapsible but in the future it will be.
Screenshots:
Flyout:
Modal:
=> feat(523): Collections-flyout component

app/collection/model.js, app/collection/serializer.js, tests/unit/collection/model-test.js, tests/unit/collection/serializer-test.js
This PR adds a model and serializer for collections for use with `ember-data`.
Blocked by PR: #195 
=> feat(523): Add collection model and serializer

app/components/collections-flyout/component.js, app/components/collections-flyout/template.hbs, tests/integration/components/collections-flyout/component-test.js
Currently, all the interactions with the store that the collections-flyout component needs to do are done through the controllers of the routes that require the collections-flyout component. This is not very DRY.
This PR moves all the store interactions into the collections-flyout component itself so that it can be a self-sustained component. So now, any route that needs the collections-flyout component can simply just add it to the template like so `{{collections-flyout}}`.
=> refactor(collections): Move store interactions to component

app/components/search-list/component.js, app/components/search-list/styles.scss, app/components/search-list/template.hbs, app/search/controller.js, app/search/route.js, app/search/template.hbs, tests/acceptance/search-test.js, tests/integration/components/search-list/component-test.js, tests/unit/search/controller-test.js
For the dashboards feature, users need to be able to add pipelines to their collections
This PR adds functionality to allow users to add pipelines to their collections from the search results page.
**Screenshots**
Search page:
Dropdown:
Successful add:
=> feat(collections): Add pipelines to a collection from search route

app/authenticators/screwdriver-api.js, app/components/login-button/component.js, app/components/login-button/template.hbs, app/login/controller.js, app/login/route.js, app/login/template.hbs, tests/integration/components/login-button/component-test.js
Multiple SCM feature API has been implemented to API(#365).
There is no multiple scm support for UI yet, so we can't test it.
I added the support for multiple scms feature to the UI so that we can test the feature on cd.screwdriver.cd.
New login page uses `/v4/auth/contexts` API to show buttons for each scm. It shows the same button as current one if the API returns an error, for backward compatibility.
When the contexts API returns data as below,
```
[
{
"context": "github:github.com",
"displayName": "github"
},
{
"context": "github:mygithubinstance.mycompany.com",
"displayName": "mygithub_instance"
}
]
```
UI shows buttons as below.
Multiple SCMs feature: screwdriver-cd/screwdriver#365
TODO:
=> feat(365): Add login buttons for each scm

app/components/collection-view/component.js, app/components/collection-view/styles.scss, app/components/collection-view/template.hbs, app/components/collections-flyout/styles.scss, app/dashboard/show/controller.js, app/dashboard/show/template.hbs, tests/acceptance/dashboards-test.js, tests/integration/components/collection-view/component-test.js, tests/unit/dashboard/show/controller-test.js
Users need to be able to remove pipelines from a collection (if they own it).
This PR adds functionality to allow users to remove pipelines that they don't want to have in a collection
Example:
=> feat(collections): Add remove pipeline functionality

app/components/build-health/component.js, app/components/build-health/styles.scss, app/components/build-health/template.hbs, app/components/collection-view/template.hbs, tests/acceptance/dashboards-test.js, tests/integration/components/build-health/component-test.js, tests/integration/components/collection-view/component-test.js
Users want to see the last builds health for each of the pipelines in their collection on the dashboard
This PR adds last builds health to the dashboard
Screenshot:
=> feat(collections): Add last builds health to dashboard

app/components/pipeline-secret-settings/template.hbs
The current guide link of secrets is wrong, it returns 404. This PR will fix to correct link.
Before: http://docs.screwdriver.cd/user-guide/configuration/secrets/
After: http://docs.screwdriver.cd/user-guide/configuration/secrets
=> fix: fix link url of secrets document

app/components/collections-flyout/component.js, app/components/collections-flyout/template.hbs, package.json, tests/integration/components/collections-flyout/component-test.js
Currently if you create a new collection and then try to navigate to it, navigation won't work. This PR fixes it.
@joelseq @r3rastogi
=> fix: navigating to newly created collection should work

app/components/token-list/template.hbs
This PR fix link of the document on the access tokens page.
Same as https://github.com/screwdriver-cd/ui/pull/209
=> fix: fix link of token api guide

app/components/collection-view/styles.scss, app/components/collection-view/template.hbs, tests/acceptance/dashboards-test.js, tests/integration/components/collection-view/component-test.js
For the dashboard, users want information about the number of pull requests that are open and failing for each of the pipelines in the collection
This PR displays the pr info for each pipeline in the collection
Screenshot:
Blocked by: [screwdriver-cd/screwdriver#724](https://github.com/screwdriver-cd/screwdriver/pull/724)
=> feat(collections): Add pr info to dashboard

app/components/collection-view/component.js, app/components/collection-view/styles.scss, app/components/collection-view/template.hbs, tests/integration/components/collection-view/component-test.js
For the user dashboards, we need to be able to sort pipelines either by name or last build.
Add functionality to allow for sorting by name or last build.
**Screenshots**:
Sort by Name:
Sort by Last Build:
=> feat(collections): Sort pipelines by name and last build

nginx.conf
We should change a redirect url of badge api but it is hard coded.
This PR provides to use ECOSYSTEM_API to determine the url of API.
=> fix: use environment variable to badge url

bin/setup_chrome.sh, bin/setup_firefox.sh, config/targets.js, screwdriver.yaml, testem.js
phantomjs is no longer maintained, and has not had an update since 1/2016. phantomjs does not support any ES2105 syntax, and tests will break when the transpiled code is created for current browsers. Newer browser releases now support a headless mode, which means we can test with the actual browsers we support.
* Utilize [ember-cli targets](http://rwjblue.com/2017/04/21/ember-cli-targets/) to produce sane transpiled code for evergreen browsers. 
* Test with `chrome` in CI mode [`ember test`] instead of `phantomjs`
* Test with `chrome` and `firefox` in dev mode [`ember test --server`]
* The `node:6` container does not support user namespaces, so Chrome must run with the `--no-sandbox` flag. This is normally not recommended.
* Headless Chrome was introduced in Chrome 59. This should install …
=> fix: use targets and real browsers

app/components/pipeline-events-list/template.hbs, tests/acceptance/pipeline-builds-test.js, tests/integration/components/pipeline-events-list/component-test.js
It was confusing for users to have the title "Builds" on the Pipeline page. Changing it to "Events" to be more accurate.
=> fix: Change Builds title to Events on pipeline page

app/components/validator-results/component.js, tests/integration/components/validator-results/component-test.js
Context:
========
If there is a template validation error, the UI displays [Object object]
Objective:
----------
Template validation spits out the raw Joi validation error results, but screwdriver.yaml validation has an array of strings. This PR normalizes the errors array to an array of strings.
=> fix: dereference errors from joi when validating templates

app/components/pipeline-secret-settings/component.js
We could not add Secrets multiple times without browser refresh. 
Because `this.set('isButtonDisabled', true)` probably overrides the value of `isButtonDisabled`  to just `true` from the function.
This PR removes `this.set('isButtonDisabled', true)` because `isButtonDisabled` will be changed automatically by above `this.set('newName', null)` and `this.set('newValue', null)`.
Document: https://emberjs.com/api/ember/2.15/namespaces/Ember.computed
Related: https://github.com/screwdriver-cd/screwdriver/issues/720
=> fix(720): add set function to isButtonDisabled

app/components/pipeline-event-view/template.hbs, app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs, app/components/workflow-graph-vis/component.js, app/components/workflow-graph-vis/template.hbs, app/event/model.js, app/pipeline/builds/index/controller.js, app/pipeline/builds/index/template.hbs, app/pipeline/model.js, ember-cli-build.js, package.json, tests/integration/components/workflow-graph-vis/component-test.js
Context:
========
With the updates to the workflow backend, we need a better way to display a workflow than a linear set of builds
Objective:
-----------
Display a directed graph of the workflow for pipelines and events.
Misc:
------
This PR is meant as a stop-gap to display a graph of the workflow, but the intention is to replace this graph with something much better ASAP. 
This is still missing the following features:
* Automatically update the graph when builds for an event/pipeline update. WORKAROUND: refresh page
* Display meaningful icons for the colorblind. WORKAROUND: Status on hover
* Display a more minified graph for events
* Mobile-friendly view
There are probably a number of other things that should be cleaned up, too.
=> Workflow graphed with vis

screwdriver.yaml
The old scripts used to get the docker tag no longer work. This PR updates the yaml to use scripts in ./toolbox repo.
Should be similar to https://github.com/screwdriver-cd/guide/pull/118
=> fix: Use toolbox repo for screwdriver.yaml

app/components/workflow-graph-vis/component.js
Context:
========
The workflows in the event views were not showing build status or links
Objective:
----------
Fix identification of builds object which can be either a standard javascript Array or a DS.PromiseArray depending on the template including it. Both objects implement nearly the same interface.
=> fix: event workflow not showing build status

app/components/validator-pipeline/template.hbs, app/components/validator-results/component.js, app/components/validator-results/template.hbs, app/components/workflow-graph-vis/component.js, screwdriver.yaml, tests/integration/components/validator-pipeline/component-test.js, tests/integration/components/validator-results/component-test.js
Context:
========
After the workflow updates, the validator failed to display jobs for projects that did not explicitly define workflow
Objective:
-----------
Use the new workflowGraph property instead of workflow to display the workflow and job information
=> fix: new workflow graph breaks validator ui

app/pipeline/builds/index/controller.js
Error message is actually sitting at `e.errors[0].detail`
Reference:
https://github.com/screwdriver-cd/ui/blob/master/app/pipeline/secrets/controller.js#L19
=> fix: get err message from the right place

app/build/model.js, app/pipeline/builds/build/template.hbs, tests/acceptance/build-test.js
Display `statusMessage` on the build page if there is one.
I know this is ugly, but let's get the functionality out and let Chas makes it prettier.
example: I aborted my build with the following `statusMessage`
Related to https://github.com/screwdriver-cd/screwdriver/issues/694
=> fix(694): display statusMessage if there is one

app/components/workflow-graph-d3/component.js, app/utils/graph-tools.js, tests/unit/utils/graph-tools-test.js
Context:
========
We determined that the algorithm for calculating rows/columns for the workflow graph would end up displaying some bubbles on top of each other, or in other ways be difficult to read.
Objective:
----------
Change the algorithm for calculating rows and columns.
Goes from this:
to this:
=> fix: new algorithm for graph rows/columns

app/event/model.js, app/utils/graph-tools.js, tests/unit/event/model-test.js, tests/unit/utils/graph-tools-test.js
Context:
========
The event model is using the old workflow list instead of the new workflowGraph to compute whether it has completed all expected builds. This results in events with the new workflow from never having the isComplete flag true. This may result in unexpected api traffic for completed events.
Objective:
-----------
Use the new workflow graph to compute the number of expected jobs for an event. Pipelines configuring the old workflow will still have a new workflowGraph, so this change is backwards compatible.
Misc:
-----
* Removed the node sort in decorateGraph, as it is no longer necessary, and leads to confusion when comparing output and input.
* Added a event.status to tell the aggregate status of the event
* Wrapped status and isComplete in ObjectPromiseProxy since they …
=> fix(803): event model does not properly compute when it is finished

.eslintrc.js, app/components/pipeline-graph-nav/styles.scss, app/components/workflow-graph-d3/component.js, app/components/workflow-graph-d3/styles.scss, app/helpers/ansi-colorize.js, app/styles/denali-colors.scss, bower.json, ember-cli-build.js, package-lock.json, package.json, tests/unit/helpers/ansi-colorize-test.js
Context:
========
Minor visual tweaks
Objective:
----------
* No longer color edges unless build is successful
* Graph now has small gaps between bubbles and arrow start/end
* Added styling closer to designer guidelines for toggles
Misc:
-----
Moved ansi_up and humanize-duration dependencies from bower to npm per ember guidelines. Bower is maintained, but they [bower] recommend using something else. Remaining bower deps require changes to the vendor ember components that bring them in.
=> fix(803): update styles of toggles and graph

app/components/artifact-tree/component.js
Context:
========
Icons on the artifact tree are not displaying
Changes to the fa-icon component noted deprecations when using icon titles with the "fa-" prefix. A change to all components in a previous PR removed the prefix to remove the deprecation warnings.
Objective:
----------
The jstree component we use to display the artifact list needs the full class names, including the prefix, to display the icons. It does not use the fa-icon component internally.
=> fix(803): artifact icons not displaying

nginx.conf
Context:
=========
Incorrectly quoted `blob:` in worker-src CSP header
Misc
-----
This didn't seem to affect any operation of the current code, but this is triggered by the jstree code that renders our artifacts on the build page.
=> fix: worker-src protocol should not be quoted

app/components/pipeline-options/component.js, app/components/pipeline-options/template.hbs, tests/integration/components/pipeline-options/component-test.js
Jobs listed in options tab are not sorted, so it is hard to find a particular job to disable.
This PR sorts the jobs alphabetically on the options tab so it is easier to find them.
*Previous*
*Now*
Original issue: https://github.com/screwdriver-cd/screwdriver/issues/799
=> fix(799): Sort job names alphabetically in options tab

app/components/template-versions/template.hbs, app/template/service.js, app/templates/detail/route.js, tests/integration/components/template-versions/component-test.js, tests/unit/templates/detail/route-test.js
It's hard for users to figure out what tags are available for each template and what versions they correspond to. It would be ideal if the template tags were listed beside their respective versions on the UI.
List the template tags beside their respective versions on the UI. If a version has multiple tags, then all tags will be listed and delimited by a space. For example:
* 2.0.0 - latest stable
* 1.9.9 - deprecated
* 1.0.0
Issue: https://github.com/screwdriver-cd/screwdriver/issues/851
=> feat(851): Add template tags to template detail page

app/components/artifact-tree/template.hbs, app/components/pipeline-events-list/component.js, app/mixins/model-reloader.js, app/pipeline/builds/index/controller.js, config/environment.js, tests/unit/mixins/model-reloader-test.js, tests/unit/pipeline/builds/index/controller-test.js
Reload timeout for events is configured to be 1.5 mins in production. This does not take into account user's clicking Start button to start a new event which results in users not seeing the new event unless they manually reload the page
Reload events model after new event is started.
=> fix: force reload events model after starting a new build

app/components/build-banner/component.js, app/components/build-banner/styles.scss, app/components/build-banner/template.hbs, tests/integration/components/build-banner/component-test.js
Addresses https://github.com/screwdriver-cd/screwdriver/issues/438
Display a message with spinner when build is in queued state
=> fix(438): display loading message when build is in queued state

app/build-artifact/service.js, app/build-logs/service.js, app/pipeline/builds/build/route.js, tests/unit/build-artifact/service-test.js, tests/unit/build-logs/service-test.js, tests/unit/pipeline/builds/build/route-test.js
Context
=======
Security requirements have been set requiring users to be authenticated to view logs and artifacts
Objective
----------
Add auth requirement to view the build page. Send Authentication headers to api calls to get logs and artifacts.
=> DNM: feat: require auth for build page views

app/pipeline/builds/build/route.js
Context
=======
ember-simple-auth uses the `beforeModel` hook to determine authentication status before allowing a transition. When a route modifies this hook without calling `this._super()` then the auth check never happens. If you do add this to `beforeModel` it will use the global setting for `routeAfterAuthentication` instead of the one defined in the route.
Objective
---------
Move the logic from the `beforeModel` hook in the builds route into `model()` and remove `beforeModel` to get the expected behavior.
=> fix: auth not working on build page

app/build-artifact/service.js, tests/unit/build-artifact/service-test.js
Context
=======
For security reasons, we are adding a requirement that users must be authenticated to view build logs and artifacts
Objective
---------
This PR updates the artifacts list to link users to the API which will generate a short-lived JWT and redirect to the artifact with that credential. https://github.com/screwdriver-cd/screwdriver/pull/873
Fetching the manifest via ajax still requires a call directly to store (with the user's credentials) to prevent a CORS issue with mismatched Origin headers after the redirect.
=> fix: change artifact urls to tunnel through api

app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs, app/components/workflow-graph-d3/component.js, app/components/workflow-graph-d3/styles.scss, app/components/workflow-tooltip/component.js, app/components/workflow-tooltip/styles.scss, app/components/workflow-tooltip/template.hbs, app/pipeline/index/controller.js, app/pipeline/index/template.hbs, app/styles/app.scss, app/styles/denali-button.scss, app/styles/denali-colors.scss, app/utils/graph-tools.js, tests/integration/components/pipeline-workflow/component-test.js, tests/integration/components/workflow-graph-d3/component-test.js, tests/integration/components/workflow-tooltip/component-test.js, tests/unit/utils/graph-tools-test.js
Context:
========
We want to allow users to restart jobs in a given event and retain that event's context in the new event. For example: restart a flakey job to continue the pipeline, or redeploy an artifact after a regression. Issue https://github.com/screwdriver-cd/screwdriver/issues/806
Objective:
-----------
Provide a mechanism that ties to the graph that allows users to start jobs. This generates a dropdown that can be populated with links and other information that allows users to go to the build details page, or restart a build/detached pipeline.
Tooltip:
Confirmation on restart:
Misc:
------
Restrictions:
* Build must be in the most recent event (this is subject to change)
* Build must have previously executed -or- be the root node of a detached workflow
Additional:
------------ …
=> feat(806): Allow users to restart event jobs and detached pipelines

app/utils/graph-tools.js, tests/unit/utils/graph-tools-test.js
Context:
=======
https://github.com/screwdriver-cd/screwdriver/issues/907
Detached workflows can get confusing when the jobs merge together in their respective columns
Objective:
-----------
Make a fully detached pipeline workflow start on its own "clean" row, and bind the height of each of its jobs to start from that row.
=> feat(907): detached workflows graph start on their own row

app/event/model.js, app/event/serializer.js
Context:
========
payload sent to api for (re)start event job didn't include necessary data
Objective:
-----------
Add required data to serializer so it will be sent to API
=> fix: event doesn't serialize parentBuildId or parentEventId

app/components/collection-view/component.js, app/components/collection-view/template.hbs
How can it be reproduced?
Viewing the `/dashboards/:id` page won't display last build status
What did you expect?
To see the status of the last build
What actually occurred?
There was no value being populated in the template
=> Fixed issue where last build status wasn't being displayed on dashboard

app/components/collection-view/component.js, app/components/collection-view/styles.scss, app/components/collection-view/template.hbs, tests/integration/components/collection-view/component-test.js
Context:
========
The colors we use for build bubbles differs from bootstrap's text colors
Objective:
-----------
Fix status bubbles to be more consistent with other graph displays
=> fix: collections - pipeline health bubble colors

app/event/model.js, app/event/serializer.js, app/pipeline/index/controller.js, tests/unit/pipeline/index/controller-test.js
- pass an extra field `buildId` when recreating build/event
- after the API change is done, we can remove extra unnecessary params we pass in now, e.g. `parentBuildId`. API will fetch all the info it need with the `buildId`
Related: https://github.com/screwdriver-cd/screwdriver/issues/904
=> fix: pass buildId when recreating build

app/components/build-log/styles.scss, app/components/build-log/template.hbs
It turned out that chrome has problem with `display: grid` which caused the log lines overlap problem.
Switched it back to `display: flex` fixed the problem.
e.g. build with more than 5000 lines of logs in a step
Related to: https://github.com/screwdriver-cd/screwdriver/issues/949
=> fix: fix logs overlap problem in chrome

app/components/validator-job/template.hbs, tests/integration/components/validator-job/component-test.js
Now that users can configure `sourcePaths` in their `screwdriver.yaml` files, we should reflect those paths in the validator.
This PR adds `sourcePaths` in the validator UI.
Array of strings example:
String example:
Blocked by https://github.com/screwdriver-cd/screwdriver/pull/940 (still needs to be tested and pulled into prod)
Related to https://github.com/screwdriver-cd/screwdriver/issues/911
=> feat(911): Show sourcePaths in validator [6]

app/components/pipeline-options/styles.scss, app/components/pipeline-options/template.hbs
It can be hard to tell when a job is disabled or enabled at a quick glance.
Just adding a title to the toggle button on the pipeline options page and changing the enabled jobs' toggles to green so it's more obvious.
Before:
After:
=> fix: Enabled job will have a green toggle

app/components/pipeline-pr-view/component.js, tests/integration/components/pipeline-pr-view/component-test.js
When a user changes files in a PR that do not fall under `sourcePaths`, the PR will be created but not started. The PR should still show up in the UI, but we need a different icon to indicate it will not be run. The current default for any job that is failed or aborted is a blue X.
This PR adds a special icon for created (but not running) PRs.
Original issue: https://github.com/screwdriver-cd/screwdriver/issues/911
Created status: https://github.com/screwdriver-cd/data-schema/blob/master/models/build.js#L112
=> fix(911): Display special icon for created PRs

app/components/template-header/component.js, app/components/template-header/template.hbs, tests/integration/components/template-header/component-test.js
Currently, there's no way to find out a template's source repo without using the search function.
Issue that tracks this - https://github.com/screwdriver-cd/screwdriver/issues/522
=> Show repo url beside template name in template page

app/components/pipeline-pr-view/component.js, tests/integration/components/pipeline-pr-view/component-test.js
We don't set the build status to CREATED for PRs that shouldn't be run. The builds are not even created.
This PR fixes the icon switch statement to default to the banned icon, since we'll never reach the `CREATED` case.
Related to https://github.com/screwdriver-cd/ui/pull/272
Original issue: https://github.com/screwdriver-cd/screwdriver/issues/911
=> fix(911): Fix PR icon for non-running PR

app/components/validator-job/styles.scss, app/components/validator-job/template.hbs
https://github.com/screwdriver-cd/screwdriver/issues/973
Step commands in template pages show as a single block instead of preserving line wraps.
Preserve line breaks and formatting of a step command as specified in `sd-template.yaml`
Issue: https://github.com/screwdriver-cd/screwdriver/issues/973
=> fix: Preserve line breaks in template step commands

app/components/app-header/template.hbs, tests/integration/components/app-header/component-test.js
Display username if user logged in.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/670
=> fix: display username if logged in

app/components/build-step-collection/styles.scss, app/components/build-step-collection/template.hbs, app/components/pipeline-create-form/styles.scss, app/components/pipeline-create-form/template.hbs, app/components/pipeline-pr-view/component.js, tests/integration/components/pipeline-create-form/component-test.js
It's hard to tell when the git URL you're using is valid or not (the green border is hard to see sometimes).
This PR adds a checkmark next to the input form when the input is valid.
This PR also:
- changes `fa-ban` to `ban` since [ember-font-awesome](https://github.com/martndemus/ember-font-awesome) is deprecating using `fa-`
- changes the chevron directions for setup and teardown steps on the build page to `>`(for collapsed) and `v`(for not collapsed) instead of `v`(for collapsed) and `^`(for not collapsed)
- https://github.com/screwdriver-cd/screwdriver/issues/783
=> fix(783): Make valid pipeline more obvious

app/build-artifact/service.js, tests/unit/build-artifact/service-test.js
It can be hard to find the artifact you're looking for when they are displayed in a weird order.
This PR sorts them alphabetically so they are easier to find.
**Before:**
**After:**
Fixes https://github.com/screwdriver-cd/screwdriver/issues/719
=> fix(719): Sort artifacts alphabetically

app/pipeline/build/controller.js, app/pipeline/index/controller.js, tests/unit/pipeline/build/controller-test.js, tests/unit/pipeline/index/controller-test.js
Parent meta is not used when a user tries to Restart a build from the build detail page.
This PR uses parent meta to start a build.
Resolves https://github.com/screwdriver-cd/screwdriver/issues/1028
=> fix(1028): Parent meta exists when restarting a build from build page

app/build-logs/service.js, app/components/build-log/component.js, app/components/build-log/template.hbs, tests/unit/build-logs/service-test.js
Build logs are stored in the store as pages; each "page" is 100 lines long. Currently, the API log retrieval endpoint, `GET /builds/{id}/steps/{name}/logs`, sends a maximum of 10 pages (ie. 1000 lines) each request.
While this behavior is ideal for retrieving build updates in real-time, it's unnecessary for finished builds. Adding a `pages` query provides additional flexibility; for example, it can be set to a small value for more accurate real-time updates, or a large value to avoid additional HTTP overhead when fetching long logs from finished builds.
* Set the `pages` argument when fetching logs
* `pages=10` when the build's status is `RUNNING`
* `pages=1000` when the build is finished
* Issue: https://github.com/screwdriver-cd/screwdriver/issues/1024
* data-schema PR: …
=> feat(1024): Add pages request query for logs

app/pipeline/index/controller.js, tests/unit/pipeline/index/controller-test.js
When you run a detached job for the first time, there is no `buildId`, so we still need to pass in a bunch of information.
We're getting errors when trying to start a detached build for the first time right now: `Cannot read property 'match' of undefined`
This PR reverts the change to pass in only `buildId` and `causeMessage` so the build start can go through the other workflow: https://github.com/screwdriver-cd/screwdriver/blob/5aedfec539f4da600a1ee109b092a9a56a8b73f8/plugins/events/create.js#L36-L51
Related to https://github.com/screwdriver-cd/ui/pull/283
=> fix: Revert detached build change since it still needs other data to start

app/components/build-log/styles.scss, app/components/build-log/template.hbs, app/helpers/x-duration.js, tests/integration/helpers/x-duration-test.js
It can be hard to read/clunky when switching between the different time options on the build details page, since the formatting changes from timestamp to humanized time.
This PR converts all the build times to `HH:mm:ss` format so they're all consistent. Also changes the cursor when hovering over `Go to Top`, `Go to Bottom`, and `Timestamp`. 
_Note: Firefox still adds funky newlines in between log lines._
Related to https://github.com/screwdriver-cd/screwdriver/issues/945
=> fix(945): Convert build elapsed times to HH:mm:ss format

app/components/build-log/styles.scss, app/components/build-log/template.hbs
Fixes the following space issues wrt step log rendering
1. https://github.com/screwdriver-cd/screwdriver/issues/1034
1.1 Before
1.2 After
1. https://github.com/screwdriver-cd/screwdriver/issues/1049
2.1  https://cd.screwdriver.cd/pipelines/7/builds/22458 for step `test`
=> fix(1034): fix step log space issues

app/components/build-banner/component.js, tests/integration/components/build-banner/component-test.js
Since we're reloading the build-banner all the time when the build is running, coverage info will be recomputed all the time and making the number flashing 
This PR will fix the problem by only computing the info only twice:
- When page first started 
- When coverage step finished and the coverage info has not been set before
=> fix: do not keep recomputing coverage info

app/coverage/service.js, tests/unit/coverage/service-test.js
- set default value when failed to fetch coverage info
- should still be able to get the response from API by inspecting network in browser if needed
=> fix: set default value when failed to fetch coverage info

app/pipeline/build/controller.js, app/pipeline/build/template.hbs, tests/unit/pipeline/build/controller-test.js
When user restarts a job, modal pops up to alert user their job is restarting.
related pr: https://github.com/screwdriver-cd/screwdriver/issues/971
=> add modal popup for restart of job

app/components/nav-banner/component.js, app/pipeline/build/controller.js
Context
=======
When a build page is opened for a build that is still enqueued, the API will be spammed several times a second. This happens because the build-banner component calls `reloadBuild()` when it is either queued or running during the willRender event of the component lifecycle. When the build info is fetched, it causes the willRender event to fire again, and this loop can be extremely short. The current reload event only allows firing once per render loop, but this loop is very fast.
Objective
----------
Hit the API only as often as `BUILD_RELOAD_TIMER`, by throttling all requests to the reload handler.
Misc
------
Fix tests broken in firefox due to nav-banner component writing a value after it has been destroyed.
=> fix build page spamming api constantly when build is queued

app/components/build-log/component.js, app/components/build-log/styles.scss, app/components/build-log/template.hbs
Context
========
There's a lot of wasted space in the header of the build logs.
Time format is not persistent from one build to the next
Objective
-----------
Squash the logs header into one line
Save the selected time formate in localStorage, and load it back when the log  component initializes.
Resolves https://github.com/screwdriver-cd/screwdriver/issues/1068
=> [fix 1068] Save time format choice

app/components/pipeline-options/template.hbs, app/pipeline/model.js, tests/integration/components/pipeline-options/component-test.js
Child pipelines should only be able to be updated/deleted via changing the `screwdriver.yaml` of its parent pipeline.
Hide the "Pipeline" and "Danger zone" sections from the pipeline options UI.
https://github.com/screwdriver-cd/screwdriver/issues/937
=> feat(937): Hide pipeline options for child pipeline

app/components/pipeline-secret-settings/template.hbs, app/components/secret-view/component.js, app/components/secret-view/template.hbs, package-lock.json, tests/integration/components/pipeline-secret-settings/component-test.js, tests/integration/components/secret-view/component-test.js
Child pipelines inherit secrets from their parent pipeline and can override them.
The secrets view for child pipelines should show secrets inherited from their parent pipeline. These secrets should be differentiated and should not be allowed to be updated/deleted. 
Instead, these secrets can be overridden by creating a secret of the same name from the child pipeline. Conversely the secrets can be reverted back to their parent pipeline's values.
https://github.com/screwdriver-cd/screwdriver/issues/937
=> feat(937): Display child pipeline secrets

app/components/workflow-graph-d3/component.js
Show the full job names by increasing the X distance based on the max job name length.  If job names aren't shown then still use 2*ICONSIZE.
This is for https://github.com/screwdriver-cd/screwdriver/issues/1124
=> Show full job names

app/components/build-banner/component.js, tests/integration/components/build-banner/component-test.js
Cannot use `buildStart` attr directly cuz it's formatted by ember and our API didn't expect that date format.  Change it to be the startTime of the first step instead.
https://github.com/screwdriver-cd/ui/blob/master/app/build/model.js#L53
=> fix: set coverage query startTime to first step startTime

app/event/model.js, tests/unit/event/model-test.js
Pipeline page can show longer duration than real with parallel workflow.
I fix this by compute duration using (latest end time) - (earliest create time) for completed event, and (now) - (earliest create time) for running event.
references: [current build.totalDurationMS implementation](https://github.com/screwdriver-cd/ui/blob/4b299ce233419170828edb62e2eb24eba721c262/app/build/model.js#L75-L79)
=> Fix duration for parallel/running workflow

app/command/service.js
Command endpoints should also have auth strategy same as other endpoints.
This PR adds token to fetch command data.
- https://github.com/screwdriver-cd/screwdriver/issues/677
- https://github.com/screwdriver-cd/screwdriver/pull/1136
=> fix(677): fetch commands with token

app/command/service.js, app/commands/detail/route.js, app/components/command-versions/template.hbs, app/components/template-versions/template.hbs, package.json, tests/integration/components/command-versions/component-test.js, tests/integration/components/template-versions/component-test.js, tests/unit/command/service-test.js, tests/unit/commands/detail/router-test.js
UI does not show command tags.
This PR provides to UI for command tags like tempalate's.
It works locally.
(Tag name looks inverse but it's my command execution order.)
This PR also fixed links area for select template version. Current UI switches a version even if the users click white space like the below image.
- Issue: https://github.com/screwdriver-cd/screwdriver/issues/677
=> feat(677): Command tag UI

app/commands/route.js, tests/unit/commands/router-test.js
Commands page does not have a redirection.
This PR adds a redirection to commands pages after logging in.
=> fix: [small] add routeAfterAuthentication to commands

app/template/service.js, app/templates/detail/route.js, tests/unit/template/service-test.js, tests/unit/templates/detail/route-test.js
Template detail should filter on correct namespace
Fixes https://github.com/screwdriver-cd/screwdriver/issues/1158
=> fix(1158): dedeup templates based on full name.

app/pipeline/options/controller.js, app/pipeline/options/route.js, package-lock.json
We're currently not displayed error messages on the UI whenever people do not have permissions to perform actions on the pipeline options page.
This PR bubbles up the error message so it's clear that the user's attempt was invalid.
Trying to toggle the jobs:
Trying to sync:
Trying to delete the pipeline:
Related to https://github.com/screwdriver-cd/screwdriver/issues/1025
=> fix(1025): Display error messages on pipeline options page

app/components/pipeline-pr-view/styles.scss
Currently, the name for the PR is a bit off if it's not linkable.
This PR will add the `margin-left` for that kind of PR.
Example:
=> fix: fix css for pr-view

app/event/model.js, config/environment.js, tests/unit/event/model-test.js
Currently, if you have multiple workflow inside the pipeline. The event duration is wrong even only partial flow is triggered. Because it's using number of jobs inside the workflowGraph to determine if an event finishes or not. 
There is no good way to determine if an event is done with sourcePaths unless we store sourcePaths info in the event itself. Instead of checking number of builds, in this PR, If no new builds added in 2 reloads(each reload has 1 min delay), we consider the event as complete.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1173
=> fix: fix event duration

app/utils/git.js
Blocked by https://github.com/screwdriver-cd/data-schema/pull/265
Related to https://github.com/screwdriver-cd/screwdriver/issues/1200
*Note: wanted to pull in data-schema and use the regex directly from there but it seems to cause havoc with UI tests.*
=> fix(1200): Use checkoutUrl regex from data-schema [2]

app/components/pipeline-header/styles.scss, app/components/pipeline-header/template.hbs
When you successfully (or unsuccessfully) add a pipeline to a collection from the pipeline page, an indicator will popup.
=> add indicators for add to collection on pipeline

app/pipeline/build/controller.js, app/pipeline/build/template.hbs, tests/unit/pipeline/build/controller-test.js
Currently, if restart / stop build failed, there is no err handling.
Resolves https://github.com/screwdriver-cd/screwdriver/issues/1247
=> fix(1274): add err handling for restart/stop builds

app/template/service.js, app/templates/detail/route.js, tests/unit/templates/detail/route-test.js
We have migrated templatedTags table for the namespace issue.
After that, in template detail page, it became that tag names are displayed duplicate in version list.
That's because UI still tries to get tag lists by only the tag name, not include namespace.
As example above, `stable`, `latest` tag next to version `0.0.1` are displayed duplicate.
These duplicate tags come from other template which has same template name (but different namespace).
Refactor template detail page to get tag lists by namespace and name.
Version lists should be like below in this case.
This refactor must be applied only after the migration of namespace in `templateTags` table.
Otherwise it becomes error.
Issue: https://github.com/screwdriver-cd/screwdriver/issues/1237
=> fix(1237): Refactor to show version list in template deatil page.

screwdriver.yaml
Builds failed intermittently because it's not available immediately after deploying. Need to sleep a bit before check
=> fix: sleep before checks

app/components/build-log/component.js, config/environment.js
To improve load time for steps with huge amount of logs
Fetch the remaining old step logs when users click on `Go to Top`
Related to:
- https://github.com/screwdriver-cd/screwdriver/issues/1114
- https://github.com/screwdriver-cd/ui/pull/354
=> feat(1114): Add lazy fetch logic for Go-To-Top

app/components/build-log/styles.scss
Once the build log console surpasses the _comfort zone_ size of log, the scrolling will become janky.
Rasterize the scroll container on GPU. Bit more memory footprint on the GPU in exchange for exponentially faster scrolling experience, esp with 10000+ lines of log
Related to:
- https://github.com/screwdriver-cd/screwdriver/issues/1114
=> fix: rasterize log container for faster GPU scrolling

app/application/adapter.js, tests/unit/pipeline/build/controller-test.js
When REST api call returns `401 Unauthorized`, the app should redirect user to the login page, instead of not rendering and error out.
Invalidate session upon `401` before reaching the router so the router will check for authenticated session first.
https://github.com/screwdriver-cd/screwdriver/issues/1199
=> fix(1199): redirect to login upon 401

app/instance-initializers/supplementary-config.js, nginx.conf
To allow ppl to run UI under a subdir, e.g. `mydomain.com/ui/`, we need to make the rootUrl configurable.
https://github.com/screwdriver-cd/ui/blob/master/config/environment.js#L7
=> fix: make rootUrl configurable for production

nginx.conf
rootURL is compiled during build time for index.html.
to override that during runtime, we can use nginx sub_filter to replace it.
http://nginx.org/en/docs/http/ngx_http_sub_module.html
=> fix: replace rootUrl during runtime

nginx.conf
we have some hardcoded rootUrl value in css files too. by default, sub_filter only do replace for html
https://github.com/screwdriver-cd/ui/blob/master/app/components/workflow-graph-d3/styles.scss
=> fix: modify root url in css files too

screwdriver.yaml
Our K8S_DEPLOY step is currently failing.
Previously we point `api.k8s.screwdriver.cd`  to the ips for `api.ossd.k8s.screwdriver.cd` in AWS route53. That means whenever we update the cluster, manual change is needed. Switch to the correct endpoint.
This PR updates to the correct host.
Related to https://github.com/screwdriver-cd/guide/pull/256
=> fix: switch k8s api endpoint

app/cache/service.js, app/components/build-banner/component.js, app/components/pipeline-options/component.js, app/components/pipeline-options/template.hbs, app/job/model.js, tests/integration/components/pipeline-options/component-test.js, tests/unit/cache/service-test.js
It would be nice if users could invalidate their pipeline or job caches through the UI.
This PR adds functionality for clearing job or pipeline cache.
_Note: not sure how/if we need to add event cache invalidation._
Related to https://github.com/screwdriver-cd/screwdriver/issues/1385
=> feat: Add cache invalidation to pipeline options page

app/components/pipeline-workflow/component.js
Users should be able to start from any job.
This PR fixes a bug that set all jobs to `isRootNode = false` and allows users to start any job as long as it is not root.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1335
=> fix(1335): Allow user to trigger any job

app/cache/service.js
1. SD store service doesn't need cookies
2. CORS credential mode will need to see `Access-Control-Allow-Credentials: true` in the response
=> fix: remove `withCredentials` for SD store

.bowerrc, app/build/model.js, app/components/build-banner/template.hbs, app/components/build-log/component.js, app/components/build-step-collection/template.hbs, app/pipeline/build/template.hbs, package-lock.json, tests/integration/components/build-banner/component-test.js, tests/integration/components/build-log/component-test.js, tests/integration/components/build-step-collection/component-test.js, tests/unit/build/model-test.js
- Add a init step to build
- Changed build `startTime` to `craeteTime` and re-calculate the duration based on `createTime` and `endTime`
- Notes: if no build stats, it will only print out `build created` and `build init done`
screenshot:
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1270
=> fix(1270): add init step

app/components/build-log/component.js
`buildStartTime` is a date object, but `stepEndTime` is String, cannot compare them directly.
=> fix: fix build init fail condition check

app/components/build-log/component.js, tests/integration/components/build-log/component-test.js
Adding `blockedStartTime` to build stats to track gap of time between time when build is enqueued and when it starts running.
Note: Need to merge changes in /screwdriver pipeline to prod first.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1460
=> fix(1460): Add build blocked info in init step [3]

app/build/model.js, app/components/build-banner/component.js, app/components/build-banner/styles.scss, app/components/build-banner/template.hbs, app/components/workflow-graph-d3/component.js, app/pipeline/build/template.hbs, tests/integration/components/build-banner/component-test.js, tests/unit/build/model-test.js
It can be confusing for users to see the Duration text in the banner since they might think the build took all that time, when actually the Duration is made up of queue time, blocked by time, image pull time, and build time.
This PR adds a title when hovering over build duration banner and expands to show a slight build duration breakdown when clicked. Clicking again hides the breakdown.
_Note: This PR might not be a good idea since we still don't have a good way to break down image pull time vs blocked by time. Not sure if it would be better to wait until we have those times before adding any info to the banner._
Hover example with title:
Expansion example:
This PR also fixes so it will not show undefined for build status on hover over a build in the workflow graph (e.g.: `main - …
=> fix: Show breakdown of total build time

app/build/model.js, tests/unit/build/model-test.js
Currently, we're rounding up to 1 unit of time. It can be confusing for people to see numbers that don't add up in their build duration breakdown.
Example:
This PR changes the durations to show to 2 units by default.
Example:
Related to https://github.com/screwdriver-cd/screwdriver/issues/1474
=> fix(1474): Show more detail for build durations

app/components/build-log/styles.scss, app/helpers/ansi-colorize.js, tests/unit/helpers/ansi-colorize-test.js
I think logs displayed on bulid page is hard to read for users especially red one.
I fixed it by specifying color codes for each ansi color.
**Color diff**:
=> Tweak log color

app/utils/build.js
the icon for `FROZEN` is not exactly the same as what we have in the graph cuz that one is from icomoon, not font awesome
https://fontawesome.com/icons/snowflake?style=solid
=> fix: add side icons for FROZEN and COLLAPSED

app/components/build-banner/component.js, app/components/build-banner/template.hbs, app/coverage/service.js, app/pipeline/build/template.hbs, tests/integration/components/build-banner/component-test.js, tests/unit/coverage/service-test.js
- display tests results on build page
- override the sonar coverage / tests results if set in meta
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1452
=> fix(1452): display tests results on build page

app/components/command-header/template.hbs, app/components/template-header/template.hbs, package-lock.json
This PR:
- adds titles for: source code icon, delete icon
- also remove "Back to Commands" link in command page, since we have breadcrumbs now
=> fix: Add titles for source code icon and delete icon on command and template pages

app/build/model.js, app/components/pipeline-pr-list/component.js, app/components/pipeline-pr-list/styles.scss, app/components/pipeline-pr-list/template.hbs, app/event/model.js, app/event/serializer.js, app/pipeline/events/controller.js, app/pipeline/events/template.hbs, app/pipeline/model.js, tests/integration/components/pipeline-pr-list/component-test.js, tests/unit/pipeline/events/controller-test.js
Since the job & build models are lazily fetched, meaning, you will see the jobs first before their builds info got loaded into the models, the start button won't appear until the next render to accommodate for this flow.
Currently, two possible situations that a PR job that has no build.
1. PR's changed files are not in the sourcePaths of any of the jobs in that PR
2. Restricted PR setting causes no build is ever created (thus https://github.com/screwdriver-cd/screwdriver/issues/1528)
Because we do not mark PR job (whether it's restricted or no build simply becuz of no changed file), the UI has to know when to display the start button only for the (2) case.
There could be more edge cases involving PR restriction. But this PR only address the most common ones.
blocked by: …
=> fix: add start button for restricted PR

app/components/pipeline-pr-list/component.js, app/components/pipeline-pr-list/styles.scss, app/components/pipeline-pr-list/template.hbs, app/pipeline/events/controller.js, app/pipeline/events/template.hbs, tests/integration/components/pipeline-pr-list/component-test.js, tests/unit/pipeline/events/controller-test.js
* fix: refactor pipeline-pr-list to be one nested layer less
* fix: correctly reload "job.builds" for started jobs by PR start button
* fix: show start button first then have lazy model taking it out (faster this way without tweaking timer)
related: https://github.com/screwdriver-cd/screwdriver/issues/1528
=> fix: correct behavior for PR start button

app/components/pipeline-event-row/template.hbs, app/components/pipeline-graph-nav/component.js, app/components/pipeline-graph-nav/template.hbs, app/components/pipeline-start/component.js, app/components/pipeline-start/template.hbs, app/pipeline/events/controller.js, app/pipeline/events/template.hbs, app/pipeline/model.js, app/pipeline/pulls/route.js, app/utils/graph-tools.js, tests/acceptance/pipeline-pr-chain-test.js, tests/integration/components/pipeline-event-row/component-test.js, tests/integration/components/pipeline-graph-nav/component-test.js, tests/integration/components/pipeline-start/component-test.js, tests/mock/builds.js, tests/mock/events.js, tests/mock/jobs.js, tests/mock/pipeline.js, tests/mock/workflow-graph.js, tests/unit/pipeline/events/controller-test.js
This PR allows a pipeline page to show the workflowGraph of PR events if the prChain of the pipeline is enabled.
As above, Pipeline page shows PR event workflow graph same as Pipeline event.
It also showed mini workflow graph in PR tab in left side.
These are showed only when the pipeline is enabled for prChain.
The details of this feature is following
1. PR events are aggregated by each PR.
* One latest event is listed for each PR in left side `Pull Requests` tab, even if many events are exists for the PR
* This is realized to use prNum query in [this PR](https://github.com/screwdriver-cd/screwdriver/pull/1550)
1. The user of the pipeline with prChain enabled can start detached job in workflow graph of PR event.
1. The start button of pipeline page starts PR event which is selected in PR …
=> feat(1010): [4] show workflowGraph of PR events when prChain is enabled

app/components/collections-flyout/styles.scss
The collections flyout has a hover effect over the whole "button" but only the text is clickable.  Makes it harder to toggle between collections.  This style tweak should make the whole button area interactive.
=> Fix: Make clickable area for collections larger

app/pipeline/events/route.js
in my previous reload [fix](https://github.com/screwdriver-cd/ui/pull/427/files#diff-c4994ca67dc637b1b5acc8e3227cee80L18) I removed it thinking it's not used anywhere
=> fix: disabled jobs display in event graph is broken

app/components/pipeline-workflow/component.js, app/components/workflow-tooltip/template.hbs, package-lock.json, tests/integration/components/workflow-tooltip/component-test.js
It can be hard for users to know what triggered their pipeline/build if it was a remote trigger.
This PR adds a tooltip with a link to source pipeline for remote triggers.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1332
=> feat(1332): Show remote trigger link when applicable

app/components/pipeline-event-row/styles.scss, app/components/pipeline-event-row/template.hbs, app/components/pipeline-graph-nav/styles.scss, app/components/pipeline-graph-nav/template.hbs, app/event/model.js
It would be easier to rollback to a specific event if there was a more human-readable way to label/distinguish between events.
This PR displays `meta.label` in the pipeline events page as "label". Defaults to showing nothing if the label does not exist.
In this example `meta.label` is set to `VERSION_1.2.3`:
Related to https://github.com/screwdriver-cd/screwdriver/issues/939
=> feat(939): Allow builds to label event using meta.label

app/components/token-view/component.js, app/components/token-view/template.hbs
Currently, pipeline token and user token operations use the same template, and updating the token from either page is hardcoded to hit the same endpoint `/v4/pipelines/:pipelineId/tokens/:tokenId`.
This PR passes in `pipelineId` to the `modifyToken` function to help determine which endpoint to PUT to: `/v4/pipelines/:pipelineId/tokens/:tokenId` or `/v4/tokens/:tokenId`.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1391
=> fix(1391): Fix update user token

app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs, app/components/workflow-tooltip/component.js, app/components/workflow-tooltip/template.hbs, app/pipeline/events/controller.js, app/pipeline/events/template.hbs, package-lock.json, tests/unit/pipeline/events/controller-test.js
It would be nice if users could stop a build from the pipeline events graph.
This PR displays the "Stop Build" option if a build is active.
It also stops the build when the option is clicked.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1516
=> feat(1516): Enable stopping a build from pipeline events graph

app/pipeline/events/controller.js, tests/unit/pipeline/events/controller-test.js
Should reload builds after stopping one.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1516
=> fix(1516): Reload after stop build

app/components/pipeline-nav/styles.scss, app/components/pipeline-nav/template.hbs, tests/integration/components/pipeline-nav/component-test.js
live showing the 4th tab on pipeline page, plus a little visual cue
=> fix(build metrics): live with a visual cue

app/pipeline/build/controller.js, app/pipeline/events/controller.js, app/pipeline/events/template.hbs, package-lock.json, tests/unit/pipeline/build/controller-test.js, tests/unit/pipeline/events/controller-test.js
When an event is started by a periodic build, it can be hard for users to know if the build was started manually by a user, through a commit, or by Screwdriver automatically.
This PR passes in `causeMessage` when a new event is created manually.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1058
=> fix(1058): Pass in causeMessage to event create

app/components/pipeline-graph-nav/styles.scss, app/components/pipeline-graph-nav/template.hbs, app/components/pipeline-start/template.hbs, app/event-stop/service.js, app/pipeline/events/controller.js, app/pipeline/events/template.hbs, tests/unit/event-stop/service-test.js, tests/unit/pipeline/events/controller-test.js
It can be annoying for users to have to manually stop each build in an event. It would be nice if they could stop all running/queued/blocked builds with one click or API call.
This PR adds a Stop button to the main pipeline event graph so a user can stop all running builds with one click. The button only shows if there are builds running.
Example:
On hover it will show a text hint:
Related to https://github.com/screwdriver-cd/screwdriver/issues/1285
=> feat(1285): Can stop all builds in a selected event

Dockerfile
Nginx updated their `stable-alpine` Docker image 8 hours ago to use nginx 1.16 (https://github.com/nginxinc/docker-nginx/commit/9a052e07b2c283df9960375ee40be50c5c462a7e)
This breaks the UI
```
2019/04/24 19:04:58 [emerg] 1#1: module "/usr/lib/nginx/modules/ndk_http_module.so" version 1014002 instead of 1016000 in /etc/nginx/nginx.conf:1
nginx: [emerg] module "/usr/lib/nginx/modules/ndk_http_module.so" version 1014002 instead of 1016000 in /etc/nginx/nginx.conf:1
```
This PR pins nginx to 1.14.2-alpine, which was the previous version before the update.
nginx docker hub: https://hub.docker.com/_/nginx
=> fix: Pin to nginx:1.14.2-alpine

app/components/build-log/component.js
this should be enough to prevent:
1) potential double fetching
2) fetching of just one line of log
=> fix: small fix to add to my last attempt

app/pipeline/events/controller.js, tests/unit/pipeline/events/controller-test.js
When choose pull request event and start non-existed job (gray color job), new event is not executed as pull request job. 
Its better to create new PR event, when start job from PR event.
When start detached job from PR event, the value of startFrom has prefix of `PR-<num>:`.
Even start job which trigger from commit build has `PR-<num>:` in pull request tab, `startFrom` has pr prefix. When execute these jobs, user got 404.I think it makes the PR event more secure.
1. Open PR. 
2. Exec job from chain2 PR.
3. Exec chain1 PR, then the new event was created in event tab.
=> Fix pr detach job

app/components/collection-view/component.js, app/components/collection-view/template.hbs, tests/integration/components/collection-view/component-test.js
The collection view is not using the pipeline model, the collection object itself contains a list of pipelines. This PR will add rootDir to branch if it exists.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1455
=> fix: show rootDir if exists on collection view

app/components/pipeline-graph-nav/component.js, app/components/pipeline-graph-nav/template.hbs, app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs, app/components/workflow-graph-d3/component.js, app/components/workflow-tooltip/template.hbs, app/pipeline-triggers/service.js, app/pipeline/events/controller.js, app/pipeline/events/route.js, app/pipeline/events/template.hbs, app/utils/graph-tools.js, package-lock.json, tests/acceptance/create-page-test.js, tests/acceptance/pipeline-builds-test.js, tests/integration/components/pipeline-graph-nav/component-test.js, tests/integration/components/workflow-graph-d3/component-test.js, tests/integration/components/workflow-tooltip/component-test.js, tests/unit/pipeline-startall/service-test.js, tests/unit/pipeline-triggers/service-test.js
It's hard to tell what pipelines are triggered by one pipeline.
This PR adds a toggle button to show or hide downstream triggers. The downstream trigger node will have links to the next pipeline(s).
Note: still need to fix some small things, please DNM.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1333
=> feat(1333): Add toggle to show downstream triggers in pipeline event graph

app/components/app-header/template.hbs, tests/integration/components/pipeline-options/component-test.js, tests/integration/components/pipeline-secret-settings/component-test.js, tests/integration/components/secret-view/component-test.js
Code refactoring
1. Refactor string `SPACE` into keyCode `32`
2. Refactor string `ENTER` into keyCode `13`
3. Replace `collection` route in the header and use `home` route instead
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
=> [Refactor] Refactor string space into keyCode 32

app/command/service.js, app/commands/detail/controller.js, app/commands/detail/template.hbs, app/components/command-header/component.js, app/components/command-header/styles.scss, app/components/command-header/template.hbs, app/components/template-header/component.js, app/components/template-header/styles.scss, app/components/template-header/template.hbs, app/template/service.js, app/templates/detail/controller.js, app/templates/detail/template.hbs, package-lock.json, package.json, tests/integration/components/command-header/component-test.js, tests/integration/components/template-header/component-test.js, tests/unit/command/service-test.js, tests/unit/commands/detail/controller-test.js, tests/unit/template/service-test.js, tests/unit/templates/detail/controller-test.js
Screwdriver admins will need a UI to (un)mark template/command as `trusted`
This PR adds the required UI components
- Not the prettiest UI but it's better than doing separate solo pipeline/manual script/direct sql
- While api endpoints require token with admin scope, UI does have the jwt with right privilege for admins. No need to acquire another token for this.
https://github.com/screwdriver-cd/screwdriver/issues/1427
=>  fix: add admin UI to (un)mark template/command as "trusted"

app/components/pipeline-event-row/component.js, app/components/pipeline-event-row/template.hbs, app/components/pipeline-workflow/template.hbs, app/components/workflow-graph-d3/component.js, app/components/workflow-graph-d3/styles.scss, app/event/model.js, app/styles/app.scss, app/utils/build.js, app/utils/graph-tools.js, tests/integration/components/pipeline-event-row/component-test.js, tests/integration/components/pipeline-graph-nav/component-test.js, tests/unit/event/model-test.js
`skip ci` events' view is hard to recognize on UI.
So I improved skip ci events' view.
1. Build status becomes SKIPPED
1. Pipeline graph shows only skipped icon
1. Events list item also shows skipped icon
Temporary, I used stable status icon and running icon color for skip status.
If you have more better icon and color, feel free to change icon and color.
* Add `SKIPPED` status.
* Add `isSkipped` property to event model, and fix some property.
* Does not render workflow-graph in event-row when event status is skipped.
* Only render skipped icon in workflow-graph when event status is skipped.
https://github.com/screwdriver-cd/screwdriver/issues/1685
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that …
=> feat(1685): Improve skip ci event view

app/event/model.js, tests/unit/event/model-test.js
When starting build from `skip ci` event, the new event status still SKIPPED.
It should be the new status of new builds.
`isSkipped` is false when an event has builds.
screwdriver-cd/screwdriver#1685
=> fix(1685): Fix SKIPPED status

app/components/artifact-preview/component.js, app/components/artifact-preview/template.hbs, app/components/artifact-tree/component.js, app/components/build-step-collection/component.js, app/components/build-step-collection/template.hbs, app/styles/app.scss, config/environment.js, tests/integration/components/artifact-preview/component-test.js, tests/integration/components/build-step-collection/component-test.js
This PR implemented previewing artifacts feature by loading content from iframe. Such mechanism can keep the `html` in a sandboxed isolated environment, and not pollute the parent frame.
This feature allows UI to have preview functionality, to see what artifacts being generated prior downloading such file. i.e. html or any browser viewable items. 
See screenshot
UI: https://github.com/screwdriver-cd/ui/pull/465
Backend: https://github.com/screwdriver-cd/screwdriver/pull/1703
Store: https://github.com/screwdriver-cd/store/pull/88
=> feat: implement artifacts preview for screwdriver UI

app/components/command-header/template.hbs
When hovering over the delete icon for a command, it says "delete template" instead of "delete command".
Fix above typo
N/A
=> Fix hover text: "template" => "command"

app/components/validator-job/component.js, app/components/validator-job/template.hbs, tests/integration/components/validator-job/component-test.js
We want to know what templates and commands are used in a job when using validator or visiting template details page.
Therefore, I added templates and commands link on the result of validation and template details page.
validator
template details
If `SD_TEMPLATE_FULLNAME` env exists, a job uses template.
So I add link to template on job details.
And, validator searches all commands with regex `sd-cmd\s+exec\s+([\w-]+\/[\w-]+)` to find executed sd-cmd.
If sd-cmd is executed in a job, I add link to all executed sd-cmd on job details.
=> feat: show template and commands in validator

app/components/user-link/template.hbs, tests/integration/components/user-link/component-test.js
A periodic build is started by Screwdriver scheduler.
However, Screwdriver scheduler has no avatar.
Because of this, a user-link of periodic build's detail page is broken.
Therefore, I fixed to use favicon for an avatar when build user is scheduler.
If a build user is scheduler, favicon is used for an src of user img.
=> fix: Use favicon for scheduler's avatar

screwdriver.yaml
We need to limit k8s api access not opening it to the whole internet.
=> try internal k8s api for deployment

app/components/pipeline-graph-nav/component.js, app/components/pipeline-graph-nav/template.hbs, app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs, app/components/workflow-tooltip/component.js, app/components/workflow-tooltip/template.hbs, app/job/model.js, app/pipeline/events/controller.js, tests/integration/components/pipeline-graph-nav/component-test.js, tests/integration/components/pipeline-workflow/component-test.js, tests/unit/pipeline/events/controller-test.js
UI is making calls to ` /jobs/:jobID/builds` end point for all jobs of a pipeline. This is causing serious performance issues  for pipelines with large build history. There is no reason for UI to make this call, except for fetching PR build data, since there is no API available to fetch details of a PR.
Reduce job -> builds API call
1. Remove all references of `job.builds` unless in PR job context. 
1. Remove auto reload of job model.
1. Remove aggregate view
=> fix: do not fetch job/builds unless it's for PR

app/components/pipeline-workflow/template.hbs
Sometime user get confused when the job's sha is not the pipeline's branch. It happen when user set  branch specific job such as `requires: [~commi, ~commit:developnt]`.
I try to make it easy to understand what kind job user will start.
Add commit message and able to jump commit change page.
before:
after:
related https://github.com/screwdriver-cd/screwdriver/issues/1706
=> feat: update restart modal sentences

app/collection/model.js, app/components/collections-flyout/template.hbs
To avoid confusion for users that they cannot delete default pipeline (`My Pipelines`), knowing that API will drop if the collection `type` attribute is `default`.
Remove delete option to default pipeline
Before: 
After:
=> fix: default pipeline

app/commands/detail/controller.js, app/commands/detail/route.js, app/commands/detail/template.hbs, app/components/command-versions/template.hbs, app/components/tc-collection-linker/template.hbs, app/components/template-versions/template.hbs, app/router.js, app/templates/detail/controller.js, app/templates/detail/route.js, app/templates/detail/template.hbs, tests/integration/components/command-versions/component-test.js, tests/integration/components/template-versions/component-test.js, tests/unit/commands/detail/controller-test.js, tests/unit/commands/detail/router-test.js, tests/unit/template/service-test.js, tests/unit/templates/detail/controller-test.js, tests/unit/templates/detail/route-test.js
When the version is clicked on the template/command details screen, the content is rewritten by javascript. Since there is no link to the details screen of each version, they cannot be shared. So instead of rewriting content we changed for a link to each template and command.
The version of the template/command details screen is changed to `href` like below.
```
command: [
{id:1, namespace:'foo', name:'bar', version:'1.0.0'}
{id:2, namespace:'foo', name:'bar', version:'2.0.0 - latest'}
]  
```
1. `/foo/bar`
- It shows the screen of `latest (2.0.0)`
2. `/foo/bar/1.0.0`
- It shows the screen of `1.0.0`
3. `/foo/bar/latest`
- It shows the screen of `latest (2.0.0)`
4. `/foo/bar/9.9.9` or `/foo/bar/nonexisttag`
- It shows the screen of `404`
I confirm that this contribution is made under the …
=> feat: Enable URL with specific version or tag of commands or templates

app/components/command-versions/template.hbs, app/components/template-versions/template.hbs, tests/integration/components/command-versions/component-test.js, tests/integration/components/template-versions/component-test.js
In the case of 
* /template/namespace/name 
* /command/namespace/name 
When accessing, the screen became white like below.
This PR fixes the problem.
This PR changes the link fullpath.
=> fix: bug of version link in template/command detail page

app/components/command-versions/template.hbs, app/components/tc-collection-linker/template.hbs, app/components/tc-collection-list/component.js, app/components/template-versions/template.hbs, tests/integration/components/command-versions/component-test.js, tests/integration/components/tc-collection-list/component-test.js, tests/integration/components/template-versions/component-test.js
There is complication with aggregate group query related to `version` text on templates and commands. Remove it entirely until the data part is figured out.
1. On templates and commands pages, clicking on name on the table row reload and navigate to `/{templates|commands}/{namespace}/{name}` route which is now pointing to the latest version implicitly
2. the version links on the detail page will do client side navigation instead of hard-core reload
3. fix tests
=> fix: remove version display column on templates & commands table

app/components/collections-flyout/component.js
Collections which were created prior to adding collection type are not showing up in UI
Invert the check for normal collection
=> fix: invert check for normal collection

app/components/nav-banner/template.hbs
Sometimes it can be useful to add links in the banner message.
This PR allows for links in the banner message.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1725
=> fix(1725): Allow for <a> in banner

app/components/collection-view/template.hbs, app/dashboard/show/route.js, tests/integration/components/collection-view/component-test.js
1) Label `Move To` actually keeps the original pipeline inside the original collection, which should be. We need to change the label from `Move To` to `Copy To`.
2) Metrics fetch no longer exist pipelineId will result to 404 pages.
This PR Changes the label from `Move To` to `Copy To`
Before: 
After:
2)  While it still shows errors, but this time the errors are caught by Ember.RSVP, instead of bubbling up, and will not 404 pages
=> fix: change word from move-to to copy-to and fix metrics error bubbling up

app/components/command-header/template.hbs, app/components/template-header/template.hbs, package-lock.json
Sometimes the pipeline is removed before people get a change to delete the template/command. Even if the pipeline doesn't exist, a Screwdriver admin should be able to remove the template/command through the UI.
This PR always shows the trash icon on the template/command pages. The backend should be able to handle the case where a pipeline doesn't exist but the user is a Screwdriver admin gracefully: https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/templates/index.js#L39-L41
Related to https://github.com/screwdriver-cd/screwdriver/issues/1651
=> fix(1651): Allow admins to delete templates and commands with no pipelines

app/components/collection-view/component.js, app/components/events-thumbnail/component.js, tests/integration/components/collection-view/component-test.js, tests/integration/components/events-thumbnail/component-test.js
Events-thumbnail components show outdated events info because of an API bug. Now the API is fixed, we need to make corresponding changes for the UI.
Make events-thumbnail show latest events info.
[screwdriver feat(947)](https://github.com/screwdriver-cd/ui/pull/480)
=> fix: Reverse eventsInfo array because of pipeline model change

app/pipeline/controller.js, tests/unit/pipeline/controller-test.js
We must use `set` to notify that Ember this attribute is dirty in 
```javascript
if (!pipelineIds.includes(pipelineId)) {
collection.set('pipelineIds', [...pipelineIds, pipelineId]);
}
```
Since this method 👇  is missing `this._super(...arguments);` and does some manual `isDirty` checks.
https://github.com/screwdriver-cd/ui/blob/c95d6d6d333e3d8b2aeaccbe8e2ba12cd9c7ea18/app/collection/serializer.js#L10-L17
Otherwise, current 👆  will send `PUT` empty object
This PR fixed that so we can add pipeline to collection from pipeline detail's page
=> fix: pipeline controller.js

app/components/build-banner/template.hbs, app/components/pipeline-event-row/component.js, app/components/pipeline-event-row/template.hbs, app/components/pipeline-graph-nav/template.hbs, tests/integration/components/pipeline-event-row/component-test.js, tests/integration/components/pipeline-graph-nav/component-test.js
Currently ui displays creator user name rather than commit author user name. Most of time both are the same, when event is create by another build, UI displays previous build's author rather than sd-builtbot. This lead to user confusion due to ambiguity. 
UI now displays both committer and event creator, and in event panel correctly labels `committer` rather than `user`. And in case of event triggered by external pipeline, creator
will now link to according external build
Before:
After:
1.when event is trigger by external pipeline
2.when creator and committer is the same
3.when creator and committer is different
https://github.com/screwdriver-cd/screwdriver/issues/1790
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's …
=> fix(1833): event view does not convey context which triggered it

app/components/pipeline-event-row/component.js, app/components/pipeline-event-row/template.hbs
This PR fixing a runtime exception, and breaks the UI back button.
This PR fix exactly that by adding check to `buildId` when using `{{link-to}}`, if `buildId` exists, it would route to pipeline with given build, otherwise will default to pipeline with given `pipelineId`
=> fix: ui patching when buildId is undefined for unconventional causeMessage

app/components/pipeline-event-row/component.js, tests/integration/components/pipeline-event-row/component-test.js
In previous pr I enhanced event view, but there are builds with incorrect/undefined startFrom.
Causing UI to break.
Handle incorrect/undefined startFrom
https://github.com/screwdriver-cd/screwdriver/issues/1790
=> fix(1790): handle undefined and incorrect startFrom

app/components/pipeline-options/component.js, app/components/pipeline-options/template.hbs
If you just uncheck the checkbox but without zeroing out the text box, it still uses that value as the folder.
This PR fixes that, and will only send `rootDir` if is `checked`
=> fix: unchecking "My source directory is not at the checkout root" 

app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs, app/pipeline/events/controller.js, app/pipeline/events/route.js, tests/integration/components/pipeline-workflow/component-test.js, tests/mock/frozenBuild.js
UI work for PR: https://github.com/screwdriver-cd/data-schema/pull/360
This allows users to give reason (to override causeMessage) to `force start` during the `freezeWindow` period. 
=> fix: add cause message to override during freezeWindow

app/components/build-banner/styles.scss
The build page shows long job name in a header inappropriately.
To fix this bug, I added a `word-wrap` property to css.
before:
after:
Added `word-wrap: break-word;` property to css.
https://github.com/screwdriver-cd/screwdriver/issues/1656
=> fix(1656): Add word-wrap property

app/commands/detail/route.js, app/helpers/compare-versions.js, app/templates/detail/route.js, tests/unit/commands/detail/router-test.js, tests/unit/helpers/compare-versions-test.js, tests/unit/templates/detail/route-test.js
My screwdriver.cd has a `common/jq` command.
For example, if I input the following in the validator form, the list of Commands displays `common/jq@1.5`.
Clicking on the `common/jq@1.5` link will display the not found page.
Even if only the major version is specified, the command details page can be accessed. And I fixed the same for templates page.
https://github.com/screwdriver-cd/ui/pull/479
https://github.com/screwdriver-cd/ui/pull/504
I fixed based on this.
https://github.com/screwdriver-cd/models/blob/b88a006b832cfafa96f1114b1149055cc108f1b7/lib/commandFactory.js#L136-L153
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of …
=> fix: Display a detail page with just the major version

app/components/pipeline-workflow/component.js
Now that users can use parallel fork join, the UI should link to the remote pipeline appropriately.
This PR changes the remote pipeline to have a Go to remote pipeline tooltip.
Before:
After:
Related to https://github.com/screwdriver-cd/screwdriver/issues/1710
=> fix(1710): Show external trigger remote pipeline link

app/pipeline/build/index/route.js, app/pipeline/build/route.js, app/router.js, tests/unit/pipeline/build/route-test.js
Current implementation is that when we land to artifacts route, it will redirect to `/pipeline/1/step/` route if we encountered failure step.
This PR will prevent the redirection if users are on artifacts route.
https://github.com/screwdriver-cd/screwdriver/issues/1903
=> fix(1903): split active step inside artifacts

app/components/build-log/component.js, app/components/build-log/template.hbs
It's often useful to see the time in UTC instead of local time.
Adds another item in the rotation when clicking through the various timestamp formats to show the event time in UTC.
https://github.com/stefanpenner/ember-moment#common-optional-named-arguments
```
timeZone | An optional String time zone, defaults to moment.timeZone (the default time zone)
```
I don't see a great way to test this. Can the UI be started up with static data or do I need to set up a complete local cluster to verify this change?
=> Add UTC time as a log format option.

app/components/pipeline-header/template.hbs, app/helpers/branch-url-encode.js, tests/integration/helpers/branch-url-encode-test.js
This PR is for this Issue.
https://github.com/screwdriver-cd/screwdriver/issues/1925
Number sign of the branch name must be encoded to `%23`.
**Current**
**After**
Link to below page.
=> fix(1925): support branch names with number sign

app/pipeline/build/artifacts/route.js, app/pipeline/build/index/route.js, app/pipeline/build/route.js, app/pipeline/build/step/route.js, tests/unit/pipeline/build/route-test.js
Currently, a ui bug was introduced by pr https://github.com/screwdriver-cd/ui/pull/517
https://github.com/screwdriver-cd/ui/pull/517/files#diff-0a13691fa8d703678c66fb99133a59fbL47
It causes users click on previous steps will always redirect to most active step.
This is not desired behavior, and this PR fixes it by using (reverting) `redirect` in parent route instead of using `didTransition` action hook.
=> fix: click previous step when running build

app/components/workflow-graph-d3/component.js
The previous PR: https://github.com/screwdriver-cd/ui/pull/520 will remove parallel joined jobs
This PR will only remove jobs that name starts with `'sd@'`, and is not a `src`(source) node of an edge.
The previous implementation will remove nodes bluntly based on the name of `'sd@'`
Expected:
2 sample pipelines:
- https://cd.screwdriver.cd/pipelines/4074/events
- https://cd.screwdriver.cd/pipelines/3983/events
=> fix: properly display workflow that has sd-external job as parallel join jobs

app/components/build-banner/component.js, tests/integration/components/build-banner/component-test.js
Currently there's no way to set test and coverage urls even though we can set summary.
Allow user to set test and coverage urls .
https://github.com/screwdriver-cd/screwdriver/issues/1718
=> fix(1718): allow user to set test and coverage url

app/components/collection-dropdown/component.js, app/components/collection-dropdown/template.hbs, tests/integration/components/collection-dropdown/component-test.js, tests/integration/components/collection-view/component-test.js
When trying to add a pipeline to a collection, the default collection (My Pipelines) shows up as an option. When trying to click that option, I get an error Could not add Pipeline to `My Pipelines`.
Since users should not be allowed to modify the default collection, that option should not show up to the Add to Collection list.
https://github.com/screwdriver-cd/screwdriver/issues/1910
=> fix(1910):Remove default pipelines from 'Add to Collection' list

app/build-logs/service.js, app/shuttle/service.js, config/environment.js, screwdriver.yaml, tests/unit/build-logs/service-test.js, tests/unit/shuttle/service-test.js
Minor UI optimization
- increase `LOG_RELOAD_TIMER` from `1` to `3`s
- refactored `fetchLog` to `shuttle` api service
- add tests for `shuttle` service
- upgrade to `node:12` for https://github.com/screwdriver-cd/screwdriver/issues/1722
Issue: https://github.com/screwdriver-cd/screwdriver/issues/1950
Ember Data / Ember Ajax / Ember Fetch proposal
https://gist.github.com/tomdale/203ea125acd0be8b5f1f
=> fix(1950): refactor fetchLogs api call

app/pipeline/build/route.js, tests/unit/pipeline/build/route-test.js
If users visit a failed build with artifacts link directly, then users should not be redirected to the failed step of the build.
Please see issue: https://github.com/screwdriver-cd/screwdriver/issues/1963
This PR adds check only redirect to step route for 'pipeline.build.step', 'pipeline.build.index', which will NOT redirect users when their intention is to visit the artifacts directly.
issue: https://github.com/screwdriver-cd/screwdriver/issues/1963
FYI: 
I always refer to this doc :) 
Ember Route: https://alexdiliberto.com/posts/ember-route-hooks-a-complete-look/
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright …
=> fix(1963): fix redirect route to step route on all build route redirections

app/components/template-header/styles.scss, app/components/template-header/template.hbs, app/template/service.js, app/templates/detail/controller.js, app/templates/detail/route.js, tests/unit/template/service-test.js, tests/unit/templates/detail/route-test.js
We need to display template popularity metrics on the template details page.
Before:
After:
This PR adds template popularity metrics to the template details page. Additionally, it adds caching of template data so that when different template versions are selected on the template details page additional API calls are not made.
https://github.com/screwdriver-cd/screwdriver/issues/1091
=> feat(1091): add template popularity metrics to template details page

app/pipeline/serializer.js, tests/unit/pipeline/serializer-test.js
https://github.com/screwdriver-cd/screwdriver/issues/1604
https://github.com/screwdriver-cd/ui/blame/66dce078f0052b8a2b91d12b1fe4d9980fc81654/app/event/serializer.js 
This PR fixes sorting order on `show/hide triggers`. 
Please see screenshot: 
Before: 
After:
Related 
Issues: 
1) https://github.com/screwdriver-cd/screwdriver/issues/1359
PRs: 
1) https://github.com/screwdriver-cd/ui/pull/399
=> fix(1604): sorting order when toggle triggers on the UI

app/pipeline/build/controller.js, tests/unit/pipeline/build/controller-test.js
We had a PR: https://github.com/screwdriver-cd/ui/pull/528
That increased the reload time from `1s` to `3s`:
https://github.com/screwdriver-cd/ui/pull/528/files#diff-695693c5dabaffb064bde5b060195ff7L52
Which effects `timeout` here 
https://github.com/screwdriver-cd/ui/blob/1b8b32deb80a2c1744d1d61ff28de910d94a12c1/app/pipeline/build/controller.js#L116-L123
Cause UI to behave that: if users are on pipeline/build page, and go back to any route. Within the timeout period, users will be redirected back. This behavior was not intended, and was not visible when the timeout was set to `1s`. 
But this undesired behavior is visible now, and we need to address it. Hence this PR. Credits to @klu909 who spotted this. 
This will only trigger `changeBuildStep` if it's from the desired routes, such as …
=> fix: route from pipeline/build page to any route will redirect within timeout

app/components/build-log/component.js
This is kind annoying when UI faces racing condition: when component is getting destroyed while setting property in the component. See screenshot:
Add `!this.get('isDestroyed') && !this.get('isDestroying')` to ensure component is present. 
See other reference: 
1) [Cannot update watchers for model after it has been destroyed · Issue #5387 · emberjs/data](https://github.com/emberjs/data/issues/5387)
2) Ember Component Property: [isDestroyed](https://api.emberjs.com/ember/3.16/classes/Component/properties/isDestroyed?anchor=isDestroyed)
I'm actually thinking we should integrate with [ember-concurrency](http://ember-concurrency.com) slowly. 
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the …
=> fix: buildLog component set property when component is destroyed

app/commands/detail/route.js, app/templates/detail/route.js, tests/unit/commands/detail/router-test.js, tests/unit/templates/detail/route-test.js
This PR modifies the following issue.
https://github.com/screwdriver-cd/screwdriver/issues/1891
Modify the API as shown below. Correct the UI to the same behavior.
https://github.com/screwdriver-cd/models/pull/439
About the order in which to merge the API and UI, there is no dependency.
https://github.com/screwdriver-cd/screwdriver/issues/1891
=> fix(1891): Correctly handle the startsWith of the version

app/components/build-log/template.hbs
https://github.com/screwdriver-cd/ui/pull/519 attempted to add utc time as a new format but it didn't actually work (time was still formatted in local format). This fixes that.
=> fix: correctly format utc time

app/components/command-header/template.hbs, app/components/template-header/template.hbs
I fix [issue](https://github.com/screwdriver-cd/screwdriver/issues/1977).
Currently, template / command can only be deleted by cluster admin.
It is inconvenient because the admin of the template/command cannot be deleted.
Therefore, I modify it so that the pipeline admin can  be deleted.
Modify non-cluster admins can click on the trash icon.
If anyone other than the cluster admin and the pipeline admin tries to delete, an err message will be displayed.
https://github.com/screwdriver-cd/screwdriver/issues/1977
=> fix(1977): The pipeline admin deletes template/command

app/components/collection-view/component.js, app/home/route.js
Fixed issue https://github.com/screwdriver-cd/screwdriver/issues/1383
This PR is to keep last viewed collection. When a user back to collection screen, the last viewed collection is shown.
The collection id data is deleted if a user reload browser on other screen than collections, and I cannot find the way to keep after reloading. 
However, it might be enough to solve this issue.
https://github.com/screwdriver-cd/screwdriver/issues/1383
=> fix(1383): Keep selecting the last viewed collection

app/components/build-log/styles.scss, app/components/build-step-collection/template.hbs
Currently, the space under the build log is not constant. It depends on the window size.
I fix it to fill the build log to the bottom.
before:
after:
Fill the build log to the bottom.
=> fix: fill bottom space.

app/components/collection-view/component.js, app/home/route.js, tests/acceptance/dashboards-test.js
This PR enhances the PR https://github.com/screwdriver-cd/ui/pull/540
The PR https://github.com/screwdriver-cd/ui/pull/540 does not keep collection ID after going through Template/Command detail page. The lifetime is too short to be expected.
Using local storage is effective at these points.
- Keep collection ID when accessing collections page after go through Template/Command detail page
- Keep collection ID even if it was accessed from another tab of the browser
https://github.com/screwdriver-cd/screwdriver/issues/1383
=> fix(1383): Keep collection ID in localStorage

app/components/build-log/styles.scss
Because `.wrap`'s height is `vh70`, bottom space of build log still remain like below.
Fill the build log to the bottom.
After:
Fill the build log to the bottom.
#541 
=> fix: fix build log display

app/components/collection-view/component.js
This PR is an additional feature of https://github.com/screwdriver-cd/ui/pull/543.
This PR is to keep last viewed collection type.
Reload the screen to return to the default card type.
Therefore, I modify to Keep collection view type in localStorage.
Similar to https://github.com/screwdriver-cd/ui/pull/543
=>  fix: Keep collection view type in localStorage

app/components/pipeline-create-form/component.js, app/components/pipeline-create-form/styles.scss, app/components/pipeline-create-form/template.hbs, app/components/quickstart-guide/component.js, app/components/quickstart-guide/styles.scss, app/components/quickstart-guide/template.hbs, app/create/controller.js, app/create/route.js, app/create/template.hbs, app/shuttle/service.js, app/styles/app.scss, app/validator/controller.js, package.json, tests/acceptance/create-page-test.js, tests/integration/components/quickstart-guide/component-test.js
Add an quickstart guide on create pipeline page.
After I took a look at 
- https://prismjs.com
- https://craig.is/making/rainbows
I decided its easier to implement the simple color syntax myself.
It supports `command`, `subcommand` `argument`, simple enough :P 
> -- TESTS PENDING --
Trying to make things easier for both first time users and experienced screwdriver users
Screenshot: 
Gif: 
Introduced: 
- [Ember power select](https://2-x.ember-power-select.com/docs/how-to-use-it/)
Also took advantage of using: 
- https://yapplabs.github.io/ember-wormhole/
=> feat: add Onboarding Guide

app/components/collections-flyout/component.js, app/dashboard/show/route.js
If user accesses deleted collection URL, deleted collection ID is stored in localstorage.
Then, user accesses home (e.g. `https://mysdhost/`), user redirected to the collection which is stored in localstorage. However, collection collection which is stored in localstorage is already deleted, user redirected to `404` page.
- Reset localstorage when redirect to `404` page.
- Reset localstorage when deleting collection which is displayed.
=> fix: Reset collectionId cache

app/pipeline/events/route.js
PR: https://github.com/screwdriver-cd/screwdriver/issues/2049
Now this PR will make the following links: 
1) https://cd.screwdriver.cd/pipelines/100000
2) https://cd.screwdriver.cd/pipelines/100000/builds/20000
to be redirected to 404 page
Related to https://github.com/screwdriver-cd/screwdriver/issues/1400
=> fix(2049): redirect to 404 page if pipeline id route does not exist

app/event/model.js, app/event/serializer.js, app/pipeline/events/controller.js
Need to pass in `groupEventId` when restarting builds and events.
This PR adds new field `groupEventId` to event model and passes it in during event create.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1785
=> feat(1785): Pass in groupEventId when restarting build [5]

app/styles/screwdriver-modal-styles.scss
this changes make clear the original intent of the max-width property on modal dialogs: to not cover the screen from edge to edge, without being too small as it is today to the point of hiding important information.
With the current 320px it will not accommodate most of the content that is normally present on a dialog when there are parameters.
Before:
One of the parameters is called `bucket1` and another `bucket2` i have a retina display with the browser maximized, and still there's no space to know which one is which :(
After this small change the dialog looks like (on the widest possible display, it won't pass this, not even close to the max-width because of other existing constraints):
and on very small screens (i.e the minimum that would be usable with the old size, 400ish px)
PS: an …
=> fix: unreadable parameter names

app/pipeline/events/controller.js, tests/unit/pipeline/events/controller-test.js
- Reset jobs when toggle view button clicked
- Add test to cover when button clicked
=> fix: displaying duplicate jobs when toggle list view and workflow view buttons

app/components/pipeline-list-view/component.js
aggregate view is broken when there are jobs with 0 builds
Add check when computing coverage.
https://github.com/screwdriver-cd/screwdriver/issues/1967
=> fix(1967): aggregate view is broken when there are jobs with 0 builds

app/components/pipeline-list-view/component.js
Initially, we only load data if `list-view` option is selected. 
We run into issues within event route, if other sub-pages are selected, then use back button to go to list view. i.e. Go to `Events` & select `list-view`, click on `Opitons`, and then go back to `Events`.
This causes errors, since `list-view` is selected already.
Instead of asking users to toggle click list view again, or manually click `refresh` button to load data, we will load data on `init()` hook of the component to load data.
This PR will fix that to load event list on `init`, rather than upon clicking `list-view`
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf …
=> fix: loads events list on initial loads

app/components/create-pipeline/component.js, app/templates/detail/template.hbs
Keep the old behavior that if users only want to create a pipeline without  `screwdriver.yaml`. We will create a pipeline and close modal
Improvements:
- close create pipeline modal if users only create pipeline w/o yaml (keep pipeline creation of old behavior)
- open validator-job under `template`'s content for template details view
=> fix: ui onboarding more improvements

app/components/create-pipeline/component.js
Fix `await` is getting caught in catch errors
=> fix: sallow errors in catch when transitionTo is called

app/utils/git.js, tests/unit/utils/git-test.js
Making changes according to
https://github.com/screwdriver-cd/data-schema/pull/400/files#diff-77dea1a61b658aff6ad9cd0d2528d2daR83
Which allow `org-xxx@github.com:org/repo.git` to be valid, whereas `xxx` are digits. i.e. `org-111@github.com:org/repo.git`
Reference PR: https://github.com/screwdriver-cd/data-schema/pull/400
=> fix: allow org-xxx to be valid scmUrl

app/components/secret-view/styles.scss, app/components/secret-view/template.hbs
The button on Secrets UI is too simple that users do not notice that the button on right side of screen becomes `update`. 
Therefore, I modified `delete` and `update` button like below.
screwdriver-cd/screwdriver#1892
=> fix(1892): Fix secrets delete and update button

app/components/secret-view/component.js, app/components/secret-view/template.hbs, tests/integration/components/secret-view/component-test.js
Fix https://github.com/screwdriver-cd/screwdriver/issues/2117
Dialog appears when delete button is clicked.
https://github.com/screwdriver-cd/screwdriver/issues/2117
=> fix(2117): Add dialog for checking to delete secret

app/components/build-banner/component.js, app/components/pipeline-list-coverage-cell/component.js, app/components/pipeline-list-view/component.js, app/pipeline/build/template.hbs, app/shuttle/service.js, tests/unit/coverage/service-test.js, tests/unit/shuttle/service-test.js
Need to pass in pipelineId and prNum for new Sonar coverage calls.
This PR passes in pipelineId and prNum to get Sonar coverage info.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2152
=> fix(2152): Pass in pipelineId and prNum to Sonar coverage [2]

app/components/build-banner/component.js
Currently, it blocks if `event.pr.url` is undefined, it will break the `prNumber`.
This PR adds an empty string value to `prNumber`
=> fix: add default value to 'event.pr.url' for prNumber

app/components/pipeline-list-actions-cell/component.js, app/components/pipeline-list-actions-cell/styles.scss, app/components/pipeline-list-view/component.js, app/components/pipeline-list-view/template.hbs, app/pipeline/events/controller.js, app/pipeline/events/template.hbs, tests/integration/components/pipeline-list-view/component-test.js
Issues from https://github.com/screwdriver-cd/screwdriver/issues/2124
- [Using the `wait` helper in Ember integration tests](https://til.hashrocket.com/posts/851fb1e6f7-using-the-wait-helper-in-ember-integration-tests)
=> fix(2124):  Pipeline list view issues

app/components/build-banner/component.js, app/components/pipeline-list-coverage-cell/component.js, app/components/pipeline-list-view/component.js, app/job/model.js, app/pipeline/build/template.hbs, app/pipeline/events/controller.js, app/shuttle/service.js, tests/unit/coverage/service-test.js, tests/unit/job/model-test.js, tests/unit/pipeline/events/controller-test.js
Users might want to configure job scope for Sonar projects even if they're using enterprise edition.
This PR passes in extra params such as jobName, pipelineName, and job annotation for coverage scope.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2152
=> feat(2152): Support job annotation for coverage scope [5]

app/components/pipeline-parameterized-build/component.js, app/components/pipeline-parameterized-build/template.hbs, tests/integration/components/pipeline-parameterized-build/component-test.js
An alternative solution to https://github.com/screwdriver-cd/ui/pull/573
`Screwdriver.yaml` file: https://github.com/adong/sd-paramters-dropdown/blob/master/screwdriver.yaml
Try to squeeze much code in the handlebars using `power-select`, it is cool that `power-select` is able to handle it :) 
ember-power-select 2.x:
- [onkeydown](https://2-x.ember-power-select.com/docs/api-reference/)
ember-bootstrap:
- [Form Group](https://www.ember-bootstrap.com/api/classes/Components.FormGroup.html)
I also applied function currying to `Ember Action`, i.e.
```handlebars
onchange=(action (action "onUpdateDropdownValue" parameterizedModel parameter.name))
onkeydown=(action (action "searchOrAddtoList" parameterizedModel parameter.name))
```
and I learned from [A note on actions | …
=> fix: build parameters dropdown w/ override

app/components/build-banner/component.js, app/components/pipeline-list-coverage-cell/component.js, app/components/pipeline-list-view/component.js, app/job/model.js, app/pipeline/build/template.hbs, app/pipeline/events/controller.js, app/shuttle/service.js, tests/integration/components/build-banner/component-test.js, tests/unit/pipeline/events/controller-test.js
Would be nice if we could use existing projectKey data to get coverage info.
This PR passes projectKey to get coverage endpoint.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2152
=> fix(2152): Support passing projectKey to getCoverageInfo

ember-cli-build.js
We are now seeing errors like
when click on **Aggregate view** and set **enable/disable jobs**
This happens only during local `development` mode, and it does not happen in `production` environment.
This happened because we have introduced `ember-auto-import` from PR: https://github.com/screwdriver-cd/ui/pull/576
_I think `ember-cli-update --to 3.16.0` will auto add these newer dependencies to `package.json`_ 
Because we are running [ember-cli-content-security-policy](https://github.com/rwjblue/ember-cli-content-security-policy#ember-auto-import) and [ember-auto-import](https://github.com/ef4/ember-auto-import#i-use-content-security-policy-csp-and-it-breaks-ember-auto-import) at the same time during development mode.
`eval` mode set to be used for faster sourcemap generation.
> forbidEval: …
=> fix: set forbidEval to true for autoImport

app/components/pipeline-list-view/template.hbs
Issue: https://github.com/screwdriver-cd/screwdriver/issues/2181
This will fix the issue raised: https://github.com/screwdriver-cd/screwdriver/issues/2181
Please see my analysis in the comment section. 
Why `400px`? It's not a magic number. 
It's the `(row height) * (number of rows)` we are loading
`row height` is defined in https://github.com/screwdriver-cd/ui/blob/073db603beb4065123ea1fa6d1d8a32c60765ca1/app/components/pipeline-list-view/styles.scss#L49
`number of rows` is defined in https://github.com/screwdriver-cd/ui/blob/073db603beb4065123ea1fa6d1d8a32c60765ca1/app/pipeline/events/controller.js#L227
which is 
https://github.com/screwdriver-cd/ui/blob/073db603beb4065123ea1fa6d1d8a32c60765ca1/config/environment.js#L57
Thus, `40px` * `100` = `400px`.
This is not the best solution I'm …
=> fix(2181): fix not loading more items when scrolling

app/components/pipeline-create-form/component.js, app/components/pipeline-create-form/template.hbs
Add message Loading... while loading templates during create pipeline page
I think there are 2 ways of doing it:
1) Using [`noMatchesMessage`](https://2-x.ember-power-select.com/docs/api-reference)
```javascript
{{#power-select
options=templates
selected=selectedTemplate
onchange=(action "selectTemplate")
searchField="name"
searchEnabled=true
noMatchesMessage="Loading..."
as |template| }}
{{template.name}}
{{/power-select}}
```
2) using `{{else}}` block 
```
{{#power-select
options=templates
selected=selectedTemplate
onchange=(action "selectTemplate")
searchField="name"
searchEnabled=true
as |template| }}
{{template.name}}
{{else}}
<span>Loading...</span>
{{/power-select}}
````
Unfortunately, 2nd way is being deprecated. Ref: https://github.com/cibernox/ember-power-select/issues/1370 …
=> fix: add loading message when loading template in create pipeline form

app/components/pipeline-start/component.js
Issue: https://github.com/screwdriver-cd/screwdriver/issues/2175
Current implementation keeps using the old data rather than the newer user input.
This PR fixes the issue, and will use new user input instead.
=> fix(2175): fix parameters always use first input values

app/pipeline/job-latest-build/route.js, tests/unit/pipeline/job-latest-build/route-test.js
Issue: https://github.com/screwdriver-cd/screwdriver/issues/2184
Fix permalink issues
Option 1)
```
const pipelineInfo = transition.to.parent.parent.params;
const pipelineId = pipelineInfo.pipeline_id;
```
Option 2)
```
const pipelineId = this.paramsFor('pipeline').pipeline_id;
```
2) looks more elegant 
1) https://github.com/emberjs/ember.js/issues/18004
2) https://deprecations.emberjs.com/v3.x/#toc_remove-handler-infos
=> fix(2184): permalink for jobs is broken

app/components/create-pipeline/component.js, app/components/pipeline-create-form/template.hbs, app/components/quickstart-guide/template.hbs, app/utils/git.js, tests/unit/utils/git-test.js
Currently, default branch for Screwdriver pipeline is hardcoded to `master`. It would be nice if the default branch actually took in the Github `default_branch`.
This PR moves handling of default branch to the scm plugin.
Related to #2185 
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.
=> feat(2185): Handle default branch in scm plugin [3]

app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs
Currently, the dropdown selection is only shown at the start of the pipeline, this PR will implement and add dropdown selection to `Start pipeline from here`
After
=> fix: implement dropdown to 'pipeline start from here' on workflow graph

app/pipeline/events/show/route.js
We need to add the load-on-demand event to paginateEvents to load in to the view.
=> fix: add event to paginateEvents in order to scrollToView

app/components/pipeline-event-row/template.hbs, app/components/pipeline-options/component.js, app/components/pipeline-options/styles.scss, app/components/pipeline-options/template.hbs, app/components/pipeline-workflow/template.hbs, app/components/workflow-graph-d3/component.js, app/preference/pipeline/model.js
Currently, there's a bug when query local pipeline preferences, it will just fetch the first pipeline preference regardless of the query filter. Accidentally making pipeline specific settings across the app. (Will introduce a true global preference later 2020)
Also, the format issue is not consistent in Firefox, due to 
- Chrome will adjust input length when `<input>` type is number, and min & max is set, (in this case, min is `20` and max is `99`, making it 2 digits only), while firefox needs to set a width specifically. 
This PR fixes that.
1) fix: fetch local pipeline preferences
- change model `id` type from number to string, (ref: https://github.com/emberjs/data/issues/5279#issuecomment-358856561)
- add `filter` when `queryRecord`for `ember-local-storage`
```javascript
const records …
```
=> fix: jobNameLength is not specific to each pipeline

app/components/pipeline-event-row/component.js, app/components/pipeline-events-list/component.js, tests/integration/components/pipeline-events-list/component-test.js
Some user reports that click on PR-build, will trigger redirect to event page.
This is a regression issue, and this PR will fix that.
=> fix: prevent clicking on pr event will trigger redirect to event pages

screwdriver.yaml
We are seeing pod crash at `publish` step, i.e. https://cd.screwdriver.cd/pipelines/7/builds/496545/steps/build
We thought it was because some step has been halted, however, when we look inside k8s, we saw the pod is crashed, and we didn't know pod has crashed until timed-out in the UI.
Increase the memory usage, from default 2G to use `High` which is `12G`
```yaml
annotations:
screwdriver.cd/ram: HIGH
```
https://docs.screwdriver.cd/user-guide/configuration/annotations.html
=> fix: bump up memory/ram usage to HIGH

app/components/validator-results/component.js, app/components/validator-results/styles.scss, app/components/validator-results/template.hbs, tests/integration/components/validator-results/component-test.js
Add feature of https://github.com/screwdriver-cd/screwdriver/issues/2053
The API does not yet put any values into `warnAnnotations`. The screenshot below is a sample of how it will appear.
If the value of `warnAnnotations` is present, it is displayed as a warning in the validator.
https://github.com/screwdriver-cd/screwdriver/issues/2053
[1] https://github.com/screwdriver-cd/data-schema/pull/414
[2] https://github.com/screwdriver-cd/config-parser/pull/111
UI: https://github.com/screwdriver-cd/ui/pull/605 (this PR)
=> fix(2053): add display of warnAnnotations to validator

app/components/pipeline-nav/template.hbs, tests/integration/components/pipeline-nav/component-test.js
fix https://github.com/screwdriver-cd/screwdriver/issues/2235
This PR fixes to show pipeline description correctly even if it was a single line strings.
https://github.com/screwdriver-cd/screwdriver/issues/2235
=> fix(2235): Broken pipeline description

app/components/pipeline-parameterized-build/component.js, app/components/pipeline-parameterized-build/template.hbs, app/components/pipeline-workflow/component.js, tests/integration/components/pipeline-parameterized-build/component-test.js
Show description of parameter on the UI.
Description is shown by moving cursor on icon.
Add an icon to head of the parameter name. If parameter description is defined, parameter description is shown on UI.
screwdriver-cd/screwdriver#2210
=> feat(2210): Show parameter description

app/components/app-header/component.js, app/components/app-header/styles.scss, app/components/app-header/template.hbs, config/environment.js
Add canary badge in header to identify release
This PR adds a badge in the header controlled via env vars to view the release
=> feat: add a badge to display canary release

app/components/pipeline-start/template.hbs
Currently, for a large number of parameters, users have to view parameters dropdown and click `submit` to trigger the pipeline. 
This PR will relax and allow users to click on start button to kick-off build directly
=> fix: add startBuild to allow users to start build without viewing parameters

app/event/serializer.js, app/pipeline/serializer.js, package-lock.json, package.json, tests/unit/pipeline/serializer-test.js
The workflow graph flickers every few seconds.  This is due to different sorting of the nodes/edges every time we fetch it from the server.
=> fix: workflow graphs "flicker" every few seconds.

app/event/serializer.js
Workflow nodes order on the first column should be the same order they appear in the `screwdriver.yaml` file.
=> fix: fix workflow nodes sorting

app/components/pipeline-list-coverage-cell/component.js
Each time when we change the jobs table sorting, the latest build coverage is fetched from the back-end.
The solution is to simply cache the coverage response for each build on the first time we fetch it.  Then, if the table sorting changes, we can use the cached data.
=> fix: remove redundant build coverage requests when changing jobs table sorting

app/components/app-header/template.hbs
- The slack link goes to not a channel but a workspace.
- GitHub is officially "GitHub", not Github.
Signed-off-by: JJ Asghar <jjasghar@gmail.com>
Co-authored-by: Adam Roberts <aroberts@uk.ibm.com>
=> Fixed Slack and GitHub typos

README.md
currently license badge is broken
fix it
=> fix: fix license badge

app/pipeline/secrets/route.js
```
screwdriver-ui-ae9292dd71fc30bc654e2b8eedc538d4.js:528 Uncaught TypeError: Cannot read property 'annotations' of undefined
at n.get (screwdriver-ui-ae9292dd71fc30bc654e2b8eedc538d4.js:528)
at vendor-66ca79816001aded6a088aa0677266d2.js:1868
at te (vendor-66ca79816001aded6a088aa0677266d2.js:1785)
at i.o.get (vendor-66ca79816001aded6a088aa0677266d2.js:1868)
at n.get [as pipelineDescription] (vendor-66ca79816001aded6a088aa0677266d2.js:1766)
at Oe (vendor-66ca79816001aded6a088aa0677266d2.js:1843)
at vendor-66ca79816001aded6a088aa0677266d2.js:1105
at Z (vendor-66ca79816001aded6a088aa0677266d2.js:1783)
at n.r.compute (vendor-66ca79816001aded6a088aa0677266d2.js:1105)
at n.value (vendor-66ca79816001aded6a088aa0677266d2.js:1099)
```
fix this regression
I confirm that this contribution is made …
=> fix: fix secret tab regression

app/components/collection-table-row/component.js, app/components/collection-table-row/template.hbs, app/components/collection-view/component.js, app/components/pipeline-card/component.js, app/components/pipeline-card/styles.scss, app/components/pipeline-card/template.hbs, app/dashboard/show/controller.js, app/dashboard/show/route.js, app/dashboard/show/template.hbs, app/utils/metric.js, tests/integration/components/collection-table-row/component-test.js, tests/integration/components/collection-view/component-test.js, tests/integration/components/pipeline-card/component-test.js
Collection page does not render until metrics for all pipeline are loaded.
Move metric query to each individual pipeline card/row component so collection page render without waiting for metrics 
https://github.com/screwdriver-cd/screwdriver/issues/2267
=> feat(2267): refactor collection page and apply lazy loading

app/components/pipeline-pr-list/template.hbs, app/components/pipeline-pr-view/component.js, app/pipeline/events/template.hbs, tests/integration/components/pipeline-pr-list/component-test.js, tests/integration/components/pipeline-pr-view/component-test.js
https://github.com/screwdriver-cd/screwdriver/issues/2273
This PR fixes about comment below.
> PR job names are not updated
Job name of PR build is overwritten by screwdriver.cd/displayName annotation.
https://github.com/screwdriver-cd/screwdriver/issues/2273
=> fix(2273): Job name on PR is updated with screwdriver.cd/displayName

app/pipeline/metrics/controller.js
This catches one edges that case prevents metricsDowntimeJobs to be undefined.
=> fix: catch edge case of undefined for pipeline.settings.metricsDowntimeJobs

app/components/pipeline-pr-view/component.js
matchNode could be null and would break ui upon refresh or clicking back button
Add null check on matchNode
https://github.com/screwdriver-cd/screwdriver/issues/2273
=> fix(2273): matchNode could be null

app/components/pipeline-list-view/component.js, app/components/pipeline-list-view/styles.scss, app/components/pipeline-list-view/template.hbs, config/environment.js
Try to improve the loading experience on job lis view/`pipeline-list-view`
- add loading indicator when fetching data for more rows
- adjust default loading size `LIST_VIEW_PAGE_SIZE ` from 10 to 20
- change `height="400px"`  to `height="60vh"` [css unit](https://www.w3schools.com/cssref/css_units.asp)
Add and pass [`scrollBuffer=700`](https://github.com/adopted-ember-addons/ember-light-table/blob/078a2617b8ba08c55d9320bdf01ea2b4447736e9/addon/templates/components/lt-body.hbs#L82) to ELT `t.body` to see if it can trigger early `scrollToBottom`
Ember Light Table `scrollBuffer`: [b93f0671 ](https://github.com/adopted-ember-addons/ember-light-table/commit/b93f0671ad635bf4024aaab1f7773db52df45cc7#diff-ab978ed79068759c70dd2fabbda2b02375a05478e690c38f03004d2d8bf7cb36)fix(occlusion): pass …
=> fix(2124): fix the scroll to take 80% and load 50 jobs if applicable

app/components/pipeline-list-coverage-cell/component.js, app/components/pipeline-list-coverage-cell/template.hbs, app/pipeline/metrics/controller.js, tests/integration/components/pipeline-list-coverage-cell/component-test.js
Current implementation of getting coverages will trigger a second API call, with this PR, we will load on-demand and will only load coverages when in viewport.
Sample coverage pipeline: https://cd.screwdriver.cd/pipelines/67/jobs
=> fix: lazy load coverage when row/cell is in view-port

app/components/pipeline-event-row/template.hbs, app/components/pipeline-events-list/component.js, app/components/pipeline-events-list/template.hbs, app/pipeline/events/template.hbs, app/shuttle/service.js, app/styles/column-view.scss, tests/acceptance/create-page-test.js, tests/acceptance/pipeline-builds-test.js, tests/acceptance/pipeline-childPipelines-test.js, tests/acceptance/pipeline-pr-chain-test.js, tests/integration/components/pipeline-event-row/component-test.js, tests/integration/components/pipeline-events-list/component-test.js, tests/unit/shuttle/service-test.js
Highlight the latest commit in the events tab.
Changed the _sha_ of latest commit event to blue background color.
The last successful build will be tagged with a green background color.
https://github.com/screwdriver-cd/screwdriver/issues/2168
=> fix(2168): Highlight the latest commit in the events tab

app/pipeline/jobs/index/controller.js, app/pipeline/jobs/index/route.js, config/environment.js
Since https://github.com/screwdriver-cd/ui/pull/651, we can increase the number of jobs displayed in the first load of the job-list-view, without triggering coverages that are not in the viewport.
It's a trade off between loading/pre-loading a number of jobs in the job-list-view, or let users scroll multiple times to the desired number of jobs. So, this PR increases from 20 to 200.
=> fix: increase limit from 10 to 200 to load in job list view

app/components/pipeline-events-list/component.js, app/components/pipeline-events-list/template.hbs, app/components/pipeline-events-row-group/component.js, app/components/pipeline-events-row-group/styles.scss, app/components/pipeline-events-row-group/template.hbs, app/pipeline/events/controller.js, app/pipeline/events/show/route.js, app/pipeline/events/template.hbs, package-lock.json, package.json, tests/integration/components/build-banner/component-test.js, tests/integration/components/pipeline-events-list/component-test.js, tests/mock/events.js, tests/mock/jobs.js, tests/unit/pr-events/service-test.js
We want to be able to group jobs with the same commit id in order to reduce the clutter.
Group all jobs with the same commit id.  Allow this group to expand and collapse.
https://github.com/screwdriver-cd/screwdriver/issues/1820
=> feat(1820): Group events together

app/components/collection-table-row/component.js, app/components/collection-table-row/template.hbs, app/components/collection-view/component.js, app/components/collection-view/template.hbs, app/components/collections-flyout/template.hbs, app/components/pipeline-card/component.js, app/components/pipeline-card/template.hbs, app/components/pipeline-options/template.hbs, package-lock.json, tests/integration/components/collections-flyout/component-test.js, tests/integration/components/pipeline-options/component-test.js
Would be nice to have clearer operations when interacting with Collections. It can be confusing when options to delete or remove appear and the user does not have permissions.
This PR:
- adds titles to icons in collections pages such as trash icons, add pipeline, settings, copy link, etc
- adds notification when pipeline is successfully removed
- changes wording to "~Remove~Delete pipeline"
- only shows options to delete or add when type is "normal"; type would be "shared" for viewing other people's collections and "default" when viewing default collection (https://github.com/screwdriver-cd/screwdriver/issues/2315)
Related to https://github.com/screwdriver-cd/screwdriver/issues/2315 …
=> fix(2315): Make collections delete and add operations more clear

app/components/pipeline-events-row-group/component.js, app/pipeline/events/template.hbs
[Scroll event](https://developer.mozilla.org/en-US/docs/Web/API/Document/scroll_event) is not triggered when events are grouped together and collapsed
https://github.com/screwdriver-cd/ui/blob/388d37e33dcbaa28da8dcc9e755c92a9cc9f253a/app/pipeline/events/template.hbs#L47
https://github.com/screwdriver-cd/ui/blob/388d37e33dcbaa28da8dcc9e755c92a9cc9f253a/app/pipeline/events/controller.js#L434-L437
Example:  https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onscroll 
If you change the height to 300px, you will see no scroll events will be triggered
To accommodate this, I'm adding a bottom element to trigger when the mouse is entered, see screenshot
More Handling Events - Components - Ember Guides https://guides.emberjs.com/v2.0.0/components/handling-events/
I confirm that this …
=> fix: not triggering scrolling event when events are collapsed

app/components/validator-job/template.hbs
Would be nice if users could see inherited template name on template details page.
This PR shows inherited template on template page.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2319
=> feat(2319): [4] Show inherited template on template page

app/components/validator-job/component.js, app/components/validator-job/template.hbs, tests/integration/components/validator-job/component-test.js
When the template has namespace "default", the link generated does not work.
This PR gets the correct link for templates with default namespace.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2319
=> fix(2319): Link to template with default namespace

app/components/workflow-tooltip/template.hbs, tests/integration/components/workflow-tooltip/component-test.js
Sometimes words can be confusing to our users, we are adding `Restart` if the build had run before, `Start` otherwise, see issue https://github.com/screwdriver-cd/screwdriver/issues/2327 for more context.
Before:
After:
If a job's status is undefined, then we will show it as `Start`, otherwise, will show it as `Restart`.
Issue: https://github.com/screwdriver-cd/screwdriver/issues/2327
=> fix(2327): Restart dialog in workflow graph is confusing

app/mixins/model-reloader.js, app/pipeline/events/route.js, app/pipeline/jobs/index/route.js, app/utils/error-messages.js
Every once in a while, users are offline from the internet or disconnected from VPN. Our users should be notified if they are offline, rather than being redirected to 404 page.
This PR adds the warning only if it was an internet issue, and show screenshot like following:
https://github.com/screwdriver-cd/screwdriver/issues/2325
=> fix: only reload model if has internet access

app/components/pipeline-events-row-group/template.hbs
In the [PR for showing group events together](https://github.com/screwdriver-cd/ui/pull/658), latestCommit was forgot to be passed to `pipeline-event-row`. Therefore, the latest commit is not highlighted in current UI.
Pass latestCommit to `pipeline-event-row`.
issue: screwdriver-cd/screwdriver#2342
PR for implementing highlight latestCommit: https://github.com/screwdriver-cd/ui/pull/654
PR for implementing show group events together: https://github.com/screwdriver-cd/ui/pull/658
=> fix(2342): Highlight the latest commit in group events

app/components/pipeline-options/template.hbs, app/helpers/starts-with.js, tests/integration/components/pipeline-options/component-test.js, tests/integration/helpers/starts-with-test.js
It seems we overlooked the use case of disabling PR jobs, which does not make much sense.
Before
After:
=> fix: hide options to disable PR jobs

app/components/workflow-tooltip/styles.scss, app/components/workflow-tooltip/template.hbs, app/utils/graph-tools.js, tests/integration/components/workflow-tooltip/component-test.js, tests/unit/utils/graph-tools-test.js
Some users want to disable "Start pipeline from here button" for safety.
Hides the START link on the pipeline by setting the annotation. For the annotation name, I chose what I thought was the best idea. https://github.com/screwdriver-cd/screwdriver/issues/1901#issuecomment-736059949
```
jobs:
main:
requires: []
annotations:
screwdriver.cd/manualStartEnabled: false
```
Note: The display of the text was slightly broken, so it has been fixed.  
Before:
https://github.com/screwdriver-cd/screwdriver/issues/1901
=> [1]fix(1901): support screwdriver.cd/manualStartEnabled annotation

app/components/validator-job/component.js, app/components/validator-job/template.hbs
Would be nice to see locked steps in UI.
This PR adds locked symbol next to locked steps in the validator/template pages.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2331
=> feat(2331): Support locked steps [4]

app/components/pipeline-event-row/template.hbs, app/components/pipeline-events-list/template.hbs, app/components/pipeline-events-row-group/template.hbs, app/components/pipeline-list-view/template.hbs, app/components/pipeline-parameterized-build/component.js, app/components/pipeline-parameterized-build/styles.scss, app/components/pipeline-parameterized-build/template.hbs, app/components/pipeline-start/template.hbs, app/components/pipeline-workflow/template.hbs, app/helpers/array-includes.js, tests/integration/components/pipeline-parameterized-build/component-test.js, tests/unit/helpers/array-includes-test.js
Now we just need to test it.
When using parameter builds, it will show a warning if users fill values that differ from the default values defined in `screwdriver.yaml`.
When you change the value of the form from the default one defined in `screwdriver.yaml`, an icon will be displayed and the background color will change.
The `screwdriver.yaml` used in the image above is the following.
```
parameters:
nameA: "value1"
nameB:
value: "value2"
description: "description of nameB"
nameC: ["value3", "value4"]
jobs:
main:
image: node:12
steps:
- ls
```
The list view and parameter list display screens have been modified as well.
https://github.com/screwdriver-cd/screwdriver/issues/2302 …
=> fix(2302): Show warning when build parameters are different from default values

app/commands/detail/controller.js, app/templates/detail/controller.js, tests/unit/commands/detail/controller-test.js, tests/unit/templates/detail/controller-test.js
ui should only render template/command as trusted only if latest template/command was trusted
ui should only render template/command as trusted only if latest template/command was trusted
https://github.com/screwdriver-cd/screwdriver/issues/2350
=> fix(2350): template/command trusted logic fix

app/pipeline/events/controller.js
To fix duplicate issues when the URL is anchored to a specific event and the user scrolls down to fetch more events.
`https://cd.screwdriver.cd/pipelines/6862/events/618770`
Before:
After:
=> fix: remove duplicate events by eventId

app/components/quickstart-guide/styles.scss
- Pointer for Cursor is not shown while hovering on close icon in QuickStart Guide wizard
- Will show the pointer while hovering on close icon
**ScreenShots:**
Before:
- 
- After:
https://github.com/screwdriver-cd/screwdriver/issues/2389
=> fix: Add Pointer icon while hovering on close button in quickStart guide modal

app/components/collection-view/component.js
- After completing remove/copy to action in collection view the selection pipeline is not being reset which is cause wrong selection count and displaying actions even though nothing is selected.
This PR reset the selectionPipeline array once the copy/remove actions are completed successfully.
https://github.com/screwdriver-cd/screwdriver/issues/2396
=> fix(2396):Resets selectedPipelines array after completing pipeline actions

app/components/pipeline-list/styles.scss, app/components/pipeline-list/template.hbs, app/components/search-list/template.hbs, tests/acceptance/pipeline-childPipelines-test.js, tests/integration/components/pipeline-list/component-test.js
Would be nice if branch/rootDir is shown in child pipelines drop down.
This PR displays branch/rootDir for child pipelines. Also makes branch/rootDir clickable link in child pipelines and search list pages.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2398
=> fix(2398): Display branch for child pipelines

app/components/pipeline-options/component.js, app/pipeline/events/controller.js, app/pipeline/events/route.js, app/pipeline/pulls/route.js
We treat undefined as false value for `showPRJobs`, thus the default of workflow graph now hide `~pr` jobs
This PR fixes just that
=> fix: handle remote case for undefined value for showPRJobs

app/components/pipeline-parameterized-build/styles.scss
Request for tone down.
https://github.com/screwdriver-cd/screwdriver/issues/2302#issuecomment-815325473
See https://github.com/screwdriver-cd/ui/pull/673 for the UI before the fix
Toned down the warning display when the input parameters are different from the default values.
https://github.com/screwdriver-cd/ui/pull/673
=> fix(2302): Tone down the warning

nginx.conf
When using `set_lua` to do string concatenation, it breaks on 'null' values.
Add default values for nginx.conf
=> fix: add default value

app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs, app/components/workflow-tooltip/template.hbs, tests/integration/components/workflow-tooltip/component-test.js
fix https://github.com/screwdriver-cd/screwdriver/issues/2038
This PR fixes tooltips not to show `start pipeline from here` for prChain jobs that cannot started from tooltip.
PRChain Job:
commit Job:
=> fix(2038): hide restart button of PrChain

app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs, app/components/workflow-tooltip/template.hbs, tests/integration/components/workflow-tooltip/component-test.js
Additional fix https://github.com/screwdriver-cd/screwdriver/issues/2038
In https://github.com/screwdriver-cd/ui/pull/701 we hides all restart link of prChain.
This PR is to show restart button it has build.
If selected job has build in PRChain, it can be restarted.
Detached build never restarted because it has no build in PRChain
=> fix(2038): show restart button in prchain job if it has build

screwdriver.yaml
Often `publish` fails due to timeout, so bump up ram to turbo for `publish` job
Bump up ram
=> fix: bump up ram to turbo for publish job

app/components/pipeline-options/component.js, app/components/pipeline-options/styles.scss, app/components/pipeline-workflow/component.js, app/components/workflow-graph-d3/component.js, app/pipeline/events/route.js, app/preference/pipeline/model.js, app/shuttle/service.js, app/utils/error-messages.js, tests/integration/components/pipeline-options/component-test.js
Refactor user/settings to support storing job name length to the API (which already supported)
https://github.com/screwdriver-cd/data-schema/blob/83024712039a2243e88a58f2e6caa5c0aaa6c0de/config/settings.js#L32-L35
This PR enables users to store job name length to the backend
Update label width: 
[peekAll returns DS.RecordArray](https://api.emberjs.com/ember-data/3.3/classes/DS.Store/methods/peekAll?anchor=peekAll)
=> fix: refactor user/settings

app/event/model.js
event with `CREATED` build shouldn't be marked as in `running` state
before:
after:
exclude `CREATED` build from event status calculation
=> fix: exclude CREATED build from event status

app/utils/git.js
Invalid git repo name marked as valid. "Create pipeline" page shows green check-mark for invalid git repo urls.
Fix validation of git repo urls
https://github.com/screwdriver-cd/screwdriver/issues/2448
=> fix(2448): git repo url validation

app/components/pipeline-options/component.js, app/components/pipeline-options/template.hbs, app/shuttle/service.js, config/environment.js
Add guard to make sure input value are in range (20 - 99)
Now, the UI will not block users from the normal workflow, even if the data was legacy (out of range previously).
=> fix: set max length for display name length

app/pipeline/events/controller.js
If a pipeline has parameters, then when restart a build from job-list-view will fail.
i.e https://cd.screwdriver.cd/pipelines/3303/jobs
See screenshot:
This PR will correct the behavior: it fetches builds from a given jobId, and find the latest build's eventId, and get corresponding data from that event, such as parentEvent.
=> fix: restart latest build when pipeline has parameters dropdown

app/build-logs/service.js, tests/unit/build-logs/service-test.js
should catch 403/404 error in log fetch logic to prevent endless api calls
add appropriate error catch
https://github.com/screwdriver-cd/screwdriver/issues/466
=> fix(466): add error catch to log fetch

app/components/pipeline-events-list/component.js, app/components/pipeline-graph-nav/styles.scss, app/components/pipeline-graph-nav/template.hbs, app/pipeline/events/controller.js, app/pipeline/events/template.hbs, tests/integration/components/pipeline-graph-nav/component-test.js
If user select the latestCommit event, mark the SHA of `pipeline-graph-nav` to indicate that it is the latestCommit event.
In the event list, the latestCommit is shown with a blue background, and the pipeline-graph-nav will show the same mark.
The `.status` class in CSS resets each parameter because we don't want [them](https://github.com/screwdriver-cd/ui/blob/457f2c1cf18b8a870cf7f380d6366eaaadb2bbbd/app/styles/column-view.scss#L44-L48) to be used.
https://github.com/screwdriver-cd/ui/pull/717/files#diff-c77f1fdf1df50bb4b96a45c80dcd5838d188057a59650a0a25dd187762215425R16-R21
https://github.com/screwdriver-cd/screwdriver/issues/2168
https://github.com/screwdriver-cd/ui/pull/654 …
=> fix: Add the latestCommit marker to pipeline-graph-nav

app/components/pipeline-graph-nav/styles.scss, app/styles/app.scss, app/styles/column-view.scss
Patch for https://github.com/screwdriver-cd/ui/pull/717#issuecomment-856994721
In a previous fix, there was an unwanted blue hover in the pipeline header.
It has been fixed as follows.
=> Remove blue hover from pipeline header

app/components/build-banner/template.hbs, tests/integration/components/build-banner/component-test.js
If users click on the pipeline title link in the pr build details page, users will be get the events tab page, which should be the pr tab page.
https://cd.screwdriver.cd/pipelines/2539/builds/107009
For pr builds, fix the link destination of the pipeline title to `/pipelines/${pipelineId}/pulls`.
I'd like to make it a permalink for a specific pr event, but since there is currently no permalink that selects a specific PR event, I've implemented just link to the pr tab page for now.
https://github.com/screwdriver-cd/screwdriver/issues/1584
=> fix(1584): pipeline title on a pr build page should link pr tab

app/components/collection-table-row/component.js, app/components/collection-view/component.js, app/components/collection-view/template.hbs, app/components/pipeline-card/component.js, tests/integration/components/collection-view/component-test.js
Should not show option to remove pipelines from Default collection.
This PR adds logic to check if collection type is default or not and determine if it should show option to remove pipelines.
Now:
Related to https://github.com/screwdriver-cd/screwdriver/issues/2458
=> fix(2458): Do not show option to remove pipelines from Default Collection

app/components/collection-modal/component.js, app/components/command-header/template.hbs, app/components/template-header/template.hbs, app/components/user-link/component.js
Would be nice if users could go directly to the pipeline page that publishes a particular command or template.
This PR adds a link to the pipeline page from the command/template detail page.
Before:
After:
Related to https://github.com/screwdriver-cd/screwdriver/issues/2473
=> feat(2473): Add link to pipeline from template and command detail pages

app/components/login-button/template.hbs, app/scm/model.js, app/scm/service.js, tests/helpers/inject-scm.js, tests/integration/components/login-button/component-test.js
Should not give option to login to read-only SCM.
This PR:
- takes in readOnly flag and skips showing login option to read-only SCM
Related to https://github.com/screwdriver-cd/screwdriver/issues/2437
=> feat(2437): Support read-only SCM [7]

app/components/pipeline-list/template.hbs, app/pipeline/child-pipelines/controller.js, app/pipeline/child-pipelines/template.hbs
It would be nice if we show the SCM icon in the child pipelines list page.
This PR adds SCM icon to child pipelines list page.
Before:
After:
Related to https://github.com/screwdriver-cd/screwdriver/issues/2437
=> fix(2437): Show scm icon in child pipelines list

app/pipeline/child-pipelines/template.hbs
Start all for child pipelines is broken.
This PR fixes start all issue.
Revert bug introduced here: https://github.com/screwdriver-cd/ui/pull/726/files#diff-dbbb3f911563899c5256112ad1356a64e66126d69c689a04370bdb5252e26087L5
Related to https://github.com/screwdriver-cd/screwdriver/issues/2437
=> fix(2437): Pass pipeline info for startAll

app/components/app-header/template.hbs
We should not show option to login to read-only accounts from dropdown.
This PR removes read-only SCM from accounts dropdown.
Before:
After:
Related to https://github.com/screwdriver-cd/screwdriver/issues/2437
=> fix(2437): Do not show read-only account for login dropdown

app/pipeline/events/controller.js
PR https://github.com/screwdriver-cd/ui/pull/716 fixed restart jobs from job list view, but introduced a new bug from starting detached jobs in workflow-graph view.
This PR fix start detached jobs from workflow-graph view
Fixes https://github.com/screwdriver-cd/screwdriver/issues/2489
https://github.com/screwdriver-cd/ui/commit/186b2cf44ef22e68eef660d7985c47b2076b0680
=> fix: start detached job from workflowGraph

app/components/pipeline-workflow/template.hbs, app/pipeline/events/template.hbs, tests/integration/components/pipeline-workflow/component-test.js
Solve the issue https://github.com/screwdriver-cd/screwdriver/issues/2451
Fixed SHA displayed on restart to be highlighted in blue to make it easier to see that it is the latest commit
When latest commit:
When NOT latest commit:
https://github.com/screwdriver-cd/screwdriver/issues/2451
=> feat(#2451): Add latest-commit class on pipeline modal sha

app/build/model.js, app/components/pipeline-pr-list/template.hbs, app/components/pipeline-pr-view/template.hbs, app/job/model.js, tests/integration/components/pipeline-pr-view/component-test.js
Exact “Start Date” is not available on PR View page, only English approximation, so can’t easily compare against other events
Show Exact Date Time in MM/DD/YYYY hh:mm AM/PM format for Start Date on Pr list View
This PR is a part of following:
https://github.com/screwdriver-cd/ui/pull/731
=> fix: Add exact start date in pr view

app/commands/route.js, app/templates/route.js
[willTransition](https://github.com/sonic-screwdriver-cd/ui/blob/723a7e8e89e40e8f36d69e24a1babf49a0fa3944/app/templates/route.js#L10) always throws an error because the value of `transition.params` is undefined. So template/command breadcrumbs do not work as expected.
This PR fixes `willTransition`. We set `transition.to.params` as `newParams` which has the information of the destination url. As a result, The breadcrumbs work correctly when we click the button pointed to in the image below. 
However, if we specify the namespace from the following button, the breadcrumb will not appear.
https://github.com/screwdriver-cd/screwdriver/issues/2360
https://api.emberjs.com/ember/3.27/classes/Transition/properties/to?anchor=to
I confirm that this contribution is made under the terms of the …
=> fix(2360): fix template/command breadcrumbs

app/pipeline/events/show/route.js, tests/mock/events.js
When users access `/pipelines/PIPELINE_ID_A/events/EVENT_ID_B` and `EVENT_ID_B` is not `PIPELINE_ID_A`'s event, UI should redirect to a generic endpoint for `PIPELINE_ID_A`.
Verifies in beforeModel phase whether event's pipelineId matches param pipelineId or not.
When id does not match, UI redirect to a generic endpoint for param pipelineId.
screwdriver-cd/screwdriver#2459
=> fix(2459): Redirect if event pipelineId not match route pipelineId

app/components/pipeline-graph-nav/component.js, app/components/pipeline-graph-nav/template.hbs
No Start button after creating a new pipeline.
Show the Pipeline Nav panel when event tab is open.
Issue: https://github.com/screwdriver-cd/screwdriver/issues/2516
=> Fix: Start button not showing for New Pipeline

app/components/pipeline-graph-nav/template.hbs, tests/integration/components/pipeline-graph-nav/component-test.js
When a chainPR event is selected, the graph navigation area shows 
1. A toggle button for Show/Hide Trigger 
2. A toggle button to see events in grid/list view when 
Which are not useful for chainPR events. 
Also, Start Button in top left of graph navigation is hidden when a selected event is running. Start button should always be shown to create new events irrespective of the current running event.
1. Hide Toggle buttons on Graph nav header when chainPR event is selected.
2. Always show Start button for new events 
A part of this PR:
https://github.com/screwdriver-cd/ui/pull/742
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of …
=> fix: UI improvements - remove graph navigation toggle for chainPR

app/components/pipeline-create-form/styles.scss, app/components/pipeline-create-form/template.hbs
The tooltip message on the pipeline creation screen may be partly too dark to be seen.
This PR makes the text color of the tooltip link a little brighter.
before:
after:
=> fix: Tooltip's message color of create page

app/pipeline/events/controller.js
For PR tabs, we only display jobs with exact name `~pr` as starting points, rather than `~pr:main`, `~pr:dev` that allowed to be used in screwdriver.yaml with [branch filtering](https://docs.screwdriver.cd/user-guide/configuration/workflow.html#branch-filtering)
This PR enables job names starts with `~pr:` to be displayed
=> fix: UI display for repo uses branch filters

app/components/pipeline-viz-chart/style.scss, app/components/workflow-graph-d3/styles.scss
Modify SCSS so that workflow tooltips can be easily removed.
Previously it could be deleted by clicking on the yellow area.
This fix expands the area where tooltips can be removed.
https://github.com/screwdriver-cd/screwdriver/issues/2065
=> fix(2065): fix workflow tooltip to make it easier to remove

app/components/pipeline-workflow/component.js
Changes made in https://github.com/screwdriver-cd/ui/pull/754 broke the tooltip on workflow graph nodes
This PR delivers the fix to display tooltips on workflow graph nodes for pipelines without parameters
https://github.com/screwdriver-cd/ui/pull/754
https://github.com/screwdriver-cd/ui/pull/758
=> fix: Tooltip broken in the workflow graph for pipelines with out parameters

app/components/pipeline-events-list/component.js, app/components/pipeline-events-list/template.hbs, app/components/pipeline-options/component.js, app/components/pipeline-options/template.hbs, app/pipeline/events/show/route.js, app/pipeline/model.js, app/shuttle/service.js
Provide an option for user to set event display at pipeline level, whether is _grouped events_ or not
- https://github.com/screwdriver-cd/screwdriver/issues/2605
- https://github.com/screwdriver-cd/ui/pull/658/files
=> feat(2605) Option to display all screwdriver jobs in a chronological order

app/build-logs/service.js, tests/unit/build-logs/service-test.js
ui calls api repeatedly on status code 500
catch status code 500 when fetching log
=> fix: should catch server error when fetching build log

app/components/pipeline-event-row/template.hbs, tests/integration/components/pipeline-event-row/component-test.js
When the event status becomes UNKNOWN for some reason, for example, if there is no build at the trigger destination, a stop button is placed for the target event.
The Stop button is confusing to the user because no build is actually running.
Hides the STOP button for events in the UNKNOWN state.
Before:
After:
=> fix: Hide stop button for unknown event

app/components/pipeline-workflow/component.js
A build cannot be restarted from an event when one or more parameters from that event has been removed in the latest screwdriver configuration.
The logic which merges event parameters on top of default parameters for the new build, assumes definition for all the parameters of the event still exists in the latest screwdriver config. This results in Javascript error which prevent users from restarting the builds.
While merging the parameters include all the parameters from the event even if those parameters have been removed in the latest screwdriver config.
https://github.com/screwdriver-cd/screwdriver/issues/2644
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to …
=> fix(2644): Include stale parameters from the event when a build is restarted after the parameter(s) removed in SD config

app/components/pipeline-options/component.js, app/components/pipeline-options/template.hbs, app/pipeline/events/controller.js, app/pipeline/events/route.js, app/shuttle/service.js, tests/integration/components/pipeline-options/component-test.js
Add a setting to the pipeline preference to hide many empty events, such as skip ci, or events that have no jobs to start from the event list. (the latest events are not hidden)
Also, fixed a bug that the setting is not reflected immediately when changing the setting of Show Triggers of pipeline preference.
data-schema PR is [here](https://github.com/screwdriver-cd/data-schema/pull/482).
Added "Filter events for no builds" to pipeline preference:
filterEventsForNoBuilds OFF:
filterEventsForNoBuilds ON:
- https://github.com/screwdriver-cd/screwdriver/issues/1577
- adding a toggle switch on a pipeline or an option page to filter empty events.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have …
=> feat(1577): feat filter events for no builds [2]

app/pipeline/events/controller.js, app/pipeline/events/template.hbs, tests/unit/pipeline/events/controller-test.js
Periodic jobs will not run due to invalid credentials. It is caused by users either have not login for X days or being deactivated. Resulting git users are out of sync, this feature prompts users on the UI to click **sync** with the latest git repo admins.
One can manually produce the scenario by running the following SQL queries
```
// check admins field
SELECT name, id, admins from pipelines where id=1234;
// manually set the admins to be empty
UPDATE pipelines SET admins='{}' WHERE id=1234;
// test the feature and run the sql to check admins field being updated
SELECT name, id, admins from pipelines where id=1234;
```
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority …
=> feat: prompt users with no-admin info, and allow users to sync

app/components/validator-job/template.hbs, app/helpers/is-object.js
`provider` can either be a string or an object. Validator should handle for both cases.
String case:
```
jobs:
main:
image: node:12
steps:
- echo: echo step
provider: git@github.com:tkyi/mytest.git#master:provider.yaml
```
Object case:
```
jobs:
main:
image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
provider:
name: aws
region: us-west-2
accountId: 123456789012
vpc:
vpcId: vpc-0123abc
securityGroupIds:
- sg-0123abc
subnetIds:
- subnet-0123abc
- subnet-0123def
- subnet-0123ghi
role: arn:aws:iam::123456789012:role/screwdriver-integration-role
executor: sls
launcherImage: screwdrivercd/launcher:v6.0.149
launcherVersion: v6.0.149
steps:
- init: npm install
- test: npm test
```
- https://docs.screwdriver.cd/cluster-management/aws-integration#job-provider-configurati …
=> fix: add string case for provider for validator

app/components/pipeline-create-form/component.js, app/components/pipeline-create-form/template.hbs, tests/acceptance/create-page-test.js, tests/integration/components/create-pipeline/component-test.js
The expansion of the checkboxes on the create pipeline page is not consistent.
Modify the behavior of the pipeline creation page so that when a checkbox is checked, the form to automatically generate the screwdriver.yaml is displayed.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2573
=> fix(2573): Unify checkbox expansion behavior on pipeline creation page

app/components/pipeline-graph-nav/template.hbs, app/event/model.js, tests/integration/components/pipeline-graph-nav/component-test.js, tests/mock/events.js
User cannot know which branch is used when start detached job from a specific branch event.
This PR adds a base branch name column to the pipeline graph navigation as the following.
- Issue comment
- https://github.com/screwdriver-cd/screwdriver/issues/2465#issuecomment-896544388
=> feat(2465): Show base branch name on pipeline graph nav

app/components/quickstart-guide/template.hbs
It can be misleading/confusing to use a power off icon for quickstart information during pipeline creation.
This PR switches from power icon to info icon.
Before:
After:
Related to https://github.com/screwdriver-cd/screwdriver/issues/2552
=> fix(2552): Switch from power icon to info icon

app/components/pipeline-workflow/template.hbs, app/components/workflow-tooltip/component.js, app/components/workflow-tooltip/template.hbs, app/pipeline/controller.js, app/pipeline/events/controller.js, app/pipeline/events/template.hbs, app/pipeline/options/controller.js, app/utils/graph-tools.js, tests/integration/components/workflow-tooltip/component-test.js, tests/unit/utils/graph-tools-test.js
User cannot toggle to disable or enable jobs while looking a pipeline graph.
This PR appends a job state toggle to pipeline tooltip as the following.
Clicking this toggle will bring up a confirmation modal, similar to the option page.
Issues
- Feat: https://github.com/screwdriver-cd/screwdriver/issues/2539 
- Fix: https://github.com/screwdriver-cd/screwdriver/issues/2633
=> feat(2539): Add job enable or disable toggle on pipeline tooltip

app/components/pipeline-graph-nav/styles.scss
Introducing `branch name`(https://github.com/screwdriver-cd/ui/pull/781) accidentally caused label overflows
Before:
After:
=> fix: prevent label overflow behind event list

app/pipeline/jobs/index/controller.js, tests/unit/pipeline/jobs/controller-test.js
Modify the following Issue with `Case 1`.
https://github.com/screwdriver-cd/screwdriver/issues/2705
When restarting a build using the `listView` function, the `buildId` is not sent to the API and the restart behavior is different.
In this PR, add to parameter to send `buildId` at restart.
issue: https://github.com/screwdriver-cd/screwdriver/issues/2705
The API determines whether to restart or not by whether the buildId is present or not. 
https://github.com/screwdriver-cd/screwdriver/blob/8ee441ffbfc2c17e9246cc4c2a40ee1e944c2121/plugins/events/create.js#L39-L56
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright …
=> fix(2705): restart method when using listView

app/components/validator-job/template.hbs, app/components/validator-pipeline/template.hbs
In the UI of Screwdriver.cd, the parameters value and description are not fully explained.
We clarified which is the `value` and which is `description`. The following `parameters` are displayed as shown in the image.
```
parameters:
full-choose:
value: [ "aaa", "bbb" ]
description: "ccc"
choose: [ "aaa", "bbb" ]
value-only-choose:
value: [ "aaa", "bbb" ]
full-default:
value: "aaa"
description: "ccc"
default: "aaa"
value-only-default:
value: "aaa"
```
https://github.com/screwdriver-cd/screwdriver/issues/2662
=> fix(2662):Improve the description of the parameter

app/components/pipeline-workflow/template.hbs, app/components/workflow-graph-d3/component.js, app/pipeline/events/controller.js, app/pipeline/events/template.hbs
In PR workflow-graph, the job state display is not working, so it is not possible to see if a job that is not running is disabled or not.
Modify it as shown in the following image.
- Set PR job information as `prJobs` to determine the state of PR jobs.
- Get the original job from `prParentJobId` and set the state of the original job as the state of the PR job.
=> fix: Even in PR workflow-graph job states show up

app/components/pipeline-workflow/template.hbs, tests/integration/components/pipeline-workflow/component-test.js
Currently, when manually running a job, sha is highlighted in blue if the latest event is selected.
This indication alone may cause the user to unintentionally run a job from a non-latest sha event.
Displays a message when executing a job from a non-latest sha event.
=> fix: Display message when manually executing jobs for non-latest events

app/collection/model.js, app/collection/serializer.js, app/components/collection-table-row/component.js, app/components/collection-table-row/template.hbs, app/components/collection-view/component.js, app/components/collection-view/styles.scss, app/components/collection-view/template.hbs, app/components/pipeline-card/component.js, app/dashboard/show/route.js, app/pipeline/model.js, tests/integration/components/collection-table-row/component-test.js, tests/integration/components/collection-view/component-test.js, tests/integration/components/pipeline-card/component-test.js, tests/mock/collections.js, tests/mock/metrics.js, tests/mock/pipeline.js, tests/unit/pipeline/events/controller-test.js
Feature addition to dashboard collection to enhance the usability
Add sorting criteria based on ascending or descending order for the number of failed builds (number of red bars)
Create a column after Duration, called "Last Run Job", and sorting criteria based on ascending or descending orders.
Refer to: https://github.com/screwdriver-cd/screwdriver/issues/2713
=> feat: add sort by failed builds and Last Run Job column to dashboard collection

app/components/pipeline-workflow/template.hbs, app/styles/screwdriver-modal-styles.scss, tests/integration/components/pipeline-workflow/component-test.js
#800 displays a message when executing a job from a non-latest sha event. However, the message is quiet and can be missed.
Make the message more conspicuous.
#800
=> fix: emphasize non-latest sha warning when manually executing jobs

app/components/pipeline-options/component.js, app/components/pipeline-workflow/template.hbs, app/components/workflow-tooltip/component.js, app/job/service.js, app/pipeline/controller.js, app/pipeline/events/controller.js, app/pipeline/events/template.hbs, app/pipeline/options/controller.js, app/pipeline/options/template.hbs, tests/integration/components/pipeline-options/component-test.js, tests/unit/job/service-test.js, tests/unit/pipeline/events/controller-test.js, tests/unit/pipeline/options/controller-test.js
Fix the following issue.
- https://github.com/screwdriver-cd/screwdriver/issues/2732
- Show an error message when user without permission change job state.
- Preserve the visual of job state
Option page:
Pipeline tooltip:
https://github.com/screwdriver-cd/screwdriver/issues/2732
=> fix(2732): Show error message when unauthorized users change job state

app/pipeline/events/controller.js
Follow up of PR https://github.com/screwdriver-cd/ui/pull/806 .
When API response is delayed, job icon state may not be restored.
Reload job state after restore original job state.
https://github.com/screwdriver-cd/ui/pull/806
=> fix(2732): reload job state after restore job state

app/components/build-banner/component.js, app/components/build-banner/template.hbs, app/pipeline/build/controller.js, app/pipeline/build/template.hbs, tests/integration/components/build-banner/component-test.js
As per the comment in https://github.com/screwdriver-cd/models/pull/555#pullrequestreview-1047094026, it would be preferable to have a UI where disabled jobs cannot be Restarted from the Build Details page.
Fix the Restart button to be grayed out on the build details page of a disable job.
- While waiting for `model.pipeline.jobs` to fetch, isButtonDisabledLoaded is false and the Restart button is grayed out regardless of its state.
- The time to wait for this fetch does not occur when transitioning from tooltip, but occurs slightly when the build detail page is accessed directly.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of …
=> fix(2728): gray out the Restart button for jobs that are disabled on the build details page

app/components/collection-view/styles.scss
Pipeline collection table show non-intuitive cursor when hover over headers
When mouse hover over Last Run Job and Build History table header, mouse cursor should be a hand to indicate sorting, while other headers should be the default instead of text
https://github.com/screwdriver-cd/screwdriver/issues/2746
=> fix: Pipeline collection table show non-intuitive cursor when hover over headers

app/components/collection-view/styles.scss
For pipeline collection view, when both ALIAS and BUILD HISTORY columns exist, Alias column took much space that Build History column is skewed
For pipeline collection-list view ,to provide enough space for Build History column on Dashboard.
https://github.com/screwdriver-cd/screwdriver/issues/2745
=> fix: When pipeline alias present, build history looks way too small

app/components/pipeline-options/template.hbs, tests/integration/components/pipeline-options/component-test.js
Re-name should be rename.
This PR fixes some spelling issues.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2713
=> fix(2713): spelling error for rename pipeline

app/components/command-header/styles.scss, app/components/command-header/template.hbs, app/components/tc-collection-list/styles.scss, app/components/tc-collection-list/template.hbs, app/components/template-header/styles.scss, app/components/template-header/template.hbs, app/pipeline/metrics/template.hbs, app/styles/chart.scss
Currently, toggles move toward On when the texts are tapped, but not toward Off.
The following four toggles are modified to move in both directions when the toggle texts are tapped.
`Template/Command Search Page`
`Template/Command Description Page`
`Metrics Page 1`
`Metrics Page 2`
https://knownasilya.github.io/ember-toggle/
=> fix: Modify toggle text to work in both directions

app/components/command-header/styles.scss, app/components/tc-collection-list/styles.scss, app/components/template-header/styles.scss
Because of #813, the cursor no longer becomes a pointer when hovering over some toggle texts.
Toggle texts of `Template/Command Search Page` and `Template/Command Description Page` are fixed.
=> fix: fix toggle text cursor

app/components/collection-table-row/template.hbs, app/components/collection-view/styles.scss, app/components/collection-view/template.hbs
Build History column doesn't match with other column on Dashboard collection.
Before:
After
=> fix: update for Build History column

app/components/pipeline-options/template.hbs, app/preference/pipeline/model.js
`displayJobNameLength` is updated in https://github.com/screwdriver-cd/data-schema/pull/504, and currently blocks users to use set/unset show PR Job feature
This PR removes `displayJobNameLength` to unblock users
https://github.com/screwdriver-cd/data-schema/pull/504#issuecomment-1224728898
=> fix: remove displayJobNameLength feature

app/components/pipeline-options/component.js
To Reset alias name and update success message on save.
No API call should involve while hit Reset for alias name.
Success message updated on hit save.
=> fix: Pipeline alias reset

app/components/collection-table-row/component.js, tests/integration/components/collection-view/component-test.js
Once any pipeline's aliasName is set in a collection, that collection shows pipeline's aliasName for all pipeline, which isn't ideal.
Display pipeline's aliasName ,if an aliasName is set .
=> fix: Remove pipeline name as default aliasName

app/components/collection-view/template.hbs
To fix Build history column In collection Dashboard.
add a tool tip to show sort on number of failed builds on build history column.
=> feat: Add tooltip on build history column

app/components/collection-table-row/component.js, app/components/collection-table-row/template.hbs, app/components/collection-view/template.hbs, app/components/pipeline-card/styles.scss, app/components/pipeline-card/template.hbs, app/pipeline/model.js, app/utils/metric.js, tests/integration/components/collection-table-row/component-test.js, tests/integration/components/collection-view/component-test.js, tests/integration/components/pipeline-card/component-test.js
Last run job column's data is not correct.
Display correct data in Last run job column in collection.
card view:
List view:
=> fix: Last run column 

app/user-settings/preferences/template.hbs
Currently the two titles are:
Display Name Length
Choose Timestamp Format
Display Name Length
Timestamp Format
This PR changes titles to:
Related to https://github.com/screwdriver-cd/screwdriver/issues/2218
=> fix: Wording on User Setting to match other settings

app/components/pipeline-search-panel/styles.scss, app/components/pipeline-search-panel/template.hbs
When adding multiple pipelines to a collection from Collection page does not display branch and source path info.
current:
Expectation:
=> fix: Pipeline search panel UX

app/components/collection-view/template.hbs, app/utils/metric.js
last run column sorting is not working as expected.
To fix last run column sorting.
sorting in descending order
sorting in ascending order
=> fix: Last run column sort correction

app/components/pipeline-list-view/component.js, app/components/pipeline-pr-list/component.js, app/components/pipeline-pr-list/template.hbs, app/components/pipeline-start/template.hbs, tests/integration/components/pipeline-list-view/component-test.js, tests/integration/components/pipeline-pr-list/component-test.js
Child pipelines are marked Inactive when the associated SCM URLs have been removed from the external configuration. No new events/builds should be allowed for such inactive child pipelines.
Backend API https://github.com/screwdriver-cd/screwdriver/pull/2724 now fails creation of new events for inactive pipelines.
This PR disables all the action in the UI which submits a request to the Backend API to create a new event.
Here is the page level breakdown of UI changes...
1.  Disable 'Start' and 'Restart' buttons/icons under 'ACTIONS' column against each job listed in the table
1. Disable 'Start' button
1. Disable 'Start' button for pipeline with parameters
2. Hide 'Submit' button in the 'START PIPELINE WITH PARAMETERS' drop down menu
3. Hide 'Submit' button in the 'START PIPELINE WITH …
=> feat(2580): Disable actions that allow user to manually start an event/build

app/components/build-banner/component.js, app/components/build-banner/template.hbs, app/components/build-log/component.js, tests/integration/components/build-banner/component-test.js
To update the createTime in the build details page. 
update the createTime in the build details page to also be controlled by user pref for time format.
=> feat: Add user pref timestamp build details page and build logs
