screwdriver-cd/ui

app/components/collection-view/component.js
When user selects one or more pipelines from the collection and try to remove it, nothing happens.
User should able to delete one or more pipelines from collection.
https://github.com/screwdriver-cd/screwdriver/issues/2794
=> fix: Delete pipelines in a collection

app/components/collection-view/component.js
Select is not working properly while unselect some pipelines in a collection.
To fix select option.
=> fix: Deselect pipelines update count

app/components/pipeline-options/component.js
User clicks Sync Pipeline. Error message is shown even if the Sync is success
#2 In the pipeline options page, if user clicks Sync again and if it succeeds, then error message should be cleared.
https://github.com/screwdriver-cd/screwdriver/issues/765
=> fix: error message persists even after successful action.

screwdriver.yaml
Currently, we run on `node:12`, our `setup_chrome.sh` used to work, see [success build](https://cd.screwdriver.cd/pipelines/7/builds/834390/steps/install-browsers), but no longer works, see [failure build](https://cd.screwdriver.cd/pipelines/7/builds/835493/steps/install-browsers)
The error message show as below:
```
15:31:07 $ ./bin/setup_chrome.sh
15:31:09 OK
15:31:09 Ign:1 http://deb.debian.org/debian stretch InRelease
15:31:09 Get:2 http://security.debian.org/debian-security stretch/updates InRelease [59.1 kB]
15:31:09 Get:3 http://dl.google.com/linux/chrome/deb stable InRelease [1811 B]
15:31:09 Get:4 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
15:31:09 Get:5 http://deb.debian.org/debian stretch Release [118 kB]
15:31:09 Get:6 http://deb.debian.org/debian stretch …
```
=> feat: upgrade node version to 14

app/components/pipeline-create-form/component.js, app/components/pipeline-create-form/template.hbs
UI is not searching in template namespace.
Searching for a template name should match both namespace & name.
https://github.com/screwdriver-cd/screwdriver/issues/2282
=> fix: Create pipeline not showing all templates

app/components/pipeline-create-form/component.js
To fix the search option.
Make the search case insensitive and trim the whitespace at the beginning and end of the word.
https://github.com/screwdriver-cd/screwdriver/issues/2282
=> fix: Make search field case insensitive and trim space

app/components/collection-table-row/template.hbs, app/components/collection-view/component.js, app/components/collection-view/template.hbs, app/utils/metric.js
1) Current sorting breaks on unknown `status` for the collection page
2) Break down the collection into `knownStatus` and `unknownStatus` pipelines, and latter remain at the bottom of the list when sorting.
3) Fix up/down arrow when another column was selected
=> fix: sorting issues for collection page

app/components/collection-view/component.js, app/dashboard/show/controller.js, app/shuttle/service.js
Fix: adding pipelines to collections from different browser tabs is overwriting collection data.
https://user-images.githubusercontent.com/15989893/213005924-c9bdac9d-b905-4d55-b2d3-df849e1b6615.mp4
1. use `URLSearchParams` instead of jquery $.param
2. code clean up, that pass in collectionId instead of lookup
3. use [] notation on computed property as dependencies
4. remove unnecessary `findRecord` inside collection-view/component.js to avoid extra fetch
Collection https://github.com/screwdriver-cd/screwdriver/issues/2765
Backend PR: https://github.com/screwdriver-cd/screwdriver/pull/2797
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on …
=> fix(2765): update pipelines from different tabs

app/components/collection-view/component.js, app/dashboard/show/controller.js, app/shuttle/service.js, tests/unit/dashboard/show/controller-test.js
Fix: adding pipelines to collections from different browser tabs is overwriting collection data.
https://user-images.githubusercontent.com/15989893/213005924-c9bdac9d-b905-4d55-b2d3-df849e1b6615.mp4
Using new API call, instead of UI asks the backend to store what the pipeline to a given collection, UI will just pass the necessary pipeline ids to either delete or add, to avoid override the data in the backend. 
Collection https://github.com/screwdriver-cd/screwdriver/issues/2765
Backend PR: https://github.com/screwdriver-cd/screwdriver/pull/2797
=> fix: update pipelines from different tabs

app/components/pipeline-graph-nav/template.hbs, package-lock.json, package.json, tests/integration/components/pipeline-graph-nav/component-test.js
To set hyperlink to 'label' like 'commit' field.
Make [label](https://docs.screwdriver.cd/user-guide/metadata#event-labels) more usable, so that users can put links inside `label` content, and instead of showing as text, it shows as hyperlinks
https://github.com/screwdriver-cd/screwdriver/issues/2805
=> feat(2805): make label clickable if contains links

app/build/model.js, app/components/build-banner/component.js, app/components/build-banner/template.hbs, app/pipeline/build/template.hbs, app/shuttle/service.js, tests/integration/components/build-banner/component-test.js
If users use a template inside their sd.yaml for jobs, the build details page should show something similar as we do for the container images.
https://github.com/screwdriver-cd/screwdriver/issues/2822
=> feat: Add template details page

app/components/pipeline-search-panel/template.hbs
Syntax pipeline syntax error on Pipeline search panel.
Fix this pipeline search panel syntax error.
=> fix: pipeline search ui link-to syntax issue

app/components/build-banner/template.hbs, app/components/pipeline-pr-list/template.hbs, tests/integration/components/build-banner/component-test.js
feature request :can we have the PR title on pr build page?
Display PR title on PR build page.
https://github.com/screwdriver-cd/screwdriver/issues/2836
=> feat: PR title on PR build page

app/components/build-step-collection/styles.scss, app/components/collection-table-row/styles.scss, app/components/metrics/chart/template.hbs, app/components/pipeline-events-row-group/template.hbs, app/components/tc-collection-list/component.js, app/components/tc-collection-list/template.hbs, app/components/token-list/style.scss, app/pipeline/secrets/template.hbs, app/styles/app.scss, app/styles/user-settings.scss, tests/integration/components/metrics/chart/component-test.js
Fix some display issues caused by Ember upgrade in https://github.com/screwdriver-cd/ui/pull/844.
- Overall
- Font looks a bit large.
- [In bootstrap4, the default font size is `16px`](https://getbootstrap.com/docs/4.6/content/typography/#global-settings), so set `14px` in the root as before.
- Display position of the part using `pull-{right,left}`
- [`pull-{right,left}` is obsolete in bootstrap4](https://getbootstrap.com/docs/4.1/migration/#utilities).
- e.g. before:
after:
- Templates/Commands list page
- There are more than that, but only 10 are shown.
- Since default page size is 10, set `pageSize` to the number that should be displayed.
- Cannot sort by `Name` and `Namespace`.
- In `ember-models-table`, If `propertyName` isn't provided, sorting and filtering options for current …
=> fix(2838): Problems caused by ember upgrade

app/components/tc-collection-list/component.js, app/components/tc-collection-list/styles.scss
Ember Upgrade has turned the table on the templates / commands page into a plain table.
https://github.com/screwdriver-cd/ui/pull/844#issuecomment-1457403847
The class structure has changed due to the change in the table library, so modify the CSS so that it is applied.
[issue](https://github.com/screwdriver-cd/screwdriver/issues/2838)
=> fix(2838): Templates & Commands the table CSS looks like plain table

app/components/build-banner/styles.scss
=> fix: When CONTAINER in build banner is long, it overlaps with TEMPLATE

app/commands/controller.js, app/components/build-banner/component.js, app/components/build-step-collection/component.js, app/components/build-step-item/component.js, app/components/collection-view/component.js, app/components/pipeline-child-list-state-cell/component.js, app/components/pipeline-events/component.js, app/components/pipeline-pr-view/component.js, app/components/pipeline-start/template.hbs, app/job/model.js, app/pipeline/jobs/index/controller.js, app/templates/controller.js
Sometimes we see broken pages for these 2 reasons: 
1) Strict mode in handlebars template files `template.hbs`. 
Error message sample:
```
Uncaught (in promise) Error: Attempted to resolve a value in a strict mode template, but that value was not in scope: isShowingModal
```
Before: 
```hbs
{{#if isShowingModal}}
```
After
```
{{#if this.isShowingModal}}
```
See https://github.com/emberjs/rfcs/blob/master/text/0496-handlebars-strict-mode.md#2-no-implicit-this-fallback
2) Change the implicit `set` to explicit `this.set`, for Ember version [3.20.0+](https://github.com/emberjs/ember.js/pull/18961) for an implicit set.
Error Message: 
```
Uncaught (in promise) Error: Assertion Failed: You attempted to update <screwdriver-ui@model:job::ember545:4816773>._isDisabled to "false", but it is being …
```
=> fix: syntax errors after ember 4 upgrade

app/components/build-banner/component.js, app/components/build-banner/styles.scss, app/components/build-banner/template.hbs
Fix following 2 build-banner display bugs.
- [restart button not aligned to the right](https://github.com/screwdriver-cd/screwdriver/issues/2838#issuecomment-1457234861).
- [Build results from previous commits in the same PR can no longer be selected from the UI](https://github.com/screwdriver-cd/screwdriver/issues/2838#issuecomment-1461053310).
- fix build-banner layout to align the restart button to the right.
- fix css to show a dropdown menu correct.
https://github.com/screwdriver-cd/screwdriver/issues/2838
=> fix: Fix build-banner display

app/components/pipeline-list-history-cell/styles.scss, app/components/pipeline-list-history-cell/template.hbs, tests/integration/components/pipeline-list-history-cell/component-test.js
To find a specific build for a specific job in a very large pipeline, click on "jobs" view to get a recent list of builds for each job and hover over the green/red circles, build number visible which is not meaningful to a user.
To display build date/time.
https://github.com/screwdriver-cd/screwdriver/issues/2774
=> feat:display build date/time

app/components/artifact-tree-children/component.js
Artifact deeplink path is encoded for URI path.
Therefore, it have to be decoded to compare original text.
Decode artifact deeplink path.
screwdriver-cd/screwdriver#2842
=> fix(2842): Fix artifact deeplink expansion

app/components/tc-collection-list/component.js, package-lock.json, package.json
This is a fix for a bug caused by the ember@4 upgrade.
https://github.com/screwdriver-cd/screwdriver/issues/2838#issuecomment-1459627726
Sort Icons in ember-models-table are displayed with `<i>` tags, but ember-fontawesome@v5 requires icons to be displayed with `<svg>` tags.
Since `dom.i2svg()` is now available at ember-models-table@v4.8.0, I update the library version to convert it to `<svg>` tags for display.
https://github.com/FortAwesome/ember-fontawesome/blob/master/UPGRADING.md#mixed-modes-with-automatic-replacement-of-i-tags-to-svg
https://github.com/onechiporenko/ember-models-table/pull/532
https://github.com/onechiporenko/ember-models-table/releases/tag/v4.8.0
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's …
=> fix(2838): Sort icons do not appear in table header on Templates & Commands page

app/components/pipeline-list-job-cell/component.js, app/components/pipeline-list-job-cell/template.hbs, app/components/pipeline-list-view/component.js, tests/integration/components/pipeline-list-job-cell/component-test.js, tests/integration/components/pipeline-list-view/component-test.js
Unable to see display name on Build Details or Options, and unable to see "real" name on Overview.
All UI views should be consistent about which name is used for a job.
https://github.com/screwdriver-cd/screwdriver/issues/2773
=> fix: unable to see build display name

app/components/pipeline-options/component.js, app/components/pipeline-options/template.hbs, tests/integration/components/pipeline-options/component-test.js
When operating the danger zone, we may be worried that I'm operating the wrong pipeline. There is also the possibility of mistakenly pressing cancel and delete.
Before:
After
while no input:
while wrong input:
while correct input:
https://github.com/screwdriver-cd/screwdriver/issues/2542
=> fix:input required for delete pipeline

app/components/build-banner/component.js, app/components/build-banner/template.hbs, app/helpers/linkify.js, app/utils/url-regex.js, app/utils/url.js, tests/integration/components/build-banner/component-test.js
Add support for UI to display Saucelabs test information. 
For backward compatibility purposes,  see the screenshot attached.
UI will keep the old behavior and only override the coverage info when `buildMeta.tests.saucelabs` or `buildMeta.tests.sonarqube` present. 
https://docs.screwdriver.cd/user-guide/metadata.html#coverage-and-test-results
The precedence is `buildMeta.tests.saucelabs` > `buildMeta.tests.sonarqube` > `buildMeta.tests`
=> fix: add saucelabs coverage support

app/components/pipeline-events/component.js
In [PR911](https://github.com/screwdriver-cd/ui/pull/911), we try to reset paginateEvents.
However, it cannot be reset correctly.
Therefore, we filter the events instead of reset.
Filter events.
https://github.com/screwdriver-cd/screwdriver/issues/2846
=> fix(2846): Filter other pipeline events

app/components/command-header/component.js, app/components/command-header/template.hbs, app/components/pipeline-parameterized-build/template.hbs, app/components/template-header/component.js, app/components/template-header/template.hbs, tests/integration/components/command-header/component-test.js, tests/integration/components/template-header/component-test.js
Display corruption due to update Ember.js are fixed.
1. Screwdriver admins cannot trust the template/command.
The following error message appears
The cause is an unsuccessful attempt to override the readonly property
2. Build parameter function does not allow users to set any value
The cause was a failed action helper call.
related to: https://github.com/screwdriver-cd/screwdriver/issues/2838
=> fix(2838): Trusted tag and parameter build bugs

app/components/pipeline-events/component.js
`isFilteredEventsForNoBuilds` does not exist and is not a computed property
=> fix: isFilteredEventsForNoBuilds is not a computed property

app/components/pipeline-events/component.js, tests/integration/components/pipeline-events/component-test.js
With the event filter ON, and users visit the the url with given event, which belongs to the part of the filters, we should show the event.
For example, event 735440 is a scheduled event, which ought not to be displayed, yet if users share the URL to other users and visit the URL directly, 
https://cd.screwdriver.cd/pipelines/11326/events/735440
Users should see the event on the right side regardless
=> fix: selected event from url is not filtered

app/components/build-banner/component.js, app/pipeline/events/show/route.js, app/utils/url.js, tests/integration/components/build-banner/component-test.js
1) event from url is not showing up on workflowGraph
This is regression caused by https://github.com/screwdriver-cd/ui/pull/844/files#diff-7447ce8254a7360f874589e7e4f3f6d2a5bf45b146a010b71b889fd2bb2895a0R59-R61, which abstracted and pagination logics from controller to component. 
2) add relative path support for meta testUrl and coverageUrl
This is caused by PR https://github.com/screwdriver-cd/ui/pull/909, which added full url support while removed relative path as url. 
i.e. 
When set `meta.testsUrl` as a relative path, i.e. `'/sd/workspace/artifacts/summary.html'`, UI will redirect to artifacts 
```
https://screwdriver.cd/pipelines/eventId/builds/builId/artifacts/sd/workspace/artifacts/summary.html
i.e.
https://screwdriver.cd/pipelines/1026570/builds/62088097/artifacts/sd/workspace/art …
```
=> fix: event from url is not showing up on workflowGraph and testsUrl

app/components/pipeline-events/component.js
Show duplicate events
Before:
After:
Caused by PR https://github.com/screwdriver-cd/ui/pull/928 
https://github.com/screwdriver-cd/ui/pull/928/files#diff-29f222214b5312afa539ba16b8a5f802ad973a6dda503372ad6ea712e9d20637R55
It is addressed by only filter and only keep the uniq events: 
https://github.com/screwdriver-cd/ui/compare/adong/fix-duplicate-event?expand=1#diff-4471e0b00b5f0d4e8264e36000b4629e3002b8971be9addd16b5461b45c65d7eR387
=> fix: remove duplicate event

app/components/build-log/component.js, app/components/build-log/template.hbs
When users scroll up a loading/generating log on the build detail page, UI should not auto scroll to the bottom to show the latest log
Screenshot:
We might need a better icon for `scroll`
```
If the user opt-in to new behavior: 
if the user scrolled up:
disable auto-scroll to the bottom.
If the user opt-in back to old behavior: 
if the user scrolled to the bottom:
re-enable auto-scroll to the bottom as loading more logs.
if the user does not opt-in to new behavior:
do nothing
```
Testing Repo: https://github.com/adong/sd-random-log-loop/
Testing Pipeline: https://cd.screwdriver.cd/pipelines/11109
Test pending
https://github.com/screwdriver-cd/screwdriver/issues/1720
https://github.com/screwdriver-cd/ui/pull/912
I confirm that this contribution is made under the terms of the license found …
=> fix: add disable/enable auto scroll when viewing loading logs

app/components/artifact-tree-content/component.js, app/components/artifact-tree-content/style.scss, app/components/artifact-tree-content/template.hbs, app/components/artifact-tree/component.js, app/components/artifact-tree/template.hbs, app/components/pipeline-events/component.js, tests/integration/components/artifact-tree/component-test.js
- Artifacts can not be right clicked and opened in a new tab. 
- We have to click on the arrow to open the Artifacts dictory, and clicking on the folder icon does not open it.
The Artifacts folder was changed to a link. And, clicking on a folder icon or text now opens the directory.
https://github.com/screwdriver-cd/screwdriver/issues/2838
=> fix(2838): Fix artifacts tree

app/components/pipeline-events/component.js
Currently, users force move to workflow page after start build when show job list view.
It should stay show job list view if the build start from job list view.
If users use job list view, not to transit event tab after create event.
=> fix: Stay job list view after Build start

app/components/pipeline-events/component.js
Fixed the following Issue.
https://github.com/screwdriver-cd/screwdriver/issues/2894
The problem occurs when the nodes in the workflowGraph have values with the same name.
When the same name occurs, an object is created where pos is not given, and it is undefined at the point where pos is referenced.
Below is an example of the workflowGraph in question
```
edges: [ { src: ~pr, dest: artifact }  { src: ~pr:foo, dest: artifact }]
nodes:[  {name: '~pr'} {name: '~pr:foo'}  {name: 'artifact'} {name: 'artifact'}]
```
This PR changes the processing of the graphs displayed in the PR to avoid unnecessary duplication.
I am modifying the workflowGraph for each PR event to extract the nodes starting with `~pr` and create that unique set of nodes. …
=> fix(2894): Workflow graph not displayed for triggers [~pr, ~pr:foo]

app/components/pipeline-event-row/template.hbs, app/components/pipeline-events-list/component.js, app/components/pipeline-events/component.js
When some events are running in a pipeline and users try to stop a event which is not selected, the selected event will be stopped.
So we will fix this behavior.
When the stop event button is clicked, the eventid associated with the clicked event is passed to the stopEvent action.
=> fix: Stop exact clicked event

app/components/artifact-preview/template.hbs, app/components/build-step-collection/template.hbs
After viewing the build steps, open the Artifact preview and click on the directory to see the last build step displayed.
Build step should not be displayed in artifact preview page, we fix this behavior.
When artifact directory is selected, iframeUrl set blank.
So blank iframe is displayed in preview window if iframeUrl is blank.
screwdriver-cd/screwdriver#2901
=> fix(2901): Show blank window when dir is selected

app/pipeline/build/route.js, tests/acceptance/pipeline-builds-test.js, tests/unit/pipeline/build/route-test.js
Currently, the given step in the URL is not honored if the build is finished i.e.
Visit
`https://cd.screwdriver.cd/pipelines/3066/builds/142678/steps/install_binaries`
Will end up
`https://cd.screwdriver.cd/pipelines/3066/builds/142678/steps/publish`
If build is running, then visiting `https://cd.screwdriver.cd/pipelines/3066/builds/142678/steps/install_binaries` should redirect users to their latest step
If build is in finishing state (FAILED, ABORTED, UNKNOWN, etc,.), then visiting `https://cd.screwdriver.cd/pipelines/3066/builds/142678/steps/install_binaries` should NOT redirect users to other steps, instead, it should stay in the specified step from the given url. 
https://github.com/screwdriver-cd/screwdriver/issues/2905
I confirm that this contribution is made under the terms of the …
=> fix: redirect step from given url

app/pipeline/build/route.js, tests/acceptance/pipeline-builds-test.js
Continue work of https://github.com/screwdriver-cd/ui/pull/946
Add more logics that:
1. if step is given in the url, go to specified step route
2. if non step is given in the url, go to the default active step route
- if it's a success build, then don't redirect to any step and let users to pick
- if it's a failed build, show the first failed step
Currently, if the url is given as
`https://cd.screwdriver.cd/pipelines/1056914/builds/68077307`
We will show build page without any step preselected. 
This PR changes that behavior for failed build, will auto redirect `failed build` to `failed build with the first failed step`
i.e. 
Visiting `https://cd.screwdriver.cd/pipelines/1056914/builds/68077307`
If build `68077307` is success build, 
then go to url …
=> fix: update redirect logics

app/pipeline/build/template.hbs
it's an oversight that warning still fetching from build.meta.meta.warning, it should be build.meta.build.warning instead
build warning should fetch from meta.build instead
=> fix: build warning should fetch from meta.build instead

app/commands/controller.js, app/commands/route.js, app/components/command-header/component.js, app/components/command-header/template.hbs
1) When visit latest version of command, will show latest instead pinned version as issue https://github.com/screwdriver-cd/screwdriver/issues/1795 suggests
2) fix crumbs when change command urls
Before:
After:
https://github.com/screwdriver-cd/screwdriver/issues/1795
=> fix(#1795): crumbs header and add latest to latest version when copy command

app/components/template-version-list-actions-cell/component.js, app/components/template-version-list-actions-cell/styles.scss, app/components/template-version-list-actions-cell/template.hbs, app/components/template-versions/component.js, app/templates/detail/template.hbs, tests/integration/components/template-versions/component-test.js
PR https://github.com/screwdriver-cd/ui/pull/937 add in template detail view to delete a specific version on the template.
But, the delete action was only available to Screwdriver admins.
API to delete a template version also allow template owners (repo admins) to delete a specific version
Make delete action available to all users.
If a user who do not have admin permission on the template repo attempts to delete a template version, API would fail with 403 and below error will be displayed in the UI
https://github.com/screwdriver-cd/screwdriver/issues/2862
=> feat(2862): Allow template owners (repo admins) to delete a template version

app/components/pipeline-event-row/template.hbs, app/components/pipeline-events-list/component.js, app/components/pipeline-events/component.js
Events status do not update immediately when user stops events.
So user should reload window to get correct event status.
Reload event data just after user stops events.
=> fix: reload event data just after user stop events

app/components/collection-view/styles.scss, app/components/workflow-graph-d3/component.js, app/event/model.js, app/pipeline/jobs/index/controller.js, app/utils/metric.js, tests/integration/components/pipeline-card/component-test.js, tests/integration/components/pipeline-event-row/component-test.js, tests/integration/components/pipeline-list-history-cell/component-test.js, tests/integration/components/pipeline-workflow/component-test.js
it could confusing to users when failed builds are marked with warning
only mark successful builds
=> fix: only mark warning on successful build

app/components/time-range-picker/component.js, app/templates/detail/route.js
Fix the problem in the following comment.
https://github.com/screwdriver-cd/ui/pull/960#issuecomment-1803212548
Currently, the total for the entire period is being aggregated to show the number of builds in the template-header, and the total for one year to show the number of builds per version.
Because double aggregation is a burden on the DB, modify the values displayed in template-header to refer to one year's aggregation.
Also, add an `all` button to display version metrics for the entire period
=> fix(2862): Improve the load on the DB for template metrics

app/components/pipeline-header/component.js, app/components/pipeline-header/styles.scss, app/components/pipeline-header/template.hbs, app/pipeline/service.js, tests/integration/components/pipeline-header/component-test.js, tests/unit/pipeline/service-test.js
We want to easily transition to the pipeline in the same repository.
We implemented the function to transition to the pipeline of the same repository. The link to the scm repository has been moved to the icon on the right.
https://github.com/screwdriver-cd/screwdriver/issues/2215#issuecomment-949189578
=> feat:(2215) move to same repository pipeline

app/components/pipeline-header/component.js, tests/integration/components/pipeline-header/component-test.js
#962  allows us to switch to a pipeline of the same repository, but sometimes pipelines of other repositories also appear as options for switching to.
We filter correctly so that pipelines from other repositories do not appear.
The format of `scmUri` is `<SCM>:<repository ID>:<branch>`. We can accurately determine if they are the same repository by comparing the string up to the last `:`.
https://github.com/screwdriver-cd/screwdriver/issues/2215
=> fix:(2215): fix issue of moving between pipelines in the same branch

app/utils/git.js, tests/integration/components/pipeline-create-form/component-test.js, tests/unit/utils/git-test.js
On GitHub, it was possible to use full-width space of Japanese in branch names, but these characters were not available in SD.
Change to allow the input of Japanese full-width spaces.
This will allow the use of character pipelines such as "🚗　🚗".
- https://github.com/screwdriver-cd/screwdriver/issues/2952
=> fix(2952): Make full-width space available in branch name [4]

app/components/pipeline-header/component.js, tests/integration/components/pipeline-header/component-test.js
In #964, we made sure to verify if each of the pipeline options for a switch was of the same repository. However, this has caused improper functioning when root directory is set.
We have ensured correct operation even when root directory is set. In cases where the root directory is set, the format of `scmUri` is `<SCM>:<repository ID>:<branch>:<rootDir>`, so we decided to compare up to the second `:`.
https://github.com/screwdriver-cd/screwdriver/issues/2215
=> fix:(2215): fix issue of moving between pipelines in the same branch (rootDir)

app/pipeline/build/route.js
When using build.warning and directly transitioning to a build where the UI display is Warning, it seems that the build details screen does not turn into Warning.
build warning should be set on direct load to build page
https://github.com/screwdriver-cd/screwdriver/issues/2949
=> fix: warning not set on direct build page load

app/components/command-header/component.js, app/components/command-header/styles.scss, app/components/command-header/template.hbs, app/components/template-header/component.js, app/components/template-header/styles.scss, app/components/template-header/template.hbs, app/components/template-version-list-actions-cell/template.hbs, tests/integration/components/command-header/component-test.js, tests/integration/components/template-header/component-test.js, tests/integration/components/template-versions/component-test.js
Users might mistakenly click the command/template delete button when they actually intend to click the repository link.
This PR will move the command/template delete button to the right side and merge the trusted toggle button with the trusted icon.
SD admin can toggle trusted as below:
https://github.com/screwdriver-cd/ui/assets/43719835/06f3b1cb-5d42-4c17-940f-27976bb4b45c
Distrusted icon does not appear in user's view.
If the repository does not exist, the delete button will be disabled.
The color of the confirm button on the specific version template deletion modal is set to red.
Issue
https://github.com/screwdriver-cd/screwdriver/issues/2928
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I …
=> fix(2928): move the command/template delete button to right side

app/components/artifact-preview/style.scss, app/components/artifact-preview/template.hbs, app/components/artifact-tree-content/style.scss, app/components/build-step-collection/styles.scss
Modify the Artifact preview page layout.
Before:
- There is a blank space under the artifact preview window.
- Artifact tree cannot scroll horizontally. Because of this, deep directory paths or long file names are cutoff.
After:
Set proper properties on artifact preview iframe and artifact-tree-content.
https://github.com/screwdriver-cd/screwdriver/issues/2954
=> fix(2954): Modify Artifact preview

app/components/workflow-graph-d3/component.js
With jobs that include a large number of wide-width characters, the text overflows in the workflow graph.
We reduce the font size when overflowing.
https://github.com/screwdriver-cd/screwdriver/issues/2924
=> fix(2924): Adjust font size in workflow to prevent text overflow

app/components/app-header/template.hbs
Currently, app-header links open in the same tab, which might be inconvenient.
Open app-header links in a new tab.
=> fix: open app-header links in a new tab

app/components/command-header/template.hbs, app/components/template-header/template.hbs
Add UI to show compatibilities for Template:
and for commands:
=> feat: show compatibilities for clouds and arches on templates and commands pages

app/components/pipeline-header/component.js, tests/integration/components/pipeline-header/component-test.js
https://github.com/screwdriver-cd/ui/pull/962 adds links for pipelines from the same repository, but they are not sorted.
This makes it difficult to easily find the branch names in this list.
Sort same repository pipeline links by their names.
- https://github.com/screwdriver-cd/screwdriver/issues/2215
=> fix(2215): sort same repository pipeline links

app/templates/detail/route.js
In the template detail page, we'd like to show 1 year metrics for each template version and all time count for jobs/builds in the template header.
https://github.com/screwdriver-cd/screwdriver/issues/2862#issuecomment-1841355144
So that we show above information, we have to call API twice.
Separate API call for metrics for each template versions and the count for jobs/builds in the template header.
Revert a part of the past PR.
https://github.com/screwdriver-cd/ui/pull/961
https://github.com/screwdriver-cd/screwdriver/issues/2862
=> fix(2862): Call API twice for header and metrics

app/user-settings/preferences/controller.js, app/user-settings/preferences/template.hbs
The value of Job Name Length is reset when user click save button without inputting that value.
Fix the initial value of `Job Name Length`.
https://github.com/screwdriver-cd/screwdriver/issues/2967
=> fix(2967): keep the value of display job name length

app/components/validator-job/styles.scss, app/components/validator-pipeline/styles.scss
Long workflow graph is overflowing on validator page.
Allow horizontal scrolling like input.
Add horizontal scroll bar into workflow graph.
https://github.com/screwdriver-cd/screwdriver/issues/2971
=> fix: overflow workflow graph on validator page

app/helpers/input-sanitizer.js, tests/integration/components/info-message/component-test.js
Previous PR https://github.com/screwdriver-cd/ui/pull/974 will filter almost every tags, and will not allow `anchor` tag to work
Instead of using regex, use DOM Parser to filter out allow/deny elements and attributes
Screenshots:
Issue: https://github.com/screwdriver-cd/screwdriver/issues/2970
Test Links: 
1) https://cd.screwdriver.cd/pipelines/10293/builds/913516
2) https://cd.screwdriver.cd/pipelines/12888/builds/915788
=> feat(#2970): use DOM parser instead of Regex to sanitize user html input

app/components/app-header/styles.scss, app/components/collection-view/styles.scss, app/components/info-message/styles.scss, app/components/metrics/chart/template.hbs, app/components/nav-banner/style.scss, app/components/pipeline-child-list-actions-cell/styles.scss, app/components/pipeline-list-actions-cell/styles.scss, app/components/pipeline-list-job-cell/styles.scss, app/components/quickstart-guide/styles.scss, app/pipeline/metrics/template.hbs, app/styles/chart.scss, app/user-settings/preferences/template.hbs, tests/acceptance/metrics-test.js
After upgrading to Ember@4, `<FaIcon>` renders `<svg>` instead of `<i class='fa'>`.
Thus we need to fix CSS accordingly.
Fix CSS and icon names.
https://github.com/screwdriver-cd/screwdriver/issues/2838
=> fix(2838): migrate .fa icons to svg in CSS

app/components/pipeline-events/component.js, app/components/pipeline-pr-list/component.js, tests/integration/components/pipeline-events/component-test.js
- PR builds don't appear automatically after users click the start button on PR list
- Start button is showing during the PR builds are running
- Load PR builds automatically when user click PR start button
- Show Stop button when the PR builds are running
=> fix: load pr builds automatically when click start button

app/components/pipeline-list-actions-cell/component.js, app/components/pipeline-list-view/template.hbs
Job's build parameter form is expanded by default when user start/restart from the job on workflow tool tip.
But on pipeline list view, pipeline level parameter form is always expanded.
And the parameter modal is not appear when user restart builds on list view.
- Expands job's parameter form on list view
- Show pipeline parameter form on list view in restart case
=> fix: expand job parameter on pipeline list view

app/components/validator-input/styles.scss, app/components/validator-input/template.hbs, app/validator/controller.js, app/validator/template.hbs
The validator input form, workflow graph, job details are narrow when users use vertical display.
This PR will add the button that can switch split view / spread view.
https://github.com/screwdriver-cd/ui/assets/43719835/0dff75db-113b-4adf-a2d1-0da1d40cbd49
=> feat: spread the validator page's view

app/components/build-banner/styles.scss
The build details page now allows viewing template information in the build banner. However, the CSS settings were not updated, resulting in the components being arranged into two columns when at maximum capacity.
I've updated the CSS to ensure that all components stay in a single column even when all components are present.
https://github.com/screwdriver-cd/screwdriver/issues/2822
=> fix(2822): Increase the maximum number of columns for build-banner

app/pipeline/pulls/route.js
For pipelines with lots of build data, and especially pipelines with the `chainPR` setting configured, switching to the Pull Request view from the Events view may not render the Pull Request graph properly.
When switching to the Pull Request view from the Events view, the `showDownstreamTriggers` field is not properly configured.  This fix pins the `showDownstreamTriggers` to `false` when the Pull Request view is rendered so that `chainPR` configured pipelines will always properly render the pipeline graphs.
=> fix: PR graph rendering bug when switching to PR tab

app/components/workflow-graph-d3/component.js
There's a race condition when rendering graphs based on whether or not the data is already in the ember data store.
Changing the lifecycle back to `didUpdateAttrs` fixes the race condition on the graph being rendered multiple times in a single update.
=> fix: graph render race condition

app/components/pipeline-events/template.hbs, app/components/pipeline-workflow/template.hbs, app/components/workflow-graph-d3/component.js, app/utils/graph-tools.js
Pipeline configurations with the `chainPR` setting as false do not display the pipeline graph correctly in the Pull Request view.
Fix the pipeline graph for Pull Requests with the `chainPR` setting as `false`.  The pipeline graph will also have graph nodes fully clickable with their dropdown menu options to select.
https://github.com/screwdriver-cd/screwdriver/issues/2660
=> fix: PR graph for non-chainPR configurations

app/components/pipeline-events/template.hbs, app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs, app/components/workflow-graph-d3/component.js, app/components/workflow-graph-d3/styles.scss, app/components/workflow-tooltip/component.js, app/job/model.js, app/pipeline/events/show/route.js, app/pipeline/events/template.hbs, app/pipeline/route.js, app/shuttle/service.js, app/stage/adapter.js, app/stage/model.js, app/stage/serializer.js, app/utils/graph-tools.js, tests/acceptance/pipeline-builds-test.js, tests/integration/components/pipeline-workflow/component-test.js, tests/integration/components/workflow-graph-d3/component-test.js, tests/integration/components/workflow-tooltip/component-test.js, tests/unit/utils/graph-tools-test.js
Stage represents a group of closely related jobs acting on a specific environment in the pipeline. We need to visualize these groupings in the workflow graph for an event.
Stage will have a name and description (optional).
Render stages in the workflow graph
**Examples:**
https://github.com/sagar1312/screwdriver-config/blob/main/stage-with-linear-jobs/screwdriver.yaml
https://github.com/sagar1312/screwdriver-config/blob/main/stage-with-parallel-jobs/screwdriver.yaml
https://github.com/sagar1312/screwdriver-config/blob/main/stage-with-linear-jobs-not-in-first-row/screwdriver.yaml
https://github.com/screwdriver-cd/screwdriver/issues/2669
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the …
=> feat(2669): Render Stages in the workflow graph if configured

app/components/pipeline-events/template.hbs, app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs, app/components/workflow-tooltip/template.hbs, app/utils/graph-tools.js, tests/integration/components/workflow-tooltip/component-test.js, tests/unit/utils/graph-tools-test.js
The ability for a job to start or restart from the graph node depends on job data returned from the API.  If data is missing from the API, this prevents the UI from being able to create the tooltips correctly.
Update the tooltip logic to only rely on the workflow graph information.  Additional logic around the current view is used to further determine which jobs, and their associated workflow graph, can be triggered.
https://github.com/screwdriver-cd/screwdriver/issues/3011
=> fix: update logic for determining when a node can start and restart

app/pipeline/pulls/route.js
The pull request view makes a lot of API calls to `/user/settings` instead of using the cached value.
Change the pull request view's model to make a request for `user/settings` and cache the values for any subcomponents to use.  The model was previously not making any API calls leading to all subcomponents making those requests instead.  The model is updated to be async which ensures that the API call is only called once when the view is loaded and that any subcomponents will use the cached data.
=> fix: update pull request view model

app/components/pipeline-options/component.js, app/preference/pipeline/adapter.js, app/shuttle/service.js, tests/integration/components/pipeline-options/component-test.js
Updating pipeline settings requires 2 API calls.  Currently, to update the pipeline settings 2 API calls are required because the pipeline setting adapter does not serialize the user settings.  As a result, the current implementation makes an API call to get the current settings and update only the modified pipeline's settings.  As there is no `PATCH` API endpoint, the full settings body must be recreated.
Updates the pipeline setting adapter to serialize the user settings to remove the need for an API call.
=> fix: updating pipeline settings only requires 1 API call

app/user-settings/preferences/controller.js, tests/unit/user-settings/preferences/controller-test.js
In the `User Settings` page, the `DELETE` method of the `/user/settings` API is used to reset all user settings.  The local settings for pipelines are currently still preserved when they should be reset.
Fix the reset logic to also clear out pipeline settings from the ember store when user settings are reset.
=> Fix local options not being reset

app/job/model.js, app/utils/graph-tools.js, tests/unit/utils/graph-tools-test.js
Current implementation hides all the nodes/edges corresponding to stage `setup`/`teardown` jobs even when setup/teardown is explitctly configured in the `screwdriver.yaml`.
With https://github.com/screwdriver-cd/config-parser/pull/151, we can now distinguish implicitly vs explicitly created setup or teardown for a stage. This allows us to selectively hide nodes/edges corresponding to stage `setup`/`teardown` jobs.
Hide `setup`/`teardown` nodes, if the corresponding jobs have the annotation `'screwdriver.cd/virtualJob': true`.
**Example:**
https://github.com/sagar1312/screwdriver-config/blob/main/stage-alpha-parallel/screwdriver.yaml
```
stages:
integration:
jobs: [ci-deploy, ci-test, ci-certify]
requires: [ publish ]
description: "This stage will deploy the latest application to CI …
```
=> feat(3022): Show stage setup/teardown nodes in workflow graph when setup/teardown is explicitly specified in pipeline configuration

app/components/pipeline-events/template.hbs
The pipeline events and pull request pages make render the full sidebar (both the events shown in the events tab and the pull requests in the pull request tab).  However, only half of the sidebar is ever displayed on the page as switching tabs navigates to the other page.  There are a lot of wasted API calls and subcomponent rendering that provide no benefit to the page being viewed.
Conditionally render the sidebar to avoid wasting resources.
=> Conditionally render sidebar tab panes

app/application/route.js
The collections API is called multiple times for the `/pipeline/*` and `/dashboards` routes.  Those routes require the collections data, but they are already configured to fetch the data if required.  The main application route was configured to also request the collections API, even though many routes do not require the collections data.
Pushes API calls for collections down to the actual routes that require the data.  Also removes the redundant API call as `setupController` is not async and the routes below are not aware that the API call has already been made.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright …
=> fix: remove redundant calls to collections API

app/pipeline/events/show/route.js
When loading the pipeline page, multiple API calls are being made to the `/events/{eventId}` endpoint.  Limit the number of API calls to the `events/{eventId}` endpoint by properly checking the store cache first.
`Peek` into the ember store cache to get the event data and only make an API call if the store cache does not contain the event.
=> Fix cache checking of event

app/components/pipeline-workflow/component.js, app/utils/pipeline-workflow.js, tests/unit/utils/pipeline-workflow-test.js
#991 did not account for jobs on the ~pr path that are also joined from a detached job.  This updates the start/re-start logic to be more robust so that any job reachable from the ~pr trigger are validated to have multiple routes to determine eligibility of being started/re-started from the pipeline views.
Adds an additional check on jobs reachable from the ~pr trigger to determine how many root jobs exist for the particular node.
https://github.com/screwdriver-cd/screwdriver/issues/3053
=> fix(3053): handle re/start with joins from a detached job

app/dashboard/route.js, app/dashboard/show/route.js
#1003 Removed loading of collections for the entire application in favor of loading them as needed depending on the route.  The unfortunate side-effect is that the collections dashboard view was expecting the collections to be stored in the application controller.
Adds in the collection loading logic into the collections dashboard route to load collections data from the store if it exists or else load it via the API call.  
https://github.com/screwdriver-cd/screwdriver/issues/3048
=> fix(3048): dashboard for a collection page renders all collections in sidebar

app/components/validator-pipeline/template.hbs, app/components/validator-results/component.js, app/components/validator-results/template.hbs, app/components/workflow-graph-d3/component.js, app/utils/graph-tools.js, tests/integration/components/validator-results/component-test.js, tests/integration/components/workflow-graph-d3/component-test.js, tests/unit/utils/graph-tools-test.js
Validator UI does not render stages in the workflow graph.
Also the implicit stage/setup teardown jobs are not hidden .
```
shared:
image: node:14
steps:
- init: echo 'init'
jobs:
component:
annotations:
screwdriver.cd/displayName: compJob
publish:
requires: [ component ]
ci-deploy:
requires: [ ]
ci-test:
requires: [ ci-deploy ]
ci-certify:
requires: [ci-test]
prod-deploy:
requires: [ ]
prod-test:
requires: [ prod-deploy ]
prod-certify:
requires: [ prod-test ]
stages:
integration:
jobs: [ci-deploy, ci-test, ci-certify]
requires: [ publish ]
description: "This stage will deploy the latest application to CI environment and certifies it after the tests are passed."
production:
jobs: [ prod-deploy, prod-test, prod-certify ]
requires: [ ~stage@integration:teardown ] …
```
=> feat(3041): Validator UI - Show stages in workflow graph if configured

app/components/pipeline-event-row/styles.scss
When the workflow is long horizontally, the stop button is displayed out of the screen.
To prevent this behavior, make the workflow graph scrollable.
Before:
After:
Add css properties to make the workflow graph scrollable.
screwdriver-cd/screwdriver#3049
=> fix(3049): Add css to scroll workflow graph

app/components/pipeline-header/component.js, app/components/validator-job/component.js, app/components/validator-job/template.hbs, app/components/validator-pipeline/template.hbs, app/components/validator-results/component.js, app/components/validator-results/template.hbs, tests/integration/components/validator-results/component-test.js
Added validator support to display pipeline template and pipeline template usage
The validator should correctly display the pipeline template name, namespace, jobs, etc.
The validator should correctly display the pipeline template used in a pipeline
Template:
Usage:
https://github.com/screwdriver-cd/screwdriver/issues/3052
=> feat: add validator ui support for pipeline templates

app/application/template.hbs, app/components/app-body/component.js, app/components/app-body/template.hbs, app/components/build-banner/styles.scss, app/components/build-step-collection/styles.scss, app/components/build-step-collection/template.hbs, app/components/pipeline-events/style.scss, app/components/pipeline-events/template.hbs, app/components/pipeline-header/styles.scss, app/components/pipeline-nav/styles.scss, app/pipeline/build/template.hbs, app/pipeline/child-pipelines/template.hbs, app/pipeline/jobs/index/template.hbs, app/pipeline/metrics/template.hbs, app/pipeline/options/template.hbs, app/pipeline/secrets/template.hbs, app/styles/app.scss
The application template by default uses the `container-fluid` class which has a built in left and right padding of 15px.  This causes the pipeline route pages to have some extra white margins across the navigation bars.
Remove the whitespace showing up in the pipeline routes.
=> fix: left and right padding on pipeline routes

app/components/build-banner/component.js, app/components/pipeline-graph-nav/component.js
This PR is follow up https://github.com/screwdriver-cd/ui/pull/992.
- Displays pipeline name, job name, screwdriver icon, and status icons.
- Clicking on the notification should take you to the tab.
build detail page
pipeline page
https://github.com/screwdriver-cd/screwdriver/issues/2369
=> fix(2369): Improve the content of notifications

app/pipeline/build/controller.js, tests/unit/pipeline/build/controller-test.js
Warning status is not displayed on build details page when the build completed in this page.
https://github.com/screwdriver-cd/ui/assets/43719835/135a5d12-0c1e-4004-8627-d3f3f50ab2c4
Display warning status automatically after the build completes.
https://github.com/screwdriver-cd/ui/assets/43719835/9f52f8e9-909a-4a72-ac7c-dee23a0aff65
=> fix: automatically display warning status on build details page

app/utils/graph-tools.js, tests/integration/components/validator-results/component-test.js, tests/unit/utils/graph-tools-test.js
Workflow graph node (Ex: implicit setup/teardown job of a stage) for an event is identified as virtual based on the presence/value of `screwdriver.cd/virtualJob` annotation in the corresponding job definition.
Since the job definition reflects the latest configuration from `screwdriver.yaml`, referring to current annotations of the job may not be reliable to identify it as virtual for an event.
Changes are made in the workflow-parser https://github.com/screwdriver-cd/workflow-parser/pull/51 to include a flag in the workflow graph node to preserve whether the job is virtual or not when the event is created.
Use this new `virtual` flag to hide implicit stage setup/teardown jobs/nodes in the workflow graph
I confirm that this contribution is made under the terms of the license found in the …
=> feat(3022): Hide nodes marked as virtual in the workflow graph

app/user-settings/preferences/controller.js, tests/acceptance/user-settings-test.js
The minimum and maximum values are set on the input form.
But user can input underflow or overflow values directly and store it.
Fit the input value between the minimum and the maximum values when user store it.
=> fix: fit Display Job Name Length between minimum and maximum valuese

app/components/pipeline-parameterized-build/component.js
Currently, buildparameters are always expanded even if selected job has nether job-level build parameters nor pipeline-level parameters(That is, if there are no buildparameters used in the job).
We fix this behavior so that only buildparameters related to the job are expanded.
`normalizedParameterGroups` only contains job related job-level parameter and pipeline-level parameters at L174.
Change the timing to determine if the parameters should be expanded at this time.
After determine if the parameters should be expanded or not, all other job-level parameters are added to return value.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on …
=> fix: Only expand job related parameter

app/components/pipeline-header/component.js
#1010 accidentally introduced a bug with the associated repos not being rendered.  As another side effect,  when the dropdown is activated, API calls are infinitely called.  These abnormal behaviors were caused by the eslint rule around computed properties.
Disable the eslint rule for computed properties as that does not play nicely with the currently configuration of the ember data cache.
=> fix dropdown for other repos

app/components/app-header/styles.scss, app/styles/app.scss
The navbar changes heights based on window size, but the difference in height is fairly minor.  Setting the navbar height to a constant size will remove the height difference and also make height calculations for other components easier.
Sets the navbar to a constant height as there is currently no use case for having a variable height navbar.
=> fix: sets application navbar to a constant height

app/components/collections-flyout/styles.scss
The side bar on collections page is cut off as below.
Stretch the side bar height.
=> fix: stretch the side bar on collection page

app/application/template.hbs, app/components/app-body/styles.scss, app/components/app-body/template.hbs, app/components/nav-banner/style.scss, app/components/nav-banner/template.hbs, app/styles/app.scss
Updating the nav banner style to better handle long messages and also vertically aligning the individual components.  The updated style also keeps the height at a constant value so that the remaining space in the window can be more accurately calculated.
Vertically aligns the nav banner components and sets the height to be constant.  Long messages will also vertically scroll rather than overflowing.  Also adjusts the remaining vertical space on the page to account for whether a nav banner exists.
=> fix: update nav banner style

app/components/workflow-graph-d3/component.js
#1000 added new logic to merge graph data, but one unfortunate side effect is that it is unable to handle certain cases where the pipeline graph is modified in a pull request for the pull request page. 
Remove the new logic that was introduced in #1000 so that the main pipeline graph displayed in the pull request page will display consistently.
=> fix: revert logic for combining graph data

app/components/app-header/styles.scss
When not logged in, the profile icon has a background color set when hovering.
Remove the background color when hovering
=> fix: background color on hover for profile icon

app/components/app-header/styles.scss
Same issue as #1024 but for the focus state of the profile icon.
Fixed background color for the profile icon when focused.
=> fix: background-color for profile icon when focused

app/components/pipeline-pr-list/styles.scss
In the PR view, the height of the sidebar elements are now misconfigured for non-chained pipelines.
Fix the height of the sidebar element for non-chained pipelines.
=> fix: height on PR list element

app/templates/pipeline/detail/controller.js, tests/unit/templates/pipeline/detail/controller-test.js
Currently, delete pipeline template version only deletes the latest one.
1) delete the pipeline template by version by the target version from table
2) Add more tests
=> fix: delete pipeline by version only delete the latest one

app/components/pipeline-events/template.hbs
#1023 modified the layout a bit and the event handler for scrolling the events sidebar list is not getting fired.
Fix the scroll event handler to be attached to the correct scrollable parent element.
=> fix: event list does not fetch new data

app/components/app-body/styles.scss, app/components/pipeline-graph-nav/styles.scss
#1023 made the buttons scrollable on overflow, however the overflow prevents the dropdown from being easily accessible.
Removes the overflow behavior in favor of a minimum width so that the dropdown will display properly.
=> fix: start job dropdown

app/components/build-banner/template.hbs, app/templates/job/detail/index/route.js, tests/integration/components/build-banner/component-test.js
Fix job template info to show up on build-banner
1) rename route "templates.detail.version" to "templates.job.detail.version" 
2) Add test to check hyper link
https://github.com/screwdriver-cd/screwdriver/issues/3086
=> fix(3086): job template info now shows up on build-banner

app/components/pipeline-parameterized-build/component.js, app/components/pipeline-parameterized-build/styles.scss, app/components/pipeline-parameterized-build/template.hbs
The parameter list is hidden outside the scroll range when the drop-down is displayed.
Scrolls the screen automatically until the bottom of the dropdown is visible when the drop-down is displayed for better visibility.
(Additional jsdoc fixes.)
The main modifications are as follows
[app/components/pipeline-parameterized-build/component.js/R368-R429](https://github.com/screwdriver-cd/ui/pull/1037/files#diff-c32e55d57b1466e497b57e8c4b27cb6b608602048c28874caa305d0f0c752af1R368-R429)
https://github.com/screwdriver-cd/ui/assets/138551445/61ff234a-e6d6-41a3-a923-74cc68bc6716
https://github.com/screwdriver-cd/ui/assets/138551445/8485afaf-47e9-413f-b486-0c87396eb964
https://github.com/screwdriver-cd/screwdriver/issues/2672
I confirm that this contribution is made under the terms of the license …
=> fix(2672): build parameters scroll behavior

app/commands/index/template.hbs, app/commands/template.hbs, app/components/tc-collection-list/component.js, app/components/tc-collection-list/template.hbs, app/styles/app.scss, app/styles/commands-templates.scss, tests/acceptance/commands-test.js
1. abstract placeholder to a computed property
2. show commands instead of templates
Add header to `/commands` just as we have for pipeline/job templates 
https://github.com/screwdriver-cd/screwdriver/issues/3093
=> fix(3093): show commands instead of templates on commands route

app/components/pipeline-pr-view/component.js, app/pipeline/metrics/route.js, package-lock.json, package.json
Ember data 4.12 introduces their new architecture which requires a number of changes.  4.11 contains a principle deprecation of `objectAt` no longer being the suggested method of accessing returned items from an array.
Updates to Ember data 4.11 and changes array access to using native array access.
=> Update to ember data 4.11

app/components/pipeline-create-form/template.hbs
Not all templates have options.  In addition, the fragment here does not do anything of interest.
Fixes the error when looping through templates.
=> fix: remove problematic loop

app/components/pipeline-create-form/component.js, app/components/pipeline-create-form/template.hbs
`messageForSearching` is not doing anything meaningful anymore as all the templates are already fetched via the API via the router model.  Additionally, `templates.options` does not exist and causes an error.
Removes `messageForSearching` and updates the `PowerSelect` component to use a static string for displaying the message when an option isn't found.
Related to #1043 
=> fix: remove messageForSearching as it is not required

app/components/pipeline-pr-view/component.js, app/pipeline/metrics/route.js, package-lock.json, package.json
Reverts screwdriver-cd/ui#1041.  Seems like there is some odd instability happening with the 4.11 ember data upgrade.  Not sure what the issue is, but reverting to 4.4 may help out in the interim
=> Revert "Update to ember data 4.11"

app/utils/graph-tools.js, tests/unit/utils/graph-tools-test.js
Non stage jobs are being positioned under stage on the workflow graph in the UI giving a false impression that those jobs are part of the stage.
**Example (screwdriver.yaml)**
```
shared:
image: node:20
steps:
- init: echo 'init'
jobs:
triggering-stage:
overlapping-non-stage-job-at-start-1:
requires: [triggering-stage]
overlapping-non-stage-job-at-start-2a:
requires: [ overlapping-non-stage-job-at-start-1 ]
overlapping-non-stage-job-at-start-2b:
requires: [ overlapping-non-stage-job-at-start-1 ]
ci-deploy:
requires: [ ~stage@integration:setup ]
ci-test-batch-1:
requires: [ ci-deploy ]
ci-test-batch-2:
requires: [ ci-deploy ]
ci-certify:
requires: [ ci-test-batch-1, ci-test-batch-2 ]
overlapping-non-stage-job-at-end-1:
requires: [ ci-test-batch-1 ] …
```
=> fix(3098): Workflow graph - Non stage jobs overlap into the stage

app/utils/graph-tools.js, tests/unit/utils/graph-tools-test.js
Changes made in https://github.com/screwdriver-cd/ui/pull/1045 introduced a regression due to which mini workflow graph are not rendered in the event card as shown below
Add check to skip the logic to assign position to stage when stages is empty
https://github.com/screwdriver-cd/screwdriver/issues/3098
=> fix(3098): Mini workflow in the event card is not rendered when there are stages

ember-cli-build.js, package-lock.json, package.json
Switch to using `sass-embedded` as it is more performant than `sass`.
Provide some additional performance improvements around stylesheet compilation.  This is one step in a migration plan to use Glimmer components.
=> fix: Use Sass-embedded

app/components/pipeline-graph-nav/styles.scss, app/components/pipeline-graph-nav/template.hbs, app/components/pipeline-header/styles.scss, tests/integration/components/pipeline-graph-nav/component-test.js
On a Mac PC, if you set the scrollbars to always visible in the appearance settings, the commit message and branches are not visible by the scrollbars.
One of the causes is that the display position is lowered by `<br>`.
In addition, the list window of other pipelines in the same repository, which is displayed from the branch button, has no scrolling set up.
Therefore, it occupies the edge of the screen when there is a pipeline with a long branch name or a large number of pipelines in the same repository, and continues further off the screen.
Therefore, fix it so that they are visible and correct.
Before
After
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make …
=> fix: Display commit and branch when scrollbar is always displayed

app/components/pipeline-graph-nav/styles.scss, app/components/pipeline-header/styles.scss
Additional fix from #1056 
Scrollbar is always displayed even if the size does not cause scrolling, regardless of the Mac settings.
Especially for short Branch names, commit messages, etc.
(In the Mac settings, you can switch between always displaying the scroller only when the size requires scrolling, and only displaying the scroller when scrolling.)
Do not show scrollbars if you do not need scrolling apart from the Mac settings.
Mainly fixed the following
- Pipeline Transition Button
- Overall graph-nav
Before
After
=> fix: fix scrollbar in pipeline screen

app/components/pipeline-event-row/template.hbs, tests/integration/components/pipeline-event-row/component-test.js
Show username who creates event on hover.
Add title element to creator who creates event.
screwdriver-cd/screwdriver#3123
=> fix(3123): Show username on event-row

app/components/pipeline-list-view/styles.scss
Job list view does not appear in Safari.
Fix the CSS to ensure users can see the job list view on Safari.
=> fix: job list view does not appear in Safari browser

app/components/pipeline-parameterized-build/component.js, app/utils/pipeline/parameters.js, tests/unit/utils/pipeline/parameters-test.js
Parameters require a bit of data massaging to be used in the UI.  With the new UI work, this logic should be extracted to a utility class to be shared across the different UI components.
Refactor shared code into a utility for use in the new UI.  Also adds in missing tests around the existing logic.
=> fix: extract parameter normalization logic to utility

app/components/validator-pipeline/template.hbs, app/components/validator-results/component.js, app/components/validator-results/template.hbs, app/helpers/is-array.js, app/shuttle/service.js, tests/integration/components/validator-results/component-test.js, tests/integration/helpers/is-array-test.js
Cache and subscribe configs are missing from validator.
This PR is to add those configs into validator. 
https://github.com/screwdriver-cd/screwdriver/issues/3114
=> fix(3114): Add cache and subscribe config into validator

app/components/pipeline/parameters/selectable/component.js, app/components/pipeline/parameters/selectable/template.hbs, tests/integration/components/pipeline/parameters/selectable/component-test.js
Parameters that are an array of values use the Ember Power Select component for rendering.  The parameter can be manually overridden to a value not specified in the supplied array.  This new component is a light wrapper around the Ember Power Select component and provides hooks so that actions and values can be passed up to a parent component.
Create a glimmer component for array parameters.  This component allows us to build out a full set of job/pipeline parameters in a more composable fashion while making the handlebars template more legible.
=> feat: new power select component for parameters

app/templates/job/template-usage/template.hbs
Template name on the usage page is wrong.
https://cd.screwdriver.cd/templates/job/sd/dind/2.0.23/usage
Fix template name to `<namespace>/<name>` from `<name>/<namespace>`
=> fix: template name on the usage page

app/components/pipeline/parameters/component.js, app/components/pipeline/parameters/styles.scss, app/components/pipeline/parameters/template.hbs, app/utils/pipeline/parameters.js, tests/integration/components/pipeline/parameters/component-test.js, tests/unit/utils/pipeline/parameters-test.js
#1065 added a new Glimmer component that wraps Ember Power Select for the use with pipeline/job parameters.  This new Glimmer component wraps up all pipeline/job parameters into a single entity that has some styles applied and some basic user interactions.  Conceptually, users will interact with this component and modify parameters and any changes to these parameters are made available to a parent component via the `@onUpdateParameters` argument.
Provide a new Glimmer component that is compatible with the new UI.  There are some minor CSS changes to what exists in the old UI, but it's largely the same.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this …
=> feat: New pipeline parameters component

app/components/pipeline/parameters/styles.scss, app/components/pipeline/parameters/template.hbs, app/components/pipeline/styles.scss, tests/integration/components/pipeline/parameters/component-test.js
#1068 had missed an existing feature where default values are noted by an icon.  This adds that functionality back in.  The default value is shown when the icon is moused-over.
Add in icon with hover over to indicate that the parameter has a default value that is different that the current value in the text input
=> fix: Default parameter icon

app/components/build-banner/component.js
On the PR build details screen, you can navigate to other builds from the `COMMIT` drop-down.
Unnecessary notifications are made when the status of the build being displayed is different from the status of the build to which the user is transitioning.
Fix so that notifications are not made when transitioning from the `COMMIT` drop-down to another build.
=> fix: Avoid extra notifications when transitioning to other builds

app/components/pipeline/parameters/component.js, app/components/pipeline/parameters/util.js, tests/integration/components/pipeline/parameters/component-test.js, tests/unit/components/pipeline/parameters/util-test.js
The API consumes parameters in a concise form.  Through the various layers of UI components, the API responses are massaged into a shape that the UI can use.  In reverse, when the UI needs to send parameters back to the API, the parameters need to get massaged back into a shape that the API expects.  The ownership of this massaging is now part of the `PipelineParametersComponent`.
Moves ownership of returning parameters in a form that can be used by the API endpoint to live with the `PipelineParametersComponent`.
=> fix: Converts parameters into a format ready for API use

app/v2/pipeline/controller.js, app/v2/pipeline/secrets/controller.js, app/v2/pipeline/secrets/route.js, app/v2/pipeline/secrets/template.hbs, app/v2/pipeline/styles.scss, app/v2/pipeline/template.hbs
Add `secrets` route to v2.
Screenshot:
=> feat: add v2 secrets route

app/components/pipeline/modal/confirm-action/component.js, app/components/pipeline/modal/confirm-action/styles.scss, app/components/pipeline/modal/confirm-action/template.hbs, app/components/pipeline/modal/confirm-action/util.js, app/components/pipeline/styles.scss, app/styles/app.scss, app/styles/bootstrap-modal.scss, tests/integration/components/pipeline/modal/confirm-action/component-test.js, tests/unit/components/pipeline/modal/confirm-action/util-test.js
New UI for the modal to confirm start/restarting of a job from the workflow graph.
As part of the new UI work, this provides a new modal that is a Glimmer component and leverages the pipeline parameters component from #1068.
The new component also properly displays the desired action that is to be taken with the job (e.g., start or restarting a job)
=> feat: New confirm action modal UI

app/utils/pipeline/parameters.js, tests/unit/utils/pipeline/parameters-test.js
Fixes dereference issue where there are no parameter groups to expand.
#1066 refactored the parameter logic into a utility class, but there was an issue with cases around situations without a parameter group to expand (i.e., there is no job node provided to start the pipeline from and there are also no pipeline parameters configured).  This fix re-introduces the original length check to ensure that the `isOpen` field is properly set when there is a parameter group that needs to be expanded.
=> fix: case where there are no parameter groups to expand

app/v2/pipeline/events/index/template.hbs, app/v2/pipeline/events/show/template.hbs, app/v2/pipeline/events/styles.scss, app/v2/pipeline/events/template.hbs, app/v2/pipeline/styles.scss, app/v2/pipeline/template.hbs
Cleans up the templates and CSS for the new V2 pipeline UI.
Refactor the templates and CSS for the V2 pipeline UI.  Now that more of the subroutes for a pipeline are in place, we should clean up the templates and CSS so that the respective routes and templates components live closer their actual routes.
=> fix: Clean up the new v2 layout

app/v2/pipeline/secrets/route.js
Refactors the new v2 pipeline secrets route to not use ember data.  Also moves the logic for checking if the user is a guest to the `beforeModel` method since it does not require any model data.
The new v2 UI needs to move off of using ember data due to performance reasons for the events route.  The secrets route is currently using ember data to resolve various pieces of data which will not be available as the parent routes will not be using the resolved ember data model for those objects.  As such, the data that is needed for this route will now be directly fetched from the API endpoints.  The controller was intentionally not updated in this PR as it appears that it currently non-functional anyway.
I confirm that this contribution is made under the terms of the license found in the root …
=> fix: Refactor pipeline secrets to not use ember data

app/v2/pipeline/route.js, app/v2/pipeline/template.hbs
The new UI needs to not rely on ember data model for pipeline data.
Refactors the route to not use ember data to resolve the pipeline model; instead, the API object returned is used.  The existing pipeline header component expects to use the ember data model for pipeline, as such it is temporarily removed and will be replaced with a new glimmer component in a follow up pull request.
=> fix: Refactor to no use ember data for pipeline data

app/styles/screwdriver-button.scss
Create a style mixin for bootstrap buttons so that we can incrementally adopt a consistent standard on button styles on the new UI.
Setting the primary and outline button styles based on bootstrap ember buttons (i.e., `BsButton` components).
Primary button:
Primary button hover state:
Primary button as outline style (note that the button background color is actually transparent hence the slight grey color in the attached screenshot):
Primary button as outline hover state:
=> feat: Screwdriver style mixin for Bootstrap buttons

app/components/secret-view/component.js, app/components/token-view/component.js, app/pipeline/service.js, app/shuttle/service.js, app/v2/pipeline/options/controller.js, app/v2/pipeline/options/route.js, app/v2/pipeline/options/template.hbs, tests/unit/pipeline/service-test.js
1) Add options to v2 route
2) Use ember glimmer newer syntax 
3) Try using without ember data, after PR https://github.com/screwdriver-cd/ui/pull/1081/files
=> feat: add options to v2 route

app/components/collection/modal/add-to-collection/component.js, app/components/collection/modal/add-to-collection/styles.scss, app/components/collection/modal/add-to-collection/template.hbs, app/components/collection/modal/add-to-collection/util.js, app/components/collection/styles.scss, app/components/styles.scss, tests/integration/components/collection/modal/add-to-collection/component-test.js, tests/unit/components/collection/modal/add-to-collection/util-test.js
Provides a new modal to add a pipeline to a collection or multiple collections as part of the new UI changes.  This modal provides an improved UX as users can:
1. Create a new collection with the pipeline added to the collection in the modal
2. Add the pipeline to multiple pipelines at once
3. Do 1 and 2 from above in the same operation
Create a new modal that allows users to add a pipeline to collections.  Collections that already contain the pipeline are not displayed in the modal.
Modal when there are no existing collections for the user
Modal when the user has collections already created.
Modal displaying an error
Modal displaying multiple errors (by multiple errors, this means that a new collection was desired to be created and the user also wanted to add the pipeline to some …
=> feat: Modal for adding a pipeline to a collection

app/components/pipeline-options/component.js, app/components/pipeline-options/styles.scss, app/components/pipeline-options/template.hbs, tests/acceptance/pipeline-options-test.js, tests/integration/components/pipeline-options/component-test.js
Allows users to easily view pipeline admins.
- Display Admins in the Pipeline on the Options page.
- Click `more` to expand.
- If there is no enabled admin.
=> feat: Display admins on the pipeline page

app/styles/bootstrap-modal.scss
The new UI is making more uses of modals, as such it would be nice to have a more expansive set of styles already pre-configured.
Expands the set of styles already configured for a modal in the new UI.
=> fix: Expand default modal styles

app/components/pipeline/modal/styles.scss, app/components/pipeline/modal/toggle-job/component.js, app/components/pipeline/modal/toggle-job/styles.scss, app/components/pipeline/modal/toggle-job/template.hbs, app/components/pipeline/styles.scss, tests/integration/components/pipeline/modal/toggle-job/component-test.js
#1088 started unifying the new UI modal look and feel.  With those changes we can update the newly created modals to use that style.
Updates the modal to fit into the new look and feel of the new UI.  Additionally, fixes a bug with the submit action not triggering the correct API action.
=> fix: Use unified modal style for toggle job modal

app/templates/pipeline/detail/controller.js
Would be nice to show cache, subscribe, stages, workflowGraph for pipeline template detail page.
This PR fetches missing info so it can be displayed on pipeline template detail page.
NA
=> fix: Fetch cache, subscribe, stages, workflowGraph for pipeline template detail page

app/components/pipeline-events/component.js, app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs, app/components/workflow-graph-d3/component.js, app/components/workflow-graph-d3/styles.scss, app/components/workflow-stage-actions-menu/component.js, app/components/workflow-stage-actions-menu/styles.scss, app/components/workflow-stage-actions-menu/template.hbs, app/utils/graph-tools.js, app/utils/pipeline-workflow.js, app/utils/pipeline/graph/d3-graph-util.js, tests/integration/components/pipeline-workflow/component-test.js, tests/integration/components/workflow-graph-d3/component-test.js, tests/integration/components/workflow-stage-actions-menu/component-test.js, tests/unit/utils/graph-tools-test.js, tests/unit/utils/pipeline-workflow-test.js
When a stage is detached, there is no option in the UI to start execution of that stage.
Add a menu at stage level in the workflow, which shows an action to start the event from that stage.
https://github.com/screwdriver-cd/screwdriver/issues/3112
=> fix(3112): Start/restart an event from a stage

app/router.js, app/v2/pipeline/build/route.js, app/v2/pipeline/build/template.hbs, tests/unit/v2/pipeline/build/route-test.js
The new v2 UI for tooltips of the workflow graph needs to provide a link to a build.
Adds in a stub route so that the graph tooltip component can reference the build route.
=> feat: Add stub route for v2 builds

app/v2/pipeline/styles.scss, app/v2/pipeline/template.hbs
The `pipeline-page` class is currently used at a higher level in the DOM tree.  While the `pipeline-page` class doesn't apply any particular styles at the moment, having it used further down the DOM tree may cause styling issues further down the road.
Change the class being used to one that is more specific and contains the actual styles needed for the element.
=> fix: Fix class collision

app/components/collection/modal/add-to-collection/component.js, app/components/collection/modal/add-to-collection/template.hbs, tests/integration/components/collection/modal/add-to-collection/component-test.js
When adding a pipeline to a collection in the new UI modal, messaging to the user about the success of the operation should be displayed to the user for a better user experience.
Adds in messaging for the success of the operation just performed by the user.
=> fix: Adds success messaging for add to collection modal

app/components/pipeline/modal/confirm-action/component.js, app/components/pipeline/modal/confirm-action/styles.scss, app/components/pipeline/modal/confirm-action/template.hbs, app/components/pipeline/modal/styles.scss, app/components/pipeline/styles.scss, tests/integration/components/pipeline/modal/confirm-action/component-test.js
The confirm action modal should be unified to the same style and structure introduced in #1088 
Unifies the new confirm action modal to the new v2 UI.
=> fix: Updates confirm action modal to latest UI

app/components/pipeline/modal/stop-build/component.js, app/components/pipeline/modal/stop-build/template.hbs, tests/integration/components/pipeline/modal/stop-build/component-test.js
The new UI for tooltips needs to allow users to abort a running build.
Adds a new UI modal component to stop a running build.
New modal:
Showing notification that the action was successful:
=> feat: New modal component to stop a running build

app/utils/pipeline/graph/tooltip.js, package-lock.json, package.json, tests/unit/utils/pipeline/graph/tooltip-test.js
The new UI does not use ember data and requires extracting tooltip data from the respective API response data.  A new tooltip utility class makes this metadata extraction possible.
Provide a testable utility for extracting tooltip metadata.
=> feat: Utility for generating tooltip metadata

app/components/info-message/component.js, app/components/info-message/template.hbs
The `InfoMessage` component is a wrapper around the bootstrap alert component which has a configuration for allowing the alert to be dismissible.  The `InfoMessage` component doesn't expose this configuration; thus, all instances are by default dismissible.
Expose the dismissible option so that the `InfoMessage` component can be configured to be dismissible or not.
=> fix: Add dismissible configuration

app/components/pipeline/modal/confirm-action/template.hbs, app/components/pipeline/modal/stop-build/template.hbs, app/components/pipeline/modal/toggle-job/template.hbs
The new UI uses modals and the `InfoMessage` component, but having the `InfoMessage` component be dismissible is a little awkward.
Make the `InfoMessage` component that appears in the new UI modals to be non-dismissible.
Requires #1104
=> fix: Non-dismissible modal messages

app/v2/pipeline/events/route.js, app/v2/pipeline/events/show/route.js, app/v2/pipeline/events/show/template.hbs, app/v2/pipeline/events/template.hbs, app/v2/pipeline/route.js
The API performance improvements that we want to do is currently hinged on not using ember data and using the APIs directly, as such we need to refactor the new v2 pipeline event routes to not rely on the ember data models.
Refactors the v2 pipeline events routes to not rely on ember data models.  There are components for the event cards that still need to be refactored, so in the interim those components have been removed from the template.
=> fix: Refactor routes to not use ember data

app/templates/pipeline/detail/controller.js
The workflow graph value init [here](https://github.com/screwdriver-cd/ui/blob/6202078d8216a6c89dd8abd8f5377fe993f9a6e3/app/templates/pipeline/detail/controller.js#L23-L26) overwrites the value from [the config of selected version](https://github.com/screwdriver-cd/ui/blob/6202078d8216a6c89dd8abd8f5377fe993f9a6e3/app/templates/pipeline/detail/controller.js#L74-L78) 
The default value of workflow graph which is 
```
workflowGraph = {
nodes: [],
edges: []
};
```
should be used only when the selected version is missing the workflow graph config. 
=> fix: moved default workflow graph for pipeline template

app/utils/pipeline/event.js, tests/unit/utils/pipeline/event-test.js
Creates a new utility function that checks whether an event has was skipped due to having the `skip ci` or `ci skip` text in the commit.
The new UI needs to determine if an event was skipped and this utility function extracts that logic out so that it can be used by the new workflow graph.
=> fix: Util to check if an event was skipped

app/components/pipeline/workflow/graph/component.js, app/components/pipeline/workflow/graph/styles.scss, app/components/pipeline/workflow/graph/template.hbs, app/components/pipeline/workflow/styles.scss, tests/integration/components/pipeline/workflow/graph/component-test.js
New glimmer component for the V2 workflow graph
Creates a new glimmer component and associated stylesheet for the workflow graph.  The primary difference between the new component and the existing component is that any logic around creating and massaging data related to the workflow graph is moved up a layer and the new component is effectively a dumb display layer.
=> feat: New workflow graph component

app/components/pipeline/nav/styles.scss, app/components/pipeline/nav/template.hbs, app/components/pipeline/styles.scss, app/components/pipeline/workflow/tooltip/component.js, app/components/pipeline/workflow/tooltip/styles.scss, app/components/pipeline/workflow/tooltip/template.hbs, app/v2/pipeline/events/show/controller.js, app/v2/pipeline/events/show/template.hbs, app/v2/pipeline/events/show/util.js, app/v2/pipeline/events/styles.scss, app/v2/pipeline/styles.scss, tests/unit/v2/pipeline/events/show/controller-test.js, tests/unit/v2/pipeline/events/show/util-test.js
Integrates the new workflow graph glimmer component into the v2 event route.
Wraps up the piping for allowing the workflow graph to be displayed on the page.  Some additional clean up around the CSS has been done as well as removing some unused code. 
=> fix: Integrates the workflow graph into the v2 route

app/components/pipeline/modal/confirm-action/util.js, app/components/pipeline/workflow/graph/component.js, app/components/pipeline/workflow/graph/styles.scss, app/components/pipeline/workflow/tooltip/stage/component.js, app/components/pipeline/workflow/tooltip/stage/template.hbs, app/utils/pipeline/graph/d3-graph-util.js, app/v2/pipeline/events/show/controller.js, app/v2/pipeline/events/show/template.hbs, tests/integration/components/pipeline/workflow/tooltip/stage/component-test.js
The new UI is missing the tooltip for starting/restarting a stage from the workflow graph.
Adds in the tooltip for starting/restarting a stage from the workflow graph.  Additional logic has been added to ensure that stages that can not be triggered indicate that to the user.
A stage that can be restarted:
A stage that can not be started:
=> fix: Stage tooltip

app/components/pipeline/workflow/graph/component.js, app/components/pipeline/workflow/tooltip/component.js, app/v2/pipeline/events/show/controller.js
Sets the tooltip position to always be anchored to the graph node's midpoint.
The tooltip position is determined by the mouse position when the user clicks on a graph node.  To provide a more static and consistent position for the tooltip, the graph node's actual position is now used to determine the tooltip position rather than the mouse's coordinates.
=> fix: Fixes the tooltip position

app/components/pipeline-parameterized-build/styles.scss, app/components/pipeline-parameterized-build/template.hbs
We can't check what build parameter is filled when long value selected.
Long build parameters are
- invisible when mouse over
- omitted at the select box
Stretch the width of blue background color to show white letters.
Show the selected value when hovering select box.
=> fix: make long build parameters confirmable

app/components/workflow-tooltip/component.js, app/components/workflow-tooltip/template.hbs, tests/integration/components/workflow-tooltip/component-test.js
Start and restart buttons are not shown for stage jobs
Unhide start and restart buttons for stage jobs
https://github.com/screwdriver-cd/screwdriver/issues/3143
=> feat(3143): Unhide start and restart buttons for all stage jobs

app/components/pipeline-list-view/template.hbs, tests/integration/components/pipeline-list-view/component-test.js
The job list view only displays up to 100 jobs.
Because of this, some jobs will not be displayed in a pipeline with more than 100 jobs.
All jobs are displayed in the job list view even if the pipeline has more than 100 jobs.
https://github.com/screwdriver-cd/screwdriver/issues/3167
=> fix(3143): show all jobs in the job list view

app/components/pipeline/modal/confirm-action/component.js, app/components/pipeline/modal/confirm-action/util.js, tests/unit/components/pipeline/modal/confirm-action/util-test.js
In the new UI, there is a bug where the modal to restart a job does not correctly display the parameters when only job level parameters exist.
Fixes the aforementioned bug.  Additionally cleans up the constructor to remove an unnecessary function call that was not providing any actual benefit.
=> fix: Parameter bug for pipelines where only job level parameters exist

tests/integration/components/pipeline-list-view/component-test.js
Fix #1118 
When testing a large number of jobs in a list view test, many logs are output for each job, so tests added with #1118 make the logs unnecessarily large.
In addition, the logs of other tests will not be visible.
The drawing test can be done with the existing test, so the test added with #1118 is deleted.
https://github.com/screwdriver-cd/screwdriver/issues/3167
#1118
=> fix(3143): fix job list view test

app/components/pipeline-list-view/component.js, app/components/pipeline-list-view/template.hbs
Continued from #1118, #1119
The upper limit on the number of drawings for a job has been practically removed with #1118.
However, the number of jobs that can be loaded at one time is limited to 200 by `ENV.APP.LIST_VIEW_PAGE_SIZE`
Moreover, scrolling on the job-list-view page should cause additional jobs to be loaded every 200, but this is not working properly.
All jobs can be displayed on job-list-view page.
- Scrolling to the bottom of the job-list-view table will cause additional jobs to be loaded correctly. (Like pipeline event list)
- Stop acquisition when the number of additional acquisitions is 0, so that job loading does not occur endlessly.
Operation after change with 500 jobs
https://github.com/user-attachments/assets/792f4525-0139-4ecc-ae13-812419aaf2ed
I confirm that this …
=> fix(3143): fix job list view to load jobs sequentially

app/components/pipeline-parameterized-build/styles.scss, app/components/pipeline-parameterized-build/template.hbs
Long parameter names are overflow and they are under parameters form.
As result, we can't see them.
Set `max-width` and omit parameter names if they are very long.
Show full names when hovering label.
=> fix: show long parameter names as title

app/components/pipeline-options/styles.scss, app/components/pipeline-options/template.hbs
- When click the more and collapse buttons on pipeline admins row, then force to move to page top.
- Pipeline delete row's layout is broken when the window width is small.
- Don't jump to page top when click pipeline admins buttons.
- Fix the pipeline delete row's classes
=> fix: pipeline options page

app/components/pipeline-list-view/component.js
The build parameters form does not appear when users too quickly click start button on the job list view page.
But after wait for a moment, the form appears correctly.
https://github.com/user-attachments/assets/69bf6831-1f97-459f-af53-6c07cabb95c5
Fix to show the parameter form even users start build quickly.
=> fix: display parameter form when click start button just after rendering

app/components/pipeline-parameterized-build/styles.scss, app/components/pipeline-parameterized-build/template.hbs
Follow up https://github.com/screwdriver-cd/ui/pull/1116 and https://github.com/screwdriver-cd/ui/pull/1123 .
- It renders 2 rows when a pipeline description is defined
- Select box option value is short then its width is also short
- Put parameter description icon and parameter name into one line
- Spread the width of short parameter selector option
=> fix: build parameter tooltip style when a value is short or a description is defined

app/components/pipeline/parameters/component.js, app/components/pipeline/parameters/selectable/styles.scss, app/components/pipeline/parameters/selectable/template.hbs, app/components/pipeline/parameters/styles.scss, app/components/pipeline/parameters/template.hbs, tests/integration/components/pipeline/parameters/component-test.js
The parameters of a pipeline may be long and cause text overflows in the UI.  Adds additional support for the UI to present a read only view.
1.  Adds functionality to the parameters to be read-only
2. Truncates any long text that causes overflows and provides a mouse over that the user can activate to display the full text
For a parameter group title that overflows:
For a parameter name that overflows:
For a parameter name that overflows:
=> fix: updates parameter component

app/components/pipeline/modal/stop-build/component.js, tests/integration/components/pipeline/modal/stop-build/component-test.js
The stop build modal already allows users to stop an individual build.  The V2 UI uses modals to prevent unintended actions by the user.
Add in the ability for the stop build modal to stop all builds for an event.
=> feat: Updates modal to support stopping all builds

app/styles/screwdriver-button.scss
Bootstrap buttons have a danger style that has no custom styling using the screwdriver color theme.
Adds in the danger styling for solid and outline buttons using screwdriver color theme.
=> feat: Add danger style for buttons

app/components/pipeline/modal/show-parameters/template.hbs, tests/integration/components/pipeline/modal/show-parameters/component-test.js
Event cards need a way to display to the user the parameters that were configured for the event.  As the event has already been triggered, the parameters should also be displayed as read-only values
New modal has updated title indicating that the parameters shown are the ones configured for the event:
Builds on top of the changes from #1124
=> feat: New modal to display parameters as readonly values

app/v2/pipeline/index/route.js
The v2 pipeline index route (`/v2/pipeline/`) is an intermediary route that effectively resolve to either the pipeline event route or the child pipeline route.  The route should not provide any model information.
Update and simplify the route so that it only processes the pipeline modal information to determine which landing page to direct the user to based on the pipeline model.
=> fix: Simplify and update route implementation

app/components/pipeline/workflow/graph/styles.scss
A job with a build that completed with a warning does not have a colored arrow pointing to the next job in the pipeline.
Add a color to the graph arrow to further differentiate the graph node from other nodes in the workflow
Currently:
Updated:
=> fix: Add warning color to graph arrow

app/components/pipeline-parameterized-build/styles.scss
The long build parameter is wrapped when its value contains line breakable characters (e.g. whitespace).
Add `nowrap` style to show as one line.
=> fix: long parameter is not nowrap

tests/integration/components/pipeline/nav/component-test.js
The v2 glimmer component for the pipeline nav is missing a test.  Although the component itself is about as simple as possible, it should still have a test file in the event that it gets more complicated in the future.
Add in missing test for the pipeline nav component.
=> fix: Add missing test for v2 pipeline nav component

tests/unit/v2/pipeline/events/show/controller-test.js
Found some typos in a couple of tests that don't clearly indicate what the test is attempting to check for.
Update test name to properly reflect what the test is checking.
=> fix: typo in test names

app/v2/pipeline/controller.js, app/v2/pipeline/template.hbs
The controller for the v2 pipeline route does not need a getter for the collections and pipeline since they are already part of the model and the template can reference those values directly.
Remove unnecessary getters in the controller and update the template to use the values directly.
=> fix: Simplify pipeline controller

app/components/validator-results/template.hbs
BREAKING CHANGE: Move workflowGraph out of config and keep it at the same level as config
Changes were made in https://github.com/screwdriver-cd/data-schema/pull/571 (and related PRs) and https://github.com/screwdriver-cd/ui/pull/1101 to store `workflowGraph` of pipeline template as part of the `config
Move `workflowGraph` out of `config` and keep it at the same level as `config`
https://github.com/screwdriver-cd/screwdriver/issues/3171
=> feat(3171): Move pipeline template workflowGraph out of config into a new field

app/templates/pipeline/detail/controller.js
Workflow graph has been moved out of pipeline template `config`. Workflow graph is no longer getting rendered in the pipeline template detail view.
Look up for workflow directly on the pipeline template
https://github.com/screwdriver-cd/screwdriver/issues/3171
=> fix(3171): workflow graph is not rendering in pipeline template detail page

package.json
There is a major version upgrade of `screwdriver-data-schema` to [24.0.0](https://github.com/screwdriver-cd/data-schema/releases/tag/v24.0.0). 
This PR is to bump the dependency to the latest version. 
https://github.com/screwdriver-cd/screwdriver/issues/3171
=> fix: bump data-schema to 24.0.0

app/utils/graph-tools.js, app/utils/pipeline/graph/d3-graph-util.js, tests/unit/utils/graph-tools-test.js, tests/unit/utils/pipeline/graph/d3-graph-util-test.js
When the job has longer `displayName` than its name, the job name is omitted on the workflow graph even `Display Name Length` has enough value.
```yaml
jobs:
test:
image: node:18
requires: [ ~commit, ~pr ]
steps:
- test: echo "foo"
annotations:
screwdriver.cd/displayName: "very-long-long-long-long-name"
```
Calculate the maximum job name length correctly including `displayName`.
=> fix: job name is omitted on the workflow graph when its displayName is shorter than its name

app/utils/pipeline/graph/d3-graph-util.js, tests/integration/components/workflow-graph-d3/component-test.js, tests/unit/utils/pipeline/graph/d3-graph-util-test.js
Make it easier to know what pipeline is assign as upstream remote trigger.
https://github.com/screwdriver-cd/screwdriver/issues/3193
Show the upstream remote trigger pipeline's name on workflow graph as title.
The format is `org/repo#branch:job` and this value is stored in remote trigger node's `displayName` property. (https://github.com/screwdriver-cd/models/pull/628)
We can display pipeline name instead of `~sd@123:main` form, but it makes workflow graph longer because repository name can be too longer than job name.
https://github.com/screwdriver-cd/screwdriver/issues/3193
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its …
=> feat(3193): Show remote trigger's displayName as title [1]

app/components/pipeline/modal/stop-build/component.js
The existing text  doesn't fully capture the fact that multiple builds may have been stopped.
Update the modal text to better indicate to the user that all builds in a particular event have stopped.
=> fix: Update stop modal text

app/styles/screwdriver-button.scss
The styling for the `btn-outline-danger` got messed up previously and the style sheet needs to have the braces fixed to properly target the class.
Fix the style sheet so that the `btn-outline-danger` class is at the correct level.
=> fix: Fix button styles

app/components/pipeline/modal/confirm-action/template.hbs, app/components/pipeline/workflow/tooltip/stage/template.hbs, tests/integration/components/pipeline/modal/confirm-action/component-test.js
The modal that handles restarting a job does not handle stages particularly well at the moment.  When a start needs to be restarted, the stage name should be displayed to the user instead of the job name.
Update the modal to display the stage name instead of the job name when the user wants to restart from a stage.
=> fix: Update restart modal to better handle stages

app/utils/pipeline/modal/request.js, tests/unit/utils/pipeline/modal/request-test.js
The utility that is used to generate POST body data for starting a job needs to better handle arbitrary events.  Users are allowed to create a new event from any job in the pipeline and this utility needs to be modified to allow for such instances.
Update the request body utility to allow for events to be started from any job, not just `~commit`
=> fix: Request body utility to handle arbitrary events

app/components/pipeline/styles.scss, app/components/pipeline/tab/styles.scss, app/components/pipeline/tab/template.hbs, app/styles/variables.scss, app/v2/pipeline/events/styles.scss, app/v2/pipeline/events/template.hbs, tests/integration/components/pipeline/tab/component-test.js
The navigation tab for the v2 pipeline routes can should be extracted into a stand alone glimmer component.
Refactor the pipeline navigation tabs into a glimmer component for better reusability and testing
=> feat: V2 pipeline tab component

app/components/pipeline/modal/start-event/styles.scss, app/components/pipeline/modal/start-event/template.hbs, tests/integration/components/pipeline/modal/start-event/component-test.js
The start event modal is used in multiple places.  There may be some additional messaging that needs to happen to better alert the user to pay attention to certain specifics of their pipeline configuration.
Update the start event modal to allow for optional messaging.
=> fix: Update start modal to allow for optional messaging

app/components/pipeline/jobs/table/dataReloader.js, tests/unit/components/pipeline/jobs/table/dataReloader-test.js
The new v2 jobs UI should automatically refresh data.  For pipelines with lots of jobs, it is possible that many jobs are not actively being displayed in the UI.  This utility provides the functionality to refresh the necessary data that is only being displayed in the UI.
Creates a utility that automatically refreshes the necessary data to render the v2 jobs UI.
=> feat: Data refreshing utility for jobs table

app/components/pipeline/workflow/tooltip/template.hbs
The new v2 UI for the build details page isn't available yet.  The tooltip should instead point back to the v1 UI.
Update the tooltip to link the user to the v1 UI.
=> fix: Update tooltip route to v1 UI

app/components/pipeline/jobs/table/cell/history/component.js, app/components/pipeline/jobs/table/cell/history/styles.scss, app/components/pipeline/jobs/table/cell/history/template.hbs, tests/integration/components/pipeline/jobs/table/cell/history/component-test.js
The new jobs UI makes use of custom components for each cell in the table. This creates a new component for handling the  build history for a job.
=> feat: Table cell for job build history

app/components/pipeline/jobs/table/cell/duration/component.js, app/components/pipeline/jobs/table/cell/duration/template.hbs, tests/integration/components/pipeline/jobs/table/cell/duration/component-test.js
The new jobs UI makes use of custom components for each cell in the table. This creates a new component for handling the build duration.  If a build is running, the component will automatically increment the build duration every second for additional user feedback that there is a build in progress.
=> feat: Table cell for build duration

app/components/pipeline/jobs/table/cell/start-time/component.js, app/components/pipeline/jobs/table/cell/start-time/template.hbs, tests/integration/components/pipeline/jobs/table/cell/start-time/component-test.js
The new jobs UI makes use of custom components for each cell in the table. This creates a new component for handling the start time of the latest build for a job.
=> feat: Table cell for build start time

app/components/pipeline/jobs/table/cell/coverage/component.js, app/components/pipeline/jobs/table/cell/coverage/template.hbs, tests/integration/components/pipeline/jobs/table/cell/coverage/component-test.js
The new jobs UI makes use of custom components for each cell in the table. This creates a new component for handling the code coverage of the latest build for a job.
=> feat: Table cell for test coverage information

app/components/pipeline/jobs/table/cell/metrics/component.js, app/components/pipeline/jobs/table/cell/metrics/styles.scss, app/components/pipeline/jobs/table/cell/metrics/template.hbs, tests/integration/components/pipeline/jobs/table/cell/metrics/component-test.js
The new jobs UI makes use of custom components for each cell in the table. This creates a new component for handling the job metrics.  For now, the metrics link will take the user back to the v1 UI as there is no v2 UI available yet.
=> feat: Table cell for build metrics

app/components/pipeline/jobs/table/cell/actions/component.js, app/components/pipeline/jobs/table/cell/actions/styles.scss, app/components/pipeline/jobs/table/cell/actions/template.hbs, app/components/pipeline/jobs/table/cell/actions/util.js, tests/integration/components/pipeline/jobs/table/cell/actions/component-test.js, tests/unit/components/pipeline/jobs/table/cell/action/util-test.js
The new jobs UI makes use of custom components for each cell in the table. This creates a new component for handling the actions that a user can take for a job.
=> feat: Table cell for actions

app/components/pipeline/jobs/table/cell/job/component.js, app/components/pipeline/jobs/table/cell/job/styles.scss, app/components/pipeline/jobs/table/cell/job/template.hbs, app/components/pipeline/jobs/table/cell/job/util.js, tests/integration/components/pipeline/jobs/table/cell/job/component-test.js, tests/unit/components/pipeline/jobs/table/cell/job/util-test.js
The new jobs UI makes use of custom components for each cell in the table.  This creates a new component for handling the job name and the build status.
Create a glimmer component for the jobs.  Screenshot will be captured in the linked PR
=> feat: Table cell component for jobs

app/components/pipeline/jobs/styles.scss, app/components/pipeline/jobs/table/component.js, app/components/pipeline/jobs/table/styles.scss, app/components/pipeline/jobs/table/template.hbs, app/components/pipeline/styles.scss
The new v2 UI for the jobs route.
Creates the new v2 UI glimmer component which is a customized table using `ember-models-table` as the base.  This table also incorporates automatic data refreshing to keep all the table data up to date.
Incorporates the glimmer components for each cell:
#1161 for the cells in the `JOB` column
#1162 for the cells in the `HISTORY` column 
#1163 for the cells in the `DURATION` column
#1164 for the cells in the `START TIME` column
#1165 for the cells in the `COVERAGE` column
#1166 for the cells in the `METRICS` column
#1169 for the cells in the `ACTIONS` column
The background refresh logic is from #1170
I confirm that this contribution is made under the terms of the license found in the root directory …
=> feat: v2 jobs table glimmer component

app/v2/pipeline/controller.js, app/v2/pipeline/styles.scss, app/v2/pipeline/template.hbs
The v2 pipeline route template can be updated to be updated to be a bit less verbose
Uses ids on elements that should only exist once to provide more clear CSS targeting.  Also removes the `grid` class as it is not needed.
=> fix: Clean up styles and templates

app/components/pipeline/jobs/table/styles.scss, app/components/pipeline/jobs/table/template.hbs, app/components/pipeline/tab/styles.scss, app/v2/pipeline/jobs/styles.scss
Adds some overflow behavior to the v2 jobs table for instances where the window can not display all of the rows.
Adds overflow behavior to the v2 jobs table.  Also fixes a slight overflow issue with the navigation tabs.
Screenshot showing window not able to display all rows.  The table rows themselves are now vertically scrollable so that the search bar and navigation footer do not leave the UI and will always be accessible to the user. 
=> fix: Better overflow behavior

app/components/pipeline/workflow/util.js, app/v2/pipeline/events/show/controller.js, tests/unit/components/pipeline/workflow/util-test.js
Starting some refactoring work around the main v2 event landing page so that the page can support background data fetching.  This utility should therefore get moved to the workflow component directory as a new component will be created to replace what exists on the controller for the route.
Moves the utility to the workflow component directory.
=> fix: Refactor graph tooltips location

app/components/artifact-preview/component.js, app/components/artifact-preview/template.hbs
Would be nice if users could download all artifacts as zip file.
This PR adds button to access new endpoint `GET /builds/{id}/artifacts`.
Related to https://github.com/screwdriver-cd/screwdriver/pull/3199
=> fix: Add option to download all artifacts as zip file

app/components/artifact-preview/template.hbs
Would be nice if the title showed up when hovering on the download buttons.
This PR uses `title` instead of `@label`.
Related to https://github.com/screwdriver-cd/ui/pull/1179
=> fix: Use title instead of label for Download buttons

app/components/pipeline/workflow/graph/component.js, app/components/pipeline/workflow/graph/template.hbs, tests/integration/components/pipeline/workflow/graph/component-test.js
The glimmer component for the workflow graph used in the v2 redesign is missing support for updating when its arguments change.
Adds in the functionality for the component to update when the arguments change.
=> fix: Workflow graph component supports updating

app/components/pipeline/workflow/graph/component.js, app/utils/pipeline/event.js, tests/unit/utils/pipeline/event-test.js
The `isSkipped` logic fails to account for events that share the same commit that was initially skipped.
Fix `isSkipped` so that it correctly accounts for builds in an event.
=> fix: bug determining if an event is skipped

app/components/pipeline/workflow/graph/component.js, app/utils/pipeline/graph/d3-graph-util.js
Updating an existing graph should be only need to consist of updating the metadata on the build status of nodes and edges and then updating the classes on the existing SVG.
1. Refactor the job node in the graph so that the event handler is on the SVG `<g>` element
2. Refactor the child element of the SVG `<g>` element so that the text and title are siblings for easier targeting and updating
3. Add in a utility function that can update the graph edge on an existing SVG graph
4. Add in a utility function that can update the graph node on an existing SVG graph
5. Refactor the V2 graph component to properly update the existing SVG graph as necessary
I confirm that this contribution is made under the terms of the license found in the …
=> fix: Refactor graph updating

app/components/pipeline/event/card/util.js, tests/unit/components/pipeline/event/card/util-test.js
Update the utility functions for the v2 event card component.
Updates the utility functions for the v2 event card component for some additional improvements around dynamically updating data as needed.
1. Consolidate the `humanize-duration` configuration
2. Extracts logic to a new utility function `getFirstCreateTime`
3. Adds a new utility function `getRunningDurationText`
4. Adds extra null checking
=> fix: Update card component utilities

app/components/pipeline-event-row/component.js, app/components/pipeline-event-row/template.hbs
https://github.com/screwdriver-cd/models/pull/630 modified the API response to always return a default field.  This broke the previous assumption that minimum number of keys in the response object is 1.
Updates the minimum key length to match the updated API response so that the parameter parsing can be handled properly.  Also adjusts the spacing on the parameter colon.
=> Fix: parameters UI bug

app/components/pipeline-event-row/component.js, app/components/pipeline-workflow/component.js, app/utils/pipeline/parameters.js, tests/unit/utils/pipeline/parameters-test.js
https://github.com/screwdriver-cd/models/pull/630 modified the API response to always return a default field. This broke the previous assumption that minimum number of keys in the response object is 1.  
#1189 added in a fix for the change in the API object, however there are a few other places in the UI code that used the same logic and needs to be updated.
Add a new utility function that is less fragile to determine whether a parameter is a pipeline level parameter.  Updates all instances where determining if a parameter is a pipeline parameter is manually done.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright …
=> fix: Fix logic for determining parameter types

app/v2/pipeline/events/show/template.hbs
The pipeline page is getting a huge overhaul in the structure of the components.  The event card will also undergo a number of changes.  By removing the event card from the UI, the overhaul is more easily accomplished in isolated PRs.
Remove the existing event card component from the UI for ease of updating the entire UI structure for the pipeline event page.
=> fix: Remove event card from display

app/components/pipeline/workflow/graph/component.js, app/components/pipeline/workflow/graph/template.hbs, tests/integration/components/pipeline/workflow/graph/component-test.js
When the event cards are integrated into the UI, users will be clicking on the event cards and navigating to a different event within the pipeline event history.  As the page template is not changing, the graph component is not re-created with the new data; rather, it is updated with new arguments.  In order for the graph component to properly update due to the changing event argument, the update handler needs to account for the change in event and update the underlying graph SVG accordingly.
Updates the workflow graph component to properly update as arguments that necessitate a graph update change.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree …
=> feat: Graph updates when event argument changes

app/components/pipeline/nav/styles.scss
Consolidate colors to use the defined Screwdriver colors rather than have lots of one-off color values scattered throughout the styles.
Limit the use of arbitrary colors and leverage the Screwdriver colors template as much as possible.  There's some minor changes in the actual colors, but it still maintains the grey and blue colors for the different class states on the anchor tag.
=> fix: Update colors to use color template

app/components/pipeline/event/card/component.js, app/components/pipeline/event/card/template.hbs, tests/integration/components/pipeline/event/card/component-test.js
It is hard to differentiate the different event cards as there is no additional information displayed in the UI
Add a title attribute to the event card component.  This allows users to mouse over the event card and additional information about the event and event group are provided.
=> feat: Event card title

app/components/artifact-preview/component.js, app/components/artifact-preview/template.hbs, config/environment.js
It might be good to put the artifact directory download behind a feature flag.
This PR adds a feature flag for downloading artifact directories.
Related to https://github.com/screwdriver-cd/screwdriver/issues/3227
=> fix(3227): Add feature flag for download all artifacts

app/build/model.js, app/pipeline/build/controller.js, app/pipeline/build/template.hbs, package-lock.json, package.json, tests/acceptance/pipeline-builds-test.js, tests/mock/workflow-graph.js
For virtual jobs, builds are created but never executed. API marks status of such builds as "SUCCESS" when those are eligible for execution.
API also sets "Skipped execution of the virtual job" and "INFO" as `statusMessage` and `statusMessageType` respectively. 
In the UI, the build detail view shows that the was a failure in `sd-setup-init` step. This gives a false impression that the build got executed and the step failed.
**Before**
We need to make below changes in the build details view
1. Hide steps and logs section
2. All the status messages are displayed as a warning in the banner. Style the message based on the `statusMessageType`. In the case of virtual jobs, the message "Skipped execution of the virtual job" should be displayed as information.
**After** …
=> feat(3211): Build detail view - Hide steps and logs for virtual builds

app/components/artifact-preview/component.js, app/components/artifact-tree/component.js
Looks like a line was accidentally removed in previous PR: https://github.com/screwdriver-cd/ui/pull/1195/files#diff-394984a29f42868adf35cce2c06778edd92bbd617a870edf4cfcf178c0d65ebdL104
This PR fixes mistake and puts directory download behind feature flag.
Related to https://github.com/screwdriver-cd/screwdriver/issues/3227, https://github.com/screwdriver-cd/ui/pull/1195
=> fix(3227): Download directory should use feature flag

app/components/pipeline/event/card/component.js, app/components/pipeline/event/card/template.hbs, tests/integration/components/pipeline/event/card/component-test.js
Event cards need the ability to dynamically update.  The `WorkflowDataReloadService` handles background data fetches for the latest commit event and builds for events.  The event card injects the `WorkflowDataReloadService` and registers the event with the `WorkflowDataReloadService` for handling data refreshes.  Additionally, if an event is still running, the event card updates the build time so that users can see how long the event has been running.
Adds in the ability for event cards to dynamically update data that it is displaying.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution …
=> feat: Event card supports dynamic updating

app/components/artifact-preview/template.hbs
https://github.com/screwdriver-cd/ui/pull/1202 has a minor bug with the if-else conditions in the template which causes the download button to go missing
Fixes the missing download button
https://github.com/screwdriver-cd/screwdriver/issues/3227
=> Fix: fixes the missing download button

app/components/pipeline/event/card/component.js, app/components/pipeline/event/card/styles.scss, app/components/pipeline/event/card/template.hbs, app/components/pipeline/modal/event-group-history/component.js, app/components/pipeline/modal/event-group-history/styles.scss, app/components/pipeline/modal/event-group-history/template.hbs, app/components/pipeline/modal/styles.scss, package-lock.json, package.json, tests/integration/components/pipeline/event/card/component-test.js, tests/integration/components/pipeline/modal/event-group-history/component-test.js
Users should be able to view all events that make up a group.  In the V1 interface, there is an expandable option for displaying events, however the drawback of the V1 interface is that older events in the group are completely removed from the view and in certain aspects makes it difficult to really understand the order of events that have happened for the pipeline.
The V2 interface will instead keep all events in the event rail as they occur and have a button in within the event card that will open up a modal to display all events that make up an event group.  This will hopefully make it easier for users to navigate the full event history of a pipeline while providing the additional grouping information if they want to dive into the event history of an event group. 
Create a modal to …
=> feat: Event group modal

package-lock.json, package.json
Reverts screwdriver-cd/ui#1188
The PR pages are missing everything under the build banner and you cannot navigate away. Trying to see if reverting this change fixes it.
=> fix: Revert "build(deps-dev): bump webpack from 5.76.2 to 5.95.0"

package-lock.json
Reverts screwdriver-cd/ui#1186
The PR pages are missing everything under the build banner and you cannot navigate away. Trying to see if reverting this change fixes it.
=> fix: Revert "build(deps): bump cookie, express and socket.io"

app/job/model.js, app/pipeline/build/controller.js, tests/unit/job/model-test.js
Changes made in this PR https://github.com/screwdriver-cd/ui/pull/1201 relied on the `id` of workflow graph node to find a node corresponding to the job associated with the build.
But, it appears `id` for workflow graph nodes are not being set in case of PR event
Update the logic to find the workflow graph node by `name` instead of `id`.
https://github.com/screwdriver-cd/screwdriver/issues/3211
=> fix(3211): Find workflow graph node for a virtual build by job name

app/components/pipeline/modal/search-event/component.js, app/components/pipeline/modal/search-event/styles.scss, app/components/pipeline/modal/search-event/template.hbs, app/components/pipeline/modal/styles.scss, app/styles/screwdriver-input.scss, tests/integration/components/pipeline/modal/search-event/component-test.js
The v2 UI adds in a feature to search for an event by SHA.  To support the search feature, a new modal will be employed to provide the text input field and display of the results.  This modal will do dynamic searches so as valid characters are input into the text input field the results will be updated.  For invalid inputs, the text input field will change colors to provide immediate feedback.
The escape key is configured to allow clearing of the input field when an input has been provided.  If the input field is empty, the escape key will close the modal (which is the default behavior for all of the modals being used in the v2 UI).
Create a new modal to support event searching.
Basic modal that is presented to the user:
Valid input with search results:
Invalid input showing text color …
=> feat: Modal to search for an event

app/components/pipeline/event/card/template.hbs, tests/integration/components/pipeline/event/card/component-test.js
The event card for a running event has a button to abort the event.  With the event card being used in multiple different locations within the UI, the abort event button should be configurable to which instances actually allow the abort event action to be performed.
Make the abort event button configurable.  By default the button is not displayed, so UI components that allow the action need to explicitly set the argument.
=> feat: Make abort event button configurable

app/components/pipeline/workflow/event-rail/component.js, app/components/pipeline/workflow/event-rail/styles.scss, app/components/pipeline/workflow/event-rail/template.hbs, tests/integration/components/pipeline/workflow/event/rail/component-test.js
Creating a new Glimmer component to house all of the events and provide buttons for event search and starting a new event.
Creates a component for the event rail in the v2 UI
The screenshot below shows the first card being highlighted as the current event that has been selected and displayed on the UI.  Second card is a normal event card, while third event card shows the mouse over color.
=> Feat: Glimmer component for events rail

app/workflow-data-reload/service.js, tests/unit/workflow-data-reload/service-test.js
The workflow data service can use some updates to better support the new UI.
1. Fixes the event callback to always return the latest commit event as well (https://github.com/screwdriver-cd/ui/commit/dbf93fc814ee747d000054fcb08e2944d87b91bf)
2. Removes the builds cache clearing when the last callback for an event is removed.  This seems a bit counter-intuitive, but the event callback is only required when an event has not completed.  When an event is completed, the fetched builds should remain in the cache as the UI allows navigation between events and those events may have their build fetched already. (https://github.com/screwdriver-cd/ui/commit/b3419d1c5fbf021c03600f79776c68e5f7d14fbc)
3. Add a callback registration for `latest commit event`.  This is needed because a pipeline may not …
=> fix: Workflow data updates

app/components/pipeline/event/card/component.js, app/components/pipeline/event/card/template.hbs
Event cards need to allow users to click on them and the UI updated to display the details of that event.
Add ability to navigate to different events of the pipeline by clicking on an event card.
=> feat: Add navigation to event card

app/styles/screwdriver-button.scss
Hover states for the buttons that always present.  The disabled button state uses a lighter color and the hover state may be confusing as a result
Remove the hover state from buttons that are disabled.
=> fix: Update hover style for disabled buttons

app/components/pipeline/workflow/event-rail/component.js, app/components/pipeline/workflow/event-rail/template.hbs, tests/integration/components/pipeline/workflow/event/rail/component-test.js
When there are no events to display in the event rail, the search button can be disabled.
Disable search button when there are no events in the event rail.
=> feat: Disable search when no events are available

app/components/pipeline/workflow/component.js, app/components/pipeline/workflow/styles.scss, app/components/pipeline/workflow/template.hbs, tests/integration/components/pipeline/workflow/component-test.js
Having a glimmer component for the pipeline UI allows for more dynamic updates of the page, as well the ability to update the component as different arguments change.
Create a new component to handle the pipeline UI.  This component will provide better messaging to users with the state of the pipeline
**For a normal event:**
**For pipelines with no events:**
**For landing on an invalid event within the pipeline:**
=> feat: Glimmer component for pipeline workflow

app/workflow-data-reload/service.js
Before starting the data reloader for a given pipeline, the stop method is called to clear any stored state.  Part of the information cleared in the stop method is the pipeline id.
Set the pipeline id after `stop` returns
=> fix: bug where pipeline id gets cleared

app/components/pipeline/event/card/styles.scss
Event cards could use some help with visual separation as noted in https://github.com/screwdriver-cd/ui/pull/1205
Adds a card border to help visually separate cards when stacked in a list
=> fix: Add border around event cards

app/components/pipeline/workflow/component.js
When a pipeline has no events the pipeline page will monitor for a new commit event to occur on the pipeline.  When that event occurs, the page will update itself with the latest commit event's data.  The current implementation of this transition will update the displaying page's model, but is a bit more brittle as and changes in the model may now need to be made in two places.  By having the transition rely on the route to resolve the model, the page effectively does a hard reload which is less smooth than the existing implementation, but does become more resilient to changes to the model.
Use the route to resolve the model for the route transition.
I confirm that this contribution is made under the terms of the license found in …
=> fix: Use route to resolve model for transition

app/workflow-data-reload/buildsDataReloader.js, app/workflow-data-reload/dataReloader.js, app/workflow-data-reload/latestCommitEventReloader.js, tests/unit/workflow-data-reload/buildsDataReloader-test.js, tests/unit/workflow-data-reload/dataReloader-test.js, tests/unit/workflow-data-reload/latestCommitEventReloader-test.js
The workflow data reloading currently mixes both the latest commit event and builds together.  The latest commit event needs to be split off so that more components can receive updates from it.
Split the existing API fetches for latest commit event and builds into separate classes for better isolation.  The workflow data reloading will be refactored to use the new classes here to help address and fix some issues around event cards not being able to properly update the latest commit SHA.
=> feat: Isolate data reloading on an API level

app/instance-initializers/supplementary-config.js, nginx.conf
Feature flags for bulk download of Artifacts were added in #1202 and #1203.
Fix so that feature flags can be overridden by environment variables.
https://github.com/screwdriver-cd/screwdriver/issues/3227
=> fix(3227): Allow DOWNLOAD_ARTIFACT_DIR to be set in environment variables

app/workflow-data-reload/latestCommitEventReloader.js, app/workflow-data-reload/service.js, tests/unit/workflow-data-reload/dataReloader-test.js, tests/unit/workflow-data-reload/latestCommitEventReloader-test.js
The latest commit event should be available to be pulled from the cached response.
Exposes a getter for the latest commit event that has been cached.
=> Getter for latest commit event from response cache

app/workflow-data-reload/dataReloader.js, app/workflow-data-reload/latestCommitEventReloader.js, tests/unit/workflow-data-reload/dataReloader-test.js, tests/unit/workflow-data-reload/latestCommitEventReloader-test.js
There's a bug with the latest commit event refreshing both requiring a callback to be registered before making API calls and also making redundant API calls when only one is needed.
Fix a bug with the latest commit event data refresh.
=> fix: Fix bug with fetching latest commit event

app/components/pipeline/workflow/component.js
If the graph tooltips are open and a new event is selected from the event rail, the tooltips do not close.
Automatically close the graph tooltips when a new event is selected in the event rail.
=> fix: Tooltips not closing when selecting new events

app/components/pipeline/modal/confirm-action/component.js, app/components/pipeline/workflow/template.hbs, app/components/pipeline/workflow/tooltip/stage/template.hbs, app/components/pipeline/workflow/tooltip/template.hbs, tests/integration/components/pipeline/modal/confirm-action/component-test.js
The latest commit event response is now cached in the data reload service.  The `Confirm Action` modal can inject the service and get the cached value of the latest commit event directly.
Refactors the `Confirm Action` modal to use the cached latest commit event rather than having it passed in as a component argument.
=> fix: Use cached value of latest commit event

app/components/pipeline/workflow/component.js, app/v2/pipeline/events/index/route.js, app/v2/pipeline/events/show/route.js, app/v2/pipeline/events/show/template.hbs
The main events page should go to the latest event instead of the latest commit event.  Only for pipelines without any events will the latest commit event and the latest event be the same.  Additionally, when an invalid event has been entered, the events rail should anchor off of the latest event instead of the latest commit event.
Refactor the V2 event routes to use the latest event instead of the latest commit event.
=> Use latest event instead of latest commit event

app/components/pipeline/workflow/event-rail/component.js
The event rail should monitor for any new events when it has fetched the newest events for the pipeline.
Refactors the oldest event and newest event to be consistent.  Adds in monitoring for newer events when the event rail is at the most recent events.
=> feat: Event rail monitors latest event

app/components/pipeline-list-view/component.js
Sort by stage name is broken after https://github.com/screwdriver-cd/ui/pull/1242.
This PR fixes stage name sort in jobs list view.
Related to https://github.com/screwdriver-cd/screwdriver/issues/3197
=> fix(3197): Stage sort in jobs list view

app/components/pipeline/event/card/component.js, app/components/pipeline/event/card/styles.scss, app/components/pipeline/event/card/template.hbs, tests/integration/components/pipeline/event/card/component-test.js
The V2 event cards need some additional updates to properly support PR events.
- Make all anchor links in the event card open in a new window/tab
- Updates the event card component to include a PR event title and properly handle the highlighting of the card
The PR card title is added in between the build status and the commit SHA
=> feat: PR event card

app/components/pipeline/event/card/component.js
When clicking on the anchor links within the V2 event cards, the click event is propagated up to the event card when it does not need to.
Stop click event propagation when one of the anchor links within the event card is clicked.
=> fix: Fixes event propagation on event cards

app/v2/pipeline/events/show/route.js
The jobs API can filter out all of the PR jobs thereby reducing the total payload of the jobs API call.
Improve the jobs API fetch performance.
=> fix: Only fetch pipeline jobs

app/components/pipeline/workflow/event-rail/component.js, app/components/pipeline/workflow/event-rail/template.hbs, tests/integration/components/pipeline/workflow/event/rail/component-test.js
The start event button in the event rail is not needed for the PR page and should be removed.
Remove the start event button when used in the PR page.
=> fix: Remove start event button for PRs

app/components/pipeline-list-view/component.js, tests/integration/components/pipeline-list-view/component-test.js
The number of builds is not reset to default after leaving the pipeline list view page.
Reset number of builds to default after leaving the pipeline list view page.
https://github.com/screwdriver-cd/screwdriver/issues/3241
=> fix(3241): reset number of builds when leaving jobs list view

app/router.js, app/v2/pipeline/pulls/index/route.js, app/v2/pipeline/pulls/index/template.hbs, app/v2/pipeline/pulls/route.js, app/v2/pipeline/pulls/show/route.js, app/v2/pipeline/pulls/show/template.hbs, app/v2/pipeline/pulls/template.hbs, app/v2/pipeline/pulls/util.js, tests/unit/v2/pipeline/pulls/index/route-test.js, tests/unit/v2/pipeline/pulls/show/route-test.js, tests/unit/v2/pipeline/pulls/util-test.js
Sets up new pull request routes that largely mirror the route structure of the event routes.  A new addition in the V2 UI is that pull requests can now be directly linked via the pull request number (e.g. /pulls/5).
Set up the new pull request routes to leverage the V2 workflow component.  There is still more work that needs to go into updating other components like the event rail and background data reloading.
=> feat: Set up new pull request routes

app/components/pipeline/modal/event-group-history/component.js, app/components/pipeline/modal/event-group-history/template.hbs, tests/integration/components/pipeline/modal/event-group-history/component-test.js
The event group history modal needs some updates to better handle pull request events
Updates the event group history modal to have improved cosmetics for pull request events.  Also updates the background event refreshing while the modal is open to support pull request events.
Modal header title updated for pull requests
=> feat: Update event group modal to support PRs

app/workflow-data-reload/dataReloader.js, app/workflow-data-reload/latestCommitEventReloader.js, app/workflow-data-reload/openPrsReloader.js, tests/unit/workflow-data-reload/dataReloader-test.js, tests/unit/workflow-data-reload/latestCommitEventReloader-test.js, tests/unit/workflow-data-reload/openPrsReloader-test.js
The pull request page needs to be able to reload the open pull requests in order to populate the event rail correctly.
- Refactors the `pipelineId` variable to reside in the `DataLoader` class as both the new data loader and the `LatestCommitEventReloader` requires the `pipelineId` 
- Creates a new data reloader that monitors the open pull requests for a given pipeline.
=> feat: Pull request reloader

app/utils/pipeline/modal/request.js, tests/unit/utils/pipeline/modal/request-test.js
When starting an new event from the workflow graph in the V2 UI, the new event is not attached to the original event group
Fixes events started from the workflow graph to be attached to the correct event group
=> fix: Fix start event from job to have event group

app/components/pipeline/workflow/styles.scss
When a pipeline graph is wide, the scroll is added to the wrong container in the V2 UI
Fix the overflow to be contained in the pipeline graph containing element
=> fix: Fix issue with horizontal graph overflow

app/components/pipeline/modal/confirm-action/component.js, app/components/pipeline/modal/confirm-action/template.hbs, tests/integration/components/pipeline/modal/confirm-action/component-test.js
The confirm action modal should autoclose and transition the route to the newly created event
Updates the confirm action modal to remove the messaging when the API call succeeds.  Adds in the autoclose functionality to the the modal and also transitions the UI route to the newly created event.
=> fix: Autoclose confirm action modal

app/components/pipeline/modal/search-event/component.js, tests/integration/components/pipeline/modal/search-event/component-test.js
The search modal needs to be updated to support PR events.
Adds in the ability for the search event modal to query what event page it is opened on and set the API call with the correct query parameter.
=> feat: Update search modal to support PR events

app/components/pipeline/event/card/component.js, app/components/pipeline/modal/event-group-history/template.hbs
When selecting an event from the event history modal, the modal should automatically close.
Adds in the ability for the event history modal to close automatically when an event card is clicked.
=> fix: Autoclose event history modal

app/components/pipeline/modal/start-event/component.js, app/components/pipeline/modal/start-event/template.hbs, tests/integration/components/pipeline/modal/start-event/component-test.js
When starting a new event, the modal should automatically close and transition the UI to the newly created event.
Updates the start event modal to close and transition to the newly created event on API success.
=> fix: Close modal and transition to new event on success

app/components/pipeline/modal/stop-build/component.js, app/components/pipeline/modal/stop-build/template.hbs, tests/integration/components/pipeline/modal/stop-build/component-test.js
The stop build action should automatically close the modal when the API call succeeds
Simplify the stop build modal to automatically close when the API call succeeds.  Also removes associated messaging within the modal since the user will never see that information anymore.
=> fix: Update stop build modal to auto close on success

app/components/pipeline/workflow/component.js
When switching to a different event via the event cards in the event rail, if the event that is switched to is not complete, the workflow graph does not update correctly.
Adds in the missing builds monitoring for an event that isn't complete.
=> fix: Fix graph reloading bug

app/components/pipeline/workflow/event-rail/component.js
When the event rail is reloaded the newest event is added into the event rail twice.  This is because the newest event marker isn't reset correctly.
Fixes the issue where the newest is added twice.
=> fix: Fix reload event rail bug

app/components/search-list/component.js, app/search/controller.js, tests/acceptance/search-test.js, tests/integration/components/search-list/component-test.js, tests/unit/search/controller-test.js
`Show more results` button does not appear when search result is less than 50 (default) on the pipeline search page.
Therefore uses cannot load next pipelines if search result includes private pipelines and they are filtered.
e.g.)
The pipeline [yk634/pr-test](https://cd.screwdriver.cd/pipelines/14506) appears on 2nd page of [searching "pr"](https://cd.screwdriver.cd/search?query=pr), but guest uses cannot load 2nd page.
(Some pipelines are private and they are filtered, so the result is less than 50 and `Show more results` button is hidden.)
Fix showing `Show more results` button conditions. 
After this PR, `Show more results` button will be hidden if the loaded next page is empty. …
=> fix: cannot load next pipelines on search page when private pipelines are filtered

app/components/app-header/component.js, app/components/app-header/template.hbs, tests/integration/components/app-header/component-test.js
The dropdown menu for switching between the UI interfaces is still checking for admin privileges.
Remove the requirement for being an admin.
=> fix: Remove admin requirement

app/components/pipeline-header/component.js, app/pipeline/service.js, tests/integration/components/pipeline-header/component-test.js
Sibling pipeline link does not have all links when the pipeline has too many other branch pipelines (over 50 by default).
Fetch sibling pipeline from API properly with pagination.
=> fix: other branch pipeline link on pipeline header does not include all of sibling pipelines

app/components/pipeline/modal/search-event/template.hbs
The search modal does not auto close when an event card is selected.
Adds in the ability for the search modal to automatically close when an event is selected
=> fix: Close the search modal when event card is clicked

app/components/pipeline/workflow/component.js, app/workflow-data-reload/service.js
When switching between the `Events` and `Pulls` tabs in the v2 UI, the background data reloading stops working.  This is because Ember creates a new workflow component before destroying the old workflow component.
Adds in ID tracking for the data reloading so that the data reloading class can handle cases where the previous reloading has already stopped due to the `start` function being called.  Also fixes an issue where the data reloading for pull request data stops properly.
=> fix: Fix data reloading issues

app/components/pipeline/event/card/styles.scss
When scrolling quickly through the event card rail in the v2 UI, the selected event is difficult to notice with the current background color.  By flipping the event card highlight to the darker color, the card is more noticeable in the list of events.
Flip the highlight colors in the event cards and remove the hover color change for the selected event.
=> fix: Flip card highlight colors

app/components/workflow-graph-d3/component.js, app/utils/pipeline/graph/d3-graph-util.js
Virtual job icon is not used after the workflow graph is redrew. (e.g. Uses stops the build)
Use virtual job icon correctly when the workflow graph is redrew.
Issue: https://github.com/screwdriver-cd/screwdriver/issues/3247
=> fix(3247): virtual job icon is not used when the graph redraw

app/components/nav-banner/style.scss
Horizontal scroll bar on banner appears if user sets `Always` to `Settings > Appearance > Show scroll bars` on their Mac.
It is annoying to read the message on the banner.
Disable horizontal scroll bar since it was originally not useable.
=> fix: disable x-scroll bar on banner

app/components/pipeline/modal/confirm-action/component.js, app/components/pipeline/modal/start-event/component.js
The start event and confirm action modals are used in a few different routes (i.e., events, pulls, and jobs).  Each of these routes have different requirements for whether the transition should be made and to where.
Fix the transitions so that they redirect to the current route when the modal auto closes.
=> fix: redirect routes when closing modals

app/components/pipeline/jobs/table/cell/history/styles.scss, app/components/pipeline/jobs/table/cell/job/styles.scss, app/components/pipeline/jobs/table/component.js, app/components/pipeline/jobs/table/dataReloader.js, app/components/pipeline/jobs/table/styles.scss
The jobs table history size is fixed to a default size and should be adjustable.
Updates the jobs table to allow for configuration of the build history size.  Additionally updates the styling on the table to better handle potential overflows so that the scroll bar does not get overlayed on top of the content
=> feat: Update job table history size

app/components/pipeline/event/card/component.js
When clicking on the highlighted event card, which is the currently selected event, there is no need to have the UI to actually handle the redirect.
Removes the redirect when clicking on the currently selected/displaying event.
=> fix: Do not redirect to current route

app/utils/pipeline/pull-request.js, app/workflow-data-reload/openPrsReloader.js, app/workflow-data-reload/service.js, tests/unit/utils/pipeline/pull-request-test.js, tests/unit/workflow-data-reload/openPrsReloader-test.js
When reloading PR builds in the background, the PR job names can be cached as well.
Adds a cache of the job names for each open PR.
=> feat: Cache PR jobs data

app/components/pipeline/workflow/event-rail/component.js
When switching from the event view to the PR view, the event rail is reloaded but has no assigned value for `prNums`
Fix an invalid dereference
=> fix: Fix dereference of undefined

app/templates/job/detail/route.js, app/templates/pipeline/detail/controller.js, tests/acceptance/pipeline-template-test.js
Tags of job/pipeline template is shown on versions table. But
1. Tags will be duplicate when transition between the job template detail page and other page
https://github.com/user-attachments/assets/b8cedbec-6407-418b-a731-6ffe4f57c959
2. Tags does not appear on the pipeline template pages
This PR will fix display tags on template detail pages.
=> fix: display of tags on job/pipeline template details page

app/components/pipeline/workflow/event-rail/component.js
The event rail component allows for doing a reload when args are updated on it.  There are a couple extra tracking variables that should also get reset when the component is requested to be reset.
Clear out the remaining tracking variables for the event rail when the component should be reloaded.
=> fix: Clear out tracking variables

app/components/pipeline/jobs/table/cell/history/styles.scss, app/components/pipeline/jobs/table/cell/history/template.hbs
For created jobs, the history icon is not aligned properly
Fix the alignment problem with created job icons
=> fix: Fix alignment issue for created job history

app/components/pipeline/workflow/graph/component.js, app/components/workflow-graph-d3/component.js, app/utils/pipeline/graph/d3-graph-util.js
Changes were made in this PR https://github.com/screwdriver-cd/ui/pull/1229 to show a different icon for virtual jobs to visually differentiate with other jobs.
When the workflow graph is redrawn after refreshing the status of builds for an active event, the icon for virtual jobs is not rendered as expected.
The redraw logic does not consider where the job is virtual or not.
Update the redraw logic to consider if a node is virtual or not while determining/drawing the icon based on the updated status.
https://github.com/screwdriver-cd/screwdriver/issues/3247
=> fix(3247): Virtual job icon is broken while redrawing workflow graph with build statuses

app/components/pipeline/workflow/component.js, app/v2/pipeline/pulls/show/route.js, app/workflow-data-reload/service.js, tests/integration/components/pipeline/workflow/component-test.js
When a user is on the PR view and there are no open PRs, the UI should be reloading open PR data from the API and then redirect the page to the first open PR when it is available.
Add in background reloading of open PRs when there are none open at page load.  When a PR is finally opened, the page should redirect to the newly opened PR to load the correct workflow graph and the associated event card in the event rail.
=> fix: First PR reload

app/components/pipeline-workflow/template.hbs
When starting a stage build from the UI, the stage name is not displayed in the modal.
Fix it so that the stage name is displayed.
=> fix: stage name to be displayed in the modal to start stage build

app/components/workflow-graph-d3/component.js
https://github.com/screwdriver-cd/ui/pull/1302 introduced a dereference of an undefined arg in a classic Ember component when attempting to determine what the configured display name length should be.
Fix the value for the configured display name length.
https://github.com/screwdriver-cd/ui/pull/1302
=> fix: Fix undefined displayJobNameLength

app/components/pipeline/workflow/util.js, tests/unit/components/pipeline/workflow/util-test.js
The V2 UI graph is not handling pipelines that have external jobs in the middle of the graph.
Fixes the V2 pipeline graph to only remove external jobs if they are sink nodes
=> fix: Keep external jobs if they are not sink nodes

app/utils/graph-tools.js
Nodes in workflow graph are placed at first calculated depth by "depth-first search".
Hence it can be smaller than the depth related from other root tree.
Introduce the "Topological sort" and calculate the depth of nodes before walk around the workflow graph.
Example:
```yaml
shared:
image: node:12
steps:
- test: echo 'Foo'
jobs:
A:
requires: [~pr, B, stage@foo]
B:
C:
requires: []
D:
requires: []
E:
requires: [ C ]
stages:
foo:
jobs: [ C, E ]
setup:
steps:
- foo: bar
teardown:
steps:
- foo: bar
bar:
jobs: [ D ]
requires: [ B, A ]
setup:
steps:
- foo: bar
```
Before:
After:
Issue - https://github.com/screwdriver-cd/screwdriver/issues/2330
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source …
=> fix(2330): Calculate the maximum depth of the node on workflow graph

app/components/pipeline/workflow/graph/styles.scss
Job nodes that are created do not have any fill colors and are not apparent until the user hovers over the job node.
Adds a fill color for created job nodes to better indicate to the user that a job has a build created for it
=> feat: Add fill color for created job nodes in V2 UI

app/utils/pipeline/build.js, tests/unit/utils/pipeline/build-test.js
When the meta for warning is as a boolean value, the UI does not correctly display the warning status of the build.
Updates the build status logic to account for the meta warning value to handle boolean values.
https://github.com/screwdriver-cd/screwdriver/issues/3268
=> fix(3268): Fix build warning determination

app/components/pipeline/workflow/graph/component.js, app/components/workflow-graph-d3/component.js, app/utils/graph-tools.js, app/utils/pipeline/graph/d3-graph-util.js, tests/integration/components/pipeline/workflow/graph/component-test.js, tests/integration/components/workflow-graph-d3/component-test.js, tests/unit/utils/graph-tools-test.js, tests/unit/utils/pipeline/graph/d3-graph-util-test.js
When a stage has implicit setup/teardown jobs, in the workflow graph
1. nodes corresponding to implicit setup/teardown are hidden
2. edges to `setup` are redrawn to point to all the root nodes of that stage workflow
3. edges from `teardown` are redrawn to start from all the leaf nodes of that stage workflow
If the stage has multiple root/leaf nodes, we end up having too many edges leading to/from stages which makes the workflow graph convoluted.
Sample pipeline: https://cd.screwdriver.cd/pipelines/15595/events/826742
Replace the edges to `setup` node or from `teardown` node with edges originating or leading to stage border.
https://github.com/screwdriver-cd/screwdriver/issues/3117 …
=> feat(3117): Reduce noisy edges to/from stages

app/components/pipeline/parameters/component.js, app/components/pipeline/parameters/selectable/styles.scss, app/components/pipeline/parameters/selectable/template.hbs, app/components/pipeline/parameters/styles.scss, tests/integration/components/pipeline/parameters/selectable/component-test.js
The dropdown menu for a pipeline's parameters in the V2 UI doesn't always stay open and therefore has an unintended effect where it is difficult to select an option from the drop down.
Fix the dropdown spacing to all be done handled with CSS and removes the additional scroll logic that previously existed.
=> fix: Fix parameters drop down

app/utils/graph-tools.js
https://github.com/screwdriver-cd/ui/pull/1320 inadvertently creates a spares array with empty slots in the following code block:
https://github.com/screwdriver-cd/ui/pull/1320/files#diff-1e81a193b56d9ac00e3e89b9f7bb4d446837f1dea429e5534e19d64bfa4b8019R243-R246
This sparse array is problematic because the `Math.max` returns `NaN` when a spare array is passed in at this line of code https://github.com/screwdriver-cd/ui/pull/1320/files#diff-1e81a193b56d9ac00e3e89b9f7bb4d446837f1dea429e5534e19d64bfa4b8019R461
The resulting value of `y` after the above line of code is that `y` is an array of `NaN` values and breaks any downstream calculations using `y`.
Initializes `y` to be an array of the proper length filled with 0 values.  This prevents the `y` from being resized to a larger array in …
=> fix: Prevent empty slots

app/utils/graph-tools.js
https://github.com/screwdriver-cd/ui/pull/1327 initialize the array `y`, but the node depth is 0-based counted.
Thus if the pipeline has detached jobs only, `y` is empty array.
Fix the maximum depth.
PR - https://github.com/screwdriver-cd/ui/pull/1327
=> fix: maximum node depth

app/utils/pipeline/graph/d3-graph-util.js
https://github.com/screwdriver-cd/screwdriver/issues/3117 added more horizontal spacing between the stages. This created a regression as the additional spacing introduced is not accounted to adjust the overall width of the graph. Due to this, few jobs at the end of the workflow are not visible
When horizontal spacing is added between the stages, the overall width of the graph needs to expanded accordingly.
After fix:
https://github.com/screwdriver-cd/screwdriver/issues/3279
=> feat(3279): Job nodes are missing in the workflow graph for pipelines with sequential stages

app/components/pipeline/modal/confirm-action/component.js, app/components/pipeline/modal/confirm-action/util.js, tests/unit/components/pipeline/modal/confirm-action/util-test.js
Extracting the `isParameterized` function into a utility for additional unit testing.
Extracts the `isParameterized` function into a utility to allow for better isolated testing.  The logic should be covered in a unit test to keep the component tests less complex.
=> Extract isParameterized to a util

app/pipeline-page-state/service.js, app/v2/pipeline/route.js, tests/unit/pipeline-page-state/service-test.js
The pipeline page has a lot of static data that is being passed through many layers of glimmer components.  This static data can be injected into the components as necessary.  For this initial change, only the pipeline data will be set up, but future changes will start incorporating additional pieces of data.
Sets up an injectable ember service for capturing static data starting with the pipeline data. 
=> feat: Inject pipeline

app/components/pipeline/header/component.js, app/components/pipeline/header/template.hbs, app/v2/pipeline/template.hbs, tests/integration/components/pipeline/header/component-test.js
Refactor the pipeline header component to use the injectable pipeline data rather than having that data passed into the component.
Refactor the pipeline header component.  Also removes the `collection` component argument as it was not actually used.
https://github.com/screwdriver-cd/ui/pull/1331
=> feat: Inject pipeline state into pipeline header

app/components/pipeline/jobs/table/cell/coverage/component.js, tests/integration/components/pipeline/jobs/table/cell/coverage/component-test.js
Refactor the job coverage table cell to use the injected pipeline data
Refactors the job coverage table cell to not depend on pipeline data being passed into the component
https://github.com/screwdriver-cd/ui/pull/1331
=> feat: Inject pipeline data into job coverage cell

app/components/pipeline/modal/search-event/component.js, app/components/pipeline/workflow/event-rail/template.hbs, tests/integration/components/pipeline/modal/search-event/component-test.js
Refactor the search event modal to use injected pipeline data.
Refactor the search event modal to use injected pipeline data instead of having it passed into the component.
https://github.com/screwdriver-cd/ui/pull/1331
=> feat: Inject pipeline data into search event modal

app/components/pipeline/event/card/styles.scss
Certain long messages may not break nicely and cause a bit of a text overflow in the event card.  For these instances, the overflowing text should be handled properly
Adds horizontal overflow handling for event card messages
=> fix: Add overflow handling for long messages

app/components/pipeline/workflow/event-rail/component.js
If the scheduler filter is configured for a pipeline, the events should be filtered from the event rail.
Adds in support to the API call for filtering events created by the scheduler.
=> fix: Update API fetch to ignore scheduler events

app/v2/pipeline/events/index/route.js, app/v2/pipeline/events/index/template.hbs, app/v2/pipeline/events/route.js, app/v2/pipeline/events/show/route.js, app/v2/pipeline/events/show/template.hbs, app/v2/pipeline/index/route.js, app/v2/pipeline/index/template.hbs, app/v2/pipeline/jobs/route.js, app/v2/pipeline/jobs/template.hbs, app/v2/pipeline/options/route.js, app/v2/pipeline/pulls/index/template.hbs, app/v2/pipeline/pulls/route.js, app/v2/pipeline/pulls/show/route.js, app/v2/pipeline/pulls/show/template.hbs, app/v2/pipeline/route.js, app/v2/pipeline/secrets/route.js, app/v2/pipeline/template.hbs
Removes the pipeline data from the route models since https://github.com/screwdriver-cd/ui/pull/1331 allows for injecting the pipeline data directly into the components that require the data.
1. Refactor the pipeline routes to not include the pipeline data in the model since it was only being passed down the chain of routes.  
2. Removes an unused template for the pipeline index route
3. Cleans up a few redirects within the routes
https://github.com/screwdriver-cd/ui/pull/1331
=> fix: Remove pipeline from route models

app/components/search-list/styles.scss, app/components/search-list/template.hbs, tests/integration/components/search-list/component-test.js
The long branch name overflow on the pipeline search page.
Omit long branch name as in the [collection pages](https://github.com/screwdriver-cd/ui/blob/4b69d942d3af1307589b5a15282eb5191602bd38/app/components/collection-table-row/styles.scss#L26-L30).
=> fix: truncate long branch names on the search page

app/components/pipeline/event/card/component.js, app/components/pipeline/event/card/styles.scss, app/components/pipeline/event/card/template.hbs, app/components/pipeline/workflow/event-rail/styles.scss, app/components/pipeline/workflow/event-rail/template.hbs
The pipeline has settings to filter out events that have been skipped and this filtering should be supported in the V2 UI.  The event cards are responsible for loading in their respective builds which allows the event cards to determine the state of the event.  Thus, the event cards are able to determine whether or not they should be displayed in the UI.
Filters out the skipped events, if configured in the pipeline settings, by hiding them in the UI via CSS.
=> feat: Add support for filtering out skipped events

app/components/pipeline/workflow/component.js, app/utils/pipeline/event.js, tests/unit/utils/pipeline/event-test.js
When starting a new event, the v2 UI does not properly reload the workflow graph
Fixes the event status determination that was not properly calculating the status of a newly started event as there are no builds queued up on the initial page update.
=> fix: Fix event status determination

app/v2/pipeline/options/route.js, app/v2/pipeline/secrets/route.js
The V2 UI for the pipeline secrets and options are leveraging the old non-glimmer components using ember data.  Those components still need to be rebuilt, until then, these routes should just redirect back to the old pages.
Redirect the pipeline options and secrets pages back to the V1 route until the proper V2 versions are ready.
https://github.com/screwdriver-cd/ui/pull/1072
https://github.com/screwdriver-cd/ui/pull/1078
https://github.com/screwdriver-cd/ui/pull/1080
=> Redirect to v1 for secrets and options

app/components/pipeline/jobs/table/component.js, app/components/pipeline/workflow/template.hbs
The job view in the V2 UI for an event displays the build history column name as `HISTORY`.  As the event only has one build status per job, history doesn't accurately capture the column contents and should be renamed to `STATUS` instead.
Renames the `HISTORY` column to `STATUS`
=> fix: Change column name to status for event job display

app/components/pipeline-header/component.js, app/components/pipeline/header/component.js, app/pipeline/service.js, tests/integration/components/pipeline-header/component-test.js, tests/integration/components/pipeline/header/component-test.js
We are using `name` param to find sibling pipelines, but it has an issue.
After https://github.com/screwdriver-cd/screwdriver/pull/3285 , we will be able to find them by `scmUri` param.
Use `scmUri` param to find sibling pipelines.
- Issue: https://github.com/screwdriver-cd/screwdriver/issues/3284
- PR: https://github.com/screwdriver-cd/screwdriver/pull/3285
=> feat(3284): Find sibling pipelines by scmUri search [2]

app/utils/pipeline/modal/request.js, tests/unit/utils/pipeline/modal/request-test.js
When restarting a build for a PR job, the `startFrom` value needs to include the proper job prefix for the node, i.e. `PR-{pull request id}`
Fix the post body for a pull request job to include the properly value
=> fix: Fix post body for PR events

app/utils/pipeline/graph/d3-graph-util.js
There is not enough horizontal spacing between the stages. Due to this, the edges originating from a stage is not properly drawn.
**Before**
Provide sufficient spacing between the stages to properly render the edges.
**After**
https://github.com/screwdriver-cd/screwdriver/issues/3294
=> fix(3294): Fix - The edges from stages to upstreams are not properly drawn

app/styles/ember-models-table.scss
The use of ember models table in the V2 UI should have a shared stylesheet that can be easily included into components when needed.  Refactoring of the existing tables will happen in another PR.
Creates a shared style sheet for use in the V2 UI whenever ember models table components are used.
=> feat: Shared style for ember model tables used in V2 UI

app/components/pipeline/event/card/component.js, app/components/pipeline/event/card/styles.scss, app/components/pipeline/event/card/template.hbs, app/components/pipeline/modal/start-event/component.js, app/components/pipeline/workflow/component.js, app/components/pipeline/workflow/event-rail/template.hbs, app/components/pipeline/workflow/styles.scss, app/components/pipeline/workflow/template.hbs, tests/integration/components/pipeline/event/card/component-test.js, tests/integration/components/pipeline/workflow/component-test.js
When a pipeline has the `restrictPR annotation`, pull request events need the ability to be manually started.
https://github.com/screwdriver-cd/ui/pull/1346 should be merged prior to this.
Adds in a manual start button to the event card for pipelines with the `restrictPR` annotation
Also adds a notice within the UI to inform users what restrictions exist on the pipeline.  The hover state over the icons provides longer text to the user explaining what the restriction is.
https://github.com/screwdriver-cd/ui/pull/1346
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its …
=> feat: Handle restrict pr

app/components/pipeline/event/card/util.js, app/utils/pipeline/build.js, tests/unit/components/pipeline/event/card/util-test.js, tests/unit/utils/pipeline/build-test.js
The API returns the build meta warning object in various structural forms.  Relaxing to check for only the existence of of the key is a better option while retaining the check for a boolean value.
1. Relaxes the build meta warning object check for determining a build status.
2. Updates the event card warning count to also include warning statuses
=> fix: Deep inspect for warning

app/components/pipeline/jobs/table/cell/history/styles.scss, app/components/pipeline/jobs/table/cell/job/styles.scss, app/components/pipeline/jobs/table/cell/status/component.js, app/components/pipeline/jobs/table/cell/status/styles.scss, app/components/pipeline/jobs/table/cell/status/template.hbs, app/components/pipeline/jobs/table/component.js, app/components/pipeline/jobs/table/styles.scss, app/components/pipeline/jobs/table/template.hbs, app/components/pipeline/workflow/template.hbs, app/styles/ember-models-table.scss, package-lock.json, package.json, tests/integration/components/pipeline/jobs/table/cell/status/component-test.js
The events table view shows all the job build status for an event.  For pipelines that are large, having the ability to filter out the table to just particular build statuses is helpful for getting to particular builds of interest.
1. Creates a new component for displaying the job build status rather than leveraging the existing build history component.
2. Updates the table component to use the shared table style extracted in #1349 
3. Fixes a bug where table display changes populates incorrect build data back into the table for the event/pr event job view
https://github.com/screwdriver-cd/ui/pull/1349
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source …
=> feat: Event status filter

app/pipeline-page-state/service.js
The pipeline children V2 page needs to be able to operate off of the list of child pipelines.
Adds pipeline children data to the injectable pipeline page state service.
=> feat: Add pipeline children to injectable service

app/components/pipeline/modal/start-children/component.js, app/components/pipeline/modal/start-children/template.hbs, tests/integration/components/pipeline/modal/start-children/component-test.js
The child pipeline page in the V2 UI needs a modal to confirm starting all child pipelines
Creates a glimmer modal component for staring all child pipelines
=> feat: Create modal for starting all child pipelines

app/components/pipeline/children/table/cell/account/styles.scss, app/components/pipeline/children/table/cell/account/template.hbs, app/components/pipeline/children/table/cell/actions/component.js, app/components/pipeline/children/table/cell/actions/template.hbs, app/components/pipeline/children/table/cell/branch/styles.scss, app/components/pipeline/children/table/cell/branch/template.hbs, app/components/pipeline/children/table/cell/pipeline/styles.scss, app/components/pipeline/children/table/cell/pipeline/template.hbs, app/components/pipeline/children/table/cell/status/component.js, app/components/pipeline/children/table/cell/status/styles.scss, app/components/pipeline/children/table/cell/status/template.hbs, app/components/pipeline/children/table/component.js, app/components/pipeline/children/table/styles.scss, app/components/pipeline/children/table/template.hbs, tests/integration/components/pipeline/children/table/cell/account/component-test.js, tests/integration/components/pipeline/children/table/cell/actions/component-test.js, tests/integration/components/pipeline/children/table/cell/branch/component-test.js, tests/integration/components/pipeline/children/table/cell/pipeline/component-test.js, tests/integration/components/pipeline/children/table/cell/status/component-test.js
The child pipeline's route for the V2 UI requires having a table glimmer component.
Creates a glimmer component to handle the child pipelines table in the V2 UI.
=> feat: V2 child pipeline table

app/utils/pipeline/graph/d3-graph-util.js, tests/integration/components/workflow-graph-d3/component-test.js, tests/unit/utils/pipeline/graph/d3-graph-util-test.js
Follow up https://github.com/screwdriver-cd/ui/pull/1152
`displayName` is used to show the name of upstream pipeline but it is also used to label the normal job.
Hence we should check whether the `displayName` is from remote trigger or not.
Use `remoteName` insteadOf `displayName` to show remote trigger's pipeline name.
https://github.com/screwdriver-cd/models/pull/643
- Issue: https://github.com/screwdriver-cd/screwdriver/issues/3193
- PR: https://github.com/screwdriver-cd/models/pull/643
=> fix(3193): use remoteName instead of displayName to show remote trigger's pipeline name as title [2]

app/components/pipeline/modal/start-children/component.js, tests/integration/components/pipeline/modal/start-children/component-test.js
The shuttle service configures the ajax client to expect JSON response bodies.  The API may return a 201 without a body causing the ajax client to attempt to parse invalid JSON.  This is what is currently happening on the `v4/postV4PipelinesIdStartall` API call.
Updates the start all children pipelines API call to request the whole error object to be returned so that further introspection can be done on the actual API call and the returned status code.
https://github.com/screwdriver-cd/ui/pull/1354
=> fix: Handle 201 for start all children

app/components/build-banner/component.js, app/components/build-banner/template.hbs, tests/integration/components/build-banner/component-test.js
Users want to confirm restart/stop build when clicking button in the build detail page.
Add modal to confirm restart/stop build in the build detail page.
=> feat: Create modal for restart/stop build in build detail page

app/components/pipeline/nav/component.js, app/components/pipeline/nav/template.hbs, app/router.js, app/v2/pipeline/child-pipelines/route.js, app/v2/pipeline/child-pipelines/template.hbs, app/v2/pipeline/index/route.js, tests/integration/components/pipeline/nav/component-test.js, tests/unit/v2/pipeline/child-pipelines/route-test.js
Adds in the proper V2 route for child pipelines.  
**Requires the glimmer component from https://github.com/screwdriver-cd/ui/pull/1360 and therefore should be merged after https://github.com/screwdriver-cd/ui/pull/1360**
1. Adds the proper route for the v2 child pipeline page
2. Adds a navigation icon to the left-side navbar to the child pipeline page if the pipeline is a parent pipeline
https://github.com/screwdriver-cd/ui/pull/1360
=> feat: Child pipeline route

app/components/build-banner/template.hbs
Follow up #1363 
To apply css to the button in the build detail page modal, add classes to the button.
Apply the same css as the workflow graph tooltip start modal.
=> fix: apply css to modal button in build detail page

app/components/pipeline/children/component.js, app/components/pipeline/children/styles.scss, app/components/pipeline/children/table/styles.scss, app/components/pipeline/children/template.hbs, app/components/pipeline/modal/delete-pipeline/component.js, app/components/pipeline/styles.scss, tests/integration/components/pipeline/children/component-test.js
Creating a glimmer component to house the child pipelines table and the button to start all child pipelines.
1. Creates a glimmer component that can be used directly within the route template to display the whole child pipeline view
2. Updates the child pipeline table style to handle various viewport heights with the proper scrolling and sticky table header
=> feat: Glimmer component for child pipelines

app/components/app-header/component.js, app/opt-in-route-mapping/service.js, app/pipeline/child-pipelines/route.js, app/pipeline/events/route.js, app/pipeline/jobs/index/route.js, app/pipeline/pulls/route.js, tests/unit/opt-in-route-mapping/service-test.js
The new V2 UI should have the ability to be opt in so that users will always hit the V2 UI.  As part of an opt-in flow, all of the existing routes that have a V2 UI should be redirected to the respective destinations.  When a user decides to opt-out of the V2 UI, then the existing routes should be made available (as well as all of the V2 pages if the user goes directly to those pages).
1. Creates a route mapping going between the different UI routes.  Since there are some differences in the actual routes, this mapping will be manually maintained until the old routes are fully retired.
2. Leverage local storage to keep the state of the user's opt-in of the V2 UI.  While this will mean users need to reconfigure the UI setting per browser/device, this should be fine in the interim as most …
=> feat: V2 opt in

app/opt-in-route-mapping/service.js
When a pipeline does not have any events, the event index route is used and needs to be mapped for the v2 UI opt-in.
Adds the missing event index route mapping for v2 UI opt-in
=> fix: Add mapping for core event route

app/v2/pipeline/index/route.js
The router injection can be dropped on the route as the route class has a needed functionality to handle redirects.
Removes the unnecessary injection of the router service.
=> fix: Drop router injection

app/v2/pipeline/events/index/route.js
There's a bug with the pipeline events API that causes the endpoint to be slow/unresponsive when the `count` query parameter is set: https://github.com/screwdriver-cd/screwdriver/issues/3308
The API is fine when the `count` query parameter is not set, so temporarily it will be a better trade-off to have a larger response payload for the quick API response.
Remove the `count` query parameter due to the API issue.  Add in a TODO item to add the query parameter back in when the API issue is fixed.
https://github.com/screwdriver-cd/screwdriver/issues/3308
=> fix: Drop query parameter for now

app/components/pipeline/jobs/table/cell/history/component.js, app/components/pipeline/jobs/table/cell/history/template.hbs, tests/integration/components/pipeline/jobs/table/cell/history/component-test.js
The tooltip for the job history could be improved by also including the commit SHA to help further differentiate the builds
Adds in the commit SHA into the tooltip in the build history of the jobs table
=> feat: Include truncated sha in tooltip

app/banners/service.js, tests/unit/banners/service-test.js
Banners exist in 2 flavors, global and pipeline.  The location of all banners exists under the page navigation header, but the current implementations leaves a lot to be desired due to not being able to handle multiple banners nicely (they are currently stacked one on top of another and takes up valuable page space.  The improve upon the existing banner design, a new injectable service for capturing all of the banners that should be displayed on a given page needs to be created so that the banner UI component can properly display the relevant banners in a user-friendly manner.  The end result will look as follows:
Creates an injectable service for fetching and caching banners relevant to the given page.
I confirm that this contribution is made under the terms of the license found in the …
=> feat: Creates an injectable service for banners

app/components/banners/component.js, app/components/banners/styles.scss, app/components/banners/template.hbs, app/styles/bootstrap-alert.scss, tests/integration/components/banners/component-test.js
Expanding on #1373, creates the actual Glimmer component for the banners that will be displayed below the page header.
Banners will now take up a little bit more vertical height, but will have a banner count at the bottom right corner.  Note that banners are no longer dismissible.  Dismissibility of the banners can be revisited in the future to properly design out the actual experience.
When there are multiple banners, the bottom right will surface left and right arrows to allow users to switch through the available banner messages.
For banner messages that are large, vertical scrolling is configured.  This is the other reason why the banners now take up additional vertical space.
1. Creates a shared stylesheet that is super barebones for shared styles to theme bootstrap alert components …
=> feat: Banners component

app/v2/pipeline/events/index/route.js, app/v2/pipeline/events/show/route.js
[Due to this issue with the event API](https://github.com/screwdriver-cd/screwdriver/issues/3308), setting a count value that isn't 1 doesn't have the same performance impact; thus, it would be better to set the query parameters to minimize the payload size while still having the API performance.
Sets query parameters to avoid the API performance issue while minimizing the response payload.
https://github.com/screwdriver-cd/screwdriver/issues/3308
=> fix: Set query parameters for event API request

app/components/pipeline/workflow/component.js, app/components/pipeline/workflow/graph/component.js, app/components/pipeline/workflow/template.hbs, app/pipeline-page-state/service.js, app/v2/pipeline/events/show/route.js, app/v2/pipeline/events/show/template.hbs, app/v2/pipeline/pulls/route.js, app/v2/pipeline/pulls/show/template.hbs, tests/integration/components/pipeline/workflow/component-test.js, tests/integration/components/pipeline/workflow/graph/component-test.js
Stages can be added to the injectable page state for use in the v2 UI. This will help reduce the amount of data being passed directly into the main component and any downstream components which may require the stage data (i.e., the workflow graph component).
Refactor stages into the injectable page state
=> Refactor stages to be injectable

app/components/pipeline-workflow/component.js, app/components/pipeline-workflow/template.hbs, app/components/pipeline/workflow/component.js, app/components/pipeline/workflow/graph/component.js, app/components/pipeline/workflow/graph/styles.scss, app/components/pipeline/workflow/graph/template.hbs, app/components/pipeline/workflow/template.hbs, app/components/pipeline/workflow/tooltip/stage/component.js, app/components/pipeline/workflow/tooltip/template.hbs, app/components/workflow-graph-d3/component.js, app/components/workflow-graph-d3/styles.scss, app/components/workflow-stage-actions-menu/template.hbs, app/components/workflow-tooltip/template.hbs, app/utils/graph-tools.js, app/utils/pipeline-workflow.js, app/utils/pipeline/graph/d3-graph-util.js, tests/integration/components/pipeline/workflow/graph/component-test.js, tests/integration/components/pipeline/workflow/tooltip/component-test.js, tests/integration/components/pipeline/workflow/tooltip/stage/component-test.js, tests/integration/components/workflow-graph-d3/component-test.js, tests/integration/components/workflow-stage-actions-menu/component-test.js, tests/integration/components/workflow-tooltip/component-test.js, tests/unit/utils/graph-tools-test.js
Right now stage visualization default behavior is expanded.
Should have a way to collapse and expand a stage so it can minimize the real estate take in workflow graph.
**When Expanded**
**When Collapsed**
=> feat(3065): Ability to collapse and expand stage in the UI

app/components/pipeline/header/component.js, app/components/pipeline/header/styles.scss, app/components/pipeline/header/template.hbs, tests/integration/components/pipeline/header/component-test.js
If a pipeline has the root directory configured, it should be displayed alongside the branch name in the V2 UI
1.  Includes the root directory along with the branch if configured
2. Cleans up the CSS styling a bit
=> fix: Include pipeline root directory

app/components/pipeline/modal/add-to-collection/template.hbs, app/components/pipeline/modal/confirm-action/component.js, app/components/pipeline/modal/confirm-action/template.hbs, app/components/pipeline/modal/delete-pipeline/template.hbs, app/components/pipeline/modal/start-children/template.hbs, app/components/pipeline/modal/start-event/template.hbs, app/components/pipeline/modal/stop-build/template.hbs, app/components/pipeline/modal/toggle-job/template.hbs
The bootstrap ember components for buttons supports the use of a fulfilled text that will replace the button text when the async click action rejects; however, there's no good way to have that set unless the code rejects or throws an error which is then not compatible with the current testing setup.  As such, it's mostly dead end code and should just be removed.
Removes fulfilled text option on the bootstrap button components
=> fix: Remove fulfilled text

app/components/tokens/modal/refresh/component.js, app/components/tokens/modal/refresh/styles.scss, app/components/tokens/modal/refresh/template.hbs, tests/integration/components/tokens/modal/refresh/component-test.js
Updating the V2 UI for pipeline secrets requires a new set of components to handle management of tokens. This modal provides a new user experience that is in line with the rest of the V2 user experience leveraging modals more heavily for user interactions.
Creates a new modal for facilitating refreshing of new API tokens
=> feat: Modal component to refresh tokens

app/components/pipeline/modal/search-event/component.js, app/components/pipeline/workflow/component.js, app/components/pipeline/workflow/event-rail/component.js, app/pipeline-page-state/service.js, app/v2/pipeline/pulls/route.js, tests/integration/components/pipeline/modal/search-event/component-test.js, tests/integration/components/pipeline/workflow/component-test.js, tests/integration/components/pipeline/workflow/event/rail/component-test.js
The event type can be added to the injectable page state for use in the v2 UI. This will help reduce the need for downstream components to query the url path and extract the needed information.
Refactors the event type to be injectable and set on the PR route accordingly.
=> Refactor event type to be injectable

app/styles/screwdriver-button.scss
The shared bootstrap button styles only has styling set for the `primary` and `danger` button types.  Adding a new style for `success` button type will provide another option for use
Creates a new shared style for the success button type
=> feat: Add style for success button

app/components/tokens/modal/create/component.js, app/components/tokens/modal/create/styles.scss, app/components/tokens/modal/create/template.hbs, tests/integration/components/tokens/modal/create/component-test.js
Updating the V2 UI for pipeline secrets requires a new set of components to handle management of tokens.  This modal provides a new user experience that is in line with the rest of the V2 user experience leveraging modals more heavily for user interactions.
Creates a new modal for facilitating creation of new API tokens
New modal look and feel
In modal validation of the required token value.  Note that the submit button is disabled when a token name is invalid
Successful token creation provides the token value in the message area.  This new message area is no longer dismissible but has a new addition with a copy button that copies the token value to the user's clipboard (can only be clicked once with the current implementation.  This restriction can be removed if deemed too restrictive). …
=> feat: Modal for creating tokens

app/components/tokens/modal/delete/component.js, app/components/tokens/modal/delete/styles.scss, app/components/tokens/modal/delete/template.hbs, tests/integration/components/tokens/modal/delete/component-test.js
Updating the V2 UI for pipeline secrets requires a new set of components to handle management of tokens. This modal provides a new user experience that is in line with the rest of the V2 user experience leveraging modals more heavily for user interactions.
Creates a new modal for facilitating deletion of API tokens
=> feat: Glimmer component for delete token modal

app/components/tokens/modal/edit/component.js, app/components/tokens/modal/edit/styles.scss, app/components/tokens/modal/edit/template.hbs, tests/integration/components/tokens/modal/edit/component-test.js
Updating the V2 UI for pipeline secrets requires a new set of components to handle management of tokens. This modal provides a new user experience that is in line with the rest of the V2 user experience leveraging modals more heavily for user interactions.
Creates a new modal for facilitating updating of API tokens
=> feat: Glimmer component for editing a token modal

app/components/build-banner/component.js, app/components/pipeline/jobs/table/cost-table/component.js
Cost metrics have a build id that should be inspected before displaying cost data
Match build id in the build meta data to determine of cost metrics belong to the displaying build
=> Match cost metrics to build id

app/components/pipeline/workflow/component.js
The AWS cluster determination logic is really simple.  Additional work should be done with the backend to properly determine if an event is built within AWS.
Disables the simple AWS logic for the time being.
=> Disable AWS cluster logic

app/components/pipeline/workflow/event-rail/component.js, app/components/pipeline/workflow/event-rail/template.hbs
The V2 event rail has an issue where sometimes the selected event doesn't get rendered within the visible space of the event rail.  This is due to a how the underlying vertical collections component functions and is not really set up to handle our use case for updating event cards post initial render.
Adjusts the rendering logic to be in line with the vertical collection component expectations
=> fix: Fix event rail reloading logic

app/components/pipeline/workflow/component.js
When the toggle downstream triggers toggle is set to true, the workflow graph does not maintain the toggle state properly when switching between different events of the pipeline.
Fixes the issue where when a new event is selected, the workflow graph automatically defaults to hiding the downstream triggers.
=> fix: Fix trigger toggle state not reflecting in event graph

app/components/pipeline-event-row/template.hbs, app/components/pipeline/event/card/template.hbs, app/components/pipeline/workflow/component.js
SD configuration currently does not support pull_request closed trigger, to enable this feature we need to additional parsed information from webhook
This PR updates event rail to display cause message when start from is pr-closed 
https://github.com/screwdriver-cd/data-schema/pull/597
=> feat: update event rail to display cause message from pr-closed workflow

app/components/tokens/component.js, app/components/tokens/modal/create/component.js, app/components/tokens/modal/edit/component.js, app/components/tokens/table/cell/actions/component.js, app/components/tokens/table/component.js, app/components/tokens/table/template.hbs, app/components/tokens/template.hbs, app/tokens/service.js, tests/integration/components/tokens/component-test.js, tests/integration/components/tokens/modal/create/component-test.js, tests/integration/components/tokens/modal/edit/component-test.js, tests/unit/tokens/service-test.js
The V2 UI for managing tokens has a bit of interplay between various parent and child components.  In its current implementation, a lot of this interplay state is being passed around and tracked in a very ad hoc manner.  The token management for the components can be refactored into an injectable service so that the state does not need to be passed around.
1. Creates an injectable service to manage the tokens as various user actions are taken
2. Refactors the token components to use the newly created service
=> feat: Tokens service

app/components/pipeline/secrets-and-tokens/secrets/modal/override/component.js, app/components/pipeline/secrets-and-tokens/secrets/modal/override/styles.scss, app/components/pipeline/secrets-and-tokens/secrets/modal/override/template.hbs, tests/integration/components/pipeline/secrets-and-tokens/secrets/modal/override/component-test.js
Updating the V2 UI for pipeline secrets requires a new set of components to handle management of secrets. This modal provides a new user experience that is in line with the rest of the V2 user experience leveraging modals more heavily for user interactions.
Creates a new modal to facilitate overriding of inherited secrets
=> feat: Glimmer modal to override secrets

app/components/app-header/styles.scss
The navigation menu does not appear when expand the hamburger menu on a small display.
Display the navigation menu even on small devices.
=> fix: display navbar when expand hamburger menu

app/components/pipeline/secrets-and-tokens/tab/component.js, app/components/pipeline/secrets-and-tokens/tab/styles.scss, app/components/pipeline/secrets-and-tokens/tab/template.hbs, tests/integration/components/pipeline/secrets-and-tokens/tab/component-test.js
The v2 UI for secrets and tokens splits up the management of secrets and tokens into different sections rather than all being on the same page.  This split requires a new navigation bar to allow switching the UI between the two view.
Creates a glimmer component to support switching between the pipeline secrets and token UI
=> feat: Navbar for switching between secrets and tokens

app/components/pipeline/secrets-and-tokens/secrets/modal/create/component.js, tests/integration/components/pipeline/secrets-and-tokens/secrets/modal/create/component-test.js
https://github.com/screwdriver-cd/ui/pull/1408 added an injectable service for secrets.  The create secret modal can be simplified by using said service.
Refactors the create secret modal to use injectable services.
=> fix: Refactor create secret modal to use service

app/components/pipeline/workflow/component.js
https://github.com/screwdriver-cd/ui/pull/1398 added in some experimental work for exposing AWS build cost information.  As it was mostly experimental but still something worth pursuing in the future, the basic implementation was disabled in https://github.com/screwdriver-cd/ui/pull/1400.  Unfortunately, the original experimental work still had a bug where the `builds` may be null/undefined and should not be dereferenced.
Fixes the issue where `builds` should not be dereferenced.
https://github.com/screwdriver-cd/ui/pull/1398
https://github.com/screwdriver-cd/ui/pull/1400
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its …
=> Fix: issue with builds dereference

app/components/pipeline-event-row/component.js, app/components/pipeline-event-row/template.hbs
https://github.com/screwdriver-cd/models/pull/645 introduced an event status to be returned on the API payload and at that point all events have at least a default status set to `CREATED`.  In the v1 UI, the event card never expected the event status to be provided and therefore defaults the status to `UNKNOWN` and relies on the subsequent builds to compute the event status.
Adds additional handling for the `CREATED` event status that should allow the v1 event card to display the `STOP` button correctly.
=> fix: Fixes an issue where event status is CREATED

app/components/pipeline/secrets-and-tokens/secrets/table/cell/actions/component.js, app/components/pipeline/secrets-and-tokens/secrets/table/cell/actions/template.hbs, app/components/pipeline/secrets-and-tokens/secrets/table/cell/allowed-in-pr/styles.scss, app/components/pipeline/secrets-and-tokens/secrets/table/cell/allowed-in-pr/template.hbs, app/components/pipeline/secrets-and-tokens/secrets/table/cell/inherited/styles.scss, app/components/pipeline/secrets-and-tokens/secrets/table/cell/inherited/template.hbs, app/components/pipeline/secrets-and-tokens/secrets/table/component.js, app/components/pipeline/secrets-and-tokens/secrets/table/styles.scss, app/components/pipeline/secrets-and-tokens/secrets/table/template.hbs, tests/integration/components/pipeline/secrets-and-tokens/secrets/table/cell/actions/component-test.js, tests/integration/components/pipeline/secrets-and-tokens/secrets/table/cell/allowed-in-pr/component-test.js, tests/integration/components/pipeline/secrets-and-tokens/secrets/table/cell/inherited/component-test.js
The V2 UI needs a table component to allow users to modify existing secrets. Creating new pipeline secrets will be handled in an outer wrapping component that integrates this table component within it.
Creates a table to allow users to manage pipeline secrets.  Secrets that are inherited from a parent pipeline can be overridden and reverted.
=> feat: Glimmer component table for secrets

app/components/pipeline/workflow/tooltip/template.hbs
The current general behavior for switching to a different pipeline is to have the links open in a new window.  The graph tooltip links should be updated to follow the same pattern.
Updates the graph tooltips to open links to external pipelines in a new window.
=> External pipeline tooltip links in new window

app/components/pipeline/secrets-and-tokens/secrets/modal/delete/component.js, app/components/pipeline/secrets-and-tokens/secrets/modal/delete/template.hbs
In the v2 UI, deleting a secret should have better messaging as to whether the secret is deleted or reverted.
Improves the messaging in the delete secret modal to be less ambiguous.
=> feat: support reverting overridden secrets

app/components/pipeline/workflow/event-rail/component.js
When the user is on the v2 pipeline pull request page, there is a bug that adds a previous pull request card to the top of the event rail:
This bug happens when the user is at the top of the event rail (i.e., at the latest pull request events) and the newest pull request is closed/merged (e.g., in the screenshot above, the pull request 3 was closed/merged and pull request 2's event card gets added to the top of the list again).
Fixes the issue of adding a previous pull request event card to the event rail when the latest pull request is close/merged
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this …
=> fix: event rail pr close bug

app/v2/pipeline/events/index/route.js, app/v2/pipeline/events/show/route.js
https://github.com/screwdriver-cd/screwdriver/issues/3308 is tracking a performance issue with the query parameters.  However, the `lastEventId` field on the pipeline response has the needed information to fetch the event data directly.
Change the API call to fetch the latest event data directly
=> fix: Use lastEventId to fetch event directly

app/components/pipeline/workflow/component.js
When the v2 pipeline landing page is initially loaded without an event (i.e., the page is displaying for an invalid event for the pipeline), navigating to a new event for the pipeline fails to render the page correctly due to an invalid event dereference.
Fixes the component update logic to avoid an invalid event from being dereferenced
=> fix: Invalid event dereference

app/components/build-banner/component.js, app/components/build-banner/template.hbs
The build details page doesn't navigate to the v2 UI properly.  Due to a few changes in the v2 routes (i.e., pull requests now have a permalink), the navigation to a v2 UI page should go to the most specific route possible.
Adds support to navigate back to the proper v2 UI URL.
=> fix: navigation from build details page for v2 UI

app/components/pipeline/workflow/event-rail/component.js
When navigating to a new PR event from the event history modal, the ember route does not set the path parameter as the entire model is passed in.  As such, there's a event rail reload issue when the starting PR event is no longer open where any open PRs do not repopulate in the event rail.  Although the event id is not set on the params of the route, model that is set on the route contains the id variable with the correct event id value.
Fixes the event rail reloading issue when navigating from a PR event that is no longer open.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on …
=> fix: PR navigation

app/v2/pipeline/events/index/route.js
https://github.com/screwdriver-cd/ui/pull/1425 extracts the last event ID directly from the response payload; however, for pipelines that do not have any events, the last event ID is undefined.
Fixes the issue where a pipeline with no events does not display the UI correctly
=> fix: Fix missing last event ID

app/components/build-log/component.js, app/components/build-log/styles.scss, app/components/build-log/template.hbs
Allows timestamps to be added to downloaded logs.
Press the Log Download button to display the following download dropdown
The following PR is required
- https://github.com/screwdriver-cd/data-schema/pull/605
- https://github.com/screwdriver-cd/screwdriver/pull/3365
1. Allows user to select when download logs.
- Whether to include a timestamp 
- Timestamp format 
- Timestamp time zone (Only affects full-time and simple-time format)
2. Prevent timestamps from being selected when copying a step's log by selecting a range of steps on the UI
https://github.com/screwdriver-cd/screwdriver/issues/2856
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this …
=> feat(2856): Add timestamp in downloaded logs [3]

app/settings/service.js, tests/unit/settings/service-test.js
The V2 UI is moving off of ember data and requires a new injectable service to managing user settings.  This injectable service will refactored into a few existing V2 components as well an upcoming component for pipeline settings.
Creates a simple injectable service with the core functionality for managing user settings.
=> feat: User settings as an injectable service

app/components/pipeline/event/card/component.js, app/components/pipeline/event/card/template.hbs, app/components/pipeline/jobs/table/cell/start-time/component.js, app/components/pipeline/jobs/table/component.js, app/components/pipeline/modal/event-group-history/component.js, app/components/pipeline/modal/event-group-history/template.hbs, app/components/pipeline/modal/search-event/component.js, app/components/pipeline/modal/search-event/template.hbs, app/components/pipeline/workflow/component.js, app/components/pipeline/workflow/event-rail/template.hbs, app/components/pipeline/workflow/template.hbs, app/v2/pipeline/events/index/route.js, app/v2/pipeline/events/index/template.hbs, app/v2/pipeline/events/route.js, app/v2/pipeline/events/show/route.js, app/v2/pipeline/events/show/template.hbs, app/v2/pipeline/jobs/route.js, app/v2/pipeline/jobs/template.hbs, app/v2/pipeline/pulls/index/route.js, app/v2/pipeline/pulls/index/template.hbs, app/v2/pipeline/pulls/route.js, app/v2/pipeline/pulls/show/route.js, app/v2/pipeline/pulls/show/template.hbs, tests/integration/components/pipeline/event/card/component-test.js, tests/integration/components/pipeline/jobs/table/cell/start-time/component-test.js, tests/integration/components/pipeline/modal/event-group-history/component-test.js, tests/integration/components/pipeline/modal/search-event/component-test.js, tests/integration/components/pipeline/workflow/component-test.js
https://github.com/screwdriver-cd/ui/pull/1437 added an injectable ember service to manage user settings.  The v2 UI components that previously required user settings should now have the settings injected at the component level where they are used rather than passed around as component parameters.
Refactors the v2 UI components to use the injected user settings where necessary.
=> fix: Refactor to inject user settings

app/components/pipeline/settings/main/modal/pipeline/component.js, app/components/pipeline/settings/main/modal/pipeline/styles.scss, app/components/pipeline/settings/main/modal/pipeline/template.hbs, tests/integration/components/pipeline/settings/main/modal/pipeline/component-test.js
Creates a modal to update pipeline repository settings
=> feat: Modal update pipeline repository settings

app/components/pipeline/settings/main/modal/pipeline-alias/component.js, app/components/pipeline/settings/main/modal/pipeline-alias/styles.scss, app/components/pipeline/settings/main/modal/pipeline-alias/template.hbs, tests/integration/components/pipeline/settings/main/modal/pipeline-alias/component-test.js
Creates a modal to update pipeline alias
=> feat: Glimmer modal for updating pipeline alias

app/components/pipeline/header/component.js, app/components/pipeline/settings/main/modal/sonar-badge/component.js, app/components/pipeline/settings/main/modal/sonar-badge/styles.scss, app/components/pipeline/settings/main/modal/sonar-badge/template.hbs, app/pipeline-page-state/service.js, tests/integration/components/pipeline/settings/main/modal/sonar-badge/component-test.js
Creates a modal to update Sonar badge settings
=> feat: Sonar badge modal

app/components/pipeline/jobs/table/component.js, app/components/pipeline/jobs/table/cost-table/component.js, app/components/pipeline/jobs/table/util.js, app/utils/pipeline/job.js, tests/unit/components/pipeline/jobs/table/util-test.js, tests/unit/utils/pipeline/job-test.js
Some job utility functions should be refactored to a more shareable utility
Refactors the utility functions for extracting a job's display name and stage into a more shareable utility
=> fix: Reactor to more easily shared utility

app/event/model.js, tests/unit/event/model-test.js
The duration shows `0 seconds` when the last build is virtual since the virtual builds do not have `endTime`.
Filter the builds without `endTime` to get the last build's end time properly.
=> fix: event duration shows 0 second when the last build is virtual

app/components/pipeline/settings/metrics/modal/toggle/component.js, app/components/pipeline/settings/metrics/modal/toggle/styles.scss, app/components/pipeline/settings/metrics/modal/toggle/template.hbs, app/components/pipeline/settings/metrics/modal/toggle/util.js, tests/integration/components/pipeline/settings/metrics/modal/toggle/component-test.js, tests/unit/components/pipeline/settings/metrics/modal/toggle/util-test.js
Creates a component for managing pipeline jobs configuration for the metrics page.  
The modal supports including or excluding a job from the metrics:
The modal supports including or excluding multiple jobs from the metrics as a bulk action:
=> feat: Modal for managing job metrics settings

app/components/pipeline/settings/main/modal/sync/component.js, app/components/pipeline/settings/main/modal/sync/template.hbs, tests/integration/components/pipeline/settings/main/modal/sync/component-test.js
Creates a modal for force resync of webhooks
=> feat: Modal for webhooks sync

app/pipeline/pulls/route.js
The v2 redirect for the pulls route does not load pipeline data correctly.
Fixes the pipeline id extraction
=> Fix v2 redirect for pulls route

app/components/pipeline/settings/cache/modal/clear/component.js, app/components/pipeline/settings/cache/modal/clear/styles.scss, app/components/pipeline/settings/cache/modal/clear/template.hbs, tests/integration/components/pipeline/settings/cache/modal/clear/component-test.js
Creates a modal for clearing pipeline and jobs caches.
=> Modal to clear pipeline and job caches

app/commands/detail/route.js, app/commands/detail/version/route.js, app/dashboard/route.js, app/dashboard/show/route.js, app/pipeline/build/index/route.js, app/pipeline/events/route.js, app/pipeline/jobs/index/route.js, app/pipeline/route.js, app/routes/error.js, app/templates/error.hbs, app/templates/job/detail/route.js, app/templates/job/detail/version/route.js, app/templates/pipeline/detail/route.js, app/templates/pipeline/detail/version/route.js, app/user-settings/preferences/route.js, app/utils/not-found-error.js, tests/acceptance/commands-test.js, tests/acceptance/dashboards-test.js, tests/acceptance/pipeline-builds-test.js, tests/acceptance/pipeline-template-test.js, tests/acceptance/templates-test.js, tests/unit/commands/detail/router-test.js, tests/unit/commands/detail/version/router-test.js, tests/unit/templates/job/detail/route-test.js, tests/unit/templates/job/detail/version/router-test.js
Screwdriver UI redirects to the `/404` page when access non-existent content or non-permitted content.
Users need to re-fill in the full URL to fix it, but that is a little hard.
https://github.com/screwdriver-cd/screwdriver/issues/3388
Keep original URL when show the 404 page using [Error Substates](https://guides.emberjs.com/v4.12.0/routing/loading-and-error-substates/) feature.
- Issue - https://github.com/screwdriver-cd/screwdriver/issues/3388
=> feat(3388): Keep URL when show the 404 page

app/components/pipeline/settings/cache/table/styles.scss
The spacing between the cache button and the number of selected job cache text is missing a margin value
Adds the correct margin spacing value
=> fix: margin spacing

app/components/pipeline/settings/main/template.hbs
The buttons in the v2 UI for pipeline settings has some missing and erroneous button titles.
1. Adds the missing button titles for the buttons that require titles
2. Fixes the erroneous button title
=> fix: Add missing titles

app/components/app-header/component.js, app/components/app-header/template.hbs, app/opt-in-route-mapping/service.js, app/pipeline/options/route.js
Users should be able to toggle between the legacy and v2 UI for pipeline settings
1. Creates the proper mapping for the v2 pipeline settings routes so users can switch between the two interfaces
2. Fixes a typo causing the hover text to display incorrect information
=> feat: V2 settings toggle

app/components/pipeline/event/card/component.js, tests/integration/components/pipeline/event/card/component-test.js
Events with a failure should have failure status as the priority in the event card
1. Refactors the event card tests for better use of stubs
2. Updates the event card status to prioritize failure status
https://github.com/screwdriver-cd/screwdriver/issues/3386
=> fix: V2 event status failure priority

app/event/model.js
The event status does not accurately highlight build statuses when there are multiple builds with different statuses.
Updates the event status calculation to account for multiple builds with different statuses.
https://github.com/screwdriver-cd/screwdriver/issues/3386
=> Update event status priority
